### ISSUE TITLE
how to compile example

### ISSUE THREAD

**Issue by zhaolei** [Dobiasd/frugally-deep#1]
`// main.cpp
#include <fdeep/fdeep.hpp>
int main()
{
    const auto model = fdeep::load_model("fdeep_model.json");
    const auto result = model.predict(
        {fdeep::tensor3(fdeep::shape3(4, 1, 1), {1, 2, 3, 4})});
    std::cout << fdeep::show_tensor3s(result) << std::endl;
}`
How to compile this code?
> g++ main.cpp -o r --std=c++11 
is not work

**Comment by Dobiasd** [comment]
The line breaks in your code look broken. And you need C++14, not 11.

So, assuming you have FunctionalPlus and frugally-deep installed on your system, the following code

```cpp
#include <fdeep/fdeep.hpp>
int main()
{
    const auto model = fdeep::load_model("fdeep_model.json");
    const auto result = model.predict(
        {fdeep::tensor3(fdeep::shape3(4, 1, 1), {1, 2, 3, 4})});
    std::cout << fdeep::show_tensor3s(result) << std::endl;
}
```

should be compiled with this command line

```
g++ --std=c++14 -o r asd.cpp
```

and if no compilation errors occurs run like that.

```
./r
```

If you encounter further errors, please report the full error message.

**Comment by zhaolei** [comment]
Thanks , it's Ok

**Comment by Ihsan149** [comment]
Will it work for the segmentation model?
Is there any example how we can use image in predict?

**Comment by Dobiasd** [comment]
@Ihsan149 You can load images (for example with OpenCV) and then use [`fdeep::tensor3_from_bytes`](https://github.com/Dobiasd/frugally-deep/blob/cc2b4904e80b8a3cc0c08afd8a5753fbac907905/include/fdeep/tensor3.hpp#L416) to convert the pixel values into an `fdeep::tensor3` to use in `model::predict`.

But what do you mean with "the segmentation model"?
