### ISSUE TITLE
Multiple Definition errors with release v0.7.0-p0

### ISSUE THREAD

**Issue by nerdgilbert** [Dobiasd/frugally-deep#100]
First off, thank you for this work on this library. Working well so far!

Unfortunately, I am running into compilation errors of the form: 
```
In function `fdeep::internal::linear_activation(float)':
main.cc:(.text+0x0): multiple definition of `fdeep::internal::linear_activation(float)'
```
for the following functions:
```
fdeep::internal::linear_activation
fdeep::internal::hard_sigmoid_activation
fdeep::internal::relu_activation
fdeep::internal::tanh_activation
fdeep::internal::sigmoid_activation
fdeep::internal::selu_activation
fdeep::internal::elu_activation
fdeep::internal::get_activation_func
```
The issue is that in release v0.7.0-p0, these functions are not marked as inline.

Fortunately, these seemed to be fixed in `master`, specifically on this [commit](https://github.com/Dobiasd/frugally-deep/commit/da3fdf274beee9872b7b94af34e1a4e11b85f745#diff-8869e75e88124dd4b158fd22f3c4568b). I verified this by compiling against `master`.

 My question/issue here is: when can we expect a minor release to fix these issues? It would be nice to build against tagged releases instead of `master`.

Thanks!

**Comment by Dobiasd** [comment]
Hi Gilbert,

thanks for the positive feedback and the suggestion. You are right of course, this needs to be new release. So [here](https://github.com/Dobiasd/frugally-deep/releases/tag/v0.7.1-p0) it is. :)
