### ISSUE TITLE
Issue in Library On Windows 10 Machine

### ISSUE THREAD

**Issue by HackersSpirit** [Dobiasd/frugally-deep#101]
Hello, 
I have followed all the instructions mentioned on the github to run my model in cpp.
I have converted my model to json. 
The issue is the program takes a lot of time to load the model and plus on top of it takes 
even more time for the model to predict compared to that of python.
For Ex: In python the model load in about 20ms and prediction happen in about 10 ms.
Here it takes about 120 sec to load the model and more than that to  predict. Also the program exits
with giving error message with any log.

qt.pro file:
CONFIG += console
CONFIG -= app_bundle

TEMPLATE = app
SOURCES += main.cpp
DEFINES += QT_DEPRECATED_WARNINGS
INCLUDEPATH +=C:\\john\\pc\\Downloads\\frugally-deep-master\\include

```
#include <QCoreApplication>
#include "fdeep/fdeep.hpp"
#include <opencv2/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <iostream>
#include <QDebug>

using namespace fdeep;
using namespace cv;
int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
    const Mat image = imread("sample.jpg");
    qDebug()<<"At Assert";
    assert(image.isContinuous());
     qDebug()<<"2t";
    const auto model = load_model("model.json");
     qDebug()<<"3";
    //Use the correct scaling ie. low and high
    const auto input = tensor5_from_bytes(image.ptr(),image.rows,image.cols,image.channels(),0.0f,1.0f);
    const auto result = model.predict_class({input});
    qDebug()<<"Prediction Result"<<result;

    return a.exec();
}
```
Please let me know any thing else should i provide.

**Comment by HackersSpirit** [comment]
@Dobiasd : Thanks for the quick response. Actually i read your statement from the introduction part:
works out of-the-box also when compiled into a 32-bit executable.
Will it give same performance for the 64-bit system.

**Comment by Dobiasd** [comment]
Yes, there should be no measurable performance difference in 32-bit and 64-bit versions ran on the same machine.

**Comment by HackersSpirit** [comment]
@Dobiasd : Thanks for the steps. I was able to run the program but still i am facing some issues regarding predicting the image and time.
In the below comparison log I have passed same sample to both python and cpp
Sharing you the log of Python & implementation in cpp. Please have a look:
Time to Load Module 1.271470546722412
1.0 status prediction time  0.08649158477783203
1.0 status prediction time  0.03510165214538574
1.0 status prediction time  0.034160614013671875
1.0 status prediction time  0.03513312339782715
1.0 status prediction time  0.03611254692077637
1.0 status prediction time  0.03412604331970215
1.0 status prediction time  0.03806352615356445
1.0 status prediction time  0.03510689735412598
1.0 status prediction time  0.03419017791748047
1.0 status prediction time  0.051692962646484375

CPP Logs:
Loading json ... done. elapsed time: 0.315956 s
Running test 1 of 1 ... done. elapsed time: 0.136610 s
Loading, constructing, testing of C:\Users\thermo\Downloads\fragle\frugally-deep-master\include\fulldeepModel.json took 0.828466 s overall.
Load Time= 0
Result: 0 Prediction Time 0.129454
Result: 0 Prediction Time 0.129454
Result: 0 Prediction Time 0.131072
Result: 0 Prediction Time 0.13269
Result: 0 Prediction Time 0.126217
Result: 0 Prediction Time 0.126217
Result: 0 Prediction Time 0.126217
Result: 0 Prediction Time 0.129454
Result: 0 Prediction Time 0.126217
Result: 0 Prediction Time 0.126217

Also sharing the sample Cpp code. Please have a look:
```
#include <QCoreApplication>
#include "fdeep/fdeep.hpp"
#include <opencv2/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <iostream>
#include <QDebug>

using namespace fdeep;
using namespace cv;
int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
    float loadTime1,loadTime2,totalloadtime;
    float predictTime1,predictTime2,totalpredictTime;
    loadTime1 = getTickCount();
    const auto model = load_model("fulldeepModel.json");
    loadTime2 = getTickFrequency();
    totalloadtime = (predictTime2-predictTime1)/getTickFrequency();
    qDebug()<<"Load Time="<<totalloadtime;
    for(int i=0;i<10;i++){
         Mat image1 = imread("1.jpeg");
         Mat image,image2;
         Size size(256,256);
         resize(image1,image2,size);
        image2.convertTo(image, CV_32F, 1.0 / 255, 0);
       //Use the correct scaling ie. low and high
      const auto input = tensor5_from_bytes(image.ptr(),image.rows,image.cols,image.channels(),0.0f,1.0f);
      predictTime1 = getTickCount();
      const auto result = model.predict_class({input});
      predictTime2 = getTickCount();
      totalpredictTime = (predictTime2- predictTime1)/getTickFrequency();
      qDebug()<<"Result:"<<result<<"Prediction Time"<<totalpredictTime;
  }
    return a.exec();
}

```

**Comment by Dobiasd** [comment]
OK, so if I understand correctly, switching from debug mode to release mode brought the prediction time in C++ down from ~120 s to ~0.126 s. But in Python you have ~0.035 and want to achieve the same performance in C++, right?

Might it be the case that in Python you are utilizing a GPU, or multiple CPUs / CPU cores? Frugally deep does nothing of those. It ignores the GPU, and it also only uses one CPU / CPU core.

**Comment by HackersSpirit** [comment]
@Dobiasd : My one of the main concern is the output is not correct.
I am passing a image having data and the output of the keras model is 1. Where as the cpp 
is giving the prediction result as 0.
And my python program is not using gpu. But tensorflow library may be using multiple cores as you mentioned in python.
Is there any way to increse the efficiency Frugally Deep ortherwise any other alternative if you can suggest.

**Comment by Dobiasd** [comment]
OK, so we are dealing with two questions here.

1) Performance: No, if you have all your compiler optimizations enabled, I think you can not get much more performance from your hardware with frugally-deep.

2) Prediction results: Can you post a minimal example ([1](https://stackoverflow.com/help/mcve), [2](http://sscce.org/)) that reproduces the problem? It should contain:
- The model file (`.h5` and `.json`)
- The example image file
- A short python script that loads your model and image and produces the `1` output.
- A short C++ source that produces the `0`.

Leave out everything that is not needed, e.g., the Qt stuff etc.

**Comment by Dobiasd** [comment]
To conclude our discussions we had via email here, there were multiple issues with your code:

1) In the C++ part, you converted the OpenCV image to `CV_32F`, but you then used `fdeep::tensor5_from_bytes` on this memory. This is not valid.

2) `fdeep::model::predict_class` returns the index of the output neuron with the maximal activation, which is `0`. On python side however you output the raw activation value of your single output neuron, which is `1.0`.

3) The examples were everything else but minimal. There was still Qt stuff in there. And also since we are now investigating classification results and not runtime any more, all the timing stuff can be removed.

4) Also I suggest to not resize the image in both source codes after loading, because this can result in different interpolation methods being used. In your case you were using area interpolation in Python, and linear interpolation (OpenCV default) in C++. So even if the rest would have been correct, the input to the models would still not have been exactly the same. So I resized your image once and saved it in the correct size (256x256) [as PNG](https://i.imgur.com/QREIDfZ.png) (lossless) instead of JPG.

---

Here is the corrected and minimal example, demonstrating that your model is working fine in frugally-deep and produces the same results with it as it does with Keras:

```python
# minimal.py
import cv2
from keras.models import load_model
model = load_model("test10.h5")
img = cv2.imread('input.png') / 255.0
print(model.predict(img.reshape(1, 256, 256, 3)))
```

```cpp
// fixed.cpp
#include "fdeep/fdeep.hpp"
#include <opencv2/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <iostream>
using namespace fdeep;
using namespace cv;
int main()
{
    const auto model = load_model("test10.json");
    const auto image = imread("input.png");
    const auto input = tensor5_from_bytes(
        image.ptr(),
        static_cast<std::size_t>(image.rows),
        static_cast<std::size_t>(image.cols),
        static_cast<std::size_t>(image.channels()));
    std::cout << fdeep::show_tensor5s(model.predict({input})) << std::endl;
}
```

```bash
python3 minimal.py
```

Output:
```
[[1.]]
```

Convert the model:
```bash
python3 convert_model.py test10.h5 test10.json
```

Compile the C++ code:
```bash
g++ -std=c++14 -O3 fixed.cpp -L/usr/local/lib -lopencv_core -lopencv_imgproc -lopencv_imgcodecs -lopencv_highgui -o fixed
```

Run the C++ code:
```bash
./fixed
```

Output:
```
[[[[1.0000]]]]
```

So it's the same result in C++ as it is in Python.
