### ISSUE TITLE
Requesting support/alternative for Permute layer

### ISSUE THREAD

**Issue by aashaka** [Dobiasd/frugally-deep#102]
I have read that combining LSTM and CNN components requires input dimensions to be shuffled using the Permute layer. I have an architecture with LSTM and CNN layers in parallel whose concatenation of output is sent to the softmax layer.

It seems like a common use case, I am wondering if support for Permute layer will be added soon, or do people have a workaround for that?

**Comment by Dobiasd** [comment]
You are right, it makes sense to add this layer type to the library.

Are you interested in implementing it and opening a pull request? If not, I'd try to do in the coming week.

**Comment by aashaka** [comment]
I am interested in giving it a shot. Will take me about a week and a half to get to it though.

**Comment by Dobiasd** [comment]
@aashaka Any news regarding this? In case you are still interested in support for this layer, but no longer in implementing it, please let me know.

**Comment by Dobiasd** [comment]
Just in case anybody reading this commit is concerned about possible inefficiency of [the most inner loop](https://github.com/Dobiasd/frugally-deep/commit/46b39a23b2912b9fba90e8c9255727d9da88ca9b#diff-4cad945dbbf8a12ad6e3699c8722f99dR552): Modern C++ compilers have no trouble in optimizing the immutability of the `tensor5_pos` completely away, and thus produce the same asm output as a hand-optimized loop with mutation of the `tensor5_pos` would do.

I.e., this ([godbolt.org link](https://godbolt.org/z/oCLniK)):

```cpp
#include <iostream>

struct foo {
    int a;
    int b;
};

foo replace_a(const foo& f, int value) {
    return foo{value, f.b};
}

int main() {
    int a;
    int n;
    // Disallow compile-time optimizations (i.e., removal) of loop
    std::cin >> a;
    std::cin >> n;

    foo my_foo{1, 2};
    for (int i = 0; i < n; ++i) {
        my_foo = replace_a(my_foo, my_foo.a + i);
    }
    std::cout << my_foo.a << std::endl;
}
```


is not only equally fast, but also yields the exact same optimized executable, as that ([godbolt.org link](https://godbolt.org/z/L1z0NQ)):

```cpp
#include <iostream>

struct foo {
    int a;
    int b;
};

foo replace_a(const foo& f, int value) {
    return foo{value, f.b};
}

int main() {
    int a;
    int n;
    // Disallow compile-time optimizations (i.e., removal) of loop
    std::cin >> a;
    std::cin >> n;

    foo my_foo{1, 2};
    for (int i = 0; i < n; ++i) {
        my_foo.a += i;
    }
    std::cout << my_foo.a << std::endl;
}
```

:slightly_smiling_face:
