### ISSUE TITLE
How to speed up frugally-deep by multi-thread on multi-core cpu?

### ISSUE THREAD

**Issue by chenxian9999** [Dobiasd/frugally-deep#105]
How to speed up frugally-deep by multi-thread on multi-core cpu?

**Comment by Dobiasd** [comment]
If you have multiple predictions to do, you can use [`fdeep::model::predict_multi](https://github.com/Dobiasd/frugally-deep/blob/5a920627b37280acd56e0d427ed582dd83d40193/include/fdeep/model.hpp#L42) with `parallelly == true`, and it simply spawn each prediction in a `std::async` (via `fplus::transform_parallelly`). So with this you can use as many CPUs as you have predictions to do.

Running one single prediction however can always only use one CPU. No parallelization here.

**Comment by chenxian9999** [comment]
Thanks!
