### ISSUE TITLE
TypeError: ('Keyword argument not understood:', 'data_format')

### ISSUE THREAD

**Issue by SamuelXJames** [Dobiasd/frugally-deep#107]
Thanks for this project!

I am having difficulty converting my model using keras_convert.py
I get the following error:

`File "C:\Users\Sam\AppData\Local\Programs\Python\Python36\Lib\site-packages\keras\engine\base_layer.py", line 128, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'data_format')`

I double checked the layers I used and I couldn't find anything that was incompatible. I also tried converting the example model and it worked without a problem.

I would really appreciate your help.
Thanks!

Link to h5 file: https://drive.google.com/open?id=1rTMgep_ekAQDJOkztoiktcLf4v6-kV3v

**Comment by Dobiasd** [comment]
Hi Samuel,

just downloaded your model `Autoencoder.h5` and ran
```bash
python3 convert_model.py Autoencoder.h5 Autoencoder.json
```
on it. It worked without any error on my system and produces [this `Autoencoder.json` file](https://gist.github.com/Dobiasd/494615fb57280b68773870271b0a5b05).

Please make sure you are using the latest version of Keras and frugally-deep, and then try again.

**Comment by SamuelXJames** [comment]
Yes, the version of Keras that I was using was out of date.

Thank you
