### ISSUE TITLE
Convert_model fail?

### ISSUE THREAD

**Issue by hoanganhtuanfsoft** [Dobiasd/frugally-deep#110]
`if model.model == model:` in line 513 convert_model.py
Why do you have the above code?
I run fail with it :(

**Comment by Dobiasd** [comment]
>  `if model.model == model:` in line 513 convert_model.py
> Why do you have the above code?

Since version 2.2.0 Keras wraps the sequential models differently than before. For frugally-deep we need to obtain the underlying functional representation of the model ([commit](https://github.com/Dobiasd/frugally-deep/commit/95b5d77e75c18b2dd2a6b7aafc86f540668c4ee2).

---

> I run fail with it :(
What is the error message?

Also have you tried updating to the latest Keras version?

**Comment by hoanganhtuanfsoft** [comment]
> > `if model.model == model:` in line 513 convert_model.py
> > Why do you have the above code?
> 
> Since version 2.2.0 Keras wraps the sequential models differently than before. For frugally-deep we need to obtain the underlying functional representation of the model ([commit](https://github.com/Dobiasd/frugally-deep/commit/95b5d77e75c18b2dd2a6b7aafc86f540668c4ee2)).
> 
> > I run fail with it :(
> 
> What is the error message?
> 
> Also have you tried updating to the latest Keras version?

Fail when running convert_model in the above line.
Now, i'm using tf. I change all code that have keras to tensorflow.keras.

After editing follow by your point, i have other issue:
![image](https://user-images.githubusercontent.com/19376164/50988998-c9d85900-1540-11e9-90b6-9d9c82f7104e.png)

**Comment by Dobiasd** [comment]
> Fail when running convert_model in the above line.

Yes, but what does "Fail" mean? What was the exact error message?

---

> Now, i'm using tf. I change all code that have keras to tensorflow.keras.

This should not be the primary solution for such a mundane problem.

> After editing follow by your point, i have other issue:

Yeah, the code is made to work with `keras`, not with `tensorflow.keras`.

---

I suggest you install Keras again in its latest version (`sudo pip3 install keras --upgrade` in case you are using Linux), and then try again to use `convert_model.py` in its original version. If you still encounter an error, please post the exact error message and your keras version number (`python3 -c 'import keras; print(keras.__version__)'`).

**Comment by Dobiasd** [comment]
@hoanganhtuanfsoft Any news? Did you manage to make it work?

**Comment by Dobiasd** [comment]
OK, I'll close this issue due to inactivity. Feel free to re-open it if you have new information.
