### ISSUE TITLE
Softmax and RLU as Layers instead of Activations

### ISSUE THREAD

**Issue by mkeller97** [Dobiasd/frugally-deep#111]
Hi Tobias,

As promised in November I had more time to use your awesome frugally-deep lib, thanks again!

I found some glitches when using Softmax and ReLU as distinct layers instead of activation functions.
Both are sometimes useful, softmax to translate from values to probabilities, ReLU used after batchnormalization (found this in a paper) where you can't supply an activation function.

**Softmax:**
import_model.hpp: softmax is missing in `layer_ptr create_layer`, just add
`{"Softmax", create_softmax_layer},`
and everything is fine

**ReLU**
This one seems a bit more tricky and I couldn't fix it so far but found a workaround.

Workaround: use with activation layer is ok as it's not the last layer
`  x = tf.keras.layers.Activation('relu')(x)`

Otherwise the export of the layer already  crashes with different reactions if you use tf.keras or keras.

modified **_convert_model using tf.keras_** (which I would prefer as I use it everywhere else):

>   File "/data/Michael/MachineLearning/convert_model.py", line 609, in convert
>     model = load_model(in_path)
> 
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/saving.py", line 230, in load_model
>     model = model_from_config(model_config, custom_objects=custom_objects)
> 
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/saving.py", line 310, in model_from_config
>     return deserialize(config, custom_objects=custom_objects)
> 
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/serialization.py", line 64, in deserialize
>     printable_module_name='layer')
> 
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 173, in deserialize_keras_object
>     list(custom_objects.items())))
> 
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py", line 1292, in from_config
>     process_layer(layer_data)
> 
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py", line 1278, in process_layer
>     layer = deserialize_layer(layer_data, custom_objects=custom_objects)
> 
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/serialization.py", line 64, in deserialize
>     printable_module_name='layer')
> 
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 175, in deserialize_keras_object
>     return cls.from_config(config['config'])
> 
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1606, in from_config
>     return cls(**config)
> 
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/advanced_activations.py", line 312, in __init__
>     if negative_slope < 0.:
> 
> TypeError: '<' not supported between instances of 'dict' and 'float'
> 

I tried to modify advanced activations.py, class ReLU(Layer) but could note get it to make it work with import in frugally-deep.

this is what happens with your **_original convert_model using keras, 2.2.4_**:

>   File "/data/Michael/MachineLearning/PMP_DNN_AspClassify.py", line 835, in <module>
>     convert_model.convert(file, out_path)
> 
>   File "/data/Michael/MachineLearning/convert_model.py", line 599, in convert
>     model = load_model(in_path)
> 
>   File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 419, in load_model
>     model = _deserialize_model(f, custom_objects, compile)
> 
>   File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 225, in _deserialize_model
>     model = model_from_config(model_config, custom_objects=custom_objects)
> 
>   File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 458, in model_from_config
>     return deserialize(config, custom_objects=custom_objects)
> 
>   File "/usr/local/lib/python3.6/dist-packages/keras/layers/__init__.py", line 55, in deserialize
>     printable_module_name='layer')
> 
>   File "/usr/local/lib/python3.6/dist-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
>     list(custom_objects.items())))
> 
>   File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 1022, in from_config
>     process_layer(layer_data)
> 
>   File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 1008, in process_layer
>     custom_objects=custom_objects)
> 
>   File "/usr/local/lib/python3.6/dist-packages/keras/layers/__init__.py", line 55, in deserialize
>     printable_module_name='layer')
> 
>   File "/usr/local/lib/python3.6/dist-packages/keras/utils/generic_utils.py", line 147, in deserialize_keras_object
>     return cls.from_config(config['config'])
> 
>   File "/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py", line 1109, in from_config
>     return cls(**config)
> 
>   File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
>     return func(*args, **kwargs)
> 
>   File "/usr/local/lib/python3.6/dist-packages/keras/layers/convolutional.py", line 359, in __init__
>     **kwargs)
> 
>   File "/usr/local/lib/python3.6/dist-packages/keras/layers/convolutional.py", line 117, in __init__
>     self.kernel_initializer = initializers.get(kernel_initializer)
> 
>   File "/usr/local/lib/python3.6/dist-packages/keras/initializers.py", line 508, in get
>     return deserialize(identifier)
> 
>   File "/usr/local/lib/python3.6/dist-packages/keras/initializers.py", line 503, in deserialize
>     printable_module_name='initializer')
> 
>   File "/usr/local/lib/python3.6/dist-packages/keras/utils/generic_utils.py", line 138, in deserialize_keras_object
>     ': ' + class_name)
> 
> ValueError: Unknown initializer: GlorotUniform
> 

Now I write the update of the issue I realize I probably should have switched to original keras for model creation as well, otherwise this test does not make much sense.

But as mentioned, I have a workaround which works at least for me.

Regards,
Michael

**Comment by Dobiasd** [comment]
Hi Michael,

thanks a lot for the feedback.

---

Yes, the `Softmax` issue was easy to fix.

I first created a minimal example to reproduce the problem.

```python
# create_model.py
import numpy as np
from keras.layers import Input, Dense, Softmax
from keras.models import Model

inputs = Input(shape=(4,))
x = Dense(5, activation='relu')(inputs)
predictions = Softmax()(x)
model = Model(inputs=inputs, outputs=predictions)
model.compile(loss='categorical_crossentropy', optimizer='nadam')

model.fit(
    np.asarray([[1,2,3,4], [2,3,4,5]]),
    np.asarray([[1,0,0,0,0], [0,0,0,0,1]]), epochs=10)

model.save('keras_model.h5', include_optimizer=False)
```

```cpp
// main.cpp
// g++ -std=c++14 -O3 main.cpp -o main

#include <fdeep/fdeep.hpp>
int main()
{
    const auto model = fdeep::load_model("fdeep_model.json");
    const auto result = model.predict(
        {fdeep::tensor5(fdeep::shape5(1, 1, 1, 1, 4), {1, 2, 3, 4})});
    std::cout << fdeep::show_tensor5s(result) << std::endl;
}
```

And then I implemented, tested and pushed [the fix](https://github.com/Dobiasd/frugally-deep/commit/3f0be1f1cbd7ab7f8b43b68ef527f62c913e5e3e).

---

I also reproduced the `ReLU` problem with this minimal example:

```python
# create_model.py
import numpy as np
from keras.layers import Input, Dense, ReLU
from keras.models import Model

inputs = Input(shape=(4,))
x = Dense(5, activation='relu')(inputs)
predictions = ReLU()(x)
model = Model(inputs=inputs, outputs=predictions)
model.compile(loss='mean_squared_error', optimizer='nadam')

model.fit(
    np.asarray([[1,2,3,4], [2,3,4,5]]),
    np.asarray([[1,0,0,0,0], [0,0,0,0,1]]), epochs=10)

model.save('keras_model.h5', include_optimizer=False)
```

```cpp
// main.cpp
// g++ -std=c++14 -O3 main.cpp -o main

#include <fdeep/fdeep.hpp>
int main()
{
    const auto model = fdeep::load_model("fdeep_model.json");
    const auto result = model.predict(
        {fdeep::tensor5(fdeep::shape5(1, 1, 1, 1, 4), {1, 2, 3, 4})});
    std::cout << fdeep::show_tensor5s(result) << std::endl;
}
```

In C++ during import the following happened:

```
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be number, but is null
```

[This code change](https://github.com/Dobiasd/frugally-deep/commit/07d75ebadc65e284025a0766583f6b4de7f4bf26) fixed it.

---

So now both examples are working on my system.

Could you please check if this also fixed the problems for you, at least when you use the default `convert_model.py`? :slightly_smiling_face:

**Comment by mkeller97** [comment]
Hi Tobias,

Thanks for the quick fixes!

Softmax is ok, ReLU probably also, the error you reproduced is the same as mine.

The export with the original convert_model fails as I produce the models using tf.keras, see my last update of the issue (didn't expect you to get back to me this fast ;)
I managed to improve advanced_activations.py of tf.keras so I could make the convert_model (which uses tf.keras) to work.

AND NOW:
Very cool, with the ReLU fix of frugally deep I can now import the .json I export with my modified tf.keras, advanced_activations.py!

I suspect tf.keras is just a bit behind there and keras 2.2.4 has fixed this.
As I expect this to change in the next months (the main Keras dev is with google tf team now as far as I understand) I will probably stay on tf,keras.

Thanks again for the great support!
Michael
