### ISSUE TITLE
Right Keras version?

### ISSUE THREAD

**Issue by SergeySlyusarEZlo** [Dobiasd/frugally-deep#112]
Hello Tobias, I clonned your project, and run the tests, but test war failed. I try keras 2.2.4 on Python3.
What is wrong ?

Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/frugally-deep/keras_export/convert_model.py", line 665, in <module>
    main()
  File "/home/frugally-deep/keras_export/convert_model.py", line 661, in main
    convert(in_path, out_path)
  File "/home//frugally-deep/keras_export/convert_model.py", line 596, in convert
    assert K.image_data_format() == 'channels_last'
AttributeError: module 'keras.backend' has no attribute 'image_data_format'
test/CMakeFiles/readme_example_main_data.dir/build.make:60: recipe for target 'test/readme_example_model.json' failed
make[3]: *** [test/readme_example_model.json] Error 1
CMakeFiles/Makefile2:447: recipe for target 'test/CMakeFiles/readme_example_main_data.dir/all' failed
make[2]: *** [test/CMakeFiles/readme_example_main_data.dir/all] Error 2
CMakeFiles/Makefile2:528: recipe for target 'test/CMakeFiles/unittest.dir/rule' failed
make[1]: *** [test/CMakeFiles/unittest.dir/rule] Error 2
Makefile:331: recipe for target 'unittest' failed
make: *** [unittest] Error 2

**Comment by Dobiasd** [comment]
The error `AttributeError: module 'keras.backend' has no attribute 'image_data_format'` points to an [old Keras version being used](https://github.com/fchollet/deep-learning-models/issues/45).

Can you please check if you are really using 2.2.4?

You can do it like so:
```bash
python3 -c "import keras; print(keras.__version__)"
```

**Comment by Dobiasd** [comment]
@SergeySlyusarEZlo Any news regarding this issue? Were you able to solve it?

**Comment by SergeySlyusarEZlo** [comment]
Hello, no thank you i don't try more.
Best regards.
Sergey Slyusar

**Comment by Dobiasd** [comment]
OK, thanks. I'll close this issue then.
