### ISSUE TITLE
Support for SpatialDropout1D

### ISSUE THREAD

**Issue by swilson314** [Dobiasd/frugally-deep#113]
I'm using the KerasTCN library: https://github.com/philipperemy/keras-tcn

The model uses SpatialDropout1D, so load_model() fails. Given that dropout shouldn't affect recall, I suspect this is a straightforward change, and that appears to be the case when examining the fdeep function create_dropout_layer().

I made the following change to import_model.hpp and all works as expected:

	{"Dropout", create_dropout_layer},
	// SBW 2019.01.17 Support SpatialDropout1D for TCN.
	{"SpatialDropout1D", create_dropout_layer},

Do you see anything wrong with what I'm doing?

**Comment by Dobiasd** [comment]
Thanks. Yes, this seems correct.

While we are at it, we could do have this not only for `Dropout` and `SpatialDropout1D`, but also for `AlphaDropout`, `GaussianDropout`, `SpatialDropout2D` and `SpatialDropout3D`.

Would you like to open a pull request with the changes, or should I include it?

**Comment by swilson314** [comment]
Agreed. I'm happy to make the changes. This will be my first time doing a pull request and making changes -- can you watch that I do it right? Are there guidelines I should be following?

**Comment by Dobiasd** [comment]
Cool. There are no special guidelines. Basically, you have two options:
- For very small changes, you can use the [edit function in GitHub](https://help.github.com/articles/editing-files-in-another-user-s-repository/) and create a PR with it.
- For normal/large changes, you fork the repo, clone the fork locally, do the changes on your machine (and run tests etc. if needed), commit and push the changes to your fork, and then [create a PR from your fork](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)

In any case, I'll review your PR and (after optionally suggesting some improvements) then merge it. So there is no "danger" involved of breaking something. :)

**Comment by swilson314** [comment]
Ok. I used the edit function.

**Comment by Dobiasd** [comment]
I see [your fork](https://github.com/swilson314/frugally-deep), but there is no [pull request](https://github.com/Dobiasd/frugally-deep/pulls) yet.

**Comment by swilson314** [comment]
Sorry, I didn't follow all the steps to the end. Maybe it's ok now?

**Comment by Dobiasd** [comment]
Yes, looks good. :)

**Comment by swilson314** [comment]
Excellent. Thanks for your help!

**Comment by Dobiasd** [comment]
Thanks for the contribution. :heart:
