### ISSUE TITLE
Question nº 1 (logging)

### ISSUE THREAD

**Issue by phoemur** [Dobiasd/frugally-deep#115]
First of all, I'd like to say that I really enjoyed this library, thanks for your work...

I have 2 questions, this is the first one:

Is there a way to silence the following messages ?

> Loading json ... done. elapsed time: 0.428861 s
> Running test 1 of 1 ... done. elapsed time: 0.060067 s
> Loading, constructing, testing of fdeep_model.json took 1.398807 s overall.

I've been using a rather hackish solution like this:
``` cpp
inline void shutup_logger(const std::string& str)
{
    // Do nothing
}

(...)

const auto model = fdeep::load_model("fdeep_model.json", false, shutup_logger);
```
or using lambdas:
``` cpp
const auto model = fdeep::load_model("fdeep_model.json", false, [](const std::string&){});
```
Is there a better way to do this ?

Thanks in advance.

**Comment by Dobiasd** [comment]
Hi, and thanks for the positive feedback.

Yes, this is the supposed way, currently. :grimacing:

But maybe it would be better to rename `fdeep::load_model` to `fdeep::load_model_log_cout` and provide a new `fdeep::load_model` that uses your `dev_null_logger` as default. What do you think?

**Comment by phoemur** [comment]
Well, it seems ok... 
I'm just a user learning the features of the library, so I don't have a wide overview about it so far.

Actually, my intent is to do something like this:
``` cpp
#ifdef NDEBUG
    const auto model = fdeep::load_model("fdeep_model.json");
#else
    const auto model = fdeep::load_model("fdeep_model.json", false, [](const std::string&){});
#endif
``` 
In order to let cmake handle the build types, making all tests and outputs on Debug builds, but avoiding it on Release...

Again, tx a lot.

**Comment by Dobiasd** [comment]
OK, so the lambda-based solution does not feel too hackish any more? :slightly_smiling_face:
