### ISSUE TITLE
Normalization Different

### ISSUE THREAD

**Issue by King-Of-Knights** [Dobiasd/frugally-deep#117]
Hi there, thank for your great work!
I choose to convert [VGG-16](https://github.com/keras-team/keras-applications/blob/master/keras_applications/vgg16.py) into C++ and predict my image. Everything seems to be OK until I run opencv [example](https://gist.github.com/Dobiasd/3140cfd9f539b6adb346e0b4a0ce157b). Plenty of time has been cost (about 40mins) and I still got no result.
```
const auto model = fdeep::load_model("model.json");
```
loading json cost me 586s and I believe I must screw up something
My VGG-16 json file is 730MB and my compiler is VS2017 and my CPU is i9-8950HK 4.8GHz.  I'm a newbie to C++ and please point out where I made mistake. I really appreciate it .

**Comment by King-Of-Knights** [comment]
@Dobiasd Thanks for quick response! This advice solve my problem!
However, I find the prediction from keras and fdeep are different:
In python version, my code is:
```
from keras.models import load_model
import cv2
import numpy as np

model = load_model('vgg16_weight.h5')
im = cv2.resize(cv2.imread('test.jpg'), (224, 224))
im = np.expand_dims(im, 0)
print(model.predict_classes(im)[0])
```
and fdeep version is:
```
#include <fdeep/fdeep.hpp>
#include <opencv2/opencv.hpp>

int main()
{
	const cv::Mat image = cv::imread("test.jpg");
	cv::cvtColor(image, image, cv::COLOR_BGR2RGB);
	assert(image.isContinuous());
	const auto model = fdeep::load_model("model.json");
	// Use the correct scaling, i.e. low and high.
	const auto input = fdeep::tensor5_from_bytes(image.ptr(),
		static_cast<std::size_t>(image.rows),
		static_cast<std::size_t>(image.cols),
		static_cast<std::size_t>(image.channels()),
		0.0f, 1.0f);
	const auto result = model.predict_class({ input });
	std::cout << result << std::endl;
}
```
I can confirm the image for python and fdeep is the same and `model.json` indeed comes from `vgg16_weight.h5 `. But the prediction result is different. Please correct me if I am wrong, Thanks!

**Comment by Dobiasd** [comment]
The input values you give to the model are different in Python and in C++.
- In Python you are resizing the image, in C++ you are not.
- In C++ you scale the pixel values from [0, 255] to [0.0, 1.0], in Python you do not.

Please compare the raw values you give to the `predict`/`predict_call` function.

Python:
```python
print(im)
```

C++:
```cpp
std::cout << fdeep::show_tensor5(input) << std::endl;
```

**Comment by King-Of-Knights** [comment]
@Dobiasd Hi! 
I come back since I find some inconvenience caused by `tensor5_from_bytes` function.
If we want to train CNN from our raw image dataset, the keras documentation uses 
```
train_datagen = ImageDataGenerator(rescale=1./255)
```
to normalize the image. It means we directly divide our image pixels by 255.
The normalization in fdeep is:
```
template <typename T>
T reference_interval(const T& new_low, const T& new_high,
    const T& old_low, const T& old_high, const T& x)
{
    const T scale = (new_high - new_low) / (old_high - old_low);
    return scale * (x - old_low) + new_low;
```
which is min-max normalization and may cause different result from the CNN trained on `ImageDataGenerator(rescale=1./255)`. I hope you could notice it.
Thanks!

**Comment by Dobiasd** [comment]
No, it's doing the exact same thing. A call to `fplus::reference_interval(0.0, 1.0, 0.0, 255.0)` is equivalent to `x / 255.0`. :slightly_smiling_face:

See this minimal example in Python:
```python
def scale_version_1(x):
    return x / 255.0

def scale_version_2(x):
    # like fplus::reference_interval
    new_low = 0.0
    new_high = 1.0
    old_low = 0.0
    old_high = 255.0
    scale = (new_high - new_low) / (old_high - old_low)
    return scale * (x - old_low) + new_low

xs = list(range(10))
ys1 = list(map(scale_version_1, xs))
ys2 = list(map(scale_version_2, xs))
print(ys1)
print(ys2)
```

It has the following output:
```
[0.0, 0.00392156862745098, 0.00784313725490196, 0.011764705882352941, 0.01568627450980392, 0.0196078431372549, 0.023529411764705882, 0.027450980392156862, 0.03137254901960784, 0.03529411764705882]
[0.0, 0.00392156862745098, 0.00784313725490196, 0.011764705882352941, 0.01568627450980392, 0.0196078431372549, 0.023529411764705882, 0.027450980392156862, 0.03137254901960784, 0.03529411764705882]
```

**Comment by King-Of-Knights** [comment]
@Dobiasd Hmmm, looks like the output of Vgg16 `model.predict` in keras and fdeep are still different. the max value in softmax are different though they are in the same position in softmax. Have you ever try it? Thanks!

**Comment by King-Of-Knights** [comment]
@Dobiasd OK, I will try mnist dataset with keras and fdeep opencv example, will report it back soon.

**Comment by King-Of-Knights** [comment]
@Dobiasd Hi, I'm glad to tell you that it is not fdeep fault. This issuse is caused by` cvtColor(image, image, cv::COLOR_BGR2RGB);`, which is not conducted by Python. The fdeep pave a wide road for me to my embedding device, exciting about it. Thanks for your patience and quickly response

**Comment by King-Of-Knights** [comment]
@Dobiasd Hello! Sorry to disturb you again, but I cannot convert this [yolo model](https://drive.google.com/open?id=1eb9IgDKHEMmDEGEQVev9DEK6tC6JxvWa) to json. When 
 `model.summary()`, I find all the layers are supported by fdeep.  Can you verify it?
Traceback is here:
```
Traceback (most recent call last):
  File "keras_export/convert_model.py", line 665, in <module>
    main()
  File "keras_export/convert_model.py", line 661, in main
    convert(in_path, out_path)
  File "keras_export/convert_model.py", line 616, in convert
    test_data = gen_test_data(model, random_fn)
  File "keras_export/convert_model.py", line 138, in gen_test_data
    measure_predict(model, data_in)
  File "keras_export/convert_model.py", line 96, in measure_predict
    data_out = model.predict(data_in)
  File "D:\Anaconda3\lib\site-packages\keras\engine\training.py", line 1169, in predict
    steps=steps)
  File "D:\Anaconda3\lib\site-packages\keras\engine\training_arrays.py", line 294, in predict_loop
    batch_outs = f(ins_batch)
  File "D:\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "D:\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [1,128,4,4] vs. shape[1] = [1,256,5,5]
         [[{{node concatenate_2/concat}} = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](concatenate_2/concat-0-TransposeNHWCToNCHW-LayoutOptimizer, add_11/add, concatenate_1/concat-2-LayoutOptimizer)]]
```
Looks like issue arise in concatenate layer

**Comment by Dobiasd** [comment]
As far as I can see, your problem has nothing to do with frugally-deep, but
with the model you are trying to use.

The following minimal code already fails on my system:

from keras.models import load_model
import numpy as np
model = load_model('yolo.h5')
data_in = np.random.normal(size=(1, 42, 42, 3))
print(data_in.shape)
model.predict([data_in])

If it does not work on your system too, I'm out. ;)

**Comment by King-Of-Knights** [comment]
@Dobiasd Hello! After some examination, I find the key to this issue. In a general CNN, the input layer shape is fixed: 
e.g AlexNet:
`print(model.input)`
we will get:
`Tensor("conv1_input:0", shape=(?, 227, 227, 3), dtype=float32)`
In `yolo.h5` scene, where the input shape is not fixed, the input shape should be multiples of 32 and 
`print(model.input)`
we will get:
`Tensor("input_1:0", shape=(?, ?, ?, 3), dtype=float32)`

> Yes, I have tried it over and over again. In fact, every time you export a Keras model in fdeep format, i.e., conversion `h5` to `json`, test inputs are generated on python side and send through the model in a forward pass. The results are also stored in the `json` file, and when you load it with fdeep in C++, the input values are again put through the net and it is validated that the C++ code gived the exact same output as Python does.

So I guess fdeep will check some input shape like 32x32x3, 42x42x3 or something else. This mechanism may prevent something like `yolo.h5` from converting. Please correct me if I'm wrong. Thanks!

**Comment by Dobiasd** [comment]
Ah, now I understand. Thanks for the investigation. :+1:

For the test predictions `convert_model.py` used (quite arbitrary) the `42` as a replacement for the undefined dimension sizes. I just replaced this with `32`, so if you pull the latest version of fdeep, you can convert `yolo.h5` to JSON. I tested it, and it works. :)

**Comment by King-Of-Knights** [comment]
@Dobiasd Great, one less problem to be worried about. I will do some check and if there exist some other unexpected problem, I will report it back!
