### ISSUE TITLE
Conan Package Manager support

### ISSUE THREAD

**Issue by danimtb** [Dobiasd/frugally-deep#12]
Hi @Dobiasd!

I have been working on adding support of [Conan](https://www.conan.io/) in your libraries and I am glad to tell you that I have created conan packages for two of your great libraries!

- frugally-deep: https://github.com/conan-community/conan-frugally-deep
- FunctionalPlus: https://github.com/conan-community/conan-functionalplus

As frugally-deep depends on FunctionalPlus, I made a package of the latest one in order to get that dependency managed by Conan.

Now for users of frugally-deep library it is quite easy to install it:

```
$ conan install frugally-deep/0.1-p0@conan/stable
```

Conan will also download its dependencies: [Eigen](https://bintray.com/conan-community/conan/eigen%3Aconan), [Json for modern cpp](https://bintray.com/vthiery/conan-packages/jsonformoderncpp%3Avthiery), and FunctionalPlus.
You can check the generated packages of your header-only libraries in conan-community bintray repository:

- frugally-deep: https://bintray.com/conan-community/conan/frugally-deep:conan
- FunctionalPlus: https://bintray.com/conan-community/conan/functionalplus:conan

We would like to have official support of your libraries in [conan-center](https://bintray.com/conan/conan-center) so anyone in the C++ community can use them with Conan. Would you like to add support of conan in your libraries?

I could help you setting up the conan recipes and CI jobs to automate the process. Just tell me in any case.

thanks! 😃

**Comment by Dobiasd** [comment]
Wow, that sounds great, thanks a lot! I have no experience with Conan yet, so yeah, I could probably need your help with that. :)

@headupinclouds is planning on doing something with the the cmake configuration of this project during the next days (similar to [what he did with FunctionalPlus](https://github.com/Dobiasd/FunctionalPlus/pull/116)). Just mentioning, in case you two need to coordinate with each other, since this seems somewhat related to me.

**Comment by danimtb** [comment]
Great @Dobiasd!

The best approach would be to start with FunctionalPlus as it is a denpendency. I would make a PR in its repo adding the minimal support for conan. That way you would be able to have an idea of how the setup of conan is done. WDYT?

Regarding the cmake reconfiguration of @headupinclouds it doesn't interfere with Conan as it can work with any desired config of CMake. So I think we can work on these enhancements at the same time 😃

**Comment by Dobiasd** [comment]
OK, that's good.

I'll probably be afk until Tuesday, but yes, please go ahead. I will check back then.

**Comment by Dobiasd** [comment]
@danimtb Should I now simply try to replicate [what you did in FunctionalPlus](https://github.com/Dobiasd/FunctionalPlus/pull/118#issuecomment-365649961), or is there something special I have to consider in case of frugally-deep?

**Comment by danimtb** [comment]
Yes, the process is the same for frugally-deep but adding the dependency of FunctionalPlus, Eigen and Json fro modern cpp.

Have a look here: https://github.com/conan-community/conan-frugally-deep/blob/3ea788756324ab8731a530c2819c67f91aaf4d1e/conanfile.py#L13

So first, you need to upload FunctionalPlus to a Bintray repository to get the dependency solved!

Anyway, I think it is a good excercise to experience how conan works and I'll be glad to hear your feedback and support in the process :)

**Comment by Dobiasd** [comment]
Hi Daniel,

I just added `CONAN_PASSWORD` to Travis, adapted the files from FunctionalPlus and added the dependencies as shown in your example. But I'm pretty sure I missed something, since [I don't really know what I'm doing](https://i.imgur.com/bagRZBJ.png). Could you have a look?

[Pull request #20: Conan support](https://github.com/Dobiasd/frugally-deep/pull/20)

**Comment by danimtb** [comment]
Hi @Dobiasd 

Seems quite good, just some details to improve! I have commented in the review of the PR 😄

**Comment by danimtb** [comment]
Aaaaand finally there you've got it: https://bintray.com/dobiasd/public-conan/frugally-deep%3Adobiasd/v0.2.3-p0%3Astable

I think with frugally-deep you see the point of conan fetching all its dependencies in this case: eigen, jsonformoderncpp and functionalplus

Hope to see your inclusion request for conan-center soon!

Thanks a lot for your patience and nice work! :)
