### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Siwar11** [Dobiasd/frugally-deep#120]
i didn't understand the conversion line where it should be written in the code or the terminal or in the c++ code and for your information i will use QT creator 
thank you so much for helping me

**Comment by Dobiasd** [comment]
Hi Siwar,

sorry, I'm not sure I understand your problem correctly. So you are trying to follow the [usage example from the `README.md`](https://github.com/Dobiasd/frugally-deep#usage), but you are struggling to recognize which parts are source code and which are meant to be executed in the terminal, right?

**Comment by Siwar11** [comment]
Yes , I'd like to know if this command "python3
keras_export/convert_model.py keras_model.h5 fdeep_model.json" is executed
in the terminal or in the code ?

Le jeu. 14 févr. 2019 à 16:42, Tobias Hermann <notifications@github.com> a
écrit :

**Comment by Dobiasd** [comment]
Terminal.
