### ISSUE TITLE
Hunter package out of date?

### ISSUE THREAD

**Issue by kmader** [Dobiasd/frugally-deep#125]
The package on hunter seems to be out of date (shape3 and tensor3 instead of tensor5/shape5). Would it be possible to update it?

**Comment by Dobiasd** [comment]
Mhh, usually it should update automatically with every release build on Travis.

@headupinclouds do you have any idea?

**Comment by kmader** [comment]
I tried clearing hunter's cache and then everything rebuilt again but it still appears to be out of date files

ls of /Users/kmader/.hunter/_Base/d7d1d54/b59e805/fbdaf95/Install
```bash
ls -hR include/fdeep/
base64.hpp		fdeep.hpp		layers			shape2.hpp		tensor2_pos.hpp
common.hpp		filter.hpp		model.hpp		shape3.hpp		tensor3.hpp
convolution.hpp		import_model.hpp	node.hpp		tensor2.hpp		tensor3_pos.hpp

include/fdeep//layers:
activation_layer.hpp			global_average_pooling_2d_layer.hpp	pooling_2d_layer.hpp
add_layer.hpp				global_max_pooling_2d_layer.hpp		relu_layer.hpp
average_pooling_2d_layer.hpp		global_pooling_2d_layer.hpp		selu_layer.hpp
batch_normalization_layer.hpp		hard_sigmoid_layer.hpp			separable_conv_2d_layer.hpp
concatenate_layer.hpp			input_layer.hpp				sigmoid_layer.hpp
conv_2d_layer.hpp			layer.hpp				softmax_layer.hpp
conv_2d_transpose_layer.hpp		leaky_relu_layer.hpp			softplus_layer.hpp
cropping_2d_layer.hpp			linear_layer.hpp			tanh_layer.hpp
dense_layer.hpp				max_pooling_2d_layer.hpp		upsampling_2d_layer.hpp
elu_layer.hpp				maximum_layer.hpp			zero_padding_2d_layer.hpp
flatten_layer.hpp			model_layer.hpp
```

**Comment by headupinclouds** [comment]
Hi @kmader .  The frugally deep repo is Hunter compatible, but an an updated entry has to be added to the package definitions if you want to use the latest frugally deep version in the upstream Hunter release.  The last entry added was [v0.2.2-p0](https://github.com/ruslo/hunter/blob/6eb80ffb74b2154d9775d5804f37433871c6dd7f/cmake/projects/frugally-deep/hunter.cmake#L16-L21).

hunter/cmake/projects/frugally-deep/hunter.cmake
```
hunter_add_version(
    PACKAGE_NAME frugally-deep
    VERSION 0.2.2-p0
    URL "https://github.com/Dobiasd/frugally-deep/archive/v0.2.2-p0.tar.gz"
    SHA1 330fd9d2177c4b2ac5ebb9ef17bf358a8dfbd62b
)
```

 You have a few options:

* if you are using a fork of Hunter you can just add an entry for the latest release as shown above
* if you want to use the latest frugally deep with the upstream Hunter releases (you aren't maintaining a fork) you have two options:
  - BEST: update the package entry, see [docs](https://docs.hunter.sh/en/latest/creating-new/update.html)
  - QUICK : manage frugally deep as a submodule with `GIT_SUBMODULE`, see [docs](https://docs.hunter.sh/en/latest/user-guides/hunter-user/git-submodule.html?highlight=GIT_SUBMODULE)

I added the package a while ago, but I haven't been using Keras.

**Comment by kmader** [comment]
QUICK solution worked great!!! Thanks
```
Loading model
Loading json ... done. elapsed time: 0.083228 s
Running test 1 of 1 ... done. elapsed time: 1.083874 s
Loading, constructing, testing of ../model.json took 1.586121 s overall.
Speed: 1.07662
```

**Comment by Dobiasd** [comment]
@headupinclouds Ah, so nothing is updated automatically. Sorry. I think I confused it with Conan.

So ideally, with every new release, I would open a pull request in `ruslo/hunter` with a new section added to `cmake/projects/frugally-deep/hunter.cmake`?

**Comment by headupinclouds** [comment]
Yes, that's the basic process.

There is also a CI test step that exercises a range of toolchains in Travis and Appveyor:

See https://docs.hunter.sh/en/latest/creating-new/update.html

**Comment by headupinclouds** [comment]
It would be nice to get the package updated.  If you want to update it, but get stuck somewhere, I can help sometime later this week.

**Comment by Dobiasd** [comment]
OK, I think I understand the process, and I just created a [PR](https://github.com/ruslo/hunter/pull/1753) for this.

I don't believe I would like to do this manual process for every new release. But I'll keep it in mind for the next issue like this. :)

**Comment by Dobiasd** [comment]
@headupinclouds  Urgh, sorry, I did not manage to create a valid pull request on the first attempt. Since I'll not manually update hunter with future requests anyways, I think we can just drop it.

Maybe in that case (me being too lazy for this process) we should remove hunter completely from frugally-deep (and FunctionalPlus) to not produce further confusion of users with older versions. What do you think?

**Comment by kmader** [comment]
That works, but I think having a note and sample repo on how to do it with Hunter would be useful for people already using that, I can set those up.

**Comment by Dobiasd** [comment]
@kmader Sure, if you could provide a correction for the [hunter part of `INSTALL.md`](https://github.com/Dobiasd/frugally-deep/blob/master/INSTALL.md#installation-using-the-hunter-cmake-package-manager) as a pull request, that would be very nice. :slightly_smiling_face:
