### ISSUE TITLE
Exception during check_test_outputs() when loading model in C++

### ISSUE THREAD

**Issue by LukasKn** [Dobiasd/frugally-deep#127]
First of all, thank you for your great work, it's exactly what I was looking for!
However, when I try to load my model in C++, I get an exception.
At the moment I have identified the following problems:

1. When I use `interpolation = 'bilinear'` the model cannot be loaded, the default `nearest` works.
```
input  = keras.engine.input_layer.Input(shape=(256,256,1))
hid   = keras.layers.UpSampling2D(size=(2,2), interpolation='bilinear')(input)
model = keras.Model(input,hid)
```

2. When I train and save the following model, an exception occurs only sometimes. Therefore, I uploaded two files *model_issue.h5* and *model_no_issue.h5*, both are the result of the same model after training with the same data (see below). I think the frequency depends on the number of layers, but I am not sure about that...
[h5_examples.zip](https://github.com/Dobiasd/frugally-deep/files/2914303/h5_examples.zip)
```
input  = keras.engine.input_layer.Input(shape=(256,256,1))
hid = keras.layers.Conv2D(16,kernel_size=(3,3),padding='same', activation='relu', bias_initializer='glorot_uniform')(input)
hid = keras.layers.BatchNormalization()(hid)
hid = keras.layers.Conv2D(16,kernel_size=(3,3),strides=(1, 1), padding='same', activation='relu', bias_initializer='glorot_uniform')(hid)
hid = keras.layers.BatchNormalization()(hid)
hid = keras.layers.MaxPool2D(pool_size=(2,2), strides=(2,2))(hid)         
output = keras.layers.Conv2D(5,kernel_size=(3,3),strides=(1, 1), padding='same', activation='relu', bias_initializer='glorot_uniform')(hid)
model = keras.Model(input,output)
```

All the examples were compiled, trained and saved using:
```
model.compile(loss='mean_squared_error',optimizer='sgd', metrics=['mse'])
input = np.array([1]*256*256*1)
input.shape = (1,256,256,1)`
output = np.array([1]*512*512*1)
output.shape = (1,512,512,1)
model.fit(input,output, epochs=1, batch_size =1)
model.save("PoseNet.h5",include_optimizer = False)
```
Only the output was changed to fit to the required shape.

Do you have any idea how to solve these problems (especially 2.)?
If you need more information, please let me know!
Thanks in advance.

**Comment by LukasKn** [comment]
I am using:
Python 3.6.8
Keras 2.2.4
Tensorflow 1.5.0 (newer versions resulted in exceptions when executing convert_model.py)

**Comment by Dobiasd** [comment]
Hi, and thanks for the positive feedback and the clear error reports. :)

---

> When I use interpolation = 'bilinear' the model cannot be loaded, the default nearest works.

Good catch. Frugally-deep currently only supports `nearest` interpolation. But of course this should produce an error more early in the users workflow, i.e., not when loading the converted model in C++, but instead already when trying to convert the model from `h5` to `json`. I just pushed a [commit implementing such a check in `convert_model.py`](https://github.com/Dobiasd/frugally-deep/commit/e0672409e9a8fb7c011d984f8d3628e3a32757ba).

---

> When I train and save the following model, an exception occurs only sometimes.

That's interesting. I just downloaded your `h5`-format models and converted both multiple times successfully using `convert_model.py`. You can find the resulting `json` files here: https://www.dropbox.com/s/skbx1n8juqxs8db/fdeep_issue_127_converted_models.zip?dl=1
I'm using the latest version of frugally-deep and currently have the following things installed:

```
$ python3 --version
Python 3.6.8
```

```
$ python3 -c 'import tensorflow as tf; print(tf.__version__)'
1.13.1
```

```
$ python3 -c 'import keras; print(keras.__version__)'
2.2.4
```

---

> I am using:
> Python 3.6.8
> Keras 2.2.4
> Tensorflow 1.5.0 (newer versions resulted in exceptions when executing convert_model.py)

Can you please try again updating to the latest TensorFlow version. If you still encounter exceptions when applying `convert_model.py`, please post the exact exception verbatim, including the traceback.

**Comment by LukasKn** [comment]
Thank you for your quick response!

>That's interesting. I just downloaded your `h5`-format models and converted both multiple times successfully using `convert_model.py`. 

When I try to load your `json` files in C++ the results are the same: 
model_issue.json cannot be loaded, model_no_issue.json works fine.

>Can you please try again updating to the latest TensorFlow version. If you still encounter exceptions when applying `convert_model.py`, please post the exact exception verbatim, including the traceback.

After upgrading tensorflow to version 1.13.1 I get an error when calling convert_model.py:
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RoboticUser\Desktop\frugally_deep\frugally-deep-master\keras_export\convert_model.py", line 11, in <module>
    import keras
  File "C:\Program Files\Python36\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Program Files\Python36\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Program Files\Python36\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Program Files\Python36\lib\site-packages\keras\backend\__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "C:\Program Files\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```
But this exception occurs even when simply importing tensorflow, so that seems to be a problem of my installation and not of frugally-deep.
I have installed tensorflow via `pip install tensorflow` and checked for updates with `pip install --upgrade tensorflow`.

**Comment by Dobiasd** [comment]
Ah, OK. Sorry, seems like I misunderstood. So the issue with `model_issue` is not mainly when converting, but when loading in C++.

I am afk now, but will try to reproduce when I am back online, which will be on Tuesday.

---

Regarding the dll-load problem when importing TensorFlow, I unfortunately can not help. But maybe stackoverflow can.

**Comment by LukasKn** [comment]
My old Intel Xeon CPU X5470 does not support AVX, which seems to be the problem for tensorflow 1.6 and newer. I will try to run my project on another computer (with the latest tensorflow version) in the next days...
I hope this fixes the problem.
If you have further ideas, please let me know.
Thank you for your support!

**Comment by LukasKn** [comment]
>Ah, OK. Sorry, seems like I misunderstood. So the issue with `model_issue` is not mainly when converting, but when loading in C++.

Exactly, all exceptions occur when executing load_model().

**Comment by Dobiasd** [comment]
Ah, OK. Yeah, I misunderstood your original post. So in that case I guess there is no need to update your TensorFlow version.

I'll try to load `model_issue.json` with frugally-deep in C++.

In the meantime you can try if using the following helps:

```cpp
#define FDEEP_FLOAT_TYPE double
#include <fdeep/fdeep.hpp>
```

**Comment by LukasKn** [comment]
>In the meantime you can try if using the following helps:
#define FDEEP_FLOAT_TYPE double
#include <fdeep/fdeep.hpp>

Unfortunately, this doesn't solve the problem.

**Comment by Dobiasd** [comment]
The exception you encounter means, that the output on some fixed test inputs is different in C++ compared to Python. Maybe the difference is small. Try to increase `verify_epsilon` in your call to `fdeep::load_model`. Or, of course, you can even set `verify` to `false` to just use the model without running the tests.

That's all I can do for you from just my phone. ;)
On Tuesday I'll look into it. But maybe the proposed workaround can unblock you already.

**Comment by LukasKn** [comment]
I have already compared these two outputs, but that was before I removed bilinear interpolation. Now it seems to fit quite well.
Thank you again!

**Comment by Dobiasd** [comment]
`model_issue` does not use an `UpSampling2D` layer. How can the problem be related to the interpolation method?

**Comment by LukasKn** [comment]
I tested my real model, but I think it's similar with the example above, nevertheless I will check the difference of the outputs tomorrow.

**Comment by LukasKn** [comment]
The outputs of `model_issue` are very similar, when I print the message which is raised during `check_test_outputs` in `import_model.hpp` they are identical, so at least the first three digits after the decimal point are the same.

I think, the interpolation and the very small `verify_epsilon` caused the issue, but now everything seems to work fine.

Thank you for your help!

**Comment by Dobiasd** [comment]
Glad to hear that. Hope the rest of you experience with the library will be smoother. :)

**Comment by Dobiasd** [comment]
Just for the sake of completeness: I tried to reproduce the failing tests on my system with the two provided models and the default `verify_epsilon`, but was unable to do so. It worked without error:

```cpp
#include <fdeep/fdeep.hpp>
int main()
{
    const auto model_no_issue = fdeep::load_model("model_no_issue.json");
    const auto model_issue = fdeep::load_model("model_issue.json");
}
```

```
Loading json ... done. elapsed time: 0.039810 s
Running test 1 of 1 ... done. elapsed time: 0.067844 s
Loading, constructing, testing of model_no_issue.json took 0.113216 s overall.
Loading json ... done. elapsed time: 0.012148 s
Running test 1 of 1 ... done. elapsed time: 0.062010 s
Loading, constructing, testing of model_issue.json took 0.077864 s overall.
```

But these marginal floating-point differences could be caused by different things like
- TensorFlow version
- CPU vs. GPU
etc.

However I guess with catching the non-supported `interpolation = 'bilinear'` early and the process, we can leave this issue closed. :)
