### ISSUE TITLE
model.predict to float

### ISSUE THREAD

**Issue by bforland** [Dobiasd/frugally-deep#128]
Hello,

I've got everything working, but I have missed something simple and I can't seem to figure it out. predict() return as a tensor5 for me, but I can't figure out how to get the results into floats.

fdeep::shape5 tensor5_shape_2(1, 1, 1, 1, 6);
fdeep::tensor5 test_values(tensor5_shape_2, 0.0f);
const auto result = model.predict({tensor, test_values});
std::cout << fdeep::show_tensor5s(result) << std::endl;

Those lines work, and I get the output:

...
[[[[0.1421]]]]
[[[[0.1499]]]]
[[[[0.1343]]]]
[[[[0.1396]]]]
[[[[0.1562]]]]
...

Is there a simple way to convert "result" in this example to the values in the tensor as vector<float>?

Thanks

**Comment by Dobiasd** [comment]
Yes, you can do
```cpp
const std::vector<float> result_vec = *result.front().as_vector();

**Comment by Dobiasd** [comment]
Oh, and I just saw [your comment on one of the example gists](https://gist.github.com/Dobiasd/8f41ef8bf4198ab535060a78b53f2008#gistcomment-2836723). Sorry for not answering. I did not receive a notification. [Hopefully this behavior of GibHub will change at some point](https://github.com/isaacs/github/issues/21). ;)

**Comment by bforland** [comment]
No worries, figured them both out, but thank you for responding. Your
software is awesome!
