### ISSUE TITLE
Problem on loading model

### ISSUE THREAD

**Issue by jodumagpi** [Dobiasd/frugally-deep#134]
I trained a VGG16 network using Keras. I was able to convert the .h5 model to a .json one using the keras_export/convert_model.py.

However, when I load the model in Visual Studio it seems to get stuck there. I tried waiting and nothing happens (actually it seems to be stuck) for as long as 11 minutes until I just stop the program. What could be the reason for this?

[my model](https://drive.google.com/open?id=1ZR1osEzjpF8lm7-NvcUftwSRLMLoHNMO)

**Comment by Dobiasd** [comment]
Hi Jo,

Maybe you did not tell your C++ compiler to optimize for speed, and thus running the program takes extremely long? In case of Microsoft Visual C++, you need to compile your project not in "Debug" mode but in "Release" mode, and then run it without the debugger attached.

**Comment by jodumagpi** [comment]
Hey. Thanks for the prompt reply. That was definitely the case. I was able to load it in Release mode. I have another concern though. When I try to use model.predict() it's throwing an exception std::runtime_error at memory location. I'm pretty sure I'm using the same type of images I used in training.

**Comment by Dobiasd** [comment]
> By the way, I used your simple code for predicting from a single image loaded using OpenCV.

Yes, please see here: https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#how-to-use-images-loaded-with-opencv-as-input-for-a-model

Maybe this also fixes your `std::runtime_error`.

**Comment by jodumagpi** [comment]
Yes, I used the exact code. I also placed the " #define FDEEP_FLOAT_TYPE double " before I include the header. I still get the same runtime_error. Can you check if you also get this error? I put a download link to my model above.

**Comment by Dobiasd** [comment]
Does the `std::runtime_error` has any message attached to it?

Also, can you please provide a minimal example code to reproduce the issue?

**Comment by jodumagpi** [comment]
Hi. Sorry for the delayed response. So here is the code I used which I believe is basically the same as the example you gave.

```
// test_frugally_deep.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include <fdeep/fdeep.hpp>
#include <opencv2/opencv.hpp>
#include <stdio.h>

int main()
{
	const cv::Mat image = cv::imread("image.jpg");
	cv::cvtColor(image, image, cv::COLOR_BGR2RGB);
	assert(image.isContinuous());
	const auto model = fdeep::load_model("fdeep_model.json");
	// Use the correct scaling, i.e., low and high.
	const auto input = fdeep::tensor5_from_bytes(image.ptr(),
		static_cast<std::size_t>(image.rows),
		static_cast<std::size_t>(image.cols),
		static_cast<std::size_t>(image.channels()),
		0.0f, 1.0f);

	const auto result = model.predict_class({ input });
	std::cout << result << std::endl;
    return 0;
}
```

This is the error that I am getting.
![image](https://user-images.githubusercontent.com/24381086/56018465-2a905100-5d3d-11e9-9079-736190d79014.png)

And it is pointing to this part
![image](https://user-images.githubusercontent.com/24381086/56018517-4f84c400-5d3d-11e9-94f4-ec7eed2d48e7.png)

I'm still not able to figure this out.

**Comment by Dobiasd** [comment]
The size image of the image you are using does not match the input shape of your model.

Your model takes tensors of shape (224, 224, 3) as input. Please make sure your image is 224x224 and color (3 channels) instead of gray (1 channel).

Also the `std::runtime_exception` that is thrown at the position contains a message. If you inspect with your debugger, or just run the application normally in the terminal, you will see it.

For example, trying to invoke your model with a 640x480 grayscale image results in the following output (g++, Linux).

```
Loading json ... done. elapsed time: 3.014115 s
Running test 1 of 1 ... done. elapsed time: 0.730980 s
Loading, constructing, testing of /home/tobias/Documents/coding/CPP/frugally-deep/experiments/fdeep_issue_134/model.json took 4.902470 s overall.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Invalid inputs shape.
The model takes [(Just 1, Just 1, Just 224, Just 224, Just 3)] but provided was: [(1, 1, 480, 640, 1)]
Aborted
```

Instead of now just fixing your image to have the right resolution, I recommend you find out how you can see the informations (shown above) on your system (MSVC, Windows), because knowing how to log/ debug exceptions properly will help you in the future.
