### ISSUE TITLE
Does it support spp layer which may be self-defined

### ISSUE THREAD

**Issue by WigenTang** [Dobiasd/frugally-deep#138]
In my works, I want to apply the Spatial Pyramid Pooling (spp) before dense. So does this project support the spp layer which is self-defined as the "https://github.com/yhenon/keras-spp/blob/master/spp/SpatialPyramidPooling.py". 

Thank you a lot. 

Best wishes

**Comment by Dobiasd** [comment]
Hi Wigen,

the `SpatialPyramidPooling` is not supported out-of-the-box by frugally-deep, and very likely will not be supported, as long as it is not a standard Keras layer.

But if you re-implement it in C++, you can inject support for it into the the library without modifying it's internals. I just added a new paragraph to the FAQ, explaining how to do this: [How to use lambda/custom layers?](https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#how-to-use-lambdacustom-layers)

**Comment by WigenTang** [comment]
Thank you a lot
