### ISSUE TITLE
make: *** No targets specified and no makefile found.  Stop.

### ISSUE THREAD

**Issue by willychang21** [Dobiasd/frugally-deep#143]
I'm trying to install `frugally-deep` step by step.
but THERE ARE SOME ERROR

```
C:\Users\竣傑>git clone https://github.com/Dobiasd/FunctionalPlus
Cloning into 'FunctionalPlus'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 8482 (delta 1), reused 4 (delta 0), pack-reused 8473 eceiving objects: 100% (848
Receiving objects: 100% (8482/8482), 2.17 MiB | 372.00 KiB/s, done.
Resolving deltas: 100% (5691/5691), done.

C:\Users\竣傑>cd FunctionalPlus

C:\Users\竣傑\FunctionalPlus>mkdir -p build && cd build

C:\Users\竣傑\FunctionalPlus\build>cmake ..
-- Building for: Visual Studio 15 2017
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
-- The C compiler identification is MSVC 19.16.27031.1
-- The CXX compiler identification is MSVC 19.16.27031.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ===( FunctionalPlus 0.2.3 )===
-- Building Unit Tests OFF
-- Use conan OFF
-- Building examples ON
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/竣傑/FunctionalPlus/build

C:\Users\竣傑\FunctionalPlus\build>make && sudo make install
make: *** No targets specified and no makefile found.  Stop.
```
What did I miss ??

**Comment by Dobiasd** [comment]
This issue might also belong in the [FunctionalPlus repository](https://github.com/Dobiasd/FunctionalPlus). :slightly_smiling_face:

Anyways, your steps seem totally correct.

Could you please check if after `cmake ..`, there is `Makefile` in `C:\Users\竣傑\FunctionalPlus\build>`?

Maybe try in a directory consisting just of plain ASCII characters. :man_shrugging:

**Comment by willychang21** [comment]
I check the `build` file.
![image](https://user-images.githubusercontent.com/38349902/59284135-52008d00-8c9e-11e9-9459-f24f1fef304f.png)
`Makefile` is in `C:\Users\willy\FunctionalPlus\build>`
I try in a directory consisting just of plain ASCII characters but still the same.

**Comment by Dobiasd** [comment]
Can you show the content of your makefile?

Or you could try one of the other install possibilities: https://github.com/Dobiasd/FunctionalPlus/blob/master/INSTALL.md

**Comment by Dobiasd** [comment]
Ah, I see you are using MSVC++. Maybe just copy (or point your compiler manually to) the directory with the header files. Cmake/make under windows (instead of Linux) is sometimes quite complicated.

**Comment by willychang21** [comment]
sorry I don't know how to copy (or point your compiler manually to) the directory with the header files.
:disappointed_relieved::disappointed_relieved:
Is there a simple way to install `frugally-deep`?
because I saw the `INSTALL.md`  but I still can't figure it out (I almost spent 1 day :sleepy::sleepy:)
(I had alreay trained a LSTM model by keras but I still don't know how to import to my c++ project.

**Comment by Dobiasd** [comment]
> sorry I don't know how to copy (or point your compiler manually to) the directory with the header files.

If you want to develop a project using C++, I strongly recommend learning these basics first.

> Is there a simple way to install frugally-deep?

This already is a quite simple way. Many other libraries are not header-only but require building `.lib` files and linking against them, which is much more complicated.

---

So your problem is not related to frugally-deep or to FunctionalPlus, but related to "How to use a (header-only) library in Visual C++". This I'll close this issue here, and wish you look in googling, reading and stackoverflowing. :grimacing:
