### ISSUE TITLE
Crash on LSTM layer with return_state (was "Problem with Feeding Sequences into fdeep::Tensor5 data structure")

### ISSUE THREAD

**Issue by MarlonCajamarca** [Dobiasd/frugally-deep#145]
Hello, I am working with LSTM Encoder-Decoder Architecture for Vehicle Trajectory Forecasting. I created both models in Python/Keras/Tensorflow using the functional API. The model receives a fixed-length sequence of past trajectories {t-2, t-1, t} (sequence of bounding boxes coordinates) and produces a fixed-length sequence of future trajectories {t+1, t+2, T}. The models were instantiated separately for the inference/prediction phase, however, they were trained together using teacher forcing. There is no error when converting both encoder and decoder models 

For example, I trained the models to receive the last 10 box positions (given directly from YOLOV3), and produce the next 10 box positions. Therefore, the input shape will be (batch_size, num_timesteps, num_features), assuming batch_size = 1, the input shape will be (1,10,4), where 4 indicates the number of features (x, y, width, height) for each bounding box.   

Models creation in Python/Keras:
### Encoder
![image](https://user-images.githubusercontent.com/29712145/59641186-337b1580-9126-11e9-97be-306263f0dde1.png)
### Decoder
![image](https://user-images.githubusercontent.com/29712145/59641203-4e4d8a00-9126-11e9-8817-f7b8aeda8312.png)
Instantiating inference models:
### Encoder + Decoder for Inference:
![image](https://user-images.githubusercontent.com/29712145/59641343-ccaa2c00-9126-11e9-8587-c3bbe34202bc.png)

I am new to C++ but the main issue is when creating a `fdeep::tensor5` to store sequences with `fdeep::shape5 = (1, 1, batch_size, num_seqs, num_features)`... the generated tensors have some axis swapped when creating the tensor5 and, therefore, sequences cannot be read by the model. This is the cpp main file where I am trying to get the encoder LSTM working before start with decoder's model:
![image](https://user-images.githubusercontent.com/29712145/59644597-38929180-9133-11e9-9c62-3803dd7ce7a2.png)
Throwing this error in the creation of the appropriate (1, 1, batch_size, num_seqs, num_features) but creating tensor with shape = (1, 1, batch_size, num_features, num_seqs):
![image](https://user-images.githubusercontent.com/29712145/59644649-6d064d80-9133-11e9-8cd5-e6f34478c069.png)
I changed to `fdeep::shape5 = (1, 1, batch_size, num_features, num_seqs)` and I obtained the correct shapes:
![image](https://user-images.githubusercontent.com/29712145/59644756-ed2cb300-9133-11e9-8156-5e669ef455d7.png)
Obviously, the model did not recognize the input tensor shape because the shape did not match with the previously trained models. 
![image](https://user-images.githubusercontent.com/29712145/59644833-50b6e080-9134-11e9-8e8e-50181ee66916.png)

This is the LSTM-based encoder model I am trying to use: 
https://drive.google.com/open?id=1YBx8Gmmg2xw1WCRmBC_E3R2R7ZBfdLBW

I really appreciate any guidance about how can I embed the sequences into the right-shaped tensor5 structures. Maybe this could be a C++ related question or some misunderstanding about the functionality of the `fdeep::tensor5`. 

Thanks in advance :)

**Comment by Dobiasd** [comment]
Hi Marlon,

thanks for the very clear report.

I downloaded your model and tried it out with the following minimal example code:

```cpp
#include <fdeep/fdeep.hpp>
int main()
{
    const auto model = fdeep::load_model("fdeep_encoder_model_NT.json");
    const fdeep::tensor5s inputs = {fdeep::tensor5(fdeep::shape5(1, 1, 1, 10, 4), 0)};
    const auto outputs = model.predict(inputs);
    std::cout << fdeep::show_tensor5s(outputs) << std::endl;
}
```

I think your attempt and your understanding of shapes is correct.

However I also get:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  invalid tensor index
```

This exception is thrown from [here](https://github.com/Dobiasd/frugally-deep/blob/ceea8ec94521213a99fed07ae280b993260b3912/include/fdeep/layers/layer.hpp#L78-L79), which is inside `fdeep::model::predict`. It has nothing to do with how you initialize the input. It's something much "later" and deeper in the library.

Are you allowed to post the full Keras model, and a minimal Python code, which creates its architecture, so I can reproduce the conversion step locally?

**Comment by MarlonCajamarca** [comment]
Hi Dobias,

Thanks for your fast response!

Of course yes, I could share minimal Python/Keras scripts I used to train and test both models (encoder and decoder). Something I noticed was that I exported the models using `convert_model.py` and it initially failed (when I did not use `--no-test` flag) then I exported the model successfully using no_tests (`--no-tests` flag).

Here are the Keras/Tensorflow scripts for training and testing, at your dispose to be downloaded:
Training Script:

Inference Script:

**Comment by Dobiasd** [comment]
I don't think you have a problem with swapped axis.
`fdeep::shape5(1, 1, 1, 10, 4)` matches what you have in Python. Also, if I read your initial post correctly, this version triggers the prediction correctly and does not result in a shape error. With `fdeep::shape5(1, 1, 1, 4, 10)` however you get an `Invalid inputs shape` exception.

So the reason is something else. The fact that you had to use `--no-tests` already is fishy. This flag is meant to models resulting in minor numerical errors. In your case, we have an actual problem with the links inside the computational graph. Avoiding the tests only delays the surfacing of the problem from the testing phase, ran in `load_model`, to the prediction phase.

I'll try to find out what is going on using the files you provided and then get back to you.

**Comment by Dobiasd** [comment]
Ah, now I understand what you mean with the shapes. There was a bug in `show_tensor5`. I just [fixed](https://github.com/Dobiasd/frugally-deep/commit/7923c725d25ad8038c467ccd96004682b4241ef4) it. With the latest version this:

```cpp
std::cout << fdeep::show_tensor5s({fdeep::tensor5(fdeep::shape5(1, 1, 1, 10, 4), 0)}) << std::endl;
```

will correctly print:
```
[[[[[[[0.0000, 0.0000, 0.0000, 0.0000], [0.0000, 0.0000, 0.0000, 0.0000], [0.0000, 0.0000, 0.0000, 0.0000], [0.0000, 0.0000, 0.0000, 0.0000], [0.0000, 0.0000, 0.0000, 0.0000], [0.0000, 0.0000, 0.0000, 0.0000], [0.0000, 0.0000, 0.0000, 0.0000], [0.0000, 0.0000, 0.0000, 0.0000], [0.0000, 0.0000, 0.0000, 0.0000], [0.0000, 0.0000, 0.0000, 0.0000]]]]]]]
```

Sorry for the inconvenience. And thanks a lot for finding this problem. It's kind of funny that I never realized it up to now.

---

So, with that out of the way, it's every more clear that you made no mistake. I'll check what's wrong with the computational graph.

**Comment by Dobiasd** [comment]
FYI: I've reduces the problem to a more minimal example and reproduced the error with it:

```python3
from keras.layers import Input, LSTM, Dense, TimeDistributed
from keras.models import Model

latent_dim = 512
input_feature_vect_length = 4
output_feature_vect_length = 4

encoder_inputs = Input(shape=(None, input_feature_vect_length))
encoder_LSTM = LSTM(units=latent_dim, return_state=True)
encoder_outputs, state_h, state_c = encoder_LSTM(encoder_inputs)
encoder_states = [state_h, state_c]

decoder_inputs = Input(shape=(None, output_feature_vect_length))
decoder_LSTM = LSTM(units=latent_dim, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_LSTM(decoder_inputs, initial_state=encoder_states)
decoder_dense_hidden = TimeDistributed(Dense(512, activation="linear"))
decoder_dense_hidden_2 = TimeDistributed(Dense(32, activation="linear"))
decoder_dense = TimeDistributed(Dense(output_feature_vect_length, activation="linear", name="dec_dense_out"))

decoder_outputs_dense = decoder_dense_hidden(decoder_outputs)
decoder_outputs_dense_2 = decoder_dense_hidden_2(decoder_outputs_dense)
decoder_outputs = decoder_dense(decoder_outputs_dense_2)

encoder_model = Model(inputs=encoder_inputs, outputs=encoder_states)
encoder_model.save("minimal_encoder_model.h5")
```

```bash
python3 convert_model.py minimal_encoder_model.h5 minimal_encoder_model.json
```

```cpp
#include "fdeep/fdeep.hpp"
int main()
{
    const auto model = fdeep::load_model("minimal_encoder_model.json");
}
```

```text
Running test 1 of 1 ... terminate called after throwing an instance of 'std::runtime_error'
  what():  invalid tensor index
Aborted
```

Next step is to make it even more minimal such that the problem hopefully surfaces. :)

**Comment by Dobiasd** [comment]
OK, I found the problem.

The LSTM implementation of frugally-deep does support `return_sequences`, but not `return_state`.

Of course, this should not fail that obscurely in C++. Instead, it should fail with a clear error message earlier in `convert_model.py`. I just pushed [a commit](https://github.com/Dobiasd/frugally-deep/commit/06edb35945d410d61e942bdf68241e234781826d) adding exactly this check.

While this will avoid future users spending too much time when running into the problem, it, of course, does not solve your problem at hand.

Is there a chance for you to derive a model with `return_state` being `False` for exporting to frugally-deep, while still providing the functionality you need?

The alternative is to try to add support for LSTM layers with `return_state` to frugally-deep.

**Comment by Dobiasd** [comment]
@n-Guard Since you did such a great job on implementing `LSTM` layers for frugally-deep. What do you think about the feasibility adding support for `return_state`?

**Comment by MarlonCajamarca** [comment]
Hi Dobias,

Thank you for your detailed and timed response! 
It is great to help you spot the issues with the `LSTM` and `fdeep::show_tensor5`. Really thanks for the information about the `return_states` incompatibility as the root cause of the issue with running the models with frugally-deep. 

Actually, the decoder LSTM needs to make future predictions based on these returned states, previously obtained as the output of the encoder LSTM. Both LSTMs are using `return_states = True`, the encoder LSTM by processing input sequences of bounding boxes and producing a set of hidden states to be feed to decoder LSTM, which also receives past hidden states and returns new ones **in order to make long-term predictions at each output timestep**.

It would be awesome to try again once this new functionality is added to frugally-deep. For the time, I would explore other ways to embed the current models into a C++ custom application.

Thanks for your help and feedback information. Surely, I will keep the eye over this issue (and frugally in general). By the way, great job with frugally-deep :1st_place_medal:

**Comment by n-Guard** [comment]
Hi @Dobiasd, hi @MarlonCajamarca,

in principle it should not be that difficult to add this functionality.
I think these are the states that have to be returned after the last timestep was processed (i.e. when the loop has finished):
https://github.com/Dobiasd/frugally-deep/blob/06edb35945d410d61e942bdf68241e234781826d/include/fdeep/recurrent_ops.hpp#L154-L155

I will have a further look into this but I'm not absolutely sure if or when I have time to implement this feature.

**Comment by Dobiasd** [comment]
@n-Guard Thanks. That sounds like I might be able to do it on my own if you currently don't have the time for it. When starting, I'll open a feature branch for it and ideally verify the correctness by adding tests. In case I need a review, I'll bother you again. :grin:

**Comment by Dobiasd** [comment]
@MarlonCajamarca I just added support for LTSM layers with `return_state`. If you are still interested, you can clone the latest version from the `master` branch and check if this works for you. :tada:

@n-Guard Thanks again for the hint. Adding support was straightforward. :slightly_smiling_face:

**Comment by MarlonCajamarca** [comment]
Hi @Dobiasd and @n-Guard! Many thanks for adding the support to LSTM cell. Of course, I will give it a try and post some feedback about the results. Thanks!

**Comment by MarlonCajamarca** [comment]
Hi @Dobiasd 
After some experiments, the LSTM-Based encoder and decoder models are not giving me any problem related to `returned_states = True` or `show_tensor5`, confirming frugally-deep fixes worked. However, I have been trying to replicate the results I obtained using the Keras/Tensorflow models without success.

The frugally-deep `fdeep_encoder_model_NT` is returning the exact same `encoder_hidden_state` and `encoder_cell_state` states compared to its Tf + Keras counterparts using the `encoder_model.hdf5`. However, the `fdeep_decoder_model_NT` is not giving me the same `decoder_hidden_state` and `decoder_cell_state` output states (compared to the results using Tf + Keras `encoder_model.hdf5`) :(

Specifically, I develop the decoder inference model using TF + Keras ([please refer yourself to past comments in this issue to see the corresponding code](https://github.com/Dobiasd/frugally-deep/issues/145#issuecomment-503313963)), and then converted it from .hdf5 to .json, ready to be ported into the C++ application (same as with the encoder model). Validating the encoder states:
![image](https://user-images.githubusercontent.com/29712145/60611686-82fb4b80-9d8c-11e9-8a3f-5b58c1fdecb3.png)
However, both frugally-deep `decoder_hidden_state` and `decoder_cell_state` differ from corresponding Keras-based `decoder_hidden_state` and `decoder_cell_state`:
![image](https://user-images.githubusercontent.com/29712145/60611757-af16cc80-9d8c-11e9-9e9e-4902caad4499.png)
Resulting, as expected, in a wrong bounding box prediction:
![image](https://user-images.githubusercontent.com/29712145/60612114-8d6a1500-9d8d-11e9-9283-0b53053e6ff4.png)
which does not match with the corresponding Keras Results:
![image](https://user-images.githubusercontent.com/29712145/60619895-54d33700-9d9f-11e9-8f50-07c4fb3baf6d.png)
I do not really know about what is happening with `fdeep_decoder_model_NT`, so I have various options in mind:
* I have trained another model using `LSTM` instead `CuDNNLSTM` layers in order to check if the problem is with `CuDNNLSTM` layer implementation. However, the problem is still present when using other LSTM-based cells like `CuDNNLSTM` and `LSTM`. The `fdeep_encoder_model` works well but `fdeep_decoder_model` is still making wrong predictions (both at states returned and next bbox prediction).
* Now I am working in the `main.cpp` file. Maybe the problem is inside my internal manipulation of `fdeep::tensor5` and `fdeep::tensor5s` when feeding the data into the ported models. However, both models are working well, except that the decoder's model is making (inaccurate) predictions of future bounding boxes, but it did not crash in any step of the script execution.

Here is the main.cpp file I am running to test the results. Any comment would be welcomed!

```javascript
#include <fdeep/fdeep.hpp>
#include <vector>
#include <fstream>
#include <iostream>

int main()
{
	// Loading the previously trained models
	const auto encoder_model = fdeep::load_model("fdeep_encoder_model_NT.json");
	std::cout << "Encoder Model Loaded!" << std::endl;
	const auto decoder_model = fdeep::load_model("fdeep_decoder_model_NT.json");
	std::cout << "Decoder Model Loaded!" << std::endl;
	// Batch_size = 1, num_timesteps = 10 and num_features = 4
	fdeep::shape5 in_traj_shape(1,1,1,10,4);
	// Loading a sample sequence trajectory into tensor5 data structure
	const std::vector<float> src_traj  = {1728, 715, 191, 221,
						1717, 710, 202, 215,
					        1706, 704, 206, 198,
						1695, 700, 217, 196,
						1687, 696, 228, 183,
						1680, 689, 240, 181,
						1668, 668, 240, 198,
						1661, 668, 243, 194,
						1650, 664, 251, 189,
						1635, 660, 266, 181};
	// Input trajectory from vector to tensor5 data structure
	const fdeep::shared_float_vec shared_traj(fplus::make_shared_ref<fdeep::float_vec>(src_traj));
	const fdeep::tensor5 encoder_inputs(in_traj_shape, shared_traj);
	std::cout << "Trajectory #0!" << std::endl;
	std::cout << fdeep::show_tensor5(encoder_inputs) << std::endl;
	// Using loaded encoder model to predict encoder output states
	// Then encoder_states can be feed as input tensors into decoder_model
	const auto encoder_states = encoder_model.predict({encoder_inputs});
	// Getting the encoder's last hidden state values
	// Converting encoder_states from from fdeep::tensor5s into separate fdeep::tensor5 data structures
	// When training we use latent dimension (number of neurons in LSTM) = 512
	fdeep::shape5 LSTM_latent_dim(1,1,1,1,512);
	fdeep::tensor5 h_enc(LSTM_latent_dim, 0);
	fdeep::tensor5 c_enc(LSTM_latent_dim, 0);
	// Getting the data from encoder_states and filling previously initialized h_enc and c_enc fdeep::tensor5
	for (int i = 0; i < 512; ++i)   {   
                 h_enc.set(0,0,0,0,i, encoder_states.at(0).get(0,0,0,0,i));
		 c_enc.set(0,0,0,0,i, encoder_states.at(1).get(0,0,0,0,i)); }
	// Printing for debbuging purposes
	std::cout << "h_enc: "<< fdeep::show_tensor5(h_enc) << std::endl;
	std::cout << "c_enc: "<< fdeep::show_tensor5(c_enc) << std::endl;
	// Creating a SOS input sequence token to signal decoder model to start making predictions
	fdeep::shape5 bbox_shape(1,1,1,1,4);
	// Loading a sample sequence trajectory into tensor5 data structure
	const std::vector<float> SOS_token  = {9999.0, 9999.0, 9999.0, 9999.0};
	const fdeep::shared_float_vec shared_SOS_token(fplus::make_shared_ref<fdeep::float_vec>(SOS_token));
	fdeep::tensor5 target_seq(bbox_shape, shared_SOS_token);
	std::cout << fdeep::show_tensor5(target_seq) << std::endl;
	// In Python we have: Prediction, h, c = decoder_model.predict([target_seq] + state)
	auto decoder_outputs = decoder_model.predict({target_seq, h_enc, c_enc});
	// Getting the results into separate fdeep::tensor5 data structures
	fdeep::tensor5 prediction(bbox_shape, 0);
	fdeep::tensor5 h_dec(LSTM_latent_dim, 0);
	fdeep::tensor5 c_dec(LSTM_latent_dim, 0);
	// Setting resulting hidden states into corresponding tensors
	for (int i = 0; i < 512; ++i)     { 
                  h_dec.set(0,0,0,0,i, decoder_outputs.at(1).get(0,0,0,0,i));
		  c_dec.set(0,0,0,0,i, decoder_outputs.at(2).get(0,0,0,0,i)); }
	// Printing for debugging purposes
	std::cout << "h_dec: "<< fdeep::show_tensor5(h_dec) << std::endl;
	std::cout << "c_dec: "<< fdeep::show_tensor5(c_dec) << std::endl;
	// Setting next bbox prediction results into corresponding Tensor
	for (int i = 0; i < 4; ++i)      {
                  prediction.set(0,0,0,0,i, decoder_outputs.at(0).get(0,0,0,0,i)); }
	std::cout << "Predicted next bounding box!" << fdeep::show_tensor5(prediction) << std::endl;
}
```
The `fdeep_encoder_model_NT.json` model imported into the C++ application is avaliable to dowload and inspect [from this past comment](https://github.com/Dobiasd/frugally-deep/issues/145#issuecomment-503313963). The `fdeep_decoder_model_NT.json` can be downloaded from the following link:
Decoder model: 
https://drive.google.com/open?id=1hwrjcnNfWaqQI0o8TmJKtfsAwj6zd9aq
I would really appreciate any help with this issue. I am puzzled because the encoder model is working perfectly but the decoder model does not, specifically, the results between the Keras vs Frugally decoder models differ, giving me wrong output predictions that cannot be used at all.
