### ISSUE TITLE
Unknown Initializer 

### ISSUE THREAD

**Issue by RajarshiRoy2** [Dobiasd/frugally-deep#146]
Hi,

When I run python convert_model/convert_model.py my_mode.h5 fdeep_model.json, I always get an error saying unknown initializer:GlorotUniform. Do I need to change my code? 

Thanks,
Raj

**Comment by Dobiasd** [comment]
Hi Raj,

in case you have not yet tried, maybe the following helps:
- Update your TensorFlow version to the recent one (`1.14.0`).
- Update your Keras version to the recent one (`2.2.4`).
- Store the `h5` file again.
- Try to run `convert_model.py` again.

In case this does not help, or you can for some reason not update, please let me know your Keras version, your Tensorflow version, and if possible upload the `h5` file, so I can check if I can reproduce the problem on my machine and find a solution.

**Comment by RajarshiRoy2** [comment]
yes. I checked the versions on Pycharm and it is Tensor flow as 1.14.0 and Keras is 2.2.4. I am attaching my H5 model here. 
[my_model2.zip](https://github.com/Dobiasd/frugally-deep/files/3346385/my_model2.zip)

**Comment by Dobiasd** [comment]
Thanks. I just tested loading your model, and your issue seems to be unrelated to frugally-deep.

I can not even simply load your model:

```
>>> import keras
Using TensorFlow backend.
>>> import tensorflow as tf
>>> from keras.models import load_model
>>> print(tf.__version__)
1.14.0
>>> print(keras.__version__)
2.2.4
>>> load_model('my_model2.h5')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.7/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.7/dist-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/sequential.py", line 300, in from_config
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.7/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.7/dist-packages/keras/utils/generic_utils.py", line 147, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 1109, in from_config
    return cls(**config)
  File "/usr/local/lib/python3.7/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/keras/layers/core.py", line 848, in __init__
    self.kernel_initializer = initializers.get(kernel_initializer)
  File "/usr/local/lib/python3.7/dist-packages/keras/initializers.py", line 508, in get
    return deserialize(identifier)
  File "/usr/local/lib/python3.7/dist-packages/keras/initializers.py", line 503, in deserialize
    printable_module_name='initializer')
  File "/usr/local/lib/python3.7/dist-packages/keras/utils/generic_utils.py", line 138, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown initializer: GlorotUniform
```

Please double-check this by running the following code on your machine:

```python3
import keras
import tensorflow as tf

from keras.models import load_model

print(tf.__version__)
print(keras.__version__)

load_model('my_model2.h5')
```

In case it succeeds on your system, we have a *really* interesting problem here. :)

**Comment by RajarshiRoy2** [comment]
I cannot do load_model('my_model2.h5') but I do model = tf.keras.models.load_model('my_model2.h5') where I load my model. Is there a difference? I get warning like this below: 

C:\Users\rroy\AppData\Local\Programs\Python\Python37\python.exe C:/Users/rroy/Desktop/testmodel.py
Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
1.14.0
2.2.4
W0701 12:17:03.921163 21512 deprecation.py:506] From C:\Users\rroy\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\init_ops.py:97: calling GlorotUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0701 12:17:03.921163 21512 deprecation.py:506] From C:\Users\rroy\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0701 12:17:03.921163 21512 deprecation.py:506] From C:\Users\rroy\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\init_ops.py:97: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0701 12:17:03.950337 21512 deprecation.py:506] From C:\Users\rroy\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\init_ops.py:97: calling Ones.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
2019-07-01 12:17:04.185639: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
W0701 12:17:04.304289 21512 deprecation.py:323] From C:\Users\rroy\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

It did print the statements 1.14.0 and 2.2.4 though.

**Comment by RajarshiRoy2** [comment]
When I did load_model(my_model2.h5) it gives me your same error.

**Comment by RajarshiRoy2** [comment]
import keras
import numpy as np
import tensorflow as tf
from sklearn import preprocessing

print(tf.__version__)
print(keras.__version__)

model = tf.keras.models.load_model('my_model2.h5')

This is my part just for reference. Then it starts to run on test data later on.

**Comment by Dobiasd** [comment]
OK, that **is** interesting. :grin: Usually this should not make a difference.

While trying to solve it, my first idea was to just temporarily replace:
```python3
from keras.models import Model, load_model
```

with:
```python3
from keras.models import Model
from tensorflow.keras.models import load_model
```

in `convert_model.py`.

But then we get the following error:
```
  File "convert_model.py", line 664, in convert_sequential_to_model
    if model.model == model:
AttributeError: 'Sequential' object has no attribute 'model'
```

I'll try to find a workaround and get back to you with the results.

**Comment by Dobiasd** [comment]
Even the following fails:

```python3
from keras.initializers import glorot_uniform
from keras.models import load_model
from keras.utils import CustomObjectScope

with CustomObjectScope({'GlorotUniform': glorot_uniform()}):
    model = load_model('my_model2.h5')
```
Error:
```
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 327, in assert_input_compatibility
    str(K.ndim(x)))
ValueError: Input 0 is incompatible with layer flatten: expected min_ndim=3, found ndim=2
```

:scream:

**Comment by Dobiasd** [comment]
Working with
```python3
from tensorflow.keras import backend as K
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model, load_model
```
in `convert_model.py` also does not look too good:

```
    size=replace_none_with(32, set_shape_idx_0_to_1_if_none(shape))).astype(np.float32)
  File "mtrand.pyx", line 1657, in mtrand.RandomState.normal
  File "mtrand.pyx", line 242, in mtrand.cont2_array_sc
TypeError: 'tuple' object cannot be interpreted as an integer
```

So it seems `keras` and `tensorflow.keras` are way more incompatible than I thought. :neutral_face:

---

@RajarshiRoy2 Is it possible for you to use `keras` instead of `tensorflow.keras` in the script that you use to build/train/save the model?

**Comment by RajarshiRoy2** [comment]
When I just change from tensorflow import keras to import keras then I get an error saying ValueError: Input 0 is incompatible with layer flatten_1: expected min_ndim=3, found ndim=2. I am trying to see if I can find a fix for it online.

**Comment by RajarshiRoy2** [comment]
I am not sure what this error means exactly in regards to my model. Is it because of the way I am passing data? I am making a numpy array and then passing it in. 

model = keras.Sequential([
    keras.layers.Dense(6,input_shape =(6,)),
    keras.layers.Flatten(),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(30,activation='relu'),
    keras.layers.Dropout(0.1),
    keras.layers.Flatten(),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(40,activation='relu'),
    keras.layers.Dropout(0.1),
    keras.layers.Flatten(),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(1500,activation='sigmoid'),
])
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X,AAcolumn, epochs=2)

model.save('my_model2.h5')
This is my model overall.

**Comment by Dobiasd** [comment]
Try to remove all the flatten layers. Your tensors already are flat.

**Comment by RajarshiRoy2** [comment]
yep now it worked and I made the json file. Thanks. How did you know it is already flattened?

**Comment by Dobiasd** [comment]
Your input shape is one-dimensional, and dense layers always output 1-d tensors.
