### ISSUE TITLE
Issues with building

### ISSUE THREAD

**Issue by RajarshiRoy2** [Dobiasd/frugally-deep#147]
Hi,

When I try to build the cpp file to take in the json file in codeblocks, I get into loads of errors saying libraries missing so I had to add each of them individually. I am not sure where to get #include <nlohmann/json.hpp> file. Which repository is it in?

**Comment by Dobiasd** [comment]
It's here: https://github.com/nlohmann/json

See: https://github.com/Dobiasd/frugally-deep/blob/master/INSTALL.md

**Comment by RajarshiRoy2** [comment]
Thanks. But in my model, I need to input 7 inputs. But I keep getting error saying 5 only allowed. Am I not allowed to enter more than 5?
Code:
const auto model = fdeep::load_model("fdeep_model.json");
    const auto result = model.predict(
        {fdeep::tensor5(fdeep::shape5(-14, 0, 0, -441,0,170,0))});
    cout << fdeep::show_tensor5s(result) << endl;

Error:
C:\Users\rroy\Desktop\frugallydeep\main.cpp:9:65: error: no matching function for call to 'fdeep::model::predict(<brace-enclosed initializer list>) const'
         {fdeep::tensor5(fdeep::shape5(-14, 0, 0, -441,0,170,0))});
                                                                 ^
In file included from C:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/lib/gcc/i686-w64-mingw32/8.1.0/include/c++/fdeep/fdeep.hpp:63,
                 from C:\Users\rroy\Desktop\frugallydeep\main.cpp:2:
C:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/lib/gcc/i686-w64-mingw32/8.1.0/include/c++/fdeep/model.hpp:25:14: note: candidate: 'fdeep::tensor5s fdeep::model::predict(const tensor5s&) const'
     tensor5s predict(const tensor5s& inputs) const
              ^~~~~~~
C:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/lib/gcc/i686-w64-mingw32/8.1.0/include/c++/fdeep/model.hpp:25:14: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'const tensor5s&' {aka 'const std::vector<fdeep::internal::tensor5>&'}
Process terminated with status 1 (0 minute(s), 6 second(s))
2 error(s), 0 warning(s) (0 minute(s), 6 second(s))

**Comment by RajarshiRoy2** [comment]
So I actually updated my code and I am getting tensor5 does not name a type and type5s  is not a valid class. Is there any additonal hpp files needed?

**Comment by RajarshiRoy2** [comment]
This line to be particular and few lines below it as well. 

using output_dict = std::map<std::pair<std::string, std::size_t>, tensor5s>;

Error:

||=== Build: Debug in frugallydeep (compiler: GNU GCC Compiler) ===|
C:\Users\rroy\Desktop\frugally-deep-master\include\fdeep\node.hpp|37|error: 'tensor5s' was not declared in this scope|
C:\Users\rroy\Desktop\frugally-deep-master\include\fdeep\node.hpp|37|error: template argument 2 is invalid|
C:\Users\rroy\Desktop\frugally-deep-master\include\fdeep\node.hpp|37|error: template argument 4 is invalid|
C:\Users\rroy\Desktop\frugally-deep-master\include\fdeep\node.hpp|43|error: 'tensor5' does not name a type|
C:\Users\rroy\Desktop\frugally-deep-master\include\fdeep\node.hpp|45|error: 'tensor5s' does not name a type|
C:\Users\rroy\Desktop\frugally-deep-master\include\fdeep\node.hpp|54|error: 'tensor5s' does not name a type|

**Comment by Dobiasd** [comment]
> const auto model = fdeep::load_model("fdeep_model.json");
> const auto result = model.predict(
> {fdeep::tensor5(fdeep::shape5(-14, 0, 0, -441,0,170,0))});
> cout << fdeep::show_tensor5s(result) << endl;

A shape has to have 5 dimensions, and the values have to be supplied to the call of the constructor of the tensor:

```cpp
#include <fdeep/fdeep.hpp>
int main()
{
    const auto model = fdeep::load_model("fdeep_model.json");
    const auto result = model.predict(
        {fdeep::tensor5(fdeep::shape5(1, 1, 1, 1, 7), {-14, 0, 0, -441, 0, 170, 0})});
    std::cout << fdeep::show_tensor5s(result) << std::endl;
}
```

---

> type5s is not a valid class

`type5s` does not exist in frugally-deep.

**Comment by RajarshiRoy2** [comment]
Is there a way to convert results to a list/array? Because the output comes in format of decimals. [[[[[[[0.9500, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0063, 0.0980, 0.1772, .... I want to get the index of the largest value in this case being 0 as that will be the actual value of my prediction.

**Comment by Dobiasd** [comment]
You could use `result.front().as_vector()`, and then manually find the index with the highest activation.

However, there already is a convenience function, that does all the work for you: [`fdeep::model::predict_class`](https://github.com/Dobiasd/frugally-deep/blob/1c61ca5bb829cdfc514502a2583ac1d6680585b4/include/fdeep/model.hpp#L59-L63). Example usage:

```cpp
#include <fdeep/fdeep.hpp>
int main()
{
    const auto model = fdeep::load_model("fdeep_model.json");
    const auto result = model.predict_class(
        {fdeep::tensor5(fdeep::shape5(1, 1, 1, 1, 7), {-14, 0, 0, -441, 0, 170, 0})});
    std::cout << result << std::endl;
}
```

**Comment by RajarshiRoy2** [comment]
Yep it worked. I tried it before but it gave me a weird error like type not able to cout or maybe it was because some library was missing in the code. Thanks
