### ISSUE TITLE
Frugally LSTM Encoder-Decoder results different from Keras/Tensorflow LSTM Encoder-Decoder

### ISSUE THREAD

**Issue by MarlonCajamarca** [Dobiasd/frugally-deep#148]
Hi @Dobiasd 

I have been working on the Encoder-Decoder model for Vehicle Path Forecasting since you added support for `returned_states ` and `show_tensor5` on LSTM-based models. The workflow of the project was described [on this past issue](https://github.com/Dobiasd/frugally-deep/issues/145). After some experiments, the LSTM-Based encoder and decoder models are not giving me any problem related to `returned_states = True` or `show_tensor5`, confirming frugally-deep fixes worked. However, I have been trying to replicate the results I obtained using the Keras/Tensorflow models without success.

The frugally-deep `fdeep_encoder_model_NT` is returning the exact same `encoder_hidden_state` and `encoder_cell_state` states compared to its Tf + Keras counterparts using the `encoder_model.hdf5`. However, the `fdeep_decoder_model_NT` is not giving me the same `decoder_hidden_state` and `decoder_cell_state` output states (compared to the results using Tf + Keras `encoder_model.hdf5`) :(

Specifically, I develop the decoder inference model using TF + Keras ([please refer yourself to past comments in this issue to see the corresponding code](https://github.com/Dobiasd/frugally-deep/issues/145#issuecomment-503313963)), and then converted it from .hdf5 to .json, ready to be ported into the C++ application (same as with the encoder model). Validating the encoder states:
![image](https://user-images.githubusercontent.com/29712145/60611686-82fb4b80-9d8c-11e9-8a3f-5b58c1fdecb3.png)
However, both frugally-deep `decoder_hidden_state` and `decoder_cell_state` differ from corresponding Keras-based `decoder_hidden_state` and `decoder_cell_state`:
![image](https://user-images.githubusercontent.com/29712145/60611757-af16cc80-9d8c-11e9-9e9e-4902caad4499.png)
Resulting, as expected, in a wrong bounding box prediction:
![image](https://user-images.githubusercontent.com/29712145/60612114-8d6a1500-9d8d-11e9-9283-0b53053e6ff4.png)
which does not match with the corresponding Keras Results:
![image](https://user-images.githubusercontent.com/29712145/60619895-54d33700-9d9f-11e9-8f50-07c4fb3baf6d.png)
I do not really know about what is happening with `fdeep_decoder_model_NT`, so I have various options in mind:
* I have trained another model using `LSTM` instead `CuDNNLSTM` layers in order to check if the problem is with `CuDNNLSTM` layer implementation. However, the problem is still present when using other LSTM-based cells like `CuDNNLSTM` and `LSTM`. The `fdeep_encoder_model` works well but `fdeep_decoder_model` is still making wrong predictions (both at states returned and next bbox prediction).
* Now I am working in the `main.cpp` file. Maybe the problem is inside my internal manipulation of `fdeep::tensor5` and `fdeep::tensor5s` when feeding the data into the ported models. However, both models are working well, except that the decoder's model is making (inaccurate) predictions of future bounding boxes, but it did not crash in any step of the script execution.
* I am puzzled about the following fact: At `main.cpp` the decoders predictions is made with the following command: `auto decoder_outputs = decoder_model.predict({target_seq, encoder_states.at(0), encoder_states.at(1)});`, where `encoder_states.at(0)` and `encoder_states.at(1)` represent `h_enc` and `c_enc` respectively. However, I tried by interchanging the encoder states at the input of the decoder prediction line like this: `auto decoder_outputs = decoder_model.predict({target_seq, encoder_states.at(1), encoder_states.at(0)});` and obtaining the exact same `predicted_next_box` (even though I interchanged the input order of `decoder_states` at the prediction function).
* Finally, apart from the wrong values of `h_dec` and `c_dec` returned by `fdeep_decoder_model`, I noticed both `h_dec` hidden states (from frugally **AND** Keras) are in the range `[-1, 1]`, but that does not occur to `c_dec` hidden states. In Keras, `c_dec` have values from `[-11, 11]` but, in frugally, `c_dec` takes values from `[-1, 1]`. In addition, based on [your suggestion about internal scaling causing this kind of issues](https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md), by inspecting the `fdeep_encoder_model.json`, there are some `initializers` parameters that are using `Variance_Scaling` parameter inside that maybe are the cause of errors at inference-time.
I think maybe this at the root of the problem but I have no idea of how to get the correct `h_enc` and `c_enc`, both between the same ranges used in Keras and with the correct values as well. 

Here is the `main.cpp` file I am running to test the results. Any comment or suggestion about the code would be welcomed!

```javascript
#include <fdeep/fdeep.hpp>
#include <vector>
#include <fstream>
#include <iostream>

int main()
{
	// Loading the previously trained models
	const auto encoder_model = fdeep::load_model("fdeep_encoder_model_NT.json");
	std::cout << "Encoder Model Loaded!" << std::endl;
	const auto decoder_model = fdeep::load_model("fdeep_decoder_model_NT.json");
	std::cout << "Decoder Model Loaded!" << std::endl;
	// Batch_size = 1, num_timesteps = 10 and num_features = 4
	fdeep::shape5 in_traj_shape(1,1,1,10,4);
	// Loading a sample sequence trajectory into tensor5 data structure
	const std::vector<float> src_traj  = {1728, 715, 191, 221,
					1717, 710, 202, 215,
					1706, 704, 206, 198,
					1695, 700, 217, 196,
					1687, 696, 228, 183,
					1680, 689, 240, 181,
					1668, 668, 240, 198,
					1661, 668, 243, 194,
					1650, 664, 251, 189,
					1635, 660, 266, 181};
	// Input trajectory from vector to tensor5 data structure
	const fdeep::shared_float_vec shared_traj(fplus::make_shared_ref<fdeep::float_vec>(src_traj));
	const fdeep::tensor5 encoder_inputs(in_traj_shape, shared_traj);
	std::cout << "Trajectory #0!" << fdeep::show_tensor5(encoder_inputs) << std::endl;
	// Using loaded encoder model to predict encoder output states
	// Then encoder_states can be feed as input tensors into decoder_model
	const auto encoder_states = encoder_model.predict({encoder_inputs});
	// Printing for debbuging purposes
	std::cout << "h_enc: "<< fdeep::show_tensor5(encoder_states.at(0)) << std::endl;
	std::cout << "c_enc: "<< fdeep::show_tensor5(encoder_states.at(1)) << std::endl;
	// Creating a SOS input sequence token to signal decoder model to start making predictions
	fdeep::shape5 bbox_shape(1,1,1,1,4);
	// Loading a sample sequence trajectory into tensor5 data structure
	const std::vector<float> SOS_token  = {9999.0, 9999.0, 9999.0, 9999.0};
	const fdeep::shared_float_vec shared_SOS_token(fplus::make_shared_ref<fdeep::float_vec>(SOS_token));
	fdeep::tensor5 target_seq(bbox_shape, shared_SOS_token);
	// In Python we have: Prediction, h, c = decoder_model.predict([target_seq] + state)
	auto decoder_outputs = decoder_model.predict({target_seq, encoder_states.at(1), encoder_states.at(0)});
	// Printing for debugging purposes
	std::cout << "h_dec: "<< fdeep::show_tensor5(decoder_outputs.at(1)) << std::endl;
	std::cout << "c_dec: "<< fdeep::show_tensor5(decoder_outputs.at(2)) << std::endl;
	std::cout << "Predicted next bounding box!" << fdeep::show_tensor5(decoder_outputs.at(0)) << std::endl;
}
```
The `fdeep_encoder_model_NT.json` model imported into the C++ application is avaliable to download and inspect [from this past comment](https://github.com/Dobiasd/frugally-deep/issues/145#issuecomment-503313963). The `fdeep_decoder_model_NT.json` can be downloaded from the following link:
Decoder model: 
https://drive.google.com/open?id=1hwrjcnNfWaqQI0o8TmJKtfsAwj6zd9aq
I would really appreciate any help with this issue. I am puzzled because the encoder model is working perfectly but the decoder model does not, specifically, the results between the Keras vs Frugally decoder models differ, giving me wrong output predictions that cannot be used at all.

**Comment by Dobiasd** [comment]
Hi Marlon,

and thanks for the very clean report.

I ran your C++ code on my machine and can confirm the output:

```
Predicted next bounding box![[[[[[579.6933, 412.2126, 429.9233, 482.8473]]]]]]
```

Could you please also upload the two `.h5` files for these two models, and ideally also post a second minimal example code, one that does the same as your C++ code, but this time in Python using Keras and the `.h5` files? It would be awesome if I could reproduce the discrepancy on my machine for digging into where it originates.

**Comment by Dobiasd** [comment]
@MarlonCajamarca Any news on that? Let me know if I can help in some way.

**Comment by MarlonCajamarca** [comment]
Hi @Dobiasd 

Sorry for the late response! We have been trying a couple of other options to integrate Python models for vehicle trajectory prediction and C++ optimized YOLO-V3 (Darknet) for object detection. For the time being, I am really interested in the frugally-deep implementation, and therefore, these are the files you requested for debugging purposes. I will try to be as concise as possible in the explanation :)

These are the two models, `encoder_model.h5` and `decoder_model.h5`, in .h5 format used for the tests. You can download them using the following links:
- Keras Encoder Pretrained Model: https://drive.google.com/open?id=1A7HgYa3gAUWerw2blI7SO2WxMxNsGvtF
- Keras Decoder Pretrained Model: https://drive.google.com/open?id=1sJqLBN-BuuRgUbbDrtLBBZQhpvoe9ZUr
- Frugally-deep Encoder Pretrained Model: https://drive.google.com/open?id=1PE4kT2UHEDc4UjBmL57lbeAGAN7dLopv
- Frugally-deep Decoder Pretrained Model: https://drive.google.com/open?id=1p_Bt45TRXXLSiKS4zd8S9fsdRDiJrvVq

These are the Keras/Python scripts used for making inference both in Python and C++:
- Minimal inference test example (Python):
```javascript
import numpy as np
from keras.models import load_model
np.set_printoptions(suppress=True)

encoder_model = load_model("encoder_model.h5")
print("Encoder model loaded!")
decoder_model = load_model("decoder_model.h5")
print("Decoder model loaded!")
source_trajectory  = np.array([[1728, 715, 191, 221],
			[1717, 710, 202, 215],
			[1706, 704, 206, 198],
			[1695, 700, 217, 196],	
			[1687, 696, 228, 183],
			[1680, 689, 240, 181],
			[1668, 668, 240, 198],
			[1661, 668, 243, 194],
			[1650, 664, 251, 189],
			[1635, 660, 266, 181]])
output_trajectory_length = source_trajectory.shape[0]
num_output_features = source_trajectory.shape[1]
print("Source trajectory : \n {}".format(source_trajectory))
src_traj_batched = np.expand_dims(source_trajectory, axis = 0)
state = encoder_model.predict(src_traj_batched)
print("h_enc: \n {}".format(np.round(state[0], 2)))
print("c_enc: \n {}".format(np.round(state[1], 2)))
sos_token = 9999
target_trajectory = np.array([sos_token, sos_token, sos_token, sos_token]).astype("uint16").reshape(1,1, num_output_features)
prediction, h, c = decoder_model.predict([target_trajectory] + state)
print("h_dec = \n {}".format(np.round(h, 2)))
print("c_dec = \n {}".format(np.round(c, 2)))
print("Predicted next bounding box = {}".format(np.array(prediction).astype("uint16")))
```
- Equivalent Minimal Inference test example (Frugally-C++):
```javascript
#include <fdeep/fdeep.hpp>
#include <vector>
#include <fstream>
#include <iostream>

int main()
{
   const auto encoder_model = fdeep::load_model("fdeep_encoder_model.json");
   std::cout << "Encoder Model Loaded!" << std::endl;
   const auto decoder_model = fdeep::load_model("fdeep_decoder_model.json");
   std::cout << "Decoder Model Loaded!" << std::endl;
   const int num_input_features = 4;
   const int input_trajectory_length = 10;
   fdeep::shape5 input_trajectory_shape(1, 1, 1, input_trajectory_length, num_input_features);
   const std::vector<float> source_trajectory  = {1728, 715, 191, 221,
				1717, 710, 202, 215,
				1706, 704, 206, 198,
				1695, 700, 217, 196,
				1687, 696, 228, 183,
				1680, 689, 240, 181,
				1668, 668, 240, 198,
				1661, 668, 243, 194,
				1650, 664, 251, 189,
				1635, 660, 266, 181};
   const fdeep::shared_float_vec shared_trajectory(fplus::make_shared_ref<fdeep::float_vec>(source_trajectory));
   const fdeep::tensor5 encoder_inputs(input_trajectory_shape, shared_trajectory);
   std::cout << "Trajectory #0!" << fdeep::show_tensor5(encoder_inputs) << std::endl;
   const auto encoder_states = encoder_model.predict({encoder_inputs});
   std::cout << "h_enc: "<< fdeep::show_tensor5(encoder_states.at(0)) << std::endl;
   std::cout << "c_enc: "<< fdeep::show_tensor5(encoder_states.at(1)) << std::endl;
   fdeep::shape5 bbox_shape(1, 1, 1, 1, num_input_features);
   const std::vector<float> SOS_token  = {9999, 9999, 9999, 9999};
   const fdeep::shared_float_vec shared_SOS_token(fplus::make_shared_ref<fdeep::float_vec>(SOS_token));
   ffdeep::tensor5 target_sequence(bbox_shape, shared_SOS_token);
   auto decoder_outputs = decoder_model.predict({target_sequence, encoder_states.at(0), encoder_states.at(1)});
   std::cout << "h_dec: "<< fdeep::show_tensor5(decoder_outputs.at(1)) << std::endl;
   std::cout << "c_dec: "<< fdeep::show_tensor5(decoder_outputs.at(2)) << std::endl;
   std::cout << "Predicted next bounding box!" << fdeep::show_tensor5(decoder_outputs.at(0)) << std::endl;
}
```
One thing I noticed when analysing the test results was the values and their scales, for both `encoder_model.h5` and `fdeep_encoder_model.json`. Specifically, the resulting `encoder_states` are exactly the same, and obviously having its internal values ranging at the same scale. This case, `h_enc` values are ranging from [-1, 1] and `c_enc` values from [-10, 10] for both Python and Frugally-Deep. 

However, the same thing does not happen when computing the `decoder_outputs = [prediction, h_dec, c_dec]`. For this case, **`h_dec` values are different between Keras/Python and Frugally/C++**, but their **scale for both implementations are the same**, [-1,1] this case. 

The worst case is with the `c_dec` values! This case, **both `c_dec` values and their scale differ between Keras/Python and Frugally/C++ implementations**. In Keras, **`c_enc` values' scale is [-11, 11]** (I really do not why...), but in frugally-deep, **the `c_enc` values' scale is ranging between [-1, 1]**. 

Maybe, something inside the frugally-deep decoder's prediction routine is transforming the decoder's hidden state values, and/or their scale, and therefore, the `fdeep_decoder_model` is giving the wrong bounding box predictions and wrong next decoder states.

I hope this information and files are enough for you to debug and digging deeper into what is the issue. Please feel free to ask for more information (or files you may need for debugging purposes). I will be waiting for your insights. Thank you very much @Dobiasd.

**Comment by Dobiasd** [comment]
Thanks for this perfect minimal example and the explanations. I'll investigate and get back to you.

**Comment by Dobiasd** [comment]
@MarlonCajamarca I know, this might be a bit weird thing to request, but would it be possible for you to build and upload your model using `LSTM` instead of `CuDNNLSTM`? I'm asking because currently, I'm [failing to get the GPU version of TF to run on my system](https://stackoverflow.com/questions/57089628/cuda-error-invalid-device-invalid-device-ordinal-when-starting-a-tensorflow-s). :neutral_face:

**Comment by Dobiasd** [comment]
There are no tests stored in `fdeep_decoder_model.json`, which means when you converted your model from `h5` to `json` you explicitly used the `--no-tests` flag for `convert_model.py`.

When leaving the tests activated (as by default), the problem turns up already when loading the model, which makes it not only easier to detect but also simpler to debug, because we don't need the manual input and checking.

```bash
python3 convert_model.py decoder_model.h5 fdeep_decoder_model.reconverted.json
```

```
// decoder_test.cpp
#include <fdeep/fdeep.hpp>
int main()
{
   fdeep::load_model("fdeep_decoder_model.reconverted.json");
}
```

```
g++ -std=c++14 -O3 ./decoder_test.cpp -o decoder_test
```

```
./decoder_test
```

```
Loading json ... done. elapsed time: 0.026045 s
Running test 1 of 1 ... done. elapsed time: 0.002452 s
terminate called after throwing an instance of 'std::runtime_error'
  what():  test failed: output=0 pos=0,0,0 value=-3.03278 target=-12.7334
```

I'll investigate further.

**Comment by Dobiasd** [comment]
That's a difficult one.

Could you provide a minimal example (in Python) to reproduce your model architecture? Ideally, one that also fails when running the tests during loading in C++ after conversion? I'd then like to trim it down to something like that to narrow down the issue:

```python3
from keras.layers import Input, FooLayer, BarLayer
from keras.models import Model

inputs = Input(shape=(...))
x = FooLayer(...)(inputs)
x = BarLayer(...)(x)
model = Model(inputs=inputs, outputs=x)
model.compile(loss='mse', optimizer='nadam')

model.save('model.h5', include_optimizer=False)
```

**Comment by MarlonCajamarca** [comment]
Hi @Dobiasd 

You can access the train.py Python script used to train the models here:
https://drive.google.com/open?id=1yffJ7DhavaCTQU2Ey8ASqVBsquS3KJY5

Sorry, that script is not the minimal Python script you requested, but you can inspect the instantiation and fitting functions to clarify what is going with the resulting models. Specifically, these are the `create_models()` and `fit_models()` functions (isolated from other functions used to load datasets, etc):
```javascript
def create_models(encoder_input_train, decoder_input_train, hyperparams):
    """
    Instantiate full_model, encoder_model and decoder_model
    
    Parameters
    ----------
    encoder_input_train -> HDF5_Group : HDF5_Group containing train encoder_input dataset 
    decoder_input_train -> HDF5_Group : HDF5_Group containing train/test decoder_input dataset
    hyperparams -> dict : Dictionary containing all hyperparamers for training/testing/predicting
        latent_dim -> int : Number of Neurons for LSTM encoder and decoder cells.
        hidden_dense_dim -> int : Number of Neurons for hidden Dense layer
    Returns
    ------
    full_model -> keras model : Keras model for the complete encoder-decoder model training
    encoder_model -> keras model : Keras model for the inference encoder
    decoder_model -> keras_model : Keras model for the inference decoder
    """
    latent_dim = hyperparams["latent_dim"]
    hidden_dense_dim = hyperparams["hidden_dense_dim"]
    """ TRAINING ENCODER """
    input_feature_vect_length = encoder_input_train.shape[2]  
    output_feature_vect_lenght = decoder_input_train.shape[2]
    encoder_inputs = Input(shape = (None, input_feature_vect_length), name = "enc_input")
    encoder_lstm = CuDNNLSTM(units = latent_dim, return_state = True, name = "enc_CuDNNLSTM")
    encoder_outputs, state_h, state_c = encoder_lstm(encoder_inputs)
    encoder_states = [state_h, state_c]
    """ TRAINING DECODER """
    decoder_inputs = Input(shape = (None, output_feature_vect_lenght), name = "dec_input")
    decoder_lstm = CuDNNLSTM(units = latent_dim, return_sequences = True, return_state = True, name = "dec_CuDNNLSTM")
    decoder_outputs, _, _ = decoder_lstm(decoder_inputs, initial_state = encoder_states)
    decoder_dense_hidden = TimeDistributed(Dense(latent_dim, activation = "linear", name = "dec_dense_1"))
    decoder_dense_hidden_2 = TimeDistributed(Dense(hidden_dense_dim, activation = "linear", name = "dec_dense_2"))
    decoder_dense = TimeDistributed(Dense(output_feature_vect_lenght, activation = "linear", name = "dec_dense_out"))
    decoder_outputs_dense = decoder_dense_hidden(decoder_outputs)
    decoder_outputs_dense_2 = decoder_dense_hidden_2(decoder_outputs_dense)
    decoder_outputs = decoder_dense(decoder_outputs_dense_2)
    """  FULL TRAINING ENCODER-DECODER MODEL """
    full_model = Model(inputs = [encoder_inputs, decoder_inputs], outputs = decoder_outputs)
    """  DEFINING INFERENCE ENCODER  """
    encoder_model = Model(inputs = encoder_inputs, outputs = encoder_states)
    """  DEFINING INFERENCE DECODER """
    decoder_state_input_h = Input(shape=(latent_dim,), name = "inf_enc_in_h")
    decoder_state_input_c = Input(shape=(latent_dim,), name = "inf_enc_in_c")
    decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]
    decoder_outputs, state_h, state_c = decoder_lstm(decoder_inputs, initial_state = decoder_states_inputs)
    decoder_states = [state_h, state_c]
    decoder_outputs_dense = decoder_dense_hidden(decoder_outputs)
    decoder_outputs_dense_2 = decoder_dense_hidden_2(decoder_outputs_dense)
    decoder_outputs = decoder_dense(decoder_outputs_dense_2)
    decoder_model = Model(inputs= [decoder_inputs] + decoder_states_inputs, outputs = [decoder_outputs] + decoder_states)
    print(" Train and Inference models successfully created!!!")
    return full_model, encoder_model, decoder_model
```
This is the `fit_models()` function:
```javascript
def fit_models(all_models, hyperparams, out_directory, encoder_input_train, decoder_input_train, decoder_target_train):
    """
    Fit training data with choosen hyperparameters.
    
    Parameters
    ----------
    all_models -> list() : List containing previously compiled full_model, encoder_model and decoder_model.
    out_directory -> str :Path to the output directory where resulting models, graphs and history results are saved.
    encoder_input_train -> HDF5_Group : HDF5_Group containing train encoder_input dataset 
    decoder_input_train -> HDF5_Group : HDF5_Group containing train decoder_input dataset
    decoder_target_train -> HDF5_Group : HDF5_Group containing train decoder_targets dataset
    hyperparams -> dict : Dictionary containing all hyperparamers for training/testing/predicting
        patience_steps -> int : Early-Stopping parameter. Number of epochs with no improvement after which training will be stopped
        batch_size -> int : Number of samples per gradient update.
        epochs -> int : Number of epochs to train the model. An epoch is an iteration over the entire x and y data provided.
        val_split_size -> float : Parameter used for making the train and test dataset splitting process. It is a value in the range [0,1].
        
    Returns
    ------
    training_history -> json : A .json file containing all information form the training process.
    Note: Best trained models (full_model, encoder_model, decoder_model) will be saved at out_directory path using
          model checkpointing and Early Stopping with `save_best = True`
    """
    full_train_model = all_models[0]
    encoder_model = all_models[1]
    decoder_model = all_models[2]
    patience_steps = hyperparams["patience_steps"]
    batch_size = hyperparams["batch_size"]
    epochs = hyperparams["epochs"]
    val_split_size = hyperparams["val_split_size"]
    early_stop = EarlyStopping(monitor = 'val_rmse', mode = 'min', patience = patience_steps, verbose = 1)
    checkpoint_filename = "full_model.h5"
    checkpoint_path = os.path.join(out_directory, checkpoint_filename)
    model_ckpnt = ModelCheckpoint(filepath=checkpoint_path, monitor = 'val_rmse', mode = 'min', save_best_only = True, save_weights_only = False, verbose = 1)
    training_history = full_train_model.fit(x = [encoder_input_train, decoder_input_train], y = decoder_target_train, shuffle = "batch", batch_size = batch_size, epochs = epochs, validation_split = val_split_size, callbacks = [early_stop, model_ckpnt])
    encoder_model_filename = "encoder_model.h5"
    decoder_model_filename = "decoder_model.h5"
    encoder_model_path = os.path.join(out_directory, encoder_model_filename)
    decoder_model_path = os.path.join(out_directory, decoder_model_filename)
    encoder_model.save(encoder_model_path, include_optimizer = False)
    decoder_model.save(decoder_model_path, include_optimizer = False)
    return training_history
```
If you need more any additional or a real minimal example, I will be waiting to reply you as soon as possible. Hope this is enough for your debugging process :)

**Comment by Dobiasd** [comment]
Thanks a lot. I think I should be able to work with this. I'll get back to you with the results.

**Comment by Dobiasd** [comment]
I really appreciate your nice code, however, I can not re-build your model from this alone. There are some shapes required coming from for external training-data files, and also some hyperparameter settings, coming from an external config file.

Can you hardcode those in the code and chop off the training part?
Ideally one could just run your script, and the built (but untrained) `h5` models would be produced. Then they could be converted to `json`,  loaded in C++, and would hopefully produce the same kind of error during the automatic test.

**Comment by MarlonCajamarca** [comment]
Hi @Dobiasd 

Sure! I can give you two ways to reproduce the results. Firstly, this is the `config.json` file used to train the model using the code I shared with you in the last comment:
- Configuration file `config.json` :  https://drive.google.com/open?id=1xDgDdS1qLCuUI9c3wQSxGiKp-Kczen2h
Secondly, I can share with you one of the early versions of the training script, one thas has all the hyperparameters hardcoded within the script:
- Training Script with hardcoded hyperparameters: https://drive.google.com/open?id=1yc7yE8Baw2zecx8mJIxWWBaLXEPUCa0O

Let me know if this is enough for reproducing the results. I will be waiting for your response :)

**Comment by Dobiasd** [comment]
Thanks. I'm trying to work with the early version (`PathPredLSTM_Train.py`) having the hyperparameters hardcoded.

I'll of course skip the training part, and thus the loading of the training dataset. However the shape of the dataset is needed to build the model architecture:

```python3
input_feature_vect_length = encoder_input_train.shape[2]  # Receiving in Bounding Boxes (4 arguments)
output_feature_vect_lenght = decoder_input_train.shape[2] # Predicting out bounding boxes (4 arguments)
```

Do you think it is possible that you adjust the script in a way, that I can actually run it, and get as a result an `h5` model, that ideally can be used to reproduce the problem in C++ after converting to `json`?

**Comment by MarlonCajamarca** [comment]
Hi @Dobiasd 

Ok, I have hardcoded that parameters into the `early_train.py` file. Additionally, this is a small train/test dataset you can use to replicate the results. Basically, the dataset has the name `10i_10o_10s_8-1-E-W-LBV.hdf5`, which means the encoder receives 10 input bounding boxes (from `t-9` to `t`), and it outputs 10 bounding boxes corresponding to the predicted path for the next 10  timesteps (from `t+1` till `t+10`). Therefore, the datasets have `(num_train_samples, num_timesteps, num_features) = (num_train_examples, 10, 4)` for train dataset and similar for test_dataset, i.e. `(num_test_samples, num_out_timesteps, num_out_features)=(num_test_samples, 10, 4)`.

These are the files:

- `early_train.py` script with hardcoded hyperparameters that depended on input dataset shape: https://drive.google.com/open?id=1NB8hi5v15OO3GKzVZF4wBqQnx48gY4eo
- A small dataset ready to train new models with the provided scripts (early and recent versions of `train.py`): https://drive.google.com/open?id=1OohMHp574o6U7NLSnpZnouvpEbAgxaCK

I will be waiting for any issue, comment or anything to supply you if you needed!

**Comment by Dobiasd** [comment]
When I try to run the script (`early_train.py`), it complains that it can not load `v2_s4_10i_10o_FullLBV.hdf5`. The file you provided is called `10i_10o_10s_8-1-E-W-LBV.hdf5`.

I mean I could try to figure it out, but probably it would be faster for both of us if you would modify the script in a way that I can just run it. Please? :grin:

**Comment by Dobiasd** [comment]
OK, with making the following adjustment the script trains and saves a `decoder_model.h5`.

```python3
HDF5_in_dir = "."
HDF5_in_filename = "10i_10o_10s_8-1-E-W-LBV.hdf5"
```

```python3
model_saving_dir = "."
base_saving_dir = "."
```

Then, after running `python3 convert_model.py decoder_model.h5 decoder_model.json`, in C++ `fdeep::load_model("decoder_model.json");` fails.

So now I have something reproducible, I can work with.

Thanks a lot for your patience. :slightly_smiling_face:

I'll get back to you with the results.

**Comment by Dobiasd** [comment]
Findings so far:

The error during testing in C++ also happens
- with LSTM instead of CuDNNLSTM
- without any training at all (which is good for faster feedback cycle during debugging)
- with the following chopped down version of [your script](https://gist.github.com/Dobiasd/2e0a7a878ebdd9f27cfe465e9639db6c):

```python3
from keras.layers import Input, LSTM, Dense, TimeDistributed
from keras.models import Model

latent_dim = 512

input_feature_vect_length = 4
output_feature_vect_lenght = 4

encoder_inputs = Input(shape=(None, input_feature_vect_length), name="enc_input")
encoder_LSTM = LSTM(units=latent_dim, return_state=True, name="enc_LSTM")
encoder_outputs, state_h, state_c = encoder_LSTM(encoder_inputs)
encoder_states = [state_h, state_c]

decoder_inputs = Input(shape=(None, output_feature_vect_lenght), name="dec_input")
decoder_LSTM = LSTM(units=latent_dim, return_sequences=True, return_state=True, name="dec_LSTM")
decoder_outputs, _, _ = decoder_LSTM(decoder_inputs, initial_state=encoder_states)

decoder_dense_hidden = TimeDistributed(Dense(512, activation="linear", name="dec_dense_1"))
decoder_dense_hidden_2 = TimeDistributed(Dense(32, activation="linear", name="dec_dense_2"))
decoder_dense = TimeDistributed(Dense(output_feature_vect_lenght, activation="linear", name="dec_dense_out"))

decoder_outputs_dense = decoder_dense_hidden(decoder_outputs)
decoder_outputs_dense_2 = decoder_dense_hidden_2(decoder_outputs_dense)
decoder_outputs = decoder_dense(decoder_outputs_dense_2)

encoder_model = Model(inputs=encoder_inputs, outputs=encoder_states)

decoder_state_input_h = Input(shape=(latent_dim,), name="inf_enc_in_h")
decoder_state_input_c = Input(shape=(latent_dim,), name="inf_enc_in_c")
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]

decoder_outputs, state_h, state_c = decoder_LSTM(decoder_inputs, initial_state=decoder_states_inputs)
decoder_states = [state_h, state_c]

decoder_outputs_dense = decoder_dense_hidden(decoder_outputs)
decoder_outputs_dense_2 = decoder_dense_hidden_2(decoder_outputs_dense)
decoder_outputs = decoder_dense(decoder_outputs_dense_2)

decoder_model = Model(inputs=[decoder_inputs] + decoder_states_inputs, outputs=[decoder_outputs] + decoder_states)
decoder_model.save("decoder_model.h5", include_optimizer=False)
```

I'll continue to chop off as many things as possible from this script, while checking each iteration if the error still happens. Hopefully this will bring us to the essence of the problem.

**Comment by Dobiasd** [comment]
I reduced the model further:

```python3
from keras.layers import Input, LSTM
from keras.models import Model

decoder_inputs = Input(shape=(None, 4))

decoder_state_input_h = Input(shape=(12,))
decoder_state_input_c = Input(shape=(12,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]

decoder_outputs, state_h, state_c = LSTM(units=12,
                                         return_sequences=True,
                                         return_state=True)(decoder_inputs,
                                                            initial_state=decoder_states_inputs)
decoder_states = [state_h, state_c]

decoder_model = Model(inputs=[decoder_inputs] + decoder_states_inputs, outputs=decoder_states)
decoder_model.save("decoder_model.h5", include_optimizer=False)
```

And the tests when loading in C++ still fail.

The problem is `initial_state`. Frugally-deep does not support it, but also not complain about it when converting the model.

I'll try to add support for it, and get back to you with the results.

**Comment by Dobiasd** [comment]
@MarlonCajamarca I just added support for `initial_state` in `LSTM` layers. :tada:

Please try to use your model with [fdeep version `0.8.5`](https://github.com/Dobiasd/frugally-deep/releases/tag/v0.8.5-p0) (or the latest version pulled from the `master` branch). I'm confident it will produce the results you expect since the automated tests are now passing, which they did not do before. :slightly_smiling_face:

Thanks again a lot for your help and for all the time you invested in tracking down this bug. It's those things, that contribute a lot to improve the quality of the library. :heart:

I hope the rest of your user journey with frugally-deep will be less bumpy. :grimacing:

**Comment by MarlonCajamarca** [comment]
Hi @Dobiasd 

Thank you very much! Firstly, thanks for pinpointing the issue with the `initial_state` in LSTM layers as the root course of the issue. Secondly, I will definitely try the new `0.8.5` frugally-deep version with the fixes for the Vehicle Path Prediction project and see how it performs. Finally, it is a pleasure to contribute to the improvement of Frugally-Deep. IMHO, this kind of tools and developments are really appreciated for the entire Machine Learning Community. 

I will continue the journey with Frugally-Deep library and hope to share interesting results when getting results. Keep the great work @Dobiasd!

**Comment by noe** [comment]
It seems that frugally-deep does not support GRU layers with `initial_state` either (see [this assert in `convert_model.py`](https://github.com/Dobiasd/frugally-deep/blob/master/keras_export/convert_model.py#L386)). Would it be possible to support `initial_state` also for GRU?  @Dobiasd thanks for this fantastic project.

**Comment by hunyadi** [comment]
When GRU support was added about 3 years ago, it was heavily based on the LSTM implementation in frugally-deep, there are a lot of similarities. I would estimate that a new parameter such as `initial_state` would take approximately the same effort it took to incorporate it in the LSTM layer.

**Comment by Dobiasd** [comment]
Ok, cool, thanks. :+1:

@noe Are you interested in giving the implementation a try in a merge request?

**Comment by noe** [comment]
For now, I cannot commit to this. If I find the time I will let you know.
