### ISSUE TITLE
Arrayfire backend

### ISSUE THREAD

**Issue by pfeatherstone** [Dobiasd/frugally-deep#150]
Have you considered using the arrayfire library as a backend. It supposedly outperforms eigen by a considerable amount and supports multiple devices

**Comment by Dobiasd** [comment]
Thanks for the suggestion. No, I've not yet considered it but I will do. Maybe I can run some performance tests similar to [those ones](https://github.com/Dobiasd/frugally-deep/issues/55) to evaluate.

**Comment by pfeatherstone** [comment]
Looking at that link i noticed the -mavx2 and -mfma flags on top of -O3. That speeds things up. Still worth a try using arrayfire. According to the maintainers, it's the best thing since sliced bread but of course they would say that.

**Comment by Dobiasd** [comment]
The [benchmark](https://arrayfire.com/performance-improvements-to-jit-in-arrayfire-v3-4/) seem to be quite GPU centered. Also, I'm a bit reluctant to start depending on a library that is not header-only. This would make it more complicated to integrate frugally-deep into an application.

But in case, arrayfire really does beat Eigen's speed on raw CPU matrix multiplication significantly, it might be worth it.

**Comment by Dobiasd** [comment]
Assuming the TensorFlow people already use the fastest possible code for convolution (and GEMM), the fact that [convolution in frugally-deep is roughly equally fast compared with TensorFlow](https://github.com/Dobiasd/frugally-deep/issues/167#issuecomment-554938299) points to the conclusion, that currently there is not much to gain in terms of speed. So I'll close this issue for now.
