### ISSUE TITLE
output has two parts in Python

### ISSUE THREAD

**Issue by msv5450** [Dobiasd/frugally-deep#153]
I have a model that takes 8 inputs and give 5 output parameters. There are 4 output variables in one group and another variable in a separate group. When I predict something using Frugally, this is what happens:

    const auto result = model.predict(
        {fdeep::tensor5(fdeep::shape5(1, 1, 1, 1, 8), {-1.774, -1.396, -2.091, 1.124, -0.261, -1.489, 0.273, -0.503})});

std::cout << fdeep::show_tensor5s(result) << std::endl;

This results in:
 [[[[[[[-0.5995,  0.0043, -0.0348, -0.0045]]]]]], [[[[[[0.0000]]]]]]]

When I convert this data from frugally format into a vector like this: 
const std::vector<float> vec = *result.front().as_vector();
it ignores the second part of the output, which is [[[[0.000]]] I did not find out how to work around this.

**Comment by Dobiasd** [comment]
`result` is of type `tensor5s`, which is a `typedef` for `std::vector<tensor5>`. It has two elements, of which you are only getting the first one when using [`std::vector<T>::front()`](https://en.cppreference.com/w/cpp/container/vector/front).

You can access both elements of it for example by using the [index operator of `std::vector`](https://en.cppreference.com/w/cpp/container/vector/operator_at):
```cpp
const auto vec1 = *result[0].as_vector();
const auto vec2 = *result[1].as_vector();
```
