### ISSUE TITLE
When I run main.cpp, it gives me fatal error: fdeep/fdeep.hpp: No such file or directory  #include <fdeep/fdeep.hpp>

### ISSUE THREAD

**Issue by fatemeakbari** [Dobiasd/frugally-deep#154]
- Before reporting an issue, please make sure you are using the latest versions of frugally-deep, TensorFlow and Keras.

- Also check out the [FAQ](../FAQ.md). Maybe your problem/question is common and there already is a canonical answer for it.

- If you have a model and you get unexpected errors when converting it for or when using it with frugally-deep, please upload and post a link to your model file (`.h5`).

- Please try to make the problem reproducible by providing a [SSCCE](http://sscce.org/) as code.

- Feel free to also submit any other feedback, suggestions or questions you might have. :)

**Comment by Dobiasd** [comment]
Your compiler does not find the library files. You either have to install them on your system or point your compiler to the additional include directory. Please see [`INSTALL.md`](https://github.com/Dobiasd/frugally-deep/blob/master/INSTALL.md) for details.

**Comment by fatemeakbari** [comment]
thank you so much.
