### ISSUE TITLE
BatchNormalizationV1?

### ISSUE THREAD

**Issue by ectg** [Dobiasd/frugally-deep#156]
Hi,

Thanks for this implementation.

When I run convert_model.py to on a (keras) trained resnet model, I get the following error:

> ValueError: Unknown layer: BatchNormalizationV1

Is this a version issue? I am using keras 2.2.4, python 3.6.8 and tensorflow 1.13.1

**Comment by Dobiasd** [comment]
Hi, and thanks for the report.

Could you create a minimal example, that can be used to reproduce this issue?

**Comment by Dobiasd** [comment]
Or, maybe the following might be even simpler:

Can you load your model with the following isolated python code?
```python3
from keras.models import load_model
load_model('whatever_path_to_your_model.h5')
```
If not, `convert_model.py` will also fail.

**Comment by ectg** [comment]
Hi, thanks for the reply. So I am trying to port a trained resnet model, something like [this](https://github.com/raghakot/keras-resnet).

_load_model_ in the snippet above fails with the same error, but it passes if I do the following instead:

```
import tensorflow as tf
modelh5 = tf.keras.models.load_model('Resnet34.h5')
```

**Comment by Dobiasd** [comment]
OK, googling for `BatchNormalizationV1` seems to show that this is a bug in TensorFlow's `model.save` function. So I guess you are using `tf.keras` instead of `keras` in the script that builds/trains/saves the model. If so, would it an option for you to use `keras` instead of `tf.keras` there?

**Comment by ectg** [comment]
Hi, I have been using `model.save(savename + ".model")` to save the trained model, but replacing it with _save_model_ works. Thanks!

```
from keras.models import load_model, save_model
save_model(model, 'model.h5', include_optimizer=False)
modelh5 = load_model('model.h5')
```

`convert_model.py` now outputs a json file. For the C++ bit, I assume I don't need to build anything, but just set the include directories and call fdeep::load_model, and model.predict?
