### ISSUE TITLE
UpSampling2D

### ISSUE THREAD

**Issue by FanFdeep** [Dobiasd/frugally-deep#157]
I would like to ask you if UpSampling2D works properly in the version 0.7.3.
- Loading my model that has Upsampling2D layers (4 times, scale=(2,2)) with frugally-deep throws an run-time exception at verifying the very first test. 
- The prediction of the model with frugally-deep shows that the prediction resolution is about 16 times lower than that with Keras. 16 would come from 2^4, i.e. something wrong with Upsampling.
 - in jason, the upsampling layer is 
   {
          "class_name": "UpSampling2D",
          "config": {
            "data_format": "channels_last",
            "interpolation": "bilinear",
            "name": "upscore_feat1",
            "size": [
              2,
              2
            ],
            "trainable": true
          },
          "inbound_nodes": [
            [
              [
                "score_feat1",
                0,
                0,
                {}
              ]
            ]
          ],
          "name": "upscore_feat1"
      }

**Comment by Dobiasd** [comment]
Hi, and thanks for the report.

usually `UpSampling2D` should work. It's covered in the "full test" and I also used it in the past.

Can you post a minimal example (Python code) creating a model that reproduces the problem when loading in C++?

**Comment by FanFdeep** [comment]
Thanks for your prompt reply. 

A minimal example should be implemented first. The model from tensorboard is
![FCN_VGG_tensorboard](https://user-images.githubusercontent.com/52953041/61285196-c0b29800-a7c0-11e9-9259-3c58e5c8af73.png)

Well, the followings are the outline of the python code that the problem has been caused:
model = FCN_VGG(input_shape=(480, 640, 1), # this is main own function, where the upsampling is called.
                      classes=4,
                      weight_decay=3e-3,
                      weights=None,
                      trainable_encoder=True)
model.compile(optimizer=keras.optimizers.Adam(1e-4),
                    loss='categorical_crossentropy'
                    metrics=['accuracy'])
model.fit_generator(
        train_data,
        epochs=300,
        validation_data=val_data,
        verbose=1,
        use_multiprocessing=True)

**Comment by Dobiasd** [comment]
Thanks. However, I struggle to re-create the problem locally from the given information.

So I started to write a minimal example:

```python3
# generate_model.py
from keras.layers import Input, UpSampling2D
from keras.models import Model

inputs = Input(shape=(16, 16, 3))
x = UpSampling2D(2)(inputs)
model = Model(inputs=inputs, outputs=x)
model.compile(loss='mse', optimizer='nadam')

model.save('model.h5', include_optimizer=False)
```

```cpp
// main.cpp
#include <fdeep/fdeep.hpp>
int main()
{
    fdeep::load_model("model.json");
}
```

```bash
python3 generate_model.py
python3 frugally-deep/keras_export/convert_model.py model.h5 model.json
g++ -std=c++14 ./main.cpp -o fdeep_issue_157
./fdeep_issue_157
```

However, this works without any error. Can you try to adjust `generate_model.py` in a way such that running the C++ executable fails?

**Comment by FanFdeep** [comment]
Hi,
as far as I understand, the interpolation of upsampling_2d_layer in Fdeep (https://github.com/Dobiasd/frugally-deep/blob/92561d33e6fb802db59391c454cca2212e7506cd/include/fdeep/layers/upsampling_2d_layer.hpp) is based on the nearest neighbor. Actually, I need a "bilinear" interpolation as specified in Keras model.
How can I activate 'bilinear" in fdeep for using Upsampling2D?

**Comment by FanFdeep** [comment]
Hi,
I've simplified the FCN model with only one Umsampling layer. For prediction, you need a VGA gray (8bit) image as an input:
    model = simple_test(input_shape=(480, 640, 1))
    model.compile(loss='categorical_crossentropy', optimizer=keras.optimizers.Adam(1e-4), metrics=['accuracy'])

def simple_test(input_shape):
    inputs = Input(shape=input_shape)
    x = Conv2D(32, (3, 3),
               padding='same',
               use_bias=False,
               kernel_initializer='he_normal',
               kernel_regularizer=l2(3e-3))(inputs)
    x = BatchNormalization()(x)
    x = Activation(activation='relu')(x)
    x = MaxPooling2D((2,2), strides=(2,2), padding='same')(x)
    x = Conv2D(filters=4, kernel_size=(1, 1),
                   activation='linear',
                   padding='valid',
                   kernel_initializer='he_normal',
                   kernel_regularizer=l2(3e-3))(x)
    x = UpSampling2D(size=(2, 2), interpolation='bilinear')(x)
    outputs = Activation('softmax')(x)

    return Model(inputs=inputs, outputs=outputs)

**Comment by Dobiasd** [comment]
Ah, OK, thanks. I missed the `bilinear` in the json you had in your original post.

And you are right, frugally-deep only supports `nearest`. But you should already see an
[`AssertionError: Only interpolation nearest is currently supported by frugally-deep.`](https://github.com/Dobiasd/frugally-deep/blob/76d6b83f80934f447b125ae8444a68ad6323f728/keras_export/convert_model.py#L520-L521)
when you try to run `convert_model.py` with a model like the following:

```python3
# generate_model.py
from keras.layers import Input, UpSampling2D
from keras.models import Model

inputs = Input(shape=(16, 16, 3))
x = UpSampling2D((2, 2), interpolation='bilinear')(inputs)
model = Model(inputs=inputs, outputs=x)
model.compile(loss='mse', optimizer='nadam')

model.save('model.h5', include_optimizer=False)
```

What version of frugally-deep are you using, so that you don't get this error, but instead an exception when loading the already converted model in C++?

---

As a quick fix, you might try to just use `nearest` interpolation for your model. From an image-processing point of view, the difference between `nearest` and `bilinear` might be more important when downsizing images, and not so much when upsizing (by a natural-numbered factor). Maybe your validation results also look good with this method.

**Comment by FanFdeep** [comment]
Hi, 

thanks a lot for your reply.
I am using the version of 0.7.3. Indeed, in this version I don't get any AssertionError w.r.t. UmSampling2D 'biliear' interpolation.

Regarding the upsampling accuracy between "nearest" and "bilinear",  using "bilinear" at upsizing is as much important as at downsizing, even more important. The layer images with the values [0.0, 1.0] lose the boundary resolution after nearest-upsizing, more worse with repeated upsizing along the layers.  This reduction can be observed clearly when the interpolation "nearest" instead of "bilinear" in my trial.

Nevertheless, I appreciate your cooperation to clarify the problem for using frugally-deep. 
Now it's clear the source of problem and I can find a solution.

**Comment by FanFdeep** [comment]
It' really cool, how you motivate me :)
I am gladly interested in extension of the frugally-deep, however I am supposed to continue the current FCN-project.

I am going to split my current Keras model into two parts, namely encoding and decoding.
The encoding parameters can be used as saved and the decoding part (i.e. upsampling, add, and softmax) can be implemented directly in C++. If I succeed, I'll let you know.

**Comment by Dobiasd** [comment]
OK, so that's the manual one-time solution.

Nevertheless, I'd be interested in having support for `bilinear` interpolation for `UpSampling2D` layers in frugally-deep.

I'll see if I can find the time to tackle this soon.

**Comment by FanFdeep** [comment]
Unfortunately, one-time solution...

Actually, the implementation of "bilinear" in frugally-deep should not be complicated. 
Maybe I could contribute any implementation if I have some time for it.

Thanks again!

**Comment by Dobiasd** [comment]
Don't worry about implementing the one-time solution, just to then later implement bilinear interpolation in frugally-deep again. I'll implement it quickly, so you don't have to do duplicate work.

**Comment by Dobiasd** [comment]
[Done](https://github.com/Dobiasd/frugally-deep/commit/56e0bb084ad9075294de6d232446b03091b325d9). Frugally-deep now supports `bilinear` interpolation in `Upsampling2D` layers. :slightly_smiling_face:

Please try to use your model with frugally-deep version [0.8.4](https://github.com/Dobiasd/frugally-deep/releases/tag/v0.8.4-p0). It should work since the tests look like.

**Comment by FanFdeep** [comment]
Hi Tobias,

it’s great to get an upgraded version of frugally-deep. What an amazing quick upgrade!
As you noticed, it does work perfect. Now I can work on FCN-project further. You saved a couple of days from me for some dirty one-project solution stuffs.
It was really cool to communicate with you. I would annoy you soon maybe with other Fdeep problems.

Take care and cheers!

Mit freundlichen Grüßen / Best regards

Dr. Ji-Young Lim
DERMALOG Identification Systems GmbH
Senior Systems Engineer

Mittelweg 120 | 20148 Hamburg
Fon +49 40 413227 0

Fax +49-40-413227-40

Mail Ji-Young.Lim@dermalog.com<mailto:Ji-Young.Lim@dermalog.com>

Web www.dermalog.com<https://www.dermalog.com>


This e-mail may contain information that is confidential or proprietary to DERMALOG Identification Systems GmbH. Any unauthorized disclosure, distribution or other use is prohibited.

P Please consider the environment before printing this email
