### ISSUE TITLE
"vocabulary item indices must all be strictly less than the value of input_dim"

### ISSUE THREAD

**Issue by bhargavz** [Dobiasd/frugally-deep#158]
I converted a Keras h5 model to json using the converter and got a model with:
input shape = (1,1,1,1,250). Right after the input layer, I have an Embedding layer with with input_dim = 146 and input_length = 250. 

When I try to pass a 250 length input to predict, I get: 
"vocabulary item indices must all be strictly less than the value of input_dim".  

If I change the input length, I get: 
"Invalid inputs shape.\nThe model takes [(Just 1, Just 1, Just 1, Just 1, Just 250)] but provided was: [(1, 1, 1, 1, 249)]"

The test passes, so I am sure I am doing something wrong, but I am not at all familiar with C++.

Also, I cannot upload the model, but here is the [architecture diagram](https://i.imgur.com/JbcN0at.png)

```
Keras=2.2.4
Tensorflow=1.12.0
```

```C++
int main()
{
	// vector
	const std::vector<float> v = { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32,36,36,35,98,54,54,35,32,71,108,144,109,92,30,144,54,35,32,71,108,144,109,33,146,36,144,65,94,92,131,96,92,35,142,105,92,144,37,144 }; 
	const fdeep::shared_float_vec sv(fplus::make_shared_ref<fdeep::float_vec>(std::move(v)));
	const fdeep::tensor5 input = fdeep::tensor5(fdeep::shape5(1, 1, 1, 1, 250), sv);

	std::cout << "Input Tensor: " << std::endl;
	std::cout << fdeep::show_tensor5(input) << std::endl;
	std::cout << "Tensor Shape: " + fdeep::show_shape5(input.shape()) << std::endl;
	
	// load model
	const auto model = fdeep::load_model("fdeep-model.json");

	// predict
	const auto result = model.predict({ input });
	std::cout << fdeep::show_tensor5s(result) << std::endl;
	std::cout << fdeep::show_shape5(result.front().shape());
}
```

OUTPUT:
```
Input Tensor:
[[[[[[  <SNIPPED ZEROES> 32.0000,  36.0000,  36.0000,  35.0000,  98.0000,  54.0000,  54.0000,  35.0000,  32.0000,  71.0000, 108.0000, 144.0000, 109.0000,  92.0000,  30.0000, 144.0000,  54.0000,  35.0000,  32.0000,  71.0000, 108.0000, 144.0000, 109.0000,  33.0000, 146.0000,  36.0000, 144.0000,  65.0000,  94.0000,  92.0000, 131.0000,  96.0000,  92.0000,  35.0000, 142.0000, 105.0000,  92.0000, 144.0000,  37.0000, 144.0000]]]]]]
Tensor Shape: (1, 1, 1, 1, 250)
Loading json ... done. elapsed time: 10.248963 s
Running test 1 of 1 ... done. elapsed time: 1.349727 s
Loading, constructing, testing of fdeep-model.json took 50.776245 s overall
```

**Comment by Dobiasd** [comment]
Hi, and thanks for the good report.

I understand that you can not share your full model, because there might be company value in the trained weights. However since you showed the architecture diagram, I guess this one is not a secret. So could you upload an untrained version of your model? Keras `h5` or frugally-deep `json` does not matter. This would make it a lot easier for me to debug your issue.

**Comment by Dobiasd** [comment]
Ah, I found it already. :slightly_smiling_face:

The values you put in the model are
```
...,144,109,33,146,36,144,65,...
```

The `146` is not allowed. With `input_dim = 146` the maximum allowed value is `145`.

**Comment by bhargavz** [comment]
I feel a bit silly now, thanks @Dobiasd
