### ISSUE TITLE
Slower compared to Python?

### ISSUE THREAD

**Issue by ectg** [Dobiasd/frugally-deep#159]
Hi,

Thanks again for this implementation. I used this to port a Resnet trained on Python/Keras to C++. The C++ results are exactly the same as the Python, but the run time seems quite low in comparison:

99 ms in Python _vs_ 450 ms in C++ for a single image. (Approximately 10 fps _vs_ 2 fps). I am running this in release mode.

Is there a reason for this? How do I fix this?

**Comment by Dobiasd** [comment]
Do you use a GPU (or multiple CPU cores) when running in Python?

**Comment by ectg** [comment]
I disable the GPU when I run Python. With the GPU on, the Python version runs at 100 fps.

**Comment by Dobiasd** [comment]
Yes, TensorFlow uses all available cores. For some architectures, like VGG, this does not help that much, but on ResNet it might help more.

Can you try running your python predictions on only one CPU core?
Using Linux this could be accomplished by prepending `taskset --cpu-list 1` on the command line.

If this does not enlighten us, could you maybe upload your model in `h5` format? Then I could test locally too.

**Comment by ectg** [comment]
Hi - Thanks for the reply. If use just one core, Python runs at 2.47 fps and C++ is at 2.2 fps. 

I will probably need to look for alternate solutions. Have you ever tried using Tensorflow's C++ APIs?

**Comment by Dobiasd** [comment]
> Hi - Thanks for the reply. If use just one core, Python runs at 2.47 fps and C++ is at 2.2 fps.

OK, that's still a bit slower than [expected](https://github.com/Dobiasd/frugally-deep/blob/master/README.md#performance), but it roughly fits.

Do you just need high throughput or is low latency also a requirement?

In case you only need to process a lot of frames per second, but it does not matter if the result for one frame is only ready after a few other frames were captured, you could parallelize up to as many frames as you have CPU cores available.

> I will probably need to look for alternate solutions. Have you ever tried using Tensorflow's C++ APIs?

Sorry, I have no experience with that.

**Comment by ectg** [comment]
Thanks for the reply. Yes, this application needs both low latency and high throughput. I ended up writing a C++ wrapper for Python, this seems to work well for now.

**Comment by Dobiasd** [comment]
Cool. Happy to hear you found a solution. :+1:
