### ISSUE TITLE
release request

### ISSUE THREAD

**Issue by headupinclouds** [Dobiasd/frugally-deep#16]
This is a follow up to #14 .  Can you please tag a new release?   Thanks!

**Comment by Dobiasd** [comment]
[done](https://github.com/Dobiasd/frugally-deep/releases)

**Comment by headupinclouds** [comment]
Thanks.  I'll add the package pointers to Hunter.  I think we can bump the internal project version next time before tagging the release:

```
project(frugally-deep VERSION 0.2.1)
```

https://github.com/Dobiasd/frugally-deep/blob/d26367295051853c4b4dd9ed7f10bce883253e7d/CMakeLists.txt#L9

**Comment by Dobiasd** [comment]
Oh right, sorry, I forgot about this.

Would it help if I delete the release, bump the internal project version and then re-create the release?

**Comment by headupinclouds** [comment]
I have sent a PR for that already.  It seems like kind of a gray area to me.  I guess someone could `find_package(frugally-deep 0.2.1 CONFIG REQUIRED)` based on the release tag but the generated package wouldn't match.  I often forget this too and have to fix it.  I've sent a PR based on that release, so maybe vanilla semantic versioning can bump to `project(frugally-deep VERSION 0.2.2)` and we can tag a plain `v0.2.2`, then I can send an update based on that to make it consistent.  Let me know what you decide.

**Comment by Dobiasd** [comment]
OK, thanks. I just bumped to ver. 0.2.2 and created a new release.
