### ISSUE TITLE
Implementing frugally-deep for Fashion-MNIST

### ISSUE THREAD

**Issue by jesukiran** [Dobiasd/frugally-deep#160]
I am trying to implement frugally-deep on Fashion-MNIST(quite new to C++), but the dataset does not have the image channels. 

I am using this code to test:

#include <fdeep/fdeep.hpp>
#include <opencv2/opencv.hpp>

int main()
{
	const cv::Mat image = cv::imread("image_1.jpg");
	cv::cvtColor(image, image, cv::COLOR_BGR2RGB);
	assert(image.isContinuous());
	const auto model = fdeep::load_model("fdeep.json");

	const auto input = fdeep::tensor5_from_bytes(image.ptr(),
		static_cast<std::size_t>(image.rows),
		static_cast<std::size_t>(image.cols),
		static_cast<std::size_t>(image.channels()),
		0.0f, 1.0f);
	const auto result = model.predict_class({ input });
	std::cout << "the result is: " << std::endl;
	std::cout << result << std::endl;
}

How could I check for a single channel image data? I would be very grateful for your help!

**Comment by Dobiasd** [comment]
Hi,

sorry, I don't yet understand the actual problem. Do you get an error?

In general, if your model works in Python, and can be converted to frugally-deep's format, it should work in C++ too.

**Comment by jesukiran** [comment]
Unhandled exception at 0x00007FFBB0FDA388 in Project5.exe: Microsoft C++ exception: std::runtime_error at memory location 0x000000C1BF2FF5E0. occurred

I keep getting this exception error?

**Comment by Dobiasd** [comment]
Interesting. Can you post the stack trace for this error (from debug mode)?

**Comment by jesukiran** [comment]
I was trying to run this basic script (to check if everything is okay):

#include <fdeep/fdeep.hpp>
int main()
{
	const auto model = fdeep::load_model("fdeep_model.json");
	const auto result = model.predict(
		{ fdeep::tensor5(fdeep::shape5(1, 1, 1, 1, 4), {1, 2, 3, 4}) });
	std::cout << fdeep::show_tensor5s(result) << std::endl;
}

But I am getting the exception error. Posting a screenshot here:
![callstack](https://user-images.githubusercontent.com/25926887/62361416-42255c80-b51b-11e9-979c-4f2695533cbe.png)

**Comment by Dobiasd** [comment]
There is a message attached to the exception you see. :)

It stems from here: https://github.com/Dobiasd/frugally-deep/blob/3eafef23d63594049e4975106798e31342f22c96/include/fdeep/model.hpp#L30

So basically the shape of the tensor you try to feed into you model does not match the input shape of your model.

**Comment by jesukiran** [comment]
Apologies, my mistake! The input shapes were indeed different!
If I may both a bit more, I am just wondering what changes I would need to make in this script to implement it for a single channel (32x32) image. (I tried commenting out the cvtColor and the image.channels part, but I still get that exception error)

const cv::Mat image = cv::imread("image_1.jpg");
cv::cvtColor(image, image, cv::COLOR_BGR2RGB);
assert(image.isContinuous());
const auto model = fdeep::load_model("fdeep.json");
const auto input = fdeep::tensor5_from_bytes(image.ptr(),
	static_cast<std::size_t>(image.rows),
	static_cast<std::size_t>(image.cols),
	static_cast<std::size_t>(image.channels()),
	0.0f, 1.0f);

**Comment by Dobiasd** [comment]
If you know the image shape, you would like to achieve, i.e., your model's input shape, you just need to find out how make your input image match. Either using OpenCV or some image processing software to create a already fitting jpg file.

Anyways, the solution to your problem is unrelated to frugally-deep. :)

**Comment by Dobiasd** [comment]
And if you find out how to display the message (`msg`) attached to the exception you get, you'll immediately see the shape you provide vs. the shape that is needed.

**Comment by jesukiran** [comment]
Thanks for this, I am going to check it out!
