### ISSUE TITLE
Compatibility with Emscripten

### ISSUE THREAD

**Issue by chiakimz** [Dobiasd/frugally-deep#161]
Hello! Let me quickly thank you for your wonderful work first. It's been helping me a lot!

As the title suggests, I'm having a problem with emscripten as I'm trying to build my application in browser. It seems like it's having an issue with loading my model, which is the first line frugally-deep library is involved. Which made me wonder if frugally-deep is compatible with emscripten? It compiles fine in Visual Studio, but in browser, it seems to be causing an error.

I'm a novice programmer so my apology in advance for not being able to figure out by myself by looking at your code, and I'm sorry for bothering you.

Please let me know if it's compatible with emscripten, and also if you have any idea of what I can do to make it work. 

Thank you so much in advance!

Best,
Chiaki

**Comment by Dobiasd** [comment]
Hi,

and thanks for looking into frugally-deep.

I've not yet tried to make it work with emscripten. What's the error?

Also, did you consider TensorFlow.js?

**Comment by chiakimz** [comment]
Thanks for getting back to me so quickly! I understand. 
The error message is basically useless, so I put some std::cout here and there to see where it stops. Haven't been able to confirm if it's about loading the model or frugally-deep as a library itself.
I don't understand why using TensorFlow.js is relevant? Emscripten does convert C++ code into js, but as I understand it, what frugally-deep does is to enable Keras model to be used in C++? What's the benefit of using Tensorflow.js?

**Comment by Dobiasd** [comment]
TF.js was just as an idea for a fallback to use a model in JavaScript in case it turns out to be too cumbersome to get frugally-deep to work in the browser.

Let me know if I can be of any help, or if you run into any questions while trying to make it work.

**Comment by chiakimz** [comment]
Ah got it. It would've been great if I could do it, but unfortunately I really need to use C++!
Thank you so much for your kind offer. And thank you for your time! Have a great day :)
