### ISSUE TITLE
Channels first

### ISSUE THREAD

**Issue by pfeatherstone** [Dobiasd/frugally-deep#163]
Does frugally support channels first ?

**Comment by Dobiasd** [comment]
No.

**Comment by Dobiasd** [comment]
But maybe [converting your model/data](https://stackoverflow.com/questions/43829711/what-is-the-correct-way-to-change-image-channel-ordering-between-channels-first) is a feasible solution to you.

**Comment by pfeatherstone** [comment]
So simply changing one line in the json file and reloading it will change all the kernels and appropriately modify concatenation layers? I will give it a go. My original problem was going pytorch -> ONNX -> keras -> frugally. My solution was pytorch -> ONNX-> opencv. It worked fine. Though not ideal because opencv is so bloated and had to cross compile it for android which took me a while.

**Comment by Dobiasd** [comment]
> So simply changing one line in the json file and reloading it will change all the kernels and appropriately modify concatenation layers?

In the JSON file with the fdeep model? No.

Otherwise, I honestly have no idea.

**Comment by pfeatherstone** [comment]
I was thinking the json file exported by keras. No matter. Thanks for the tip though.

**Comment by Dobiasd** [comment]
Ah, right. Keras also has a JSON format. I had forgotton about this. :)
