### ISSUE TITLE
Fail to build main.cpp due to Eigen error

### ISSUE THREAD

**Issue by dviettu134** [Dobiasd/frugally-deep#164]
Hi, thank you for this nice project.

I have successfully followed the installation steps described in INSTALL.md.

After that, I followed the steps in README.md to execute the example. The training part was OK and I got the "keras_model.h5" in the directory. However when I compiled the "main.cpp" file with:
`g++ -std=c++14 main.cpp`

It gives me this error:

> In file included from /usr/local/include/Eigen/Core:155:0,
>                  from /usr/local/include/fdeep/common.hpp:23,
>                  from /usr/local/include/fdeep/fdeep.hpp:9,
>                  from main.cpp:1:
> /usr/local/include/Eigen/src/Core/util/IntegralConstant.h:189:36: error: template declaration of \u2018const Eigen::internal::FixedInt<N> Eigen::fix\u2019
>  static const internal::FixedInt<N> fix{};
>                                     ^
> In file included from /usr/local/include/Eigen/Core:244:0,
>                  from /usr/local/include/fdeep/common.hpp:23,
>                  from /usr/local/include/fdeep/fdeep.hpp:9,
>                  from main.cpp:1:
> /usr/local/include/Eigen/src/Core/util/IndexedViewHelper.h:57:147: error: \u2018fix\u2019 was not declared in this scope
>  static const symbolic::AddExpr<symbolic::SymbolExpr<internal::symbolic_last_tag>,symbolic::ValueExpr<Eigen::internal::FixedInt<1> > > lastp1(last+fix<1>());
>                                                                                                                                                    ^
> /usr/local/include/Eigen/src/Core/util/IndexedViewHelper.h:57:154: error: expected primary-expression before \u2018)\u2019 token
>  static const symbolic::AddExpr<symbolic::SymbolExpr<internal::symbolic_last_tag>,symbolic::ValueExpr<Eigen::internal::FixedInt<1> > > lastp1(last+fix<1>());
>                                                                                                                                                           ^
> In file included from /usr/local/include/Eigen/Core:246:0,
>                  from /usr/local/include/fdeep/common.hpp:23,
>                  from /usr/local/include/fdeep/fdeep.hpp:9,
>                  from main.cpp:1:
> /usr/local/include/Eigen/src/Core/ArithmeticSequence.h:142:64: error: \u2018fix\u2019 was not declared in this scope
>    auto reverse() const -> decltype(Eigen::seqN(m_first+(m_size+fix<-1>())*m_incr,m_size,-m_incr)) {

Do you have any ideas why this error occurred?

My environment:
Ubuntu 16.04
gcc, g++ 4.9.3
tensorflow 1.9.0
Keras 2.2.4

**Comment by Dobiasd** [comment]
Hi, and thanks for the report.

Could you please try compiling [any minimal eigen example](https://eigen.tuxfamily.org/dox/GettingStarted.html) like the following one, and let me know about the results?

```cpp
#include <iostream>
#include <Eigen/Dense>
using Eigen::MatrixXd;
int main()
{
  MatrixXd m(2,2);
  m(0,0) = 3;
  m(1,0) = 2.5;
  m(0,1) = -1;
  m(1,1) = m(1,0) + m(0,1);
  std::cout << m << std::endl;
}
```

**Comment by dviettu134** [comment]
Hi @Dobiasd ,
Thanks for your quick reply.

I tried to compile your example by g++ 4.9.3 with std=c++14 flag,
But it still gives the same error.

**Comment by Dobiasd** [comment]
Ok, thanks. This is good, because the problem is unrelated to frugally-deep, and we know that it originates from your Eigen installation. Or maybe updating your compiler might help.

If that does also not help, you can try asking the Eigen people or on StackOverflow.

**Comment by dviettu134** [comment]
Thank your for your suggestion,

I change the compiler to g++-5 and it went well now.
