### ISSUE TITLE
ETL backend

### ISSUE THREAD

**Issue by pfeatherstone** [Dobiasd/frugally-deep#166]
Have you considered trying out the ETL library as a tensor backend?
https://github.com/wichtounet/etl
It’s header only and supposedly heavily optimised. Might be worth a try.

**Comment by Dobiasd** [comment]
Thanks for the suggestion.

I'll make some performance measurements comparing it with Eigen and post the results.

**Comment by Dobiasd** [comment]
Since frugally-deep needs to have the exact same convolution results as Keras and Tensorflow produce, simply using a different convolution algorithm is likely to not be feasible.

But luckily, the main computational part of convolution is matrix multiplication (coming from the im2col method, also used in fdeep). If we speed up GEMM, we will speed up fdeep's convolution. Thus I compared GEMM of eigen with etl:

```cpp
// gemm_benchmark.cpp

#include <chrono>
#include <iostream>

#include <eigen3/Eigen/Dense>
#include "etl/etl.hpp"


using EigenMat = Eigen::Matrix<float, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>;
using ETLMat = etl::dyn_matrix<float>;

#define mat_size_1 512
#define mat_size_2 4609
#define mat_size_3 784

float multiply_eigen()
{
    EigenMat a(mat_size_1, mat_size_2);
    EigenMat b(mat_size_2, mat_size_3);
    const std::size_t num_bytes = a.rows() * b.cols() * sizeof(float);
    float* ptr = (float*)std::malloc(num_bytes);
    Eigen::Map<EigenMat, Eigen::Unaligned> c(
        ptr,
        static_cast<Eigen::Index>(a.rows()),
        static_cast<Eigen::Index>(b.cols()));
    c.noalias() = a * b;
    float check_value = ptr[0];
    std::free(ptr);
    return check_value;
}

float multiply_etl()
{
    ETLMat a(mat_size_1, mat_size_2);
    ETLMat b(mat_size_2, mat_size_3);
    ETLMat c(mat_size_1, mat_size_3);
    c = a * b;
    float check_value = c[0, 0];
    return check_value;
}

template <typename Func>
void measure(const std::string& name, const Func f)
{
    using namespace std::chrono;
    float checksum = 0.0f; // to prevent compiler from optimizing everything away
    const auto start_time_ns = high_resolution_clock::now().time_since_epoch().count();
    const std::size_t runs = 10;
    for (size_t i = 0; i < runs; ++i)
    {
        checksum += f();
    }
    const auto end_time_ns = high_resolution_clock::now().time_since_epoch().count();
    const auto elapsed_ms = (end_time_ns - start_time_ns) / (runs * 1000000);
    std::cout << name << " (checksum: " << checksum << ") elapsed_ms: " << elapsed_ms << std::endl;
}

int main()
{
    for (std::size_t i = 0; i < 3; ++i)
    {
        measure("eigen                        ", multiply_eigen);
        measure("etl                          ", multiply_etl);
        std::cout << "--------" << std::endl;
    }
}
```

```bash
git clone --recurse-submodules https://github.com/wichtounet/etl
g++-7 --std=c++14 -I ./etl/include/ -I ./etl/lib/include/ -O3 -mfma gemm_benchmark.cpp -o gemm_benchmark
taskset --cpu-list 1 ./gemm_benchmark
```

Up to now it does not look good:
```
eigen                         (checksum: 0) elapsed_ms: 36
etl                           (checksum: 0) elapsed_ms: 492
--------
eigen                         (checksum: 0) elapsed_ms: 38
etl                           (checksum: 0) elapsed_ms: 499
--------
eigen                         (checksum: 0) elapsed_ms: 37
etl                           (checksum: 0) elapsed_ms: 491
```

But I guess there might be some ways to make it faster. @pfeatherstone would you be interested in exploring these ways, building on the minimal benchmark above?

**Comment by pfeatherstone** [comment]
Interesting. I've realised that most tensor libraries claim they are faster than each other according to their own benchmarks. But, according to the test above, it would seem that ETL loses. 

Worth saying that ETL keeps track of operations and only computes when evaluated. I think a lot of tensor libraries are doing that, including eigen with its tensor object. So I guess you see real benefits when you start chaining operations, much like in a neural network. So maybe ETL wins when you associate 2 or more convolutions in a row.

I'm off on holiday for 2 weeks so wont get any time to look at this.
When I get back i'll start doing some tests with eigen::tensor, etl and some of the other linear algebra libraries and benchmark associative operations

**Comment by Dobiasd** [comment]
Assuming the TensorFlow people already use the fastest possible code for convolution (and GEMM), the fact that [convolution in frugally-deep is roughly equally fast compared with TensorFlow](https://github.com/Dobiasd/frugally-deep/issues/167#issuecomment-554938299) points to the conclusion, that currently there is not much to gain in terms of speed. So I'll close this issue for now.
