### ISSUE TITLE
Get output shape from model

### ISSUE THREAD

**Issue by FlatErik90** [Dobiasd/frugally-deep#168]
Is there a way to get the output shape of a model without predicting a dummy input?
In my case it would be helpful to now the number of output classes after loading the model. 
Of course, predicting with a dummy input and inspecting the output would give me such information but is not the optimal solution.

Do I oversee something here or is it not implemented?

**Comment by Dobiasd** [comment]
Hi Eric,

currently it is not implemented. Up to now the model did not need to know about the output shapes. They just came from the last layer.

Also, in case of some architectures, the output shape might not be constant, but depend on the input shape instead.

In case the dummy prediction is a significant performance problem for you, I can try to add the output shape as a fix property. Or you can also submit a pull request, if you like. :)

**Comment by FlatErik90** [comment]
Thanks for your reply.
If it's not too much effort it would be very handy to have such a fix property in cases where the output shape is defined by the model. 
Submitting a pull request would probably take some time for me. So if it's a quick thing to do for you I'd be very happy :)

**Comment by Dobiasd** [comment]
OK, I'll see what I can do. :)

**Comment by Dobiasd** [comment]
@FlatErik90 [This commit](https://github.com/Dobiasd/frugally-deep/commit/32dd2f10c3023427452ad5a5a21f62875d01f43a) should solve your issue. :slightly_smiling_face:
