### ISSUE TITLE
Why load_model is not a member of fdeep?

### ISSUE THREAD

**Issue by zhoujinhai** [Dobiasd/frugally-deep#171]
I want to test the example, but it show load_model is not fdeep's member?
```C++
#include <fdeep/fdeep.hpp>

int main()
{
	const auto model = fdeep::load_model("fdeep_model.json");
	const auto result = model.predict(
	{ fdeep::tensor5(fdeep::shape5(1, 1, 1, 1, 4),{ 1, 2, 3, 4 }) });
	std::cout << fdeep::show_tensor5s(result) << std::endl;
}
```

**Comment by Dobiasd** [comment]
Please make sure have the latest version [installed](https://github.com/Dobiasd/frugally-deep/blob/master/INSTALL.md) correctly.

`load_model` definitely is a member of namespace `fdeep`. :grin:

**Comment by zhoujinhai** [comment]
ok！ thank you！
