### ISSUE TITLE
I am getting some errors as follow. Is it related to frugally-deep source code or my installation?

### ISSUE THREAD

**Issue by Terminou** [Dobiasd/frugally-deep#172]
![error](https://user-images.githubusercontent.com/27548058/64248403-a459ee80-cf19-11e9-94da-997e0b09780e.png)

**Comment by Dobiasd** [comment]
Please make sure your compiler supports C++14 and that you have it enabled.

**Comment by Terminou** [comment]
Thank you for your answer. I am using Visual Studio 2015 and it does support C++14. Could you please tell me how to check whether it is enabled or not?

**Comment by Dobiasd** [comment]
https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=vs-2015

**Comment by Terminou** [comment]
![image](https://user-images.githubusercontent.com/27548058/64282543-574c3b80-cf5e-11e9-9a5a-c5d69990cfa8.png)

I have just checked I am using C++14 since it is VS 2015. Can you help me to solve those errors?

**Comment by Dobiasd** [comment]
If you have the latest versions of FunctionalPlus and frugally-deep installed, maybe try to update the compiler. But first I'd doublecheck FunctionalPlus version.

**Comment by Terminou** [comment]
I tried with VS 2017. However, still get those outputs. Is that a problem?
![image](https://user-images.githubusercontent.com/27548058/64313640-f4d25a00-cfb4-11e9-91a5-bed914c9d1b9.png)

**Comment by Dobiasd** [comment]
What do you mean by "those outputs"?

In your original screenshot you had compiler errors. But in the recent one, the code was compiled, linked and ran successfully. :+1:

**Comment by Terminou** [comment]
Okay. It is working. Thank you for your help.
