### ISSUE TITLE
Multiply layer behaves different than in Keras

### ISSUE THREAD

**Issue by nicochidt** [Dobiasd/frugally-deep#173]
Hi again Tobias, 

While using the library I noticed that the multiply layer behaves different in fdeep than it does in Keras. 

The following model: 

```{python}
inp_layer = Input(shape = (10,), dtype=np.float)
x = Dense(2, activation='relu', name = 'nn1-h1')(inp_layer)

x2 = Dense(1, activation='relu', name = 'nn2-h1')(inp_layer)

output = multiply([x,x2])
model = Model(inputs=inp_layer, output=[output])
model.compile(optimizer='adam', loss = 'categorical_crossentropy', metrics=['accuracy'])
```

can be evaluated in Keras without any problem (notice that the dimension of x is [2,batch_size] while x2 is [1,batch_size]). Keras is broadcasting the column vector behaving like a multiplication by a scalar. 

On the other side, in fdeep, this fails with the following error: 
`terminating with uncaught exception of type std::runtime_error: all tensor5s must have the same size`. 

Is this the desired situation? 

Thanks again for this wonderful library.

**Comment by Dobiasd** [comment]
> Is this the desired situation?
Of course not. :grin:

Thanks for the great minimal example, I'll have a look.

**Comment by Dobiasd** [comment]
Fixed in version [`v0.9.4-p0`](https://github.com/Dobiasd/frugally-deep/releases/tag/v0.9.4-p0).

Thanks again. Working with you is a real pleasure. :slightly_smiling_face:

**Comment by Dobiasd** [comment]
I know from own experience with other libraries, how much work it can be to reduce a problem so such a minimal example for reporting the issue. It's really nice that you invest the time, thus making my life easier.

**Comment by nicochidt** [comment]
No problem at all! Your library it's amazing, so I'm glad to contribute at least testing it.
