### ISSUE TITLE
xtensor and xtensor-blas backend

### ISSUE THREAD

**Issue by pfeatherstone** [Dobiasd/frugally-deep#176]
Hello again!
Just come across these:
https://github.com/QuantStack/xtensor
https://github.com/QuantStack/xtensor-blas
Header-only c++14 libraries (just the way you like them) with really nice apis almost identical to numpy. Don't know if they are faster than eigen3 but would definitely be a candidate if you fancied revamping your internal api.

**Comment by pfeatherstone** [comment]
From their docs:

_**Continuous benchmarking**
Xtensor operations are continuously benchmarked, and are significantly improved 
at each new version. Current performances on statically dimensioned tensors 
match those of the **Eigen** library. Dynamically dimension tensors for which the 
shape is heap allocated come at a small additional cost._

**Comment by Dobiasd** [comment]
> if you fancied revamping your internal api.

If it improves performance, I fancy it. :slightly_smiling_face:

Would you be interested in checking it's matrix-multiplication performance with [our benchmark template](https://github.com/Dobiasd/frugally-deep/issues/166#issuecomment-524302031)?

**Comment by Dobiasd** [comment]
Mhh, [seems like xtensor does not yet support matrix multiplication](https://github.com/QuantStack/xtensor/issues/1375). :man_shrugging:

**Comment by pfeatherstone** [comment]
From xtensor-blas docs:

template<class T, class O>
auto xt::linalg::dot(const xexpression<T> &xt, const xexpression<O> &xo)
Non-broadcasting dot function.

In the case of two 1D vectors, computes the vector dot product. In the case of complex vectors, computes the dot product without conjugating the first argument. If t or o is a 2D matrix, computes the matrix-times-vector product. **If both t and o ar 2D matrices, computes the matrix-product**.

Return
resulting array

Parameters
t: input array

o: input array

**Comment by pfeatherstone** [comment]
Through it's confusing. They say in the issue that matmul is not supported. Surely _matrix-product_ is exactly that. Weird.

**Comment by Dobiasd** [comment]
```bash
git clone https://github.com/QuantStack/xtl/
git clone https://github.com/QuantStack/xtensor
git clone https://github.com/QuantStack/xtensor-blas
```

```cpp
// gemm_benchmark.cpp

#include <chrono>
#include <iostream>

#include <eigen3/Eigen/Dense>
#include "xtensor-blas/xlinalg.hpp"

using EigenMat = Eigen::Matrix<float, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>;

#define mat_size_1 512
#define mat_size_2 4609
#define mat_size_3 784

float multiply_eigen()
{
    EigenMat a(mat_size_1, mat_size_2);
    EigenMat b(mat_size_2, mat_size_3);
    const std::size_t num_bytes = a.rows() * b.cols() * sizeof(float);
    float* ptr = (float*)std::malloc(num_bytes);
    Eigen::Map<EigenMat, Eigen::Unaligned> c(
        ptr,
        static_cast<Eigen::Index>(a.rows()),
        static_cast<Eigen::Index>(b.cols()));
    c.noalias() = a * b;
    float check_value = ptr[0];
    std::free(ptr);
    return check_value;
}

float multiply_xtensorblas()
{
    const auto a = xt::zeros<float>({mat_size_1, mat_size_2});
    const auto b = xt::zeros<float>({mat_size_2, mat_size_3});
    const auto c = xt::linalg::dot(a, b);
    return c[{0, 0}];
}

template <typename Func>
void measure(const std::string& name, const Func f)
{
    using namespace std::chrono;
    float checksum = 0.0f; // to prevent compiler from optimizing everything away
    const auto start_time_ns = high_resolution_clock::now().time_since_epoch().count();
    const std::size_t runs = 10;
    for (size_t i = 0; i < runs; ++i)
    {
        checksum += f();
    }
    const auto end_time_ns = high_resolution_clock::now().time_since_epoch().count();
    const auto elapsed_ms = (end_time_ns - start_time_ns) / (runs * 1000000);
    std::cout << name << " (checksum: " << checksum << ") elapsed_ms: " << elapsed_ms << std::endl;
}

int main()
{
    for (std::size_t i = 0; i < 3; ++i)
    {
        measure("eigen                        ", multiply_eigen);
        measure("xtensor-blas                 ", multiply_xtensorblas);
        std::cout << "--------" << std::endl;
    }
}
```

```
g++-7 --std=c++14 -I ./xtl/include/ -I ./xtensor/include/ -I ./xtensor-blas/include/ -O3 -mfma gemm_benchmark.cpp -lcblas -o gemm_benchmark
taskset --cpu-list 1 ./gemm_benchmark
```

```
eigen                         (checksum: 0) elapsed_ms: 36
xtensor-blas                  (checksum: 0) elapsed_ms: 169
--------
eigen                         (checksum: 0) elapsed_ms: 37
xtensor-blas                  (checksum: 0) elapsed_ms: 167
--------
eigen                         (checksum: 0) elapsed_ms: 37
xtensor-blas                  (checksum: 0) elapsed_ms: 166
```

I'm not impressed. :wink:

**Comment by pfeatherstone** [comment]
I get this:

eigen                         (checksum: 0) elapsed_ms: 458
xtensor-blas                  (checksum: 0) elapsed_ms: 156
--------
eigen                         (checksum: 0) elapsed_ms: 463
xtensor-blas                  (checksum: 0) elapsed_ms: 170
--------
eigen                         (checksum: 0) elapsed_ms: 531
xtensor-blas                  (checksum: 0) elapsed_ms: 148

**Comment by pfeatherstone** [comment]
By the way, my laptop is old

**Comment by pfeatherstone** [comment]
Maybe your CPU has fancy instruction sets that Eigen supports that XTensor doesn't... Dunno. But the xtensor API is very nice.

**Comment by Dobiasd** [comment]
Yes, the API is nice. However frugally-deep interacts only in very few places with Eigen. So I would not like to sacrifice performance for this bit of internal beauty. Especially since the user of frugally-deep is not affected.

Maybe one would need to re-complile libcblas with more optimization to make xtensor faster.
Feel free to experiment with it.

In your tests, did you allow FMA instructions to be used (by Eigen)? Or does your CPU not even support them?

**Comment by pfeatherstone** [comment]
i just use -march=native

**Comment by pfeatherstone** [comment]
My cpu doesn't support fma

**Comment by pfeatherstone** [comment]
I'll check how the test fares on RPI zero, 2, 3, 4 tomorrow at work. That's my main application at the moment

**Comment by Dobiasd** [comment]
Interesting! Let's see what The Pis think about the benchmark.

To get an additional measurment, I just ran the thing from above not on my local machine (Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz) but on a different one (Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GH):

```
eigen                         (checksum: 0) elapsed_ms: 50
xtensor-blas                  (checksum: 0) elapsed_ms: 204
--------
eigen                         (checksum: 0) elapsed_ms: 45
xtensor-blas                  (checksum: 0) elapsed_ms: 202
--------
eigen                         (checksum: 0) elapsed_ms: 46
xtensor-blas                  (checksum: 0) elapsed_ms: 203
--------
```

**Comment by pfeatherstone** [comment]
I don't understand. I installed the latest release of eigen and got similar results. Oh well. My CPU AMD A6-5200.

**Comment by Dobiasd** [comment]
Ah, so the old Eigen was slow and the new Eigen is fast? Sounds reasonable, and also nice. :slightly_smiling_face:

**Comment by pfeatherstone** [comment]
I got the same results I got, i.e.
eigen (checksum: 0) elapsed_ms: 458
xtensor-blas (checksum: 0) elapsed_ms: 156

eigen (checksum: 0) elapsed_ms: 463
xtensor-blas (checksum: 0) elapsed_ms: 170

eigen (checksum: 0) elapsed_ms: 531
xtensor-blas (checksum: 0) elapsed_ms: 148

**Comment by Dobiasd** [comment]
Ah, OK. So I misunderstood what "similar" was referring to.
Maybe xtensor has optimizations for CPU A and B. And Eigen has for A and C.
In case your CPU is type B (assuming B is newer than A, and C is newer than B), it does not seem totally absurd that xtensor might be faster on your machine, while Eigen is faster on mine.

**Comment by pfeatherstone** [comment]
This is probably why every linear algebra library claims to be the fastest

**Comment by Dobiasd** [comment]
Assuming the TensorFlow people already use the fastest possible code for convolution (and GEMM), the fact that [convolution in frugally-deep is roughly equally fast compared with TensorFlow](https://github.com/Dobiasd/frugally-deep/issues/167#issuecomment-554938299) points to the conclusion, that currently there is not much to gain in terms of speed. So I'll close this issue for now.
