### ISSUE TITLE
Switch from keras to tf.keras

### ISSUE THREAD

**Issue by Dobiasd** [Dobiasd/frugally-deep#179]
With the [release of version 2.3.0](https://github.com/keras-team/keras/releases/tag/2.3.0), team Keras announced the following:

> This is also the last major release of multi-backend Keras. Going forward, we recommend that users consider switching their Keras code to tf.keras in TensorFlow 2.0. It implements the same Keras 2.3.0 API (so switching should be as easy as changing the Keras import statements), but it has many advantages for TensorFlow users, such as support for eager execution, distribution, TPU training, and generally far better integration between low-level TensorFlow and high-level concepts like Layer and Model. It is also better maintained.

> Development will focus on tf.keras going forward. We will keep maintaining multi-backend Keras over the next 6 months, but we will only be merging bug fixes. API changes will not be ported.

So frugally-deep should follow this change.

**Comment by maazulmosaid** [comment]
When is it going to happen? I installed latest version of tensorflow and keras using pip on windows but it is failing.

**Comment by Dobiasd** [comment]
Currently I'm planning to work on making frugally-deep compatible with TensorFlox 2.x (and switch from `keras` to `tf.keras`) in November.

**Comment by Dobiasd** [comment]
Status report: I'm on it, but it's arduous.

Not just interfaces are incompatible:
- `layer.batch_input_shape`s that were something like `(1, 2, 3)` in `keras` are `[(1, 2, 3)]` in `tf.keras`.
- `model.name` can no longer be overwritten.
- `model.model` does no longer exist for `Sequential` models.

But also implementations have changed:
- `UpSampling2D` with `bilinear` calculated the values differently (`0.5` pixel offset vs. no offset).

Nevertheless, this should all be solvable.

**Comment by Dobiasd** [comment]
Just released [version `v0.11.0-p0` of frugally-deep](https://github.com/Dobiasd/frugally-deep/releases/tag/v0.11.0-p0). It uses `tf.keras` instead of `keras`.
