### ISSUE TITLE
Model with custom metrics

### ISSUE THREAD

**Issue by wlcosta** [Dobiasd/frugally-deep#18]
Hi!
So, I have a model on Keras which uses a custom metric:

```
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=[angle_error])
```

where

```
def angle_error(y_true, y_pred):
    diff = angle_difference(K.argmax(y_true), K.argmax(y_pred))
    return K.mean(K.cast(K.abs(diff), K.floatx()))
```

When I try to convert the saved model from hdf5 to json, I get the following error:

```
ValueError: Unknown metric function:angle_error
```

How can I proceed?

**Comment by Dobiasd** [comment]
Hi,

in case you built the model using the [functional API](https://keras.io/getting-started/functional-api-guide/), simple saving the model from your code without optimizer as h5 should suffice:
```python
model.save('my_model.h5', include_optimizer=False)
```

Or are you using the [sequential API](https://keras.io/models/sequential/)?

**Comment by wlcosta** [comment]
I'm using ResNet50 as a base model:

```
base_model = ResNet50(weights='imagenet', include_top=False,
                      input_shape=input_shape)
```

I'll try your suggestion

On Feb 19, 2018 17:40, "Tobias Hermann" <notifications@github.com> wrote:

Hi,

in case you built the model using the functional API
<https://keras.io/getting-started/functional-api-guide/>, simple saving the
model from your code without optimizer as h5 should suffice:

model.save('my_model.h5', include_optimizer=False)

Or are you using the sequential API <https://keras.io/models/sequential/>?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Dobiasd/frugally-deep/issues/18#issuecomment-366797852>,
or mute the thread

**Comment by Dobiasd** [comment]
ResNet is functional, so it should work.

Nevertheless, I just pushed a commit that also should make it possible for sequential models.

If you experience further problems, just let me know, and we can reopen this issue.
