### ISSUE TITLE
Support for TensorFlow 2.x

### ISSUE THREAD

**Issue by Dobiasd** [Dobiasd/frugally-deep#180]
[TensorFlow 2.0.0 has been released](https://github.com/tensorflow/tensorflow/releases/tag/v2.0.0). Frugally-deep should be tested with it. And if needed, additional support should be added.

**Comment by maazulmosaid** [comment]
I do not know where to ask but could you please tell me the latest version of tensorflow and keras on which frugally deep is working? I am getting this error from convert_model when I try to convert hd5 file to JSON. 

ValueError: Unknown initializer: GlorotUniform

**Comment by Dobiasd** [comment]
Just tested with TensorFlow `2.0.0`. All tests passed out of the box without any adjustments. :tada:
