### ISSUE TITLE
Diffenrent result in keras and frugally (maybe a bug)! 

### ISSUE THREAD

**Issue by aligoglos** [Dobiasd/frugally-deep#183]
I tried to convert a `keras` model and use it in c++ with `frugally`.
but I've got different results for example 8 first output in python is :
```
[5.4324843e-18 1.0000000e+00 1.2433101e+00 1.3983418e-01 1.0773285e-01
 1.7222428e-01 9.0358293e-01 3.3537847e-01]
```
but in c++ is :
`inf inf 1.24331 0.139835 0.107733 0.172224 0.903583 0.335378`

Why the first two results are inf ? (and problem is a lot of results are inf)

python sample code :

```
def main():
	lp_threshold = .5
	wpod_net = load_model("data/lp-detector/wpod.h5")
	Ivehicle = cv2.imread('car.png')
	T = Ivehicle.astype('float32')/255.
	T = T.reshape((1, T.shape[0], T.shape[1], T.shape[2]))
	Yr = wpod_net.predict(T)
	Yr = np.squeeze(Yr)
	print(Yr.flatten()[0:8])
	pass
```
c++ sample code :

```
void main() {
	cv::Mat car = cv::imread("car.png");
	fdeep::model wpod = fdeep::load_model("wpod.json");

	fdeep::tensor5 input = fdeep::tensor5_from_bytes(car.data,
		car.rows, car.cols, car.channels(), 0.0, 1.0);
	fdeep::tensor5s Yr = wpod.predict({ input });
	fdeep::tensor5 var = Yr[0];
	std::cout << std::endl << std::endl;
	std::vector<float> Y = *var.as_vector();
	for (size_t i = 0; i < 8; i++)
		std::cout << Y[i] << " ";

	std::getchar();
}
```
[model](https://drive.google.com/open?id=1oq4ggdV9L3o1L3K-3ZKtuXGos4S8yOFH)
[input](https://drive.google.com/open?id=1Rc9stWvDMZPaczUAc0K0QrY4BxAuFUoA)

**Comment by Dobiasd** [comment]
Thanks for the very good report.

Currently I'm only with my phone for a few days. I could check your example next week.

But my guess is, it has something to do with the pixel-value scaling. Maybe try scaling the values not to the interval of 0.0 to 1.0 but to 0.0 to 255.0 (in the call to `tensor5_from_pixels`).

**Comment by aligoglos** [comment]
This is another weird example that results are completely different :

python code :
```
def main():
	#lp_threshold = .5
	wpod_net = load_model("data/lp-detector/wpod.h5")
	I = cv2.imread('car.png')
	w = 416
	h = 352
	Iresized = cv2.resize(I, (w, h))
	T = Iresized.astype('float32')/255.
	T = T.reshape((1, T.shape[0], T.shape[1], T.shape[2]))
	Yr = wpod_net.predict(T)
	Yr = np.squeeze(Yr)
	print(Yr.flatten()[0:50])
	pass
```
c++ code :
```
void main() {
	cv::Mat car = cv::imread("My_test/car.png");
	fdeep::model wpod = fdeep::load_model("Resources/wpod.json");
	int w = 416, h = 352;
	cv::resize(car, car, cv::Size(w, h));
	car.convertTo(car, CV_32F);
	car /= 255.0;
	fdeep::tensor5 input = fdeep::tensor5_from_bytes(car.data,
		car.rows, car.cols, car.channels());
	fdeep::tensor5s Yr = wpod.predict({ input });
	fdeep::tensor5 var = Yr[0];
	std::cout << std::endl << std::endl;
	std::vector<float> Y = *var.as_vector();
	for (size_t i = 0; i < 50 ; i++)
		std::cout << Y[i] << " , ";
	std::getchar();
}
```
python results :
```
[ 1.8990249e-18  1.0000000e+00  8.8887548e-01  4.4502267e-01
 -3.0078316e-01 -3.4347424e-01  6.8084407e-01  1.7208092e-01
  4.3536158e-18  1.0000000e+00  1.0671058e+00  1.6989625e-01
 -2.7317917e-01 -2.8231141e-01  4.6219370e-01  5.7073787e-02
  2.4894937e-14  1.0000000e+00  9.7948891e-01  1.4742213e-01
 -3.4606284e-01 -4.9185070e-01  6.9448376e-01  9.5374763e-02
  2.8436144e-12  1.0000000e+00  1.0725648e+00  2.6533031e-01
 -4.2111593e-01 -8.0518687e-01  4.8875323e-01  2.1816543e-01
  4.1113366e-18  1.0000000e+00  1.1067774e+00  2.4355637e-01
 -6.0044640e-01 -9.1815859e-01  5.0183493e-01  8.1341594e-02
  7.7956050e-19  1.0000000e+00  1.2438575e+00  5.6224191e-03
 -6.2880999e-01 -4.2654344e-01  5.8403283e-01  9.1635764e-02
  1.1364421e-16  1.0000000e+00]
```
c++ results:
`inf , inf , 0.608054 , 0.286326 , -0.270938 , -0.407815 , 0.446417 , 0.11733 , inf , inf , 0.752583 , 0.0144872 , -0.302368 , -0.214064 , 0.316837 , -0.0400211 , inf , inf , 0.650747 , 0.0385172 , -0.155947 , -0.270916 , 0.375472 , 0.00357534 , inf , inf , 0.698534 , 0.0155585 , -0.206313 , -0.183662 , 0.335891 , 0.11997 , inf , inf , 0.797784 , 0.0112997 , -0.222351 , -0.137532 , 0.297348 , 0.0744187 , inf , inf , 0.679785 , -0.0691486 , -0.159725 , -0.027909 , 0.269561 , -0.0150426 , inf , inf ,`

**Comment by aligoglos** [comment]
c++ result with `low = 0` and `high = 255`

`inf , inf , -140.924 , -133.47 , -73.8041 , 73.2795 , 173.122 , 36.5791 , inf , inf , -100.736 , -130.603 , -82.6873 , -85.6458 , 194.832 , 84.1944 , inf , inf , -80.5924 , -229.017 , -138.934 , -155.83 , 230.411 , 79.0639 , inf , inf , -72.3066 , -333.811 , -157.917 , -167.246 , 291.076 , 55.3534 , inf , inf , -40.71 , -399.14 , -181.288 , -187.075 , 324.994 , 26.2557 , inf , inf , -8.26447 , -441.197 , -198.812 , -182.107 , 338.499 , -0.298502 , inf , inf ,`

**Comment by Dobiasd** [comment]
Loading the model already does such a test, and when it succeeds, that means that your model is giving the same results in C++  compared to Keras. So my guess is still, that the actual values going in to the prediction are not the same in your C++ example as they are in Keras. Could you please verify this? Also please try with double precision instead of float. You can find more about this in the FAQ.md.

**Comment by aligoglos** [comment]
As you guess inputs are different. but before `fdeep::tensor5_from_bytes` both inputs are exactly same:
```
print(T.flatten()[0:50]) 
[0.12941177 0.13333334 0.09803922 0.13333334 0.13333334 0.09411765
 0.14509805 0.13725491 0.09803922 0.14509805 0.13725491 0.09411765
 0.11372549 0.10588235 0.0627451  0.1254902  0.12156863 0.07843138
 0.14117648 0.14117648 0.09803922 0.14901961 0.15294118 0.11764706
 0.14509805 0.15294118 0.12941177 0.14509805 0.15686275 0.13333334
 0.14117648 0.14509805 0.11764706 0.14117648 0.14117648 0.10588235
 0.16078432 0.15686275 0.11764706 0.16470589 0.15686275 0.1254902
 0.16862746 0.16078432 0.12941177 0.16470589 0.16078432 0.12941177
 0.14901961 0.15294118]
```
and c++ :
```
car.convertTo(car, CV_64F);
car /= 255.0;
std::cout << std::endl;
for (size_t i = 0; i < 50; i++)
	std::cout << car.at<double>(i) << " , ";

0.129412 , 0.133333 , 0.0980392 , 0.133333 , 0.133333 , 0.0941176 , 0.145098 , 0.137255 , 0.0980392 , 0.145098 , 0.137255 , 0.0941176 , 0.113725 , 0.105882 , 0.0627451 , 0.12549 , 0.121569 , 0.0784314 , 0.141176 , 0.141176 , 0.0980392 , 0.14902 , 0.152941 , 0.117647 , 0.145098 , 0.152941 , 0.129412 , 0.145098 , 0.156863 , 0.133333 , 0.141176 , 0.145098 , 0.117647 , 0.141176 , 0.141176 , 0.105882 , 0.160784 , 0.156863 , 0.117647 , 0.164706 , 0.156863 , 0.12549 , 0.168627 , 0.160784 , 0.129412 , 0.164706 , 0.160784 , 0.129412 , 0.14902 , 0.152941 ,
```

but after pass into fdeep::tensor5_from_bytes inputs change:

fdeep::tensor5 input = fdeep::tensor5_from_bytes(car.data,
		car.rows, car.cols, car.channels());
	std::vector<double> I = *input.as_vector();
	std::cout << std::endl << std::endl << std::endl;
	for (size_t i = 0; i < 50; i++)
		std::cout << I[i] << " , ";
`0.564706 , 0.564706 , 0.564706 , 0.564706 , 0.564706 , 0.564706 , 0.752941 , 0.247059 , 0.0666667 , 0.0666667 , 0.0666667 , 0.0666667 , 0.0666667 , 0.0666667 , 0.756863 , 0.247059 , 0.0980392 , 0.0980392 , 0.0980392 , 0.0980392 , 0.0980392 , 0.0980392 , 0.72549 , 0.247059 , 0.0666667 , 0.0666667 , 0.0666667 , 0.0666667 , 0.0666667 , 0.0666667 , 0.756863 , 0.247059 , 0.0666667 , 0.0666667 , 0.0666667 , 0.0666667 , 0.0666667 , 0.0666667 , 0.756863 , 0.247059 , 0.0941176 , 0.0941176 , 0.0941176 , 0.0941176 , 0.0941176 , 0.0941176 , 0.721569 , 0.247059 , 0.572549 , 0.572549 ,`

some thing is wrong in `fdeep::tensor5_from_bytes`

**Comment by Dobiasd** [comment]
`tensor5_from_bytes` is only to be used for Bytes. If you instead already have your pixels as floats, don't use it. You can just copy your pixel values into a tensor5 object. See FAQ.md for how to do this

**Comment by aligoglos** [comment]
I tried this code to copy input :
```
void main() {
	cv::Mat car = cv::imread("My_test/out.png");
	fdeep::model wpod = fdeep::load_model("Resources/wpod.json");
	int w = 416, h = 352;
	cv::resize(car, car, cv::Size(w, h));
	car.convertTo(car, CV_64F);
	car /= 255.0;
	std::cout << std::endl;
	for (size_t i = 0; i < 50; i++)
		std::cout << car.at<double>(i) << " , ";
	fdeep::shape5 tensor5_shape(1, 1, car.rows, car.cols, car.channels());
	fdeep::tensor5 input = fdeep::tensor5(tensor5_shape, 0.0);
	for (int y = 0; y < tensor5_shape.height_; ++y)
	{
		for (int x = 0; x < tensor5_shape.width_; ++x)
		{
			for (int c = 0; c < tensor5_shape.depth_; ++c)
			{
				input.set(0, 0, y, x, c, car.at<cv::Vec3d>(y, x)[c]);
			}
		}
	}
	std::vector<double> I = *input.as_vector();
	std::cout << std::endl << std::endl << std::endl;
	for (size_t i = 0; i < 50; i++)
		std::cout << I[i] << " , ";
	fdeep::tensor5s Yr = wpod.predict({ input });
	fdeep::tensor5 var = Yr[0];
	std::cout << std::endl << std::endl;
	std::vector<double> Y = *var.as_vector();
	for (size_t i = 0; i < 50 ; i++)
		std::cout << Y[i] << " , ";
	std::getchar();
}
```
result is :
```
Loading json ... done. elapsed time: 0.160257 s
Running test 1 of 1 ... done. elapsed time: 0.025045 s
Loading, constructing, testing of Resources/wpod.json took 0.380041 s overall.

0.701961 , 0.878431 , 0.92549 , 0.666667 , 0.784314 , 0.847059 , 0.560784 , 0.615686 , 0.67451 , 0.470588 , 0.47451 , 0.521569 , 0.34902 , 0.32549 , 0.356863 , 0.164706 , 0.133333 , 0.156863 , 0.278431 , 0.235294 , 0.243137 , 0.160784 , 0.137255 , 0.137255 , 0.0588235 , 0.0705882 , 0.0784314 , 0.168627 , 0.215686 , 0.219608 , 0.552941 , 0.619608 , 0.635294 , 0.521569 , 0.596078 , 0.615686 , 0.0784314 , 0.113725 , 0.137255 , 0.0588235 , 0.0823529 , 0.0980392 , 0.0509804 , 0.0588235 , 0.0705882 , 0.290196 , 0.313725 , 0.317647 , 0.223529 , 0.262745 ,


0.701961 , 0.878431 , 0.92549 , 0.666667 , 0.784314 , 0.847059 , 0.560784 , 0.615686 , 0.67451 , 0.470588 , 0.47451 , 0.521569 , 0.34902 , 0.32549 , 0.356863 , 0.164706 , 0.133333 , 0.156863 , 0.278431 , 0.235294 , 0.243137 , 0.160784 , 0.137255 , 0.137255 , 0.0588235 , 0.0705882 , 0.0784314 , 0.168627 , 0.215686 , 0.219608 , 0.552941 , 0.619608 , 0.635294 , 0.521569 , 0.596078 , 0.615686 , 0.0784314 , 0.113725 , 0.137255 , 0.0588235 , 0.0823529 , 0.0980392 , 0.0509804 , 0.0588235 , 0.0705882 , 0.290196 , 0.313725 , 0.317647 , 0.223529 , 0.262745 ,

inf , inf , 0.742925 , 0.129178 , -0.0187831 , -0.0405883 , 0.500434 , 0.0863447 , inf , inf , 0.679402 , 0.00228053 , -0.0352391 , 0.174584 , 0.551324 , -0.0649542 , inf , inf , 0.564841 , -0.0105782 , -0.0486337 , 0.206211 , 0.478686 , 0.0406656 , inf , inf , 0.634077 , -0.0282231 , -0.113628 , 0.153115 , 0.508854 , 0.11141 , inf , inf , 0.704396 , 0.0370189 , -0.101175 , 0.0562826 , 0.530042 , 0.128575 , inf , inf , 0.919137 , 0.0333654 , -0.165806 , 0.102123 , 0.631832 , 0.144624 , inf , inf ,
```
in python :
```
def main():
	#lp_threshold = .5
	wpod_net = load_model("data/lp-detector/wpod.h5")
	I = cv2.imread('out.png')
	# net_step = 2 ** 4
	# ratio = float(max(I.shape[:2])) / min(I.shape[:2])
	# side = int(ratio * 288.)
	# max_dim = min(side + (side % (2 ** 4)), 608)
	# min_dim_img = min(I.shape[:2])
	# factor = float(max_dim) / min_dim_img
	#
	# w, h = (np.array(I.shape[1::-1], dtype=float) * factor).astype(int).tolist()
	# w += (w % net_step != 0) * (net_step - w % net_step)
	# h += (h % net_step != 0) * (net_step - h % net_step)
	w = 416
	h = 352
	Iresized = cv2.resize(I, (w, h))
	T = Iresized.astype('float32')/255.
	T = T.reshape((1, T.shape[0], T.shape[1], T.shape[2]))
	print(T.flatten()[0:50])
	Yr = wpod_net.predict(T)
	Yr = np.squeeze(Yr)
	print(Yr.flatten()[0:50])
	pass
```
and python results:

```
[0.7019608  0.8784314  0.9254902  0.6666667  0.78431374 0.84705883
 0.56078434 0.6156863  0.6745098  0.47058824 0.4745098  0.52156866
 0.34901962 0.3254902  0.35686275 0.16470589 0.13333334 0.15686275
 0.2784314  0.23529412 0.24313726 0.16078432 0.13725491 0.13725491
 0.05882353 0.07058824 0.07843138 0.16862746 0.21568628 0.21960784
 0.5529412  0.61960787 0.63529414 0.52156866 0.59607846 0.6156863
 0.07843138 0.11372549 0.13725491 0.05882353 0.08235294 0.09803922
 0.05098039 0.05882353 0.07058824 0.2901961  0.3137255  0.31764707
 0.22352941 0.2627451 ]

[ 5.03816686e-08  1.00000000e+00  7.42924333e-01  1.29178256e-01
 -1.87831037e-02 -4.05884683e-02  5.00433624e-01  8.63448828e-02
  5.87042912e-08  1.00000000e+00  6.79401696e-01  2.28047417e-03
 -3.52391377e-02  1.74584180e-01  5.51324189e-01 -6.49542511e-02
  1.10628134e-05  9.99988914e-01  5.64840794e-01 -1.05780903e-02
 -4.86337245e-02  2.06210881e-01  4.78686571e-01  4.06655148e-02
  1.00422234e-07  9.99999881e-01  6.34077311e-01 -2.82230098e-02
 -1.13627657e-01  1.53114289e-01  5.08853972e-01  1.11409999e-01
  1.05705211e-09  1.00000000e+00  7.04396009e-01  3.70189585e-02
 -1.01174623e-01  5.62819019e-02  5.30041993e-01  1.28574848e-01
  5.46828589e-11  1.00000000e+00  9.19136584e-01  3.33653912e-02
 -1.65805906e-01  1.02122582e-01  6.31832063e-01  1.44623667e-01
  3.97266665e-13  1.00000000e+00]
```
I'm pretty sure inputs are same you can test it. But as you can see I think problem is in value near 1.0 and very small value near 0.0 are inf in c++ version.

[newInput](https://drive.google.com/open?id=1e1f2lcUDyc3k9KqOC0gH0Pb_q25vZHQ_)

**Comment by Dobiasd** [comment]
OK, thanks. Could you try with double precision instead of float as shown [here](https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#what-to-do-when-loading-my-model-with-frugally-deep-throws-an-stdruntime_error-with-test-failed)?

**Comment by aligoglos** [comment]
I'd used it before please see c++ code.

**Comment by Dobiasd** [comment]
Ah, sorry. I'll check next week when I'm fully back online.

**Comment by aligoglos** [comment]
thanks.

**Comment by Dobiasd** [comment]
First step: I was able to reproduce the issue locally on my machine:

```python3
import cv2
import numpy as np
from keras.models import load_model

wpod_net = load_model("wpod.h5")
image = cv2.imread('car.png')
x = image.astype('float32') / 255.0
x = x.reshape((1, x.shape[0], x.shape[1], x.shape[2]))
result = wpod_net.predict(x)
result = np.squeeze(result)
print(result.flatten()[0:8])
```

```
[5.4325050e-18 1.0000000e+00 1.2433102e+00 1.3983467e-01 1.0773286e-01
 1.7222387e-01 9.0358281e-01 3.3537841e-01]
```

```cpp
#include "fdeep/fdeep.hpp"
#include <opencv2/opencv.hpp>

int main()
{
    const auto image = cv::imread("car.png");
    const auto model = fdeep::load_model("wpod.json");
    const auto x = fdeep::tensor5_from_bytes(image.ptr(), image.rows, image.cols, image.channels(), 0.0, 1.0);
    const auto result = model.predict({ x });
    const auto y = *result.front().as_vector();
    for (size_t i = 0; i < 8; i++)
    {
        std::cout << y[i] << " ";
    }
}
```

```
Loading json ... done. elapsed time: 0.143580 s
Running test 1 of 1 ... done. elapsed time: 0.004994 s
Loading, constructing, testing of wpod.json took 0.220907 s overall.
inf inf 1.24331 0.139835 0.107733 0.172224 0.903583 0.335378 %
```

I'll dig into it and get back to you with the results.

**Comment by Dobiasd** [comment]
Could you share the code that builds the model architecture used in `wpod.h5`? I'd like to try creating a minimal example by chopping off more and more parts of it. Sometimes this helps in isolating the problem.

**Comment by aligoglos** [comment]
It's base on [ this project ](https://github.com/sergiomsilva/alpr-unconstrained)

**Comment by Dobiasd** [comment]
Mhh, [this](https://github.com/sergiomsilva/alpr-unconstrained/blob/master/create-model.py) does not look too exotic.
Could you try what happens if you re-train the model, or try with an untrained one? It's weird, that the values, which are not `inf`, seem to be correct.

**Comment by keko950** [comment]
Im having the same problem as @aligoglos .

**Comment by Dobiasd** [comment]
@keko950: Interesting! Can you create a minimal example of it to reproduce the problem?

**Comment by Dobiasd** [comment]
@aligoglos Any news on [that](https://github.com/Dobiasd/frugally-deep/issues/183#issuecomment-538728894)?

**Comment by Dobiasd** [comment]
@aligoglos Ah, sorry. I did not read carefully enough. Thanks for the reminder. I'll check if I can find out what layer the first produces an `inf` or similar. Maybe this can give a hint.

**Comment by Dobiasd** [comment]
Good news. The issue is fixed now. :tada:

The output of original example now is `0 0 1.24331 0.139835 0.107733 0.172224 0.903583 0.335378`. The problem was in the implementation of the softmax activation, which was not prepared to all values in a stack being `0.0`, which happens in `xprobs    = Conv2D(2, 3, activation='softmax', padding='same')(x)` in the `end_block(x)` of [the model](https://github.com/sergiomsilva/alpr-unconstrained/blob/master/create-model.py).

@aligoglos Thanks for reporting and your patience.

---

@keko950 Please let me know if this fixes your problem too.

**Comment by aligoglos** [comment]
Thanks a lot.
