### ISSUE TITLE
Predict result as vector?

### ISSUE THREAD

**Issue by keko950** [Dobiasd/frugally-deep#184]
Hi!

Im trying to convert the tensor predict result to vector with 
const std::vector<float> v = *result.as_vector();

but im receiving this error 
 ‘const class std::vector<fdeep::internal::tensor5>’ has no member named ‘as_vector’; did you mean ‘vector’?

**Comment by Dobiasd** [comment]
Hi,

`tensor5::as_vecyor` is correct (see [here](https://github.com/Dobiasd/frugally-deep/blob/master/include/fdeep/tensor5.hpp#L103)).

However, your result is not a single `tensor5`, but a `vector` of `tensor5`s. So yoy might wanna try something like `result.front().as_vector`.

**Comment by keko950** [comment]
Your solution worked, thank you!
