### ISSUE TITLE
Bug in reading 1d upsampling layer

### ISSUE THREAD

**Issue by mvparakhin** [Dobiasd/frugally-deep#185]
UpSampling1D in Keras doesn't have an interpolation parameter, it is only "nearest", so, when saving the model it's not going to be in the json. When reading the model in Frugally Deep, the 2D layer is used, which doesn't find the interpolation parameter and throws an exception. The fix is trivial, I'm too lazy to do a pull request :-)

So, in import_model.hpp create_upsampling_2d_layer should be something like:

inline layer_ptr create_upsampling_2d_layer(
    const get_param_f&, const get_global_param_f&, const nlohmann::json& data,
    const std::string& name)
{
    const auto scale_factor = create_shape2(data["config"]["size"]);
    const std::string interpolation = name.find("sampling1d") != std::string::npos? "nearest" : data["config"]["interpolation"];
    return std::make_shared<upsampling_2d_layer>(
        name, scale_factor, interpolation);
}

**Comment by Dobiasd** [comment]
Thanks for the good bug report. I'll take care of it.

**Comment by Dobiasd** [comment]
While testing the suggested fix, I stumbled over another issue. `Upsampling1D` behaves differently depending on the rank of the tensor. So I [introduced an explicit `upsampling_1d_layer`](https://github.com/Dobiasd/frugally-deep/commit/dc7aa0a4fa9c214d5862b0449ab9f46d09d8689c), which is not also covered by tests.

Thanks again for helping to improve frugally-deep. :slightly_smiling_face:
