### ISSUE TITLE
Unable to use fdeep:load_model

### ISSUE THREAD

**Issue by Charul** [Dobiasd/frugally-deep#186]
I am trying  to Load a Module with frugallyDeep Library. I am facing an issue with the load_model. There is no such method nor read_model for the same. Can someone suggest the possible solution to read this exported model in C++.

![Unbenannt](https://user-images.githubusercontent.com/5459320/66756333-1965ff80-ee9a-11e9-903f-225ba81202d8.PNG)

**Comment by aligoglos** [comment]
You should add all dependency libraries: [FunctionalPlus](https://github.com/Dobiasd/FunctionalPlus)
[eigen](http://eigen.tuxfamily.org/index.php?title=Main_Page) and [json](https://github.com/nlohmann/json)

**Comment by sasanasadiabadi** [comment]
I converted the dummy keras model and it works fine with the c++ code. But after successfully converting my own keras model related to face landmark localization to the json model, it is throwing an error    JSON_THROW(type_error::create(302, "type must be string, but is " + std::string(j.type_name())));
The model conversion is successful, what could be wrong with the json model?

Here is the model conversion log:
  warnings.warn('No training configuration found in save file: '
Forward pass took 7.436241 s.
Forward pass took 2.818471 s.
Forward pass took 3.004973 s.
Starting performance measurements.
Forward pass took 2.823453 s.
Forward pass took 2.950119 s.
Forward pass took 2.851381 s.
Forward pass took 3.033895 s.
Forward pass took 3.480701 s.
Forward pass took 3.0279097999999998 s on average.
Converting model architecture.
Determining Keras behaviour.
Converting model weights.
Done converting model weights.
Calculating model hash.
Model conversion finished.
writing fdeep_model.json

**Comment by Dobiasd** [comment]
@sasanasadiabadi: It's hard for@Charul: Is this issue solved now for you?

---

@sasanasadiabadi: Could you please try to install TensorFlow 1.15.0, Keras 2.3.1, and then try again? If this does not help, could you upload the `.h5` file of the model you are trying to convert and use?
