### ISSUE TITLE
Incorrect input size with unclear error message?

### ISSUE THREAD

**Issue by yarden24** [Dobiasd/frugally-deep#189]
Hello,
Im trying to run a model I trained using frugally-deep, however when I try and predict I get the following error message which i dont understand:
returned	"Invalid inputs shape.
The model takes [(Just 1, Just 1, Just 512, Just 512, Just 3)] but provided was: [(1, 1, 512, 512, 3)]"

what do the just's signify? 
if its needed ill be happy to load my .json file, the c++ code is just your example one with opencv.

**Comment by Dobiasd** [comment]
Hi, and thanks for the report.

> what do the just's signify?

The `Just` stems from the `Maybe` type from [`FunctionalPlus`](https://github.com/Dobiasd/FunctionalPlus).

> if its needed ill be happy to load my .json file

Yes, please. I can then try to reproduce the problem locally and debug.

**Comment by yarden24** [comment]
https://gofile.io/?c=yfad5E
that should work

**Comment by Dobiasd** [comment]
Using your model, this [`test_image_512x512x3.png`](https://i.imgur.com/Eur2jCL.png) and the latest version of frugally-deep (`v0.9.8-p0`), the following code runs without error on my machine:

```cpp
#include <fdeep/fdeep.hpp>
#include <opencv2/opencv.hpp>
int main()
{
    const cv::Mat image = cv::imread("test_image_512x512x3.png");
    cv::cvtColor(image, image, cv::COLOR_BGR2RGB);
    assert(image.isContinuous());
    const auto model = fdeep::load_model("fdeep_model_atrous.json");
    const auto input = fdeep::tensor5_from_bytes(image.ptr(),
        static_cast<std::size_t>(image.rows),
        static_cast<std::size_t>(image.cols),
        static_cast<std::size_t>(image.channels()),
        0.0f, 1.0f);
    const auto result = model.predict({input});
    std::cout << fdeep::show_tensor5s(result) << std::endl;
}
```

Could you please verify you are using the latest version too?

**Comment by yarden24** [comment]
ah, it seems the problem was that I was using predict_class instead of predict, sorry for the hassle.

Thank you for the help and for frugally-deep in general, it looks like it will be very helpful.

**Comment by Dobiasd** [comment]
Glad it helped. :slightly_smiling_face:

However, I'm still confused a bit. Using `model.predict_class` instead of `model.predict` should result in an error like `invalid output shape`, not in something like `The model takes ... but provided was ...`.
