### ISSUE TITLE
broken backward compatibility from v0.8.6-p0 to v0.9.0-p0 ?

### ISSUE THREAD

**Issue by S-Huebner** [Dobiasd/frugally-deep#190]
Hello Tobias,

I have trained a convolutional neural network with keras and ported it to c++ with your library. fdeep was able to load the network into my program and all worked fine. But that was somewhen in May 2019. When I use the same h5 or json file with the newest version of frugally-deep, the function `fdeep::load_model` throws an exception and I get the output: 
"Loading json ... done. elapsed time: 0.258549 s
FDeep RUNTIME ERROR:shape5_variable needs to be an array".

I figured out, that all works fine till v0.8.6-p0. The error emerges with v0.9.0-p0

Can you already tell what's the problem here, or do you need more information (SSCCE)?  Is it a bug or is it me doing something wrong?

**Comment by Dobiasd** [comment]
Hi,

thanks for the clear report.

An SSCCE would be fine. It probably suffices if you just upload the `.h5` file. I can then convert it to `.json` and test loading in C++ on my own.

**Comment by S-Huebner** [comment]
Hey Tobias, 

Sorry for the delay, but here is the
 h5-file and the cpp-file which together produce the error. 
[sscce.zip](https://github.com/Dobiasd/frugally-deep/files/3803547/sscce.zip)

**Comment by Dobiasd** [comment]
Hi,

using your model, I can not reproduce the problem:

```cpp
// main.cpp
#include <fdeep/fdeep.hpp>
int main()
{
    auto model = fdeep::load_model("full_model_no_Optimiser.json");
}
```

```bash
python3 keras_export/convert_model.py full_model_no_Optimiser.h5 full_model_no_Optimiser.json
g++ -std=c++14 -O3 ./main.cpp -o fdeep_issue_190
./fdeep_issue_190
```

```
Loading json ... done. elapsed time: 0.097204 s
Running test 1 of 1 ... done. elapsed time: 0.003009 s
Loading, constructing, testing of full_model_no_Optimiser.json took 0.149541 s overall.
```

Can you please make sure you are using a recent keras version when running `convert_model.py`? (I used `2.3.1` for the test above.)

**Comment by S-Huebner** [comment]
I used the almost newest version of keras, but my mistake was, that I used the old version of the `convert_model.py` file. Thanks a lot and sorry for wasting your time. Is there a short explanation of what needed to be changed in `convert_model.py`, such that the old json files can not be used with the new fdeep library?

**Comment by Dobiasd** [comment]
> I used the almost newest version of keras, but my mistake was, that I used the old version of the convert_model.py file. Thanks a lot and sorry for wasting your time.

No worries. :slightly_smiling_face:

> Is there a short explanation of what needed to be changed in convert_model.py, such that the old json files can not be used with the new fdeep library?

Not from the top of my head. One would need to go through the commit history between the two versions you are comparing and check what has changed.
