### ISSUE TITLE
Error during Load Model Json

### ISSUE THREAD

**Issue by furkank75** [Dobiasd/frugally-deep#192]
During the loading my model i became the following Error:

`Loading json ... done. elapsed time: 3.137870 s
Assertion failed: m_value.object->find(key) != m_value.object->end(), file c:\users\XXXX\desktop\json\include\nlohmann\json.hpp, line 3295`

I save my model with: 
`tf.keras.models.save_model( model, '../keras_model_UP.h5', include_optimizer=False)`

`model.save('keras_model.h5', include_optimizer=False)` not works in my situation. 
`TypeError: Not JSON Serializable: 32`

**Comment by Dobiasd** [comment]
Can you please upload your `h5` file, so I can try to reproduce the issue?

**Comment by furkank75** [comment]
[keras_model_UP.zip](https://github.com/Dobiasd/frugally-deep/files/3827124/keras_model_UP.zip)

**Comment by Dobiasd** [comment]
I just tried it out as follows, and it worked flawlessly:

```cpp
// main.cpp
#include <fdeep/fdeep.hpp>
int main()
{
    const auto model = fdeep::load_model("keras_model_UP.json");
}
```

```bash
python3 convert_model.py keras_model_UP.h5 keras_model_UP.json
g++ -std=c++14 -O3 ./main.cpp -o fdeep_issue_192
./fdeep_issue_192
```

```
Loading json ... done. elapsed time: 0.048501 s
Running test 1 of 1 ... done. elapsed time: 0.012162 s
Loading, constructing, testing of keras_model_UP.json took 0.087872 s overall.
```

Please make sure you are using the latest version of frugally-deep (`v0.11.0-p0`) and the latest version of TensorFlow (`2.0.0`) when trying again.

**Comment by furkank75** [comment]
Oh yes, I used it with tensorflow 1.14! Thanks a lot..
