### ISSUE TITLE
Multiple Input -> Invalid Output shape

### ISSUE THREAD

**Issue by furkank75** [Dobiasd/frugally-deep#193]
Hi, 
I read the images with opencv and would like predict with the keras model. But I became the msg: **"invalid output shape"** The output of the model is a image[32,32,1]
Why??

```
#include <iostream>
#include <stdio.h>
#include <fdeep/fdeep.hpp>
#include <opencv2/opencv.hpp>

int main()
{
	const cv::Mat image  = cv::imread("0.png",0);
	const cv::Mat image1 = cv::imread("0.png",0);

	assert(image.isContinuous());
	assert(image1.isContinuous());

	const auto model = fdeep::load_model("fdeep_model.json");

	const auto input = fdeep::tensor5_from_bytes(image.ptr(),
		static_cast<std::size_t>(image.rows),
		static_cast<std::size_t>(image.cols),
		static_cast<std::size_t>(image.channels()),
		0.0f, 1.0f);

	const auto input1 = fdeep::tensor5_from_bytes(image1.ptr(),
		static_cast<std::size_t>(image1.rows),
		static_cast<std::size_t>(image1.cols),
		static_cast<std::size_t>(image1.channels()),
		0.0f, 1.0f);

	const auto result = model.predict_class({ input, input1 });

	printf("\nLoad Done!");
	return 0;
}
```

```
Loading json ... done. elapsed time: 2.789558 s
Running test 1 of 1 ... done. elapsed time: 4.699930 s
Loading, constructing, testing of D:/Projects/1_Masterthesis/fdeep_model.json took 18.745950 s overall.
```

**Comment by Dobiasd** [comment]
Can you please upload the `h5` model file and the image used, so I can reproduce and debug locally?

**Comment by furkank75** [comment]
[keras_model.zip](https://github.com/Dobiasd/frugally-deep/files/3827352/keras_model.zip)

Input1: [32,32,1]
Input2: [32,32,1]
Output:[32,32,1]

In python the prediction works.

**Comment by Dobiasd** [comment]
The two images you uploaded (`https://user-images.githubusercontent.com/48141658/68529643-f3991280-0300-11ea-8e76-c185980227bf.png` and `https://user-images.githubusercontent.com/48141658/68529649-fbf14d80-0300-11ea-8615-57849177e503.png`) are of size `31x32` instead of `32x32.

But I resized them, and now I can reproduce the error. I'll have a look into it and get back to you.

In the meantime, a small remark: I guess in line `	const cv::Mat image1 = cv::imread("0.png",0);` you intend to load something like `1.png` and not `0.png` again.

**Comment by furkank75** [comment]
Yes youre right. The script was an minimal example of the code. 

Thanks a lot. I hope, it will be works.

**Comment by Dobiasd** [comment]
Your model does not predict a class. Its output is a tensor of shape `(32, 32, 1)`.

The [documenting comment of `fdeep::model::predict_class`](https://github.com/Dobiasd/frugally-deep/blob/fd34718d01183d40655b2c806b47408b1a718364/include/fdeep/model.hpp#L62-L66) explains what output shapes are valid for using it.

In short: You need to use `fdeep::model::predict` instead.

The following works:

```cpp
// main.cpp
#include <iostream>
#include <stdio.h>
#include <fdeep/fdeep.hpp>
#include <opencv2/opencv.hpp>

int main()
{
    const cv::Mat image0 = cv::imread("0_32.png", 0);
    const cv::Mat image1 = cv::imread("1_32.png", 0);

    assert(image0.isContinuous());
    assert(image1.isContinuous());

    const auto model = fdeep::load_model("keras_model_UP.json");

    const auto input = fdeep::tensor5_from_bytes(image0.ptr(),
        static_cast<std::size_t>(image0.rows),
        static_cast<std::size_t>(image0.cols),
        static_cast<std::size_t>(image0.channels()),
        0.0f, 1.0f);

    const auto input1 = fdeep::tensor5_from_bytes(image1.ptr(),
        static_cast<std::size_t>(image1.rows),
        static_cast<std::size_t>(image1.cols),
        static_cast<std::size_t>(image1.channels()),
        0.0f, 1.0f);

    const auto result = model.predict({ input, input1 });

    std::cout << fdeep::show_tensor5s(result) << std::endl;
}
```

```bash
python3 convert_model.py keras_model_UP.h5 keras_model_UP.json

g++ -std=c++14 -O3 ./main.cpp `pkg-config --libs opencv` -o fdeep_issue_193
./fdeep_issue_193
```

Here are the two images I used:
- `0_32.png`: https://i.imgur.com/LnSSP8z.png
- `1_32.png`: https://i.imgur.com/1n1hd3q.png

---

To solve your next problem before you open the third issue today (:stuck_out_tongue:):

From your output `Loading, constructing, testing of D:/Projects/1_Masterthesis/fdeep_model.json took 18.745950 s overall.` it seems you are compiling without performance optimizations. In case you need more speed, please look at the following entry in the FAQ: https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#why-is-my-prediction-roughly-100-times-slower-in-c-as-in-python
