### ISSUE TITLE
model.predict() returning zeros 

### ISSUE THREAD

**Issue by bforland** [Dobiasd/frugally-deep#195]
Hello,

I have a classifier model that is comprised on a convolutional branch and a fully connected branch. I have tested the convolutional branch on it's own and it works. However after adding the fully connected branch, the model predicts identically zero for all the predictions. I'm not sure exactly what information will be helpful, but it would be difficult to provide everything. This is essentially what I'm trying to do.  

```
float getResponse(std::vector<float> &image, std::vector<float> &features)
{
  fdeep::shape5 tensor5_shape(1, 1, 25, 25, 1);
  fdeep::tensor5 cnn_features(tensor5_shape, 0.0f);
  
  int k = 0;
  for (int y = 0; y < tensor5_rows; ++y)
  {
    for (int x = 0; x < tensor5_cols; ++x)
    {

      cnn_features.set(0, 0, y, x, 0, IMAGE_PIX[k]);
      
      k++;
    }
  }
  const fdeep::shared_float_vec sv(fplus::make_shared_ref<fdeep::float_vec>(features));
  fdeep::tensor5 dnn_features(fdeep::shape5(1, 1, 1, 1, n_features), sv);
  std::cout<<fdeep::show_tensor5(dnn_features)<<std::endl;
  const auto result = CnnDnnModel.predict({cnn_features, dnn_features});
  std::cout << fdeep::show_tensor5s(result) << std::endl;
  score = result.at(0).get(0,0,0,0,0);
  return score;
}
```
Again, the "cnn_feature" part works, and I've checked that the values going into predict are non-zero. The `cout` statements look like this:
```
[[[[[[-0.6759, -0.6342,  0.2104,  8.0281, -1.4896]]]]]]
[[[[[[[0.0000]]]]]]]
```
I think this is an issue maybe with the TYPE of the valyes in dnn_features, but I'm not sure. I have tried putting values in explicitly i.e.
```
fdeep::tensor5 dnn_features(fdeep::shape5(1, 1, 1, 1, n_features), {.5, .5, .5, .5, .5});
```
and the predictions "works" in the sense that the values are non-zero. Any advice would be greatly appreciated and I"m happy to elaborate in any way necessary.

**Comment by Dobiasd** [comment]
Hi bforland,

thanks for the report.

Could you provide a minimal example, so I can reproduce the issue locally? This might help me find out what is going on.

Ideally, the minimal example would consist of the following:
- One `.py` file, that loads the `h5` model(s), does the predictions and shows the output.
- One `.cpp` file, that does the same and shows that the output is not the same as in Python.
- The needed `.h5` file(s).
- And, if also needed, some image files or whatever.

The more you can leave off from this example, the better. Oftentimes, reducing a problem to its bare essence is the most important part of finding localizing the cause. :slightly_smiling_face:

**Comment by Dobiasd** [comment]
I'll close this issue due to inactivity. If it's still of interest, please let me know.

**Comment by bforland** [comment]
Lol, I read through this before I realized it was my post. I just wanted to resolve this issue by saying that it wasn't a Fdeep problem. There was an issue with the scaling that resulted in the zeros. This can remain closed. Thanks for the reply in any case.
