### ISSUE TITLE
classify input image which contain a single object

### ISSUE THREAD

**Issue by gabir-yusuf** [Dobiasd/frugally-deep#196]
how to set the model.predict() function parameters to classify input image which contain a single object. I misunderstand what is the tenosor5 is.

also is there any documentation for this library?

thanks for advance.

**Comment by Dobiasd** [comment]
Hi,

> how to set the model.predict() function parameters to classify input image which contain a single object.

Here are two examples:

- https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#how-to-use-images-loaded-with-cimg-as-input-for-a-model
- https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#how-to-use-images-loaded-with-opencv-as-input-for-a-model

> also is there any documentation for this library?

Yes, in the `README` and in the `FAQ`:

- https://github.com/Dobiasd/frugally-deep/blob/master/README.md
- https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md
