### ISSUE TITLE
predict() reuses the output memory from the previous calls

### ISSUE THREAD

**Issue by mvparakhin** [Dobiasd/frugally-deep#198]
Sorry, I didn't find it documented anywhere and, having spent about an hour debugging, couldn't figure it out myself. I'm seeing the subsequent calls to predict() overriding the memory containing the results of the previous calls. In other words, the smartpointer that's inside the resulting shared_float_vec is still stored between calls somewhere inside the model - I see the ref counter being incremented. 
Maybe that is an expected behavior (though I couldn't figure out where it is stored, as the reuse maps are all local variables), but it is conflicting with the statement that predict() is multithread-safe. Unless it is using TLS, of course.

**Comment by mvparakhin** [comment]
Oh, found it, in convolution layer it is using TLS and reusing it:

static boost::thread_specific_ptr<shared_float_vec>	tls_res;
shared_float_vec* p_res = tls_res.get();

This is really counter-intuitive. Should be at least be documented. Looks like is is only a problem when convolution layers are used.

**Comment by mvparakhin** [comment]
Oh, sorry, not your fault, it's local modification that's not in the upstream. Please ignore,

**Comment by Dobiasd** [comment]
> Oh, sorry, not your fault, it's a local modification that's not in the upstream. Please ignore,

Thanks. Such behavior in an official release would be terrible. :grin:
