### ISSUE TITLE
Input Image Array

### ISSUE THREAD

**Issue by kkrelax069** [Dobiasd/frugally-deep#199]
Hello, 
I have a batch of images: 8 Images in batch -> CNN Inputs are 2
So, how can I do this in cpp with fdeep? 
I read my Images with OpenCV.. 

```
cv::Mat Images1[4];
	Images1[0] = cv::imread("1.png", 0);
	Images1[1] = cv::imread("2.png", 0);
	Images1[2] = cv::imread("3.png", 0);
	Images1[3] = cv::imread("4.png", 0);

	cv::Mat Images2[4];
	Images2[0] = cv::imread("1.png", 0);
	Images2[1] = cv::imread("2.png", 0);
	Images2[2] = cv::imread("3.png", 0);
	Images2[3] = cv::imread("4.png", 0);
```

But how can I convert this to **const auto input = fdeep::tensor5_from_bytes(....)**??

**Comment by Dobiasd** [comment]
Hi,

frugally-deep does not support batch processing. Just do the 4 predictions [one by one](https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#how-to-use-images-loaded-with-opencv-as-input-for-a-model). [Here](https://github.com/Dobiasd/frugally-deep/issues/197#issuecomment-565824407) you can find an example of using two input images.
