### ISSUE TITLE
Bus error

### ISSUE THREAD

**Issue by garymmi** [Dobiasd/frugally-deep#204]
Hi all
i bulit a simple example , successfully run on linux , but failed on android
when call load_model api,
the error message is 
   Loading json ... done. elapsed time: 0.007347 s
   Building model ... done. elapsed time: 0.005359 s
   Running test 1 of 1 ... Bus error
what happened?
Thanks

**Comment by Dobiasd** [comment]
Hi garymmi,

I've never seen this error. Also, it does not originate from the code of frugally-deep itself.

A google search for `"bus error" android` points to it being a `SIGBUS` error. Since the model, you are using, probably already is quite small, the RAM of your device should not have a problem with it. Maybe some settings with the eigen lib and alignment that causes the problem?

Could you try compiling and running some minimal eigen example, like the following one?

```cpp
#include <iostream>
#include <Eigen/Dense>
using namespace Eigen;
int main()
{
  Matrix2d mat;
  mat << 1, 2,
         3, 4;
  Vector2d u(-1,1), v(2,0);
  std::cout << "Here is mat*mat:\n" << mat*mat << std::endl;
  std::cout << "Here is mat*u:\n" << mat*u << std::endl;
  std::cout << "Here is u^T*mat:\n" << u.transpose()*mat << std::endl;
  std::cout << "Here is u^T*v:\n" << u.transpose()*v << std::endl;
  std::cout << "Here is u*v^T:\n" << u*v.transpose() << std::endl;
  std::cout << "Let's multiply mat by itself" << std::endl;
  mat = mat*mat;
  std::cout << "Now mat is mat:\n" << mat << std::endl;
}
```

source: https://eigen.tuxfamily.org/dox/group__TutorialMatrixArithmetic.html#TutorialArithmeticMatrixMul

**Comment by garymmi** [comment]
thank for your reply.
the reuslt on android

root@GT-I9100:/data/local/tmp # ./teste
WARNING: linker: ./teste: unused DT entry: type 0x6ffffffe arg 0x1234
WARNING: linker: ./teste: unused DT entry: type 0x6fffffff arg 0x2
Here is mat*mat:
 7 10
15 22
Here is mat*u:
1
1
Here is u^T*mat:
2 2
Here is u^T*v:
-2
Here is u*v^T:
-2 -0
 2  0
Let's multiply mat by itself
Now mat is mat:
 7 10
15 22

**Comment by Dobiasd** [comment]
OK, so this simple eigen example works, that's good.

Can you provide a stack trace for then the `SIGBUS` happens?

> frugally-deep can run on 32-bit platform ?
Yes, it can.

**Comment by garymmi** [comment]
if built debug mode, run ok
logcat show

root@GT-I9100:/data/local/tmp # logcat
--------- beginning of main
D/HeadsetStateMachine( 3129): Disconnected process message: 10, size: 0
W/linker  (17712): ./test1: unused DT entry: type 0x6ffffffe arg 0x1338
W/linker  (17712): ./test1: unused DT entry: type 0x6fffffff arg 0x3
--------- beginning of crash
F/libc    (17712): Fatal signal 7 (SIGBUS), code 128, fault addr 0x0 in tid 17712 (test1)
I/DEBUG   ( 1854): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   ( 1854): Build fingerprint: 'samsung/GT-I9100/GT-I9100:4.1.2/JZO54K/I9100XWMS2:user/release-keys'
I/DEBUG   ( 1854): Revision: '14'
I/DEBUG   ( 1854): ABI: 'arm'
I/DEBUG   ( 1854): pid: 17712, tid: 17712, name: test1  >>> ./test1 <<<
I/DEBUG   ( 1854): signal 7 (SIGBUS), code 128 (SI_KERNEL), fault addr 0x0
--------- beginning of system
W/NativeCrashListener( 2208): Couldn't find ProcessRecord for pid 17712
W/debuggerd( 1854): type=1400 audit(0.0:2016): avc: denied { search } for name="tmp" dev=mmcblk0p10 ino=73730 scontext=u:r:debuggerd:s0 tcontext=u:object_r:shell_data_file:s0 tclass=dir
W/debuggerd( 1854): type=1400 audit(0.0:2017): avc: denied { search } for name="tmp" dev=mmcblk0p10 ino=73730 scontext=u:r:debuggerd:s0 tcontext=u:object_r:shell_data_file:s0 tclass=dir
W/debuggerd( 1854): type=1400 audit(0.0:2018): avc: denied { search } for name="tmp" dev=mmcblk0p10 ino=73730 scontext=u:r:debuggerd:s0 tcontext=u:object_r:shell_data_file:s0 tclass=dir
W/debuggerd( 1854): type=1400 audit(0.0:2019): avc: denied { search } for name="tmp" dev=mmcblk0p10 ino=73730 scontext=u:r:debuggerd:s0 tcontext=u:object_r:shell_data_file:s0 tclass=dir
W/debuggerd( 1854): type=1400 audit(0.0:2020): avc: denied { search } for name="tmp" dev=mmcblk0p10 ino=73730 scontext=u:r:debuggerd:s0 tcontext=u:object_r:shell_data_file:s0 tclass=dir
W/debuggerd( 1854): type=1400 audit(0.0:2021): avc: denied { search } for name="tmp" dev=mmcblk0p10 ino=73730 scontext=u:r:debuggerd:s0 tcontext=u:object_r:shell_data_file:s0 tclass=dir
I/DEBUG   ( 1854):     r0 00000000  r1 40c42180  r2 00000001  r3 40c42178
E/DEBUG   ( 1854): AM write failure (32 / Broken pipe)
I/DEBUG   ( 1854):     r4 beb6d275  r5 beb6d5cc  r6 40c810fc  r7 beb6d258
I/DEBUG   ( 1854):     r8 beb6d275  r9 beb6d5cc  sl beb6d328  fp 00000000
I/DEBUG   ( 1854):     ip 00000031  sp beb6d240  lr 400fc26b  pc 400fb648  cpsr 700f0030
I/DEBUG   ( 1854):
I/DEBUG   ( 1854): backtrace:
I/DEBUG   ( 1854):     #00 pc 0001f648  /data/local/tmp/test1
I/DEBUG   ( 1854):     #01 pc 00020267  /data/local/tmp/test1
W/debuggerd( 1854): type=1400 audit(0.0:2022): avc: denied { search } for name="tmp" dev=mmcblk0p10 ino=73730 scontext=u:r:debuggerd:s0 tcontext=u:object_r:shell_data_file:s0 tclass=dir
W/debuggerd( 1854): type=1400 audit(0.0:2023): avc: denied { search } for name="tmp" dev=mmcblk0p10 ino=73730 scontext=u:r:debuggerd:s0 tcontext=u:object_r:shell_data_file:s0 tclass=dir
W/debuggerd( 1854): type=1400 audit(0.0:2024): avc: denied { search } for name="tmp" dev=mmcblk0p10 ino=73730 scontext=u:r:debuggerd:s0 tcontext=u:object_r:shell_data_file:s0 tclass=dir
I/DEBUG   ( 1854):
I/DEBUG   ( 1854): Tombstone written to: /data/tombstones/tombstone_09
I/BootReceiver( 2208): Copying /data/tombstones/tombstone_09 to DropBox (SYSTEM_TOMBSTONE)

**Comment by Dobiasd** [comment]
> if built debug mode, run ok

That's interesting.

Regarding the stack trace:

It seems to come from here: https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/services/core/java/com/android/server/am/NativeCrashListener.java#272

But I don't know what this means or how to fix it. Can you make this problem reproducible with docker?

**Comment by garymmi** [comment]
i printf the error message, finally trace the crashed code [fplus::get_from_map_unsafe at layer.hpp](https://github.com/Dobiasd/frugally-deep/blob/master/include/fdeep/layers/layer.hpp#L75)

but i have no ability to fix it
maybe i should use docker and install android emulator to reproduce this issue

**Comment by Dobiasd** [comment]
Perhaps some pre-build docker image like this could make it a bit simpler: https://github.com/budtmo/docker-android

But before you invest too much effort, let's make sure it's not something trivial. Can you upload the `.json` file you are using (and the source `.h5` file)?

**Comment by garymmi** [comment]
here are  the model.json and model.h5 files
[models.zip](https://github.com/Dobiasd/frugally-deep/files/4088660/models.zip)

**Comment by Dobiasd** [comment]
OK, the model works fine on my desktop machine, also without debug mode.

```cpp
// fdeep_issue_204.cpp
#include <fdeep/fdeep.hpp>
int main()
{
    const auto model = fdeep::load_model("model.json");
}
```cpp

```bash
g++ -std=c++14 -O3 fdeep_issue_204.cpp -o fdeep_issue_204
./fdeep_issue_204
```

```
Loading json ... done. elapsed time: 0.000391 s
Building model ... done. elapsed time: 0.000288 s
Running test 1 of 1 ... done. elapsed time: 0.000122 s
Loading, constructing, testing of model.json took 0.001158 s overall.
```

So it's probably really an Android/ARM thing.

---

Could you please check, if you can reproduce the error on your Android with the following minimal example?

```cpp
// fdeep_issue_204_minimal.cpp
#include <fdeep/fdeep.hpp>

using namespace fdeep;
using namespace fdeep::internal;

using output_dict = std::map<std::pair<std::string, std::size_t>, tensor5s>;

tensor5 get_output(output_dict& output_cache,
        std::size_t node_idx, std::size_t tensor_idx)
{
    output_cache[std::make_pair("foo", 0)] = {
        fdeep::tensor5(fdeep::shape5(1, 1, 3, 4, 3), 42),
        fdeep::tensor5(fdeep::shape5(1, 1, 3, 4, 3), 43)
        };

    const auto& outputs = fplus::get_from_map_unsafe(
        output_cache, std::make_pair("foo", 0));

    return outputs[tensor_idx];
}

int main()
{
    output_dict output_cache;
    const auto y = get_output(output_cache, 0, 0);
    std::cout << show_tensor5(y) << std::endl;
}
```

**Comment by garymmi** [comment]
on linux , output
[[[[[[42.0000, 42.0000, 42.0000], [42.0000, 42.0000, 42.0000], [42.0000, 42.0000, 42.0000], [42.0000, 42.0000, 42.0000]], [[42.0000, 42.0000, 42.0000], [42.0000, 42.0000, 42.0000], [42.0000, 42.0000, 42.0000], [42.0000, 42.0000, 42.0000]], [[42.0000, 42.0000, 42.0000], [42.0000, 42.0000, 42.0000], [42.0000, 42.0000, 42.0000], [42.0000, 42.0000, 42.0000]]]]]]

on android, output
Bus error

**Comment by garymmi** [comment]
i think the problem is alignment 
in FunctionalPlus/include/fplus/maybe.hpp
`    T& unsafe_get_just()
    {
        assert(is_just());
        return *reinterpret_cast<T*>(&mem_[0]);
    }
`
cannot write 「*reinterpret_cast<T*>(&mem_[0]);」workable for x86 cpu, not for arm cpu

reference : https://blog.quarkslab.com/unaligned-accesses-in-cc-what-why-and-solutions-to-do-it-properly.html

**Comment by Dobiasd** [comment]
Very good investigation. Thanks a lot!

The `reinterpret_cast` thing was introduced with [this commit](https://github.com/Dobiasd/FunctionalPlus/commit/c05393d5f21f4d9bf91a972758083ee51eeeaac0#diff-de068c145e6ad62a8aff04d28e957a11). It's a performance optimization because it avoids heap allocation.

Going back to the old version would solve the SIGBUS, but also make things slower. I think I remember having made this change because it solved an actual bottleneck (found by profiling) in an application.

To further narrow down the issue, could you please try running the following?

```cpp
#include <array>
#include <iostream>
#include <vector>
int main()
{
    using float_vector = std::vector<float>;
    float_vector xs = {1, 2, 3};
    std::array<unsigned char, sizeof(float_vector)> mem;
    new (&mem[0]) float_vector(xs);
    float_vector& ys = *reinterpret_cast<float_vector*>(&mem[0]);
    std::cout << ys[0] << std::endl;
}
```

I hope we also get a Bus error with that one.

**Comment by garymmi** [comment]
strange, it can work, output 1

**Comment by Dobiasd** [comment]
OK, I guess this minimal example would (hopefully) create the SIGBUS:

```cpp
// fdeep_issue_204_minimal_3.cpp
#include <array>
#include <cassert>
#include <iostream>
#include <memory>
#include <type_traits>
#include <vector>

template <typename T>
class shared_ref
{
public:
    shared_ref(const shared_ref&) = default;
    shared_ref(shared_ref&&) = default;
    shared_ref& operator=(const shared_ref&) = default;
    shared_ref& operator=(shared_ref&&) = default;
    ~shared_ref() = default;

    T* operator->() { return m_ptr.get(); }
    const T* operator->() const { return m_ptr.get(); }

    T& operator*() { return *m_ptr.get(); }
    const T& operator*() const { return *m_ptr.get(); }

    template <typename XT, typename...XTypes>
    friend shared_ref<XT> make_shared_ref(XTypes&&...args);

private:
    std::shared_ptr<T> m_ptr;
    shared_ref(T* value) :m_ptr(value) { assert(value != nullptr);  }
};

template <typename T, typename...Types>
shared_ref<T> make_shared_ref(Types&&...args)
{
    return shared_ref<T>(new T(std::forward<Types>(args)...));
}

class shape5
{
public:
    explicit shape5(
        std::size_t size_dim_5,
        std::size_t size_dim_4,
        std::size_t height,
        std::size_t width,
        std::size_t depth) :
            size_dim_5_(size_dim_5),
            size_dim_4_(size_dim_4),
            height_(height),
            width_(width),
            depth_(depth)
    {
    }

    std::size_t volume() const
    {
        return size_dim_5_ * size_dim_4_ * height_ * width_ * depth_;
    }

    std::size_t size_dim_5_;
    std::size_t size_dim_4_;
    std::size_t height_;
    std::size_t width_;
    std::size_t depth_;
};

typedef std::vector<float> float_vec;
typedef shared_ref<float_vec> shared_float_vec;

struct tensor5
{
public:
    tensor5(const shape5& shape, float value) :
        shape_(shape),
        values_(make_shared_ref<float_vec>(shape.volume(), value))
    {
    }
    shape5 shape_;
    shared_float_vec values_;
};

typedef std::vector<tensor5> tensor5s;

int main()
{
    tensor5s xs = {tensor5(shape5(1, 2, 3, 4, 5), {42})};
    std::array<unsigned char, sizeof(tensor5s)> mem;
    new (&mem[0]) tensor5s(xs);
    tensor5s& ys = *reinterpret_cast<tensor5s*>(&mem[0]);
    std::cout << (*(ys[0].values_))[0] << std::endl;
}
```

But I'll try to set up something with Docker or some emulator on my machine to reproduce. It does not make much sense you need to run snippet after snippet for me. ;)

---

In general, I guess the issue could maybe be solved by using [placement `new` with alignment](https://en.cppreference.com/w/cpp/memory/new/operator_new). But it's only available since C++17. Currently, FunctionalPlus only needs C++14, and I'd like to avoid introducing this more strict requirement. So I'll try to find a better solution and get back to you.

**Comment by garymmi** [comment]
i run fdeep_issue_204_minimal_3 on android phone, output 42 without bus error

**Comment by Dobiasd** [comment]
I installed Genymotion, but then realized, it's probably not the right tool for the job, because:

> Genymotion uses the x86 architecture

source: https://www.genymotion.com/help/desktop/faq/#error-arm-application

Since we want to debug a SIGBUG, the architecture probably should match.

@garymmi: You're using an actual (physical) Android phone, not an emulated one, right?

**Comment by garymmi** [comment]
yes, i use physical android phone, and rooted
so i can run command on it.

**Comment by Dobiasd** [comment]
I just [pushed a commit to FunctionalPlus](https://github.com/Dobiasd/FunctionalPlus/commit/9f529c982f22e474c4922cff277e72decd025b47) that should fix the issue. :slightly_smiling_face:

Could you please try to use the latest version of FunctionalPlus from the `master` branch and let me know if the bus error is gone then?

**Comment by Dobiasd** [comment]
Sorry, please wait. I introduced a new bug with this. I'll need a bit more time and get back to you then.

**Comment by Dobiasd** [comment]
@garymmi OK, I think now it should be fine. (Today I learned something about unions. :slightly_smiling_face:)

Please let me know if using the latest version of FunctionalPlus (pull `master`) solves your issue.

**Comment by garymmi** [comment]
@Dobiasd , now run ok without bus error.
Thank you very much

**Comment by Dobiasd** [comment]
Thank you too! You found a very deep bug and reported it nicely. This is a very valuable contribution. It not only helped me learn and improve the library but also this change will make life easier for other users in the future. :+1:
