### ISSUE TITLE
Custom or linked model file formats.

### ISSUE THREAD

**Issue by stevenewbold** [Dobiasd/frugally-deep#205]
First of all, thank you for this library.  It has massively helped speed up the development of my project and allowed me to concentrate on the ML aspects.

I have spent a while developing CNN networks for a specific task.  Thanks to frugally-deep I am able to utilise these within a host application as a c++ plugin and run everthing multi-threaded.  All is good.  However, having to have externally, and obviously human-readable, JSON files as the method of storing the structure of the network is slightly problematic.  A lot of time has gone into creating some quite novel implementations.  As these are propriety (not academic or research based) it would be good to not have the model so easy to analyse and replicate.

At present I have a plugin that requires numerous different models for slightly different tasks.  These can be imported as JSON files.  I'm interested in your thoughts about how to best keep the models themselves as some kind of external file, as not to bloat the plugin, but not saved as JSON files.  My initial thoughts are to adapt fdeep to be able to obfuscate the model as BSON to make them just a little less easy to read, encrypting the JSON files (seems overkill) or some method of storing the fdeep models as a dynamically linked object.

How would you best go about having external yet less human-readable models?

**Comment by Dobiasd** [comment]
Thanks for the nice words. I'm always happy to hear that fdeep is useful. :)

I understand your concern about hiding the model architecture, etc., so some kind of encoding seems appropriate.

But instead of adapting fdeep to be able to read/obfuscate, I'd try to go with external "crypto", and then, in C++, instead of using:

```cpp
fdeep::model fdeep::load_model(const std::string& file_path, ...
```

use:

```cpp
fdeep::model fdeep::read_model_from_string(const std::string& content, ...
```

or:

```cpp
fdeep::model fdeep::read_model(std::istream& model_file_stream, ...
```

---

Example:

```bash
python3 keras_export/convert_model.py keras_model.h5 fdeep_model.json
```

```bash
your_custom_encrypter fdeep_model.json fdeep_model.whatever
```

```cpp
std::string your_custom_decrypter(const std::vector<std::uint8_t>& encrypted_data) {
    // whatever is needed to convert back to the content of the original JSON file 
}

#include <fdeep/fdeep.hpp>
int main()
{
    const auto encrypted_data = fplus::read_binary_file_maybe("fdeep_model.whatever").unsafe_get_just();
    const auto decrypted_data = your_custom_decrypter(encrypted_data);
    const auto model = fdeep::read_model_from_string(decrypted_data);
}

`your_custom_encrypter` might be a python script converting JSON to BSON, the `your_custom_decrypter` would then do the inverse. Or you could use base64, or zip/unzip or rar/unrar, optionally with some password. Or Caesar cipher on the bytes, or something very secure. Sky is the limit here, I guess. :grin:

**Comment by stevenewbold** [comment]
That's perfect.  Thank you.

I'll try a few things to see what works.  As this is for a plugin that could be instanced many times, speed is of the essence and I want to avoid slow decryption at run-time.  Part of the challenge so far has been to create networks that are lean but accurate.  I'm sure there are encryption methods that will be fast enough.

Thanks again.

**Comment by Dobiasd** [comment]
Yeah, my guess is that the encryption/decryption won't turn out to be the bottleneck of the application anyways, even if you choose something cryptographically secure. :+1:
