### ISSUE TITLE
allow creating empty model

### ISSUE THREAD

**Issue by LevLavy** [Dobiasd/frugally-deep#21]
In my use case I want to allow hot swap of models where initially I start with an empty model. Since there is not empty constructor it seems not to be possible. I suggest to add such empty constructor and if predict is called throw assert if nothing is loaded. This will allow dynamic use with the same reference. Thanks!

**Comment by Dobiasd** [comment]
How about a `std::unique_ptr<fdeep::model>` / `std::shared_ptr<fdeep::model>`? :)

**Comment by LevLavy** [comment]
Yep, lets close this issue.

**Comment by stevenewbold** [comment]
Hi,
Is it possible to have a quick example of how I should be using `std::unique_ptr` to create a `fdeep::model`?  I'm really not sure of the syntax.

If I create an empty pointer like this,
`std::unique_ptr<fdeep::model> model;`

How do I then later 'assign' this pointer to a model created with `fdeep::load_model()` in a different class method elsewhere?

**Comment by Dobiasd** [comment]
Basically, your question is not about how to use frugally-deep, but about how to assign an instance to an [`std::unique_ptr`](https://en.cppreference.com/w/cpp/memory/unique_ptr) in C++.

Here is a minimal example:

```cpp
#include <memory>

struct foo {};

foo create_foo() {
    return foo();
}

int main()
{
    std::unique_ptr<foo> foo_ptr;
    foo_ptr = std::make_unique<foo>(create_foo());
}
```

Transferring this to `fdeep::model`, it looks as follows:

```cpp
#include "fdeep/fdeep.hpp"

int main()
{
    std::unique_ptr<fdeep::model> model_ptr;
    model_ptr = std::make_unique<fdeep::model>(fdeep::load_model("model.json"));
}
```

For more information please refer to the [documention of `std::unique_ptr<T,Deleter>::operator=`](https://en.cppreference.com/w/cpp/memory/unique_ptr/operator%3D).

**Comment by stevenewbold** [comment]
> Basically, your question is not about how to use frugally-deep, but about how to assign an instance to an std::unique_ptr in C++.

Yeah, sorry.  Turns out I was doing it correctly (and would have realised this had I not been suppressing the test on loading the model.)  I'm still having issues with a lot of crashes during prediction, but as you say this is almost certainly something not to do with fdeep.  I'm using it within an API that is really restricting, especially when multi-threading.
