### ISSUE TITLE
How to make tensor_shape for image

### ISSUE THREAD

**Issue by cnd** [Dobiasd/frugally-deep#210]
my model takes `[3(Just 1, Just 1, Just 96, Just 96, Just 3)]`

is it possible to convert image to it using `fdeep::tensor_shape` ?

**Comment by Dobiasd** [comment]
For future reference, the [FAQ](https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md) has examples of how to convert between `fdeep::tensor` and OpenCV images.

**Comment by cnd** [comment]
Yes thank you, it works.
