### ISSUE TITLE
throwing an instance of 'nlohmann::detail::type_error'

### ISSUE THREAD

**Issue by ashishmagar600** [Dobiasd/frugally-deep#211]
I am trying to load and run a model that is generated from TensorFlow and exported in JSON format.

Getting this error:
`Loading json ... done. elapsed time: 0.000216 s
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be string, but is null
Aborted (core dumped)
`

Also when I try to convert into json from fdeep's convert_model.json, it throws error:
`loading model.h5
Traceback (most recent call last):
  File "convert_model.py", line 818, in <module>
    main()
  File "convert_model.py", line 814, in main
    convert(in_path, out_path, no_tests)
  File "convert_model.py", line 786, in convert
    model = load_model(in_path)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 212, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/serialization.py", line 89, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 192, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/network.py", line 1121, in from_config
    process_layer(layer_data)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/network.py", line 1105, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/serialization.py", line 89, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 194, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 446, in from_config
    return cls(**config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/input_layer.py", line 80, in __init__
    raise ValueError('Unrecognized keyword arguments:', kwargs.keys())
ValueError: ('Unrecognized keyword arguments:', dict_keys(['ragged']))
`

The model is attached. Thank you.
[zipped_error.tar.gz](https://github.com/Dobiasd/frugally-deep/files/4244669/zipped_error.tar.gz)

**Comment by ashishmagar600** [comment]
Any more information is needed?

**Comment by Dobiasd** [comment]
I'm afk till Tuesday. I'll look into it when back.

**Comment by ashishmagar600** [comment]
Sure. Thanks

**Comment by Dobiasd** [comment]
OK, with the following I was able to re-create the error locally using the `model.json` you provided:

```cpp
// fdeep_issue_211.cpp
#include <fdeep/fdeep.hpp>
int main()
{
    const auto model = fdeep::load_model("model.json");
}
```

```bash
g++ -std=c++14 -O3 fdeep_issue_211.cpp -o fdeep_issue_211
./fdeep_issue_211
```

```
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be string, but is null
```

---

As a next step, I wanted to try re-converting from `.h5` to `.json`.

However

```bash
python3 convert_model.py model.h5 model.json
```

results in:

```
ValueError: Unknown loss function:custom_loss
```

Could you please save your `h5` file without optimizer, i.e., using `my_model.save('model.h5', include_optimizer=False)` and re-upload the resulting `h5` file.

**Comment by ashishmagar600** [comment]
[model_wo_optimized.tar.gz](https://github.com/Dobiasd/frugally-deep/files/4248836/model_wo_optimized.tar.gz)

Here attached.

**Comment by Dobiasd** [comment]
When re-converting the model, it works without any problem on my machine:

```cpp
// fdeep_issue_211.cpp
#include <fdeep/fdeep.hpp>
int main()
{
    const auto model = fdeep::load_model("model_without_optimizer.json");
}
```

```bash
python3 convert_model.py model_without_optimizer.h5 model_without_optimizer.json
g++ -std=c++14 -O3 fdeep_issue_211.cpp -o fdeep_issue_211
./fdeep_issue_211
```

```
Loading json ... done. elapsed time: 0.000126 s
Building model ... done. elapsed time: 0.000255 s
Running test 1 of 1 ... done. elapsed time: 0.000026 s
Loading, constructing, testing of model.json took 0.000497 s overall.
```

Please make sure you're using everything from the latest version of frugally-deep, including the header files to include in C++, but also `keras_export/convert_model.py` to convert your model from `.h5` to `.json`.

**Comment by Dobiasd** [comment]
Ah, maybe it's also about the TensorFlow version used when converting the model.

You can quickly check yours like so:

```bash
python3 -c "import tensorflow as tf; import tensorflow.keras; print(tf.__version__); print(tensorflow.keras.__version__)"
```

For me the output is the following:

```
2.0.0
2.2.4-tf
```

**Comment by ashishmagar600** [comment]
It has:
`1.14.0
2.2.4-tf
`

**Comment by Dobiasd** [comment]
Ah, OK. Than that is the problem. Please update to TF 2.0 if you want to use the latest version of frugally-deep.

**Comment by ashishmagar600** [comment]
Thank you for your help.

One more thing, does fdeep supports a custom loss function?

**Comment by Dobiasd** [comment]
Loss functions are only relevant when training a model.

Frugally-deep is not concerned with training, it only provides doing predictions on an already-trained model.

When saving your model for frugally-deep simply leave out the optimizer / loss function, because it's not needed anyway.

So the answer to "does fdeep supports a custom loss function?" is neither "yes" or "no". :grin:

**Comment by ashishmagar600** [comment]
> So the answer to "does fdeep supports a custom loss function?" is neither "yes" or "no".

Yeah Alright :smile: 

I will try to dump the model without the custom loss function.

Thank you.
