### ISSUE TITLE
Issue when Loading Model

### ISSUE THREAD

**Issue by dgaleareading** [Dobiasd/frugally-deep#212]
Hi all,

I have a fairly simple model trained in Keras made up of a few Conv2D and MaxPool layers along with an attached Dense classifier, having one output. My problem comes about when trying to load the model in frugally-deep. The `fdeep:load_model()` routine fails with the error `The model should return [5(Just 1, Just 1, Just 1, Just 1, Just 1)] but actually returned: [1(1, 1, 1, 1, 1)]`, which I can't quite understand, since my model has one output value. I should also note that this model was successfully loaded by a previous version of frugally-deep, sometime in October.

Could someone help me with this?

Thanks.

**Comment by Dobiasd** [comment]
Hi,

in case you converted the model from `.h5` to `.json` with an old version of frugally-deep, yes, it probably does not work with the latest one.

Please try to re-convert your model with the frugally-deep version (`convert_model.py`) that you are also using in C++.

**Comment by dgaleareading** [comment]
This worked thanks/
