### ISSUE TITLE
Why can't I userugally-deep in MFC dialogs

### ISSUE THREAD

**Issue by jianjiangwell** [Dobiasd/frugally-deep#214]
When using frugally-deep in MFC dialogs, #include <fdeep / fdeep.hpp>
#include <Eigen / Dense> Included, vs2017 prompts multiple .hpp files with syntax errors

- Please try to make the problem reproducible by providing a [SSCCE](http://sscce.org/) as code.

- Feel free to also submit any other feedback, suggestions or questions you might have. :)

**Comment by Dobiasd** [comment]
> When using frugally-deep in MFC dialogs, #include <fdeep / fdeep.hpp>
#include <Eigen / Dense> Included, vs2017 prompts multiple .hpp files with syntax errors

Hi,

from your very vague description, it's really hard to guess.
Maybe C++14 is not enabled in your compiler settings?

**Comment by jianjiangwell** [comment]
Dear Tobias Hermann, good evening:
       I am very honored to read your article: https://github.com/Dobiasd/frugally-deep. After reading it, I was very inspired, and I implemented it in the console project of vs2017 and vs2019 (that is, the Vgg16 classification model called keras in C ++).However, when I try to call the same model in MFC, an error occurs. The error message is that I included a lot of syntax errors in the header files #include <fdeep / fdeep.hpp> and #include <Eigen / Dense>. As follows (I have uploaded the source code to the attachment):
      .
      I'm very confused about this. Also under vs2017 or vs2019, why can I run the frugal program normally in the console project, but this error occurs in the MFC dialog project. This problem has troubled me for a long time.
      I hope you can help me, solve my doubts, and look forward to your reply!
      I wish you good health and good work.
                                                                                                                                                                Sincerely   Jian Jiangwei



At 2020-03-15 20:37:59, "Tobias Hermann" <notifications@github.com> wrote:

When using frugally-deep in MFC dialogs, #include <fdeep / fdeep.hpp>
#include <Eigen / Dense> Included, vs2017 prompts multiple .hpp files with syntax errors

Hi,

from your very vague description, it's really hard to guess.
Maybe C++14 is not enabled in your compiler settings?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

从网易163邮箱发来的云附件
sd - 复件.zip (41.15M, 2020年3月30日 21:36 到期)
下载

**Comment by Dobiasd** [comment]
Could you post the content of the compiler errors you get?

**Comment by jianjiangwell** [comment]
Part of the errors:

1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ numeric.hpp (346,66): warning C4003: Insufficient "max" parameter of the function-like macro call
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ numeric.hpp (348,46): warning C4003: Insufficient "max" parameter of the call to a class function macro
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ numeric.hpp (369,80): warning C4003: Insufficient "max" parameter for calling function-like macro
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ numeric.hpp (370,42): warning C4003: Insufficient "max" parameter for calling function-like macro
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ numeric.hpp (568,1): error C2988: unrecognized template declaration / definition
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ numeric.hpp (568,1): error C2059: syntax error: "const"
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ numeric.hpp (568,1): error C2059: syntax error: ")"
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ numeric.hpp (568,66): error C2065: "U": undeclared identifier
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ numeric.hpp (568,69): error C2065: "V": undeclared identifier
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ numeric.hpp (568,1): error C3544: "_Ty": Parameter package requires a type template parameter
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ numeric.hpp (568,76): error C2039: "type": not a member of "std :: common_type"
1> F: \ vs2019 \ VC \ Tools \ MSVC \ 14.24.28314 \ include \ type_traits (1215): message: see "std :: common_type" declaration
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ numeric.hpp (569,1): error C2143: syntax error: missing ";" (before "{")
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ numeric.hpp (569,1): error C2447: "{": missing function title (is it an old-fashioned form table?)
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ numeric.hpp (591,1): error C2988: unrecognized template declaration / definition
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ numeric.hpp (591,1): error C2059: syntax error: "const"
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ numeric.hpp (591,1): error C2059: syntax error: ")"
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ numeric.hpp (591,66): error C2065: "U": undeclared identifier
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ numeric.hpp (591,69): error C2065: "V": undeclared identifier
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ numeric.hpp (591,1): error C3544: "_Ty": Parameter package requires a type template parameter
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ numeric.hpp (591,76): error C2039: "type": not a member of "std :: common_type"
1> F: \ vs2019 \ VC \ Tools \ MSVC \ 14.24.28314 \ include \ type_traits (1215): message: see "std :: common_type" declaration
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ numeric.hpp (592,1): error C2143: syntax error: missing ";" (before "{")
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ numeric.hpp (592,1): error C2447: "{": missing function title (is it an old-fashioned form table?)
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ transform.hpp (492,65): warning C4003: Insufficient "max" parameter of call of class function macro
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (42,63): warning C4003: Insufficient "min" parameter for calling class function macro
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (43,72): warning C4003: Insufficient "max" parameter of a function-like macro call
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (44,68): warning C4003: Insufficient "max" parameter for a call to a class function macro
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (42,63): error C2589: Illegal mark to the right of "(": "::"
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (42,1): error C2988: unrecognized template declaration / definition
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (42,1): error C2059: syntax error: ")"
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (42,63): error C2988: unrecognized template declaration / definition
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (42,63): error C2143: syntax error: missing "," (before "<")
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (43,72): error C2589: Illegal mark to the right of "(": "::"
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (43,1): error C2988: unrecognized template declaration / definition
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (43,1): error C2059: syntax error: ")"
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (44,68): error C2589: Illegal mark to the right of "(": "::"
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (44,1): error C2988: unrecognized template declaration / definition
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (44,1): error C2059: syntax error: ")"
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (46,28): error C2275: "size_t": illegal to use this type as an expression
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (46): message: see the declaration of "size_t"
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (46,1): error C2062: unexpected type "double"
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (46,1): error C4430: Missing type specifier-assumes int. Note: C ++ does not support default int
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (49,28): error C2275: "size_t": It is illegal to use this type as an expression
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (49): message: see the declaration of "size_t"
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (49,1): error C2062: unexpected type "double"
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (49,1): error C4430: Missing type specifier-assumes int. Note: C ++ does not support default int
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (49,1): error C2059: syntax error: ")"
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (50,1): error C2143: syntax error: missing ";" (before "{")
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (50,1): error C2447: "{": missing function title (is it an old-fashioned form table?)
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (59,64): warning C4003: Insufficient "max" parameter of the function-like macro call
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (155,70): warning C4003: Insufficient "min" parameter for calling class function macro
1> F: \ project_vs2019 \ sd \ sd \ include \ fplus \ optimize.hpp (156,74): warning C4003: Insufficient "min" argument for calling class function macro
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ tensor.hpp (366,61): warning C4003: Insufficient "max" parameter of a function-like macro call
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ max_pooling_2d_layer.hpp (103,40): error C2589: "(": illegal sign to the right of ":"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ max_pooling_2d_layer.hpp (103,40): Error C2062: Unexpected type "Unknown type"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ max_pooling_2d_layer.hpp (103,40): error C2059: syntax error: ")"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (77,20): Error C2589: Illegal mark to the right of "(": "::"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (77,1): Error C2062: Unexpected type "Unknown type"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (77,1): error C2059: syntax error: ")"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (78,20): Error C2589: Illegal mark to the right of "(": "::"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (78,1): Error C2062: Unexpected type "Unknown type"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (78,1): error C2059: syntax error: ")"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (79,20): Error C2589: Illegal mark to the right of "(": "::"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (79,1): error C2062: unexpected type "Unknown type"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (79,1): error C2059: syntax error: ")"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (80,20): Error C2589: Illegal mark to the right of "(": "::"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (80,1): error C2062: unexpected type "Unknown type"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (80,1): error C2059: syntax error: ")"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (81,61): Error C2589: Illegal mark to the right of "(": "::"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (81,1): error C2062: unexpected type "Unknown type"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (81): Error C2144: Syntax error: "Unknown type" should be preceded by "("
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (81,1): error C2059: syntax error: ")"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (82,64): Error C2589: Illegal mark to the right of "(": "::"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (82,1): error C2062: unexpected type "Unknown type"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (82): Error C2144: Syntax error: "Unknown type" should be preceded by "("
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (82,1): error C2059: syntax error: ")"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (83,62): error C2589: "(": illegal sign to the right of ":"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (83,1): Error C2062: Unexpected type "Unknown type"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (83): Error C2144: Syntax error: "(Unknown type) should be preceded by" ("
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (83,1): error C2059: syntax error: ")"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (84,63): Error C2589: Illegal mark to the right of "(": "::"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (84,1): error C2062: unexpected type "Unknown type"
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (84): Error C2144: Syntax error: "Unknown type" should be preceded by "("
1> F: \ project_vs2019 \ sd \ sd \ include \ fdeep \ layers \ upsampling_2d_layer.hpp (84,1): fatal error C1003: error count exceeds 100; stopping compilation



At 2020-03-15 21:39:54, "Tobias Hermann" <notifications@github.com> wrote:

Could you post the content of the compiler errors you get?

**Comment by Dobiasd** [comment]
It might be that the macros `min` and `max`, coming from `minwindef.h`/`Windows.h`/`windef.h`, collide with `std::numeric_limits::min<T>()` and `std::numeric_limits::max<T>()`.

That's a known issue with the windows headers. Please try to add `#define NOMINMAX` before including any windows stuff to disable them. You can find more information when you search for `NOMINMAX` with google or similar.

**Comment by jianjiangwell** [comment]
Dear Tobias Hermann,Good afternoon
Thank you very much for your email last night. In your email, you pointed out that the issue of macro conflicts caught my attention. Following your suggestion, I successfully solved the problem of compilation and errors. This reply expresses heartfelt thanks.
I wish you good health and happy work!
Sincerely Jian Jiangwei



At 2020-03-15 22:26:07, "Tobias Hermann" <notifications@github.com> wrote:

It might be that the macros min and max, coming from minwindef.h/Windows.h/windef.h, collide with std::numeric_limits::min<T>() and std::numeric_limits::max<T>().

That's a known issue with the windows headers. Please try to add #define NOMINMAX before including any windows stuff to disable them. You can find more information when you search for NOMINMAX with google or similar.
