### ISSUE TITLE
issues while loading a json file to c++

### ISSUE THREAD

**Issue by Nas-a11y** [Dobiasd/frugally-deep#215]
hello, thanks for this great library. I tried first to train a Fully connected network, then import it from python (3.7) tensorflow (2.0.0) keras (2.2.4) to c++ 14. loading the json file ( converted from .h5 ) works without issues. but when i trained a conv network ( conv2d layer and maxpooling2d), im having troubles when trying to import the json file. the conversion from .h5 to json works , but when i import it to c++ i am getting an exception : must be boolean but is null. 
Thanks in advance :)

**Comment by Dobiasd** [comment]
Hi,

can you please make sure that you are using the latest version of frugally-deep, not just the C++ headers, but also the `convert_model.py`?

If this does not help, please post a minimal example (python code to create a model) to reproduce the problem, also with the exact (full) error message.

Thanks.

**Comment by Nas-a11y** [comment]
that's it, my convert_model.py was not aligned with the latest one. thank you !
