### ISSUE TITLE
error during load mode json in c++ code

### ISSUE THREAD

**Issue by cuiwei133** [Dobiasd/frugally-deep#230]
hi @Dobiasd ,
thanks for your work
I am having an issue porting my model to c++. I have checked the frugally version and tensorflow version and they are:
tensorflow 2.2.0
Python 3.7 
gcc 5.4

I followed the steps the Usage you posted,but I still have the issue 
when i compile follow code

#include <fdeep/fdeep.hpp>
int main()
{
    const auto model = fdeep::load_model("fdeep_model.json");
    const auto result = model.predict({fdeep::tensor(
            fdeep::tensor_shape(static_cast<std::size_t>(4)),{1, 2, 3, 4}
            )});
    std::cout << fdeep::show_tensors(result) << std::endl;
}

with 
/usr/local/bin/g++ -std=c++14 -I /data0/data1/cuiwei5/keras_Test/new/include/ /data0/data1/cuiwei5/keras_Test/new/main.cpp -o out
it tell that "call to constructor of 'fdeep::tensor' is ambiguous"

hope you could check it and give me a hint where the problem might be.

thanks in advance

**Comment by Dobiasd** [comment]
Hi @cuiwei133,

since you closed the issue, I assume you have solved the problem. Would you mind sharing the gist of the solution?
