### ISSUE TITLE
How to convert the result of model.predict into a float vector?

### ISSUE THREAD

**Issue by WHMJP** [Dobiasd/frugally-deep#235]
- Before reporting an issue, please make sure you are using the latest versions of frugally-deep, and [the right TensorFlow version](README.md#requirements-and-installation).

- Also check out the [FAQ](../FAQ.md). Maybe your problem/question is common and there already is a canonical answer for it.

- If you have a model and you get unexpected errors when converting it for or when using it with frugally-deep, please upload and post a link to your model file (`.h5`).

- Please try to make the problem reproducible by providing a [SSCCE](http://sscce.org/) as code.

- Feel free to also submit any other feedback, suggestions or questions you might have. :)

**Comment by WHMJP** [comment]
Hi, thank you very much for your great contribution!
I can load a trained model and use model.predict to get the predicted result as:
     const auto result = model.predict({ input });
     cout << fdeep::show_tensors(result_value) << endl;
     cout << '\n';
Then what is the data type of the predicted result? is it a tensor? I want to continue to use the predicted results as input for random forest classification. Do I have to convert the predicted results to a float vector. I saw your example in FAQ, and tried the code as:
    const vector<float> result_vec = result.to_vector();
But I got 2 compile errors:
1. class "std::vector<fdeep::internal::tensor, std::allocator<fdeep::internal::tensor>>" has no member "to_vector"	
2. Error C2039	'to_vector': is not a member of 'std::vector<fdeep::internal::tensor,std::allocator<_Ty>>'.
I did use the latest version of fdeep.hpp, and tested your example about to_vector() in FAQ. It worked well.
Could you please help me find a solution?	

Thank you very much in advance!

**Comment by Dobiasd** [comment]
> ```cpp
> const auto result = model.predict({ input });
> ```
> 
> Then what is the data type of the predicted result? is it a tensor?

`result` is of type [`fdeep::tensors`](https://github.com/Dobiasd/frugally-deep/blob/cde05975be4d3696623c9841eafe57a7dcedc31e/include/fdeep/model.hpp#L27), which is a type alias for [`std::vector<fdeep::tensor>`](https://github.com/Dobiasd/frugally-deep/blob/cde05975be4d3696623c9841eafe57a7dcedc31e/include/fdeep/tensor.hpp#L170).

---

If your model only outputs one tensor, you can convert the result to an `std::vector<float>` by using the following:

```cpp
const auto result_vec = result.front().to_vector();
```

**Comment by WHMJP** [comment]
thank you very much, it works.
