### ISSUE TITLE
more speedup in prediction

### ISSUE THREAD

**Issue by Ashbajawed** [Dobiasd/frugally-deep#236]
how can I more speed up the prediction process as its taking around 330-360ms for single prediction since I want to use it in a search tree and for single hit tree undergoes around thousands of nodes and Each node require prediction.  predict_multi will also not provide require solution. I want to make my prediction in 1-10ms time or  is that possible in anyway?

![image](https://user-images.githubusercontent.com/46400775/89608730-fa03ed00-d886-11ea-80bf-9f4648fe7bed.png)

PS: I'm open for other suggestions also since my main objective is to call prediction method in a search tree

**Comment by Dobiasd** [comment]
> [...] the prediction process as its taking around 330-360ms [...] I want to make my prediction in 1-10ms time [...]

How long does a predicion with your model take when you use TensorFlow (without GPU, and just one CPU core)?

**Comment by Ashbajawed** [comment]
> > [...] the prediction process as its taking around 330-360ms [...] I want to make my prediction in 1-10ms time [...]
> 
> How long does a predicion with your model take when you use TensorFlow (without GPU, and just one CPU core)?

mentioned above 330ms - 360ms i.e 0.33-0.36secs

**Comment by Dobiasd** [comment]
I thought this is the time it takes with frugally-deep?

To make things clear:
a) How long does a prediction on your model take with TensorFlow (no GPU, only one CPU core)?
b) How long does a prediction on your model take with TensorFlow (no GPU, only one CPU core)?

If TensorFlow is much faster than frugally-deep, please make sure you have [enabled all compiler optimizations](https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#why-is-my-prediction-roughly-100-times-slower-in-c-as-in-python) when building your executable that uses frugally-deep.

If you don't observe a big difference in performance between TensorFlow and frugally-deep then, I guess that's the maximum you can get.

In case you do observe a big difference despite compiler optimizations, please upload your model in `h5` format, so I can profile locally.

**Comment by Ashbajawed** [comment]
a)330ms - 360ms i.e 0.33-0.36secs
b)its taking approx same time in python without gpu

**Comment by Dobiasd** [comment]
Ok, that means frugally-deep is similarly fast as TensorFlow on that model.
And since TensorFlow is quite optimized, I don't think I can beat it with by over one order of magnitude, i.e., I likely can not speed up frugally-deep on your model from `0.3 s` to `0.01 s` like you require.

Maybe you can cache the prediction results for your search tree in some way to speed up your overall use-case, but this problem is not related to frugally-deep and outside of the scope of GitHub issues of this repo.
