### ISSUE TITLE
Unable to comiple with cmake..

### ISSUE THREAD

**Issue by shouryasimha** [Dobiasd/frugally-deep#240]
Hello i tried to compile using ,

git clone https://github.com/Dobiasd/frugally-deep
cd frugally-deep
mkdir -p build && cd build
cmake ..
make && sudo make install
cd ../..
But i Get the folliwing error : ,

CMake Error at CMakeLists.txt:35 (find_package):
  Could not find a package configuration file provided by "FunctionalPlus"
  with any of the following names:

    FunctionalPlusConfig.cmake
    functionalplus-config.cmake

  Add the installation prefix of "FunctionalPlus" to CMAKE_PREFIX_PATH or set
  "FunctionalPlus_DIR" to a directory containing one of the above files.  If
  "FunctionalPlus" provides a separate development package or SDK, be sure it has been installed.

Do I need to get function plus too? because I thought i could get the package by cloning frugally-deep. P.S.:  Forgive me, I'm a newbie at this.

**Comment by Dobiasd** [comment]
Yes, you need to install FunctionalPlus (and the other dependencies) too.

**Comment by shouryasimha** [comment]
Yeah figured it out , thank you for the  quick response.
