### ISSUE TITLE
Is it possible to predict outputSfrom the Dense layer before 

### ISSUE THREAD

**Issue by WHMJP** [Dobiasd/frugally-deep#243]
- Before reporting an issue, please make sure you are using the latest versions of frugally-deep, and [the right TensorFlow version](README.md#requirements-and-installation).

- Also check out the [FAQ](../FAQ.md). Maybe your problem/question is common and there already is a canonical answer for it.

- If you have a model and you get unexpected errors when converting it for or when using it with frugally-deep, please upload and post a link to your model file (`.h5`).

- Please try to make the problem reproducible by providing a [SSCCE](http://sscce.org/) as code.

- Feel free to also submit any other feedback, suggestions or questions you might have. :)

**Comment by Dobiasd** [comment]
Closing in favor of issues #244.
