### ISSUE TITLE
Is it possible to predict the dense layer output before the last layer for softmax function?

### ISSUE THREAD

**Issue by WHMJP** [Dobiasd/frugally-deep#244]
Hello, 
Thank you very much for your great work!
I want to use CNN + SVM for classification. Then I want to use model.predict to get the extracted features at the middle dense layer or flatten layer from CNN, and continue to use  them as input to the SVM model for final classification. Is it possible to do it and if so could you please teach me how to do it.

**Comment by Dobiasd** [comment]
Frugally-deep does support inspecting the intermediate output between layers in the middle of model.

So I suggest to split your model into two model, and feed the output from the first model as input into the second model.

**Comment by WHMJP** [comment]
Thank you very much for your quick reply!
