### ISSUE TITLE
Tensorflow 1.14.0 support

### ISSUE THREAD

**Issue by YannickLecroart** [Dobiasd/frugally-deep#245]
Hi,

Could you please me if your library will work with TF version 1.14.0 even though you tested it with TF 2.3?

Thanks in advance.

Regards,

**Comment by Dobiasd** [comment]
Hi,

I've never tried with TF 1.14. Frugally-deep `v0.10.1-p0` was based on TF `1.13.1`, and the next version, i.e., `v0.11.0-p0`, was based on `2.0.0`.

But of course, feel free to try it out. If you don't succeed with the current version, i.e. `v0.12.0-p0`, maybe try `v0.10.1-p0`. It seems to be the closest match.

**Comment by YannickLecroart** [comment]
Hi Dobias,

Thank you for your feedback. I have installed your package through Conan and when I try to convert my model via the convert_model.py script I get the following error:

KeyError: "Unable to open object (object 'Conv_1_bn' doesn't exist)"

I have attached a picture so that you can look at the log.

Could you please help me with this issue?

Regards,
![frugally deep](https://user-images.githubusercontent.com/43994829/92220141-cf17b380-ee9b-11ea-9742-4598f1442695.jpg)

**Comment by Dobiasd** [comment]
Which version of frugally-deep is this? And which version of TensorFlow are you using?

**Comment by Dobiasd** [comment]
Ah, I see it's happening already when just trying to load the `h5` model.

Please make sure the following code (using the right model path) works with your model:

```python
from tensorflow.keras.models import load_model
model = load_model("your_model.h5")
```

**Comment by YannickLecroart** [comment]
I am sorry but I am a bit confused.

I have placed my h5 model in the keras_export folder.

![fg](https://user-images.githubusercontent.com/43994829/92247981-4c591d80-eec8-11ea-9c85-f3368df2d046.jpg)

Just above this folder I created a new one called "output" for the .json output conversion.

![fg2](https://user-images.githubusercontent.com/43994829/92248062-64c93800-eec8-11ea-9c28-d3c9dfa150ac.jpg)

And here is how I exectute the convert_model.py script.

![fg3](https://user-images.githubusercontent.com/43994829/92248203-993cf400-eec8-11ea-8090-a6023d97800a.jpg)


Could you please tell me what I am doing wrong?

**Comment by Dobiasd** [comment]
[The exception you get](https://user-images.githubusercontent.com/43994829/92220141-cf17b380-ee9b-11ea-9742-4598f1442695.jpg) is not related to frugally-deep.

Sure, `convert_model.py` crashes, but only because `tensorflow.keras.models.load_model` crashes with the `h5` file you give it.

Please try out the following minimal Python example and let me know the result:

```python
from tensorflow.keras.models import load_model
model = load_model("wine_plant_detector.h5")
```

**Comment by YannickLecroart** [comment]
Hi Dobias,

I just realized that I was using a broken model (for which training has been interrupted because of insufficient disk space...) and that is the reason why I could not load the H5 file correctly. I used another model that I trained before and the conversion now works fine as you can see below.

![fg6](https://user-images.githubusercontent.com/43994829/92321956-99ef9a80-f02e-11ea-9bec-12422e4e8b0a.jpg)


Thanks again for your time and effort. Your package is really helpful. 

Regards,

**Comment by YannickLecroart** [comment]
I am not very familiar with C++ even though I plan to port my python computer vision project to C++. Could you tell me if I can pass an OpenCV Mat to the Network or do I have first to convert the Mat object into a std Vector?

Thanks in advance.

**Comment by Dobiasd** [comment]
Glad the conversion is working now. 🙂

Regarding your OpenCV question, see here:
https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#how-to-use-images-loaded-with-opencv-as-input-for-a-model

**Comment by YannickLecroart** [comment]
Dobias you are awesome really.
