### ISSUE TITLE
predict_class() issue

### ISSUE THREAD

**Issue by YannickLecroart** [Dobiasd/frugally-deep#247]
Hi Tobias,

I have successfully converted my keras H5 into a json file through your library. You can find below the model summary:

[model_summary.txt](https://github.com/Dobiasd/frugally-deep/files/5194502/model_summary.txt)

The input shape of my model is (224, 224, 3) . The output in Python is a ndarray that returns the 2 class probabilities.

![fd8](https://user-images.githubusercontent.com/43994829/92588291-108fd080-f299-11ea-93ad-dec5adddc5c9.jpg)

I am now testing the converted model in C++ with the following code:

`
int main()
{

	Mat img = imread("rang25_26.jpg");

	resize(img, img, Size(224, 224));

	assert(img.isContinuous()); 

	const auto model = fdeep::load_model("fdeep_model.json");

	const auto input = fdeep::tensor_from_bytes(img.ptr(), static_cast<size_t>(img.rows), static_cast<size_t>(img.cols), static_cast<size_t>(img.channels()), 0.0f, 1.0f);

	const auto result = model.predict_class({ input });

	cout << result << endl;

	imshow("Source", img);

	waitKey(0);

	return 0;
}
`

But the result I get is a number and not the 2 class probabilities as in Python as you can see below.

![fd9](https://user-images.githubusercontent.com/43994829/92589117-62852600-f29a-11ea-9c30-10ca5fc9c722.jpg)

Is there something I am doing wrong?

Thanks in advance for your help.

Regards,

**Comment by Dobiasd** [comment]
Try `model.predict` instead of `model.predict_class`. :slightly_smiling_face:

**Comment by YannickLecroart** [comment]
Thanks for the quick reply.

I did that and it now works.

![fd11](https://user-images.githubusercontent.com/43994829/92593830-0faf6c80-f2a2-11ea-803f-6bd031b34076.jpg)

Could you now tell me how can I extract those 2 probabilities from the tensor?

I tried the following code but to no avail.

    `const auto model = fdeep::load_model("fdeep_model.json");

	const auto input = fdeep::tensor_from_bytes(img.ptr(), static_cast<size_t>(img.rows), static_cast<size_t>(img.cols), static_cast<size_t>(img.channels()), 0.0f, 1.0f);
	const auto preds = model.predict({ input });
	cout << fdeep::show_tensors(preds) << endl;

	const vector<float> vec = preds.to_vector();


	imshow("Source", img);`


`
Error E0135	class "std::vector<fdeep::internal::tensor, std::allocator<fdeep::internal::tensor>>" has no member "to_vector"	test_frugally_deep
`

**Comment by Dobiasd** [comment]
`model::predict` returns a `std::vector<fdeep::tensor>`. So try this one:

```cpp
const std::vector<float> vec = preds.front().to_vector();
```

**Comment by Dobiasd** [comment]
Your next question likely will be: "Why does my model return different values with frugally-deep compared to Keras?" :slightly_smiling_face:

To solve this, please check the following part of the FAQ: https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#why-does-my-model-return-different-values-with-frugally-deep-compared-to-keras"

**Comment by YannickLecroart** [comment]
I am sorry to keep bothering you but when I try 👍 

`const std::vector<float> vec = preds.front().to_vector();`

I get the following error message.

`Error (active)	E0312	no suitable user-defined conversion from "fdeep::internal::float_vec_unaligned" to "const std::vector<float, std::allocator<float>>" exists`

**Comment by Dobiasd** [comment]
Then try

```cpp
const std::vector<fdeep::float_type> vec = preds.front().to_vector();
```

(Maybe you have `#define FDEEP_FLOAT_TYPE double` somewhere.)

or

```cpp
const auto vec = preds.front().to_vector();
```

**Comment by YannickLecroart** [comment]
Brilliant it is all good now. 

Indeed, I am using `#define FDEEP_FLOAT_TYPE double` to get more precision as your guide suggests. 

Sorry I missed that point but once again it just shows how good you are ;)
