### ISSUE TITLE
predict_multi() usage

### ISSUE THREAD

**Issue by YannickLecroart** [Dobiasd/frugally-deep#248]
Hi Tobias,

I have created a vector of tensors.

    vector<fdeep::internal::tensor> objects;

Then I append that vector after converting an OpenCV Mat into a fdeep::tensor

    Mat image_roi = img_orig(roi);

    resize(image_roi, image_roi, Size(224, 224));

    const auto input = fdeep::tensor_from_bytes(image_roi.ptr(), static_cast<size_t>(image_roi.rows), static_cast<size_t>(image_roi.cols), static_cast<size_t>(image_roi.channels()), 0.0f, 1.0f);

    objects.push_back(input);

Finally, I try to feed the network with the vector of tensors.

    const auto preds = model.predict_multi(objects);

But I get the following error message.

    too few arguments in function call

In another question (issue #23) I saw that the predict_multi() expects a vector<tensor3>. So what changes need to be done with my code? (I am a beginner in C++)

Regards,

**Comment by Dobiasd** [comment]
The function signature of `fdeep::model::predict_multi` is the following:

```cpp
std::vector<tensors> predict_multi(const std::vector<tensors>& inputs_vec, bool parallelly) const
```

So instead of

```cpp
const auto preds = model.predict_multi(objects);
```

you need to decide if you want to run the predictions in parallel, i.e., utilizing multiple CPU cores in your machine, or not.

Example call with parallelism:

```cpp
const auto preds = model.predict_multi(objects, true);
```

**Comment by YannickLecroart** [comment]
it works only if I put objects inside brackets.

    const auto preds = model.predict_multi({ objects }, true);

Can you explain me why?

**Comment by YannickLecroart** [comment]
Thanks for the detailed explanation. Everthing clear now.
