### ISSUE TITLE
Prepare inputs using make_shared_ref 

### ISSUE THREAD

**Issue by qwum** [Dobiasd/frugally-deep#249]
Hello,

I have installed the latest version of frugally-deep, and tested it with the example provided successfully, which assigned input values explicitly. When I tried to use an existing vector to construct the inputs, an error occurred as follows:
" required from here
  /usr/local/include/fplus/shared_ref.hpp:50:26: error: no matching function for call to ‘std::vector<float, Eigen::aligned_allocator<float> >::vector(const std::vector<float>&)’
       return shared_ref<T>(new T(std::forward<Types>(args)...));"

I found an example filed previously (attached below, Issue #106 ) and made changes for the new version, but still got the same error. What is the possible cause behind? Would you please show a minimal example that works under the current version? Thanks.

#include <fdeep/fdeep.hpp>
int main()
{
    const auto model = fdeep::load_model("fdeep.json");
    const std::vector<float> v = {1, 2, 3,  1, 2, 3,  1, 2, 3,  1, 2, 3,  1, 2, 3,  1, 2, 3,  1, 2, 3,  1, 2, 3,  1, 2, 3,  1, 2, 3};
    const fdeep::shared_float_vec sv(fplus::make_shared_ref<fdeep::float_vec>(v));
    fdeep::tensor input(fdeep::tensor_shape(1, 1, 1, 10, 3), sv);
    const auto output = model.predict({input});
    std::cout << fdeep::show_tensors(output) << std::endl;
}

**Comment by Dobiasd** [comment]
The FAQ has a minimal example on [how to fill an `fdeep::tensor` with values, e.g., from an `std::vector<float>`](https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#how-to-fill-an-fdeeptensor-with-values-eg-from-an-stdvectorfloat).

But for completeness, here is the minimal example you've posted, converted to work with the current version of frugally-deep:

```cpp
#include <fdeep/fdeep.hpp>
int main()
{
    const auto model = fdeep::load_model("fdeep.json");
    const std::vector<float> v = {1, 2, 3,  1, 2, 3,  1, 2, 3,  1, 2, 3,  1, 2, 3,  1, 2, 3,  1, 2, 3,  1, 2, 3,  1, 2, 3,  1, 2, 3};
    const fdeep::tensor input(fdeep::tensor_shape(1, 1, 1, 10, 3), v);
    const auto output = model.predict({input});
    std::cout << fdeep::show_tensors(output) << std::endl;
}
```
