### ISSUE TITLE
Issue when compiling on some systems

### ISSUE THREAD

**Issue by LevLavy** [Dobiasd/frugally-deep#25]
On mac/ios I have no issue in compilation but on AWS instance:
os.arch | amd64
os.name | Linux
os.version | 3.16.0-4-amd64

When compiling I get:
...
/fplus/fplus/container_common.hpp: In function Acc fplus::fold_right(F, const Acc&, const Container&)
/fplus/fplus/container_common.hpp 
error: 
std::rbegin
has not been declared
using std::rbegin;
fplus/container_common.hpp:910:16: 
error: 
std::rend
has not been declared
using std::rend;

If I remove them from fplus everything compiles so its not a blocker.

**Comment by Dobiasd** [comment]
[`CMakeLists.txt`](https://github.com/Dobiasd/FunctionalPlus/blob/468617c9fe7deb9b96399a706d1857b82a7fd792/test/CMakeLists.txt#L14) of FunctionalPlus executes [show_versions.cpp](https://github.com/Dobiasd/FunctionalPlus/blob/f59f47ab3ce7754755ee436fcb0a01963c568fc5/test/show_versions.cpp).

Here is an [example of its output on Travis](https://travis-ci.org/Dobiasd/FunctionalPlus/jobs/346713072#L1322).

So if you search your build output of FunctionalPlus for one of these strings, you should find the answer:
```
__cplusplus
_LIBCPP_VERSION
_LIBCPP_ABI_VERSION
_MSC_VER
__GLIBCPP__
__GLIBCXX__
```

**Comment by LevLavy** [comment]
Working well on: 
GNU 5.4.0, 201402

Not compiling unless I remove few functions that use std::rend and std::rbegin from fplus (not used in fdeep):
GNU 4.9.2, 201300

I wonder if it possible to be compatible back, if no its ok (I cant upgrade it now, I will use the removing function workaround, maybe you can add some ifdef around them?)

Thanks!

**Comment by Dobiasd** [comment]
It's in [`fold_right`](https://github.com/Dobiasd/FunctionalPlus/blob/19caf25a3c6d93c1d48cde95c29fbd50746843d1/include/fplus/container_common.hpp#L900-L930), but I'll come up with a version without `std::rbegin` and `std::rend`.

**Comment by Dobiasd** [comment]
Since your compiler did not complain about `std::copy(++xs.rbegin(), xs.rend(), xs.rbegin());` in `fplus::internal::prepend_elem` I guess `xs.rbegin` is fine, it's just `std::rbegin(xs)` that is causing the problem.

I just [committed to FunctionalPlus](https://github.com/Dobiasd/FunctionalPlus/commit/727f16e8fce882624a391dea9993d403547ccfec). Now you should be able to use it without the need to manually modify the code. :)
