### ISSUE TITLE
Does frugally-deep support any type of model?

### ISSUE THREAD

**Issue by sahooora** [Dobiasd/frugally-deep#257]
Hi,

I already used frugally-deep for a keras model in image recognition and I used CImg to convert an image to deep::tensor5, it is really helpful for me. Thanks for your great job!

Now I have a keras LSTM model for human activity recognition with UCI_HAR dataset with 6 dimensions. My question is that can I‌ use the frugally-deep for such a model(since you are mentioned that "Layer types typically used in image recognition/generation are supported")? If yes, how can convert the dataset to fdeep::tensor5?

Thanks in advance.

**Comment by Dobiasd** [comment]
Hi, and thanks for the feedback. :slightly_smiling_face:

If the input tensors to your model actually are 6-dimensional, frugally-deep currently does not support it. Is the model available online somewhere, or could you upload it, so I could experiment with it?

**Comment by sahooora** [comment]
> Hi, and thanks for the feedback. 
> 
> If the input tensors to your model actually are 6-dimensional, frugally-deep currently does not support it. Is the model available online somewhere, or could you upload it, so I could experiment with it?

Thanks for your reply.
Unfortunately, I am not allowed to share the model.

By the way, please consider the below piece of code :
```
reloaded_model = keras.models.load_model('../models/tf_keras/' + str(DATASET))
reloaded_y_pred = reloaded_model.predict(X_test[0:END_INDEX_TEST], batch_size=BATCH_SIZE)

print('\nShape of the predicted output:')
print('-----------------------------------')
print(reloaded_y_pred.shape)
print('-----------------------------------')
```
and the output is:

```
Shape of the predicted output:
-----------------------------------
(2000, 6)
-----------------------------------

```

**Comment by Dobiasd** [comment]
Ok, so it's not that your tensor is 6-dimensional, i.e., has a shape of lengths 6. It's 2-dimensional (shape of length 2). It's just that the last dimension has a value of 6, which (in isolation) would correspond to a 6-dimensional vector. Weird terminology, I know, but I did not invent it. :wink:

So from what you show, I don't see why the model should not work in frugally-deep. Did you already successfully convert it from `h5` to `json` using `convert_model.py`?

Small remark: You mentioned `fdeep::tensor5`. This does not longer exist in recent versions of frugally-deep, so maybe consider updating to the latest version.

**Comment by sahooora** [comment]
Thanks for your explanation. Actually, I don't have any experience in Tensorflow/Keras and it is my first attempt.

I could convert my model to a json file but now I need to convert the input(x_test) to a tensor using frugally-deep. I already did it for images using the CImg library and CImg_to_tensor function. But now my dataset is not image and it's a space-separated values txt file. I am wondering if there is a way to convert the input(X_test[0:END_INDEX_TEST]) to a tensor using frugally-deep.

**Comment by Dobiasd** [comment]
> [...] my dataset is not image and it's a space-separated values txt [...]

> [...] I am wondering if there is a way to convert the input [...]

Sure there is a way. You could
- read your data and convert it to an `std::vector<T>`
- and then put that into an `fdeep::tensor`

But I guess the first step is what you're struggling with. Solving this is not related to frugally-deep and outside of the scope of help that I can provide. I recommend creating a minimal example of this and maybe posting it as a question on StackOverflow.

**Comment by sahooora** [comment]
Thank you.

Yes sure!
