### ISSUE TITLE
Speed improvement for audio?

### ISSUE THREAD

**Issue by GuitarML** [Dobiasd/frugally-deep#258]
Thanks for the really cool project! I am able to convert my Keras model and run it in a c++ application, but I was curious if there is a way to improve the speed.  I'm interested in using frugally-deep to convert my model to process live audio (reference "GuitarLSTM" project on Github).  The application requires passing a range of audio samples through the LSTM model for each output audio sample.  For typical audio applications, 44100Hz is required, or 44100 inferences per second! Here is my model in Keras:

```
    model = Sequential()
    model.add(Conv1D(conv1d_filters, 12,strides=conv1d_strides, activation=None, padding='same',input_shape=(100,1)))
    model.add(Conv1D(conv1d_filters, 12,strides=conv1d_strides, activation=None, padding='same'))
    model.add(LSTM(36))
    model.add(Dense(1, activation=None))
```

And here is my test implementation in my application; I'm just running dummy data through the model to see if it can keep up at 44100 Hz.  For the purposes of this example, "input_size" is 100, and "numSamples" is the number of samples per audio buffer (I'm testing at 128 samples per buffer).
```       

 for (int i = 0; i < numSamples; i++)
        {
            const fdeep::tensor input = fdeep::tensor(fdeep::tensor_shape(input_size, 1), 0.01);
            const auto result = model.predict({ input });

        }
```
I am impressed at how fast the inference runs, but it's not fast enough to keep up with 44100 Hz the way I have it written.  Is there anything I can do to speed up the model predictions? I saw in the FAQ it can do multi threading, and process multiple samples at once, but I think the nature of the LSTM model means I need to process each sample in sequence (because of how the hidden and cell states are updated).  Is there any way to speed up the inferencing for my application or have I reached the limit?

Edit: I'll close out this issue after it's answered, as it's not really an issue with the code, just a question for someone with more experience using frugally-deep.

**Comment by Dobiasd** [comment]
Hi Keith,

GuitarML looks like a very cool project. I'd be happy if frugally-deep could be helpful in it. :slightly_smiling_face:

If an LSTM model is stateful, you're right. Parallel predictions would not work out. But the way construct the LSTM layer (`model.add(LSTM(36))`) in your example code uses the default value for `stateful`, [which is `False`](https://keras.io/api/layers/recurrent_layers/lstm/). So if this is the same in your real model, this would be good, and you could try parallel predictions. :+1:

Assuming you already allowed your compiler to optimize the program as much as possible (`-O3` `-march=native` for clang and gcc), have you already benchmarked the prediction time in comparison to running it directly in Python using Keras/TensorFlow?

**Comment by GuitarML** [comment]
That's interesting, the results of this example seemed to match my tensorflow model results, so that's good. 

When I run my test program (which uses AudioFile to load .wav data), it takes two minutes to process about 30 seconds of audio. When running tensorflow prediction on the same wav file it takes about 8 seconds. That could also be related to how I construct the input data.  In the tensorflow script I have all of the input data preprocessed into vectors of 100 and loaded in RAM, but in the c++ script I create a vector of 100 from the wav data for each sample prediction.  I think this would be closer to how it would work for live audio, so the tensorflow example may be an unrealistic comparison.

What would the syntax for parallel processing look like?

**Comment by Dobiasd** [comment]
Can you please time the duration of just the prediction step? Otherwise, we don't know if trying to optimize it (for example by parallel processing) is helpful or not. In general, I recommend always first prove where the bottleneck is, and then decide where to optimize.

Here, I could imagine something like the following:

```cpp
// Load model and do all the input loading and transformation here.
fplus::stopwatch stopwatch;
model.predict(input);
std::cout << stopwatch.elapsed() << std::endl;
```

The declaration of `fdeep::model::predict_multi` is
```cpp
std::vector<tensors> predict_multi(const std::vector<tensors>& inputs_vec, bool parallelly) const
```

So it's like `fdeep::model::predict` (`tensors predict(const tensors& inputs) const`), but just takes multiple inputs instead of one and `true` as the second argument in your use-case.

**Comment by GuitarML** [comment]
Looks like I'm getting an average single sample prediction with fdeep (for input_size=100) of   6.35e-06 seconds.

Single sample prediction with the same tensorflow model is  1.395e-06  seconds.

So it looks like there is room for optimization, I will try using predict_multi to see how much that helps, thanks!

**Comment by Dobiasd** [comment]
Ok, cool, thanks for the mesurement. Was the TensorFlow time measured with disabling GPU and multi-CPU usage? This can be done by instead of using `python foo.py` something like `CUDA_VISIBLE_DEVICES='' taskset --cpu-list 1 python foo.py`.

**Comment by GuitarML** [comment]
That line didn't work for me, is that just from the command line? But my machine has 8 cores, and 6.35e-05 * 8 is roughly the same level as the tensorflow speed, so that makes sense. Thank you for you're help!

**Comment by Dobiasd** [comment]
Yes, that was meant to be used from a Linux command line.

---

Regarding the multiplication with 8, I'm not sure if I understand correctly.
You had the following average prediction durations:
- frugally-deep: 6.35e-05 s
- TensorFlow: 1.395e-06 s

That's a difference by a factor of 45, not 8. Maybe the GPU was also contributing.

**Comment by GuitarML** [comment]
Oh ok, I'm on Windows.  And yes, looks like I missed a decimal point. I'll look into it more, but it seems like the predict_multi would help, especially with multiple cores available. Thanks again!
