### ISSUE TITLE
Fortran wrapper

### ISSUE THREAD

**Issue by lkampoli** [Dobiasd/frugally-deep#259]
Hello,
even if it is not totally legitimate to ask the following question, nevertheless, it is another hot topic now, so, here it is.
Is there (or it is planned) any wrapper for Fortran? I mean, it is true that there are other similar projects like FANN, neural-fortran, FKB, etc. which directly target fortran language, but I found to be a bit less mature.

Assuming no wrapper is present, as reasonable, would you may suggest a "good" way to realize it, please? 
Should any approach be preferred such as CFFI, SWIG, Cython ... ?

Kind regards,
Lorenzo Campoli

**Comment by Dobiasd** [comment]
This sounds interesting, but no, currently there is no Fortran wrapper for frugally-deep existing or planned. At least I don't know of such a project.
Since I have zero experience with Fortran, I can not even give any hint on where to start implementing such a thing. Sorry.

**Comment by Dobiasd** [comment]
Of course, I don't know anything about your use-case, but maybe it would be feasible to write some service in C++, that exposes a frugally-deep-prediction call to clients, e.g., via HTTP POST endpoint or something like that, such that your Fortran application could use it that way?

**Comment by lkampoli** [comment]
Hi,
I'm not familiar with the solution you propose but I will look into it, thanks.
Just for the sake of information, since I'm working also a bit on this, I report the following:

Integrating trained ML components back into Fortran-based codes is not as trivial as may be expected. Current methods include:

- Re-coding specific model architectures into Fortran.
** Pros: fast, good compatibility with existing Fortran codes.
** Cons: time-consuming and inflexible as changing the ML model architecture means recoding in Fortran

- Calling Python from within Fortran (e.g. using a wrapper library such as CFFI, SWIG, Babel, Cython)
** Pros: No re-coding as the ML model remains in Python.
** Cons: This approach was tried and various compatibility issues on HPC were found. It is also potentially slow since Fortran needs to call out to Python.

- Use a Pure Fortran NN library, or bridging library (e.g. FANN, neural-fortran, FKB, frugally-deep)
** Pros: fast (probably), good compatibility with existing Fortran codes.
** Cons: The existing solutions only have limited architectures and algorithms available since they are either Fortran re-implementations of methods or APIs that mirror common ML frameworks, Translations from native ML model format are often required.

- Intrinsic Fortran procedures, such as get_command_argument, get_command to invoke Python scripts and exchange data through I/O files. This is not really HPC oriented solution.

- Idea: to interface directly to the underlying C/C++ libraries of the ML frameworks using TensorflowLite C/C++ API

In any case, may I find some good solution, I will be happy to post you.
Kind regards,
Lorenzo
