### ISSUE TITLE
LeakyRELU Support

### ISSUE THREAD

**Issue by cfitz25** [Dobiasd/frugally-deep#263]
Hello, could LeakyRELU become a supported activation function?
Sorry, it seems it says it is supported. I did get an error saying it wasnt though. Any ideas why?

**Comment by Dobiasd** [comment]
Could you give a minimal example model to reproduce the error? Asking, because [`LeakyReLU` is covered in the automated tests](https://github.com/Dobiasd/frugally-deep/blob/162b5a104cab098cd8204fb7db4bad6c4efb9829/keras_export/generate_test_models.py#L348), and working fine there.

**Comment by cfitz25** [comment]
Sorry, it appears to be me just having trouble loading the h5 files after they are saved. Is there any reason this may be? It just tells me that my Activation functions are unknown

**Comment by Dobiasd** [comment]
Maybe you're using a custom activation function?

A prerequisite for frugally-deep to work out-of-the-box is, that you can load your model (without using frugally-deep, just Keras/TensorFlow) like so:

```python3
from tensorflow.keras.models import load_model
model = load_model("your_model.h5")
```

Does this work in your case?
If not, what's the exact error message?
Can you create and upload a minimal example model to reproduce the issue?

**Comment by cfitz25** [comment]
That does not work for some reason, giving the error of "ValueError: Unknown activation function: LeakyReLU" using this model: https://drive.google.com/file/d/1gGxJmRJoRhe7Qp0I_hupmxYPndU9qDjf/view?usp=sharing

**Comment by Dobiasd** [comment]
I can't download this file. You need to make it public.

**Comment by cfitz25** [comment]
sorry, https://drive.google.com/file/d/1gGxJmRJoRhe7Qp0I_hupmxYPndU9qDjf/view?usp=drivesdk

**Comment by Dobiasd** [comment]
Thanks. I can reproduce your problem with the following `Dockerfile`:

```Dockerfile
FROM python:3.8

RUN apt-get update
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y build-essential cmake

RUN pip3 install tensorflow==2.4.0

RUN pip3 install gdown
RUN gdown -O model.h5 "http://drive.google.com/uc?id=1gGxJmRJoRhe7Qp0I_hupmxYPndU9qDjf"

RUN echo 'from tensorflow.keras.models import load_model' > main.py
RUN echo 'model = load_model("model.h5")' >> main.py

RUN python3 main.py
```

```
ValueError: Unknown activation function: LeakyReLU
```

So your issue seems to be unrelated to frugally-deep. How do you load this model in your normal code?

**Comment by cfitz25** [comment]
im just using the load model function. could it have something to do with me using the GPU version and a custom session? 
I had to set the keras session so GPU would work correctly

**Comment by Dobiasd** [comment]
Might be. It's really hard to tell without seeing the relevant code. :)
