### ISSUE TITLE
Building DLL with frugally-deep

### ISSUE THREAD

**Issue by cdl1990** [Dobiasd/frugally-deep#264]
Thanks for sharing your working, i have a queston while using frugally-deep as the header file to build a dll file,there is very rare files related, could you give any suggestions?
Thanks!!

**Comment by Dobiasd** [comment]
Sorry, I don't understand the question. You can use frugally-deep in code to build a .dll file the same way you would use it to build an .exe file.

**Comment by cdl1990** [comment]
Sorry, my question is not clear.  I use your minimal example as a test, trying to build this algorithm into a dll file.

I use VS2019, put Eigen, fdeep,fplus and nlohmann folders in include folder. 
And add include to Additional Include Dirctories.

Here is my codes of header file:
#include <string>
using std::string;

#ifdef CREATEDLL_EXPORTS
#define CREATEDLL_API __declspec(dllexport)  
#else
#define CREATEDLL_API __declspec(dllimport)  
#endif

extern "C" CREATEDLL_API int main(string path);

And codes of source file:
#include "pch.h"
#include <iostream>
#include "CreateDll.h"
#include "fdeep/fdeep.hpp"
#include <string>

int main(string path)
{
    //string path = a;
    const auto model = fdeep::load_model("path"); 
    const auto result = model.predict(
        { fdeep::tensor(fdeep::tensor_shape(static_cast<std::size_t>(4)),
        std::vector<float>{1, 2, 3, 4}) });
    std::cout << fdeep::show_tensors(result) << std::endl;
}

However, I got some errors, like fdeep doesn't exist.

**Comment by Dobiasd** [comment]
Can you please show the exact errors you get?

**Comment by cdl1990** [comment]
if I rebuild solution, I got hundreds errors.
![2020-12-22](https://user-images.githubusercontent.com/70997236/102867361-9bc15a80-4473-11eb-8159-167d862a1eb4.png)

**Comment by Dobiasd** [comment]
1) Are you using a C++14-compatible compiler?
2) Have you enabled C++14-language features?
3) Can you get [a minimal frugally-deep example without the DLL stuff](https://gist.github.com/Dobiasd/858fb0d93d0c5e2455bea734fd7403da) to compile successfully?
4) `optimize.hpp` comes from FunctionalPlus. Can you get [a minimal FunctionalPlus example](https://gist.github.com/Dobiasd/ff43c400c1af636d24163913beb804b3) to compile successfully?

**Comment by gchen001** [comment]
I got exactlly the same problem when I'm developing a product for python model deployment in our production enviroement. I also found build an exe was quite easy following the author's instruction but we got lots of unrelated errors which seems coming from the head library we were using.

I'll keep an eye on this issue. Thanks !

**Comment by yochananscharf** [comment]
@cdl1990 did you set the VS solution platform to `x86` ?

**Comment by Noirim** [comment]
Hi there,
I tried to build a dll also and it appears that the builds error comes from some macros already defined in minwint.h
so the code references in numeric.hpp and container_common.hpp from fplus lib to "min" and "max" fails.
hope that can help someone.

**Comment by Dobiasd** [comment]
Yeah, good catch @Noirim. :+1:

it might be that the macros `min` and `max`, coming from `minwindef.h`/`Windows.h`/`windef.h`, collide with `std::numeric_limits::min<T>()` and `std::numeric_limits::max<T>()`, which are not only used in FunctionalPlus, but [also in frugally-deep directly](https://github.com/Dobiasd/frugally-deep/blob/baca08ce4cfe31cb74441da4e21217dae587fe17/include/fdeep/tensor.hpp#L360).

That's a known issue with the windows headers. Please try to add `#define NOMINMAX` before including any windows stuff to disable them. You can find more information when you search for `NOMINMAX` with Google or similar.

**Comment by Noirim** [comment]
Thanks for the feedback!
