### ISSUE TITLE
How to Implement Custom Layers

### ISSUE THREAD

**Issue by Ykram12** [Dobiasd/frugally-deep#268]
Hi,

I have a model that I want to use in C++ but it has Lambda layers which from what I read from previous issues answers it might not be possible due to development for that being stopped. (Links to issues that reference it)
https://github.com/Dobiasd/frugally-deep/issues/54
https://github.com/Dobiasd/frugally-deep/issues/82

Now, I do see a custom_layer_creators argument in the fdeep::model::load_model function and it makes me question if would there could be a possibility of me reimplementing these Lambda Layers as Custom Layers in Keras and then do a similar solution to the one you suggested in the previous issues in the C++ side. If so, it would be really helpful to have a similar sample code to understand how to prepare custom layers using frugally-deep in the C++ side.

Thanks!

**Comment by Dobiasd** [comment]
Hi. :slightly_smiling_face:

These issues are from 2018. Later, in 2019, support for custom layers was actually introduced to frugally-deep. :heavy_check_mark:

The ["How to use custom layers?" section in the FAQ](https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#how-to-use-custom-layers) describes how to add them. Let me know if this is helpful.

**Comment by Ykram12** [comment]
Yes that was exactly the info I needed, thanks a lot!
