### ISSUE TITLE
Error while building a model after loading it

### ISSUE THREAD

**Issue by xianmuyang** [Dobiasd/frugally-deep#269]
Hello!

I got an 'unhandled exception' error at the throw_on_nothing function within the maybe.hpp file while it was trying to build the model after loading it. 

My Python is 3.8.5.  Made sure C++14 was enabled within Visual Studio.  The attached models was created under TF 2.4.

The example on your page worked fine.

Thanks and best,  

Will

[210111-4~1-fd_model.zip](https://github.com/Dobiasd/frugally-deep/files/5804290/210111-4.1-fd_model.zip)

**Comment by Dobiasd** [comment]
I've just tried to reproduce the problem with the following `Dockerfile`:

```Dockerfile
FROM python:3.8

RUN apt-get update
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y build-essential cmake

RUN pip3 install tensorflow==2.4.0

RUN git clone -b 'v0.2.13-p0' --single-branch --depth 1 https://github.com/Dobiasd/FunctionalPlus && cd FunctionalPlus && mkdir -p build && cd build && cmake .. && make && make install
RUN git clone -b '3.3.9' --single-branch --depth 1 https://gitlab.com/libeigen/eigen.git && cd eigen && mkdir -p build && cd build && cmake .. && make && make install && ln -s /usr/local/include/eigen3/Eigen /usr/local/include/Eigen
RUN git clone -b 'v3.9.1' --single-branch --depth 1 https://github.com/nlohmann/json && cd json && mkdir -p build && cd build && cmake -DBUILD_TESTING=OFF .. && make && make install
RUN git clone -b 'v0.15.1-p0' --single-branch --depth 1 https://github.com/Dobiasd/frugally-deep && cd frugally-deep && mkdir -p build && cd build && cmake .. && make && make install

RUN pip3 install gdown
RUN gdown https://github.com/Dobiasd/frugally-deep/files/5804290/210111-4.1-fd_model.zip
RUN unzip 210111-4.1-fd_model.zip

RUN CUDA_VISIBLE_DEVICES='' taskset --cpu-list 1 python3 ./frugally-deep/keras_export/convert_model.py 210111-4~1-fd_model.h5 210111-4~1-fd_model.json

RUN echo '#include <fdeep/fdeep.hpp>' > main.cpp
RUN echo 'int main()' >> main.cpp
RUN echo '{' >> main.cpp
RUN echo '    const auto model = fdeep::load_model("210111-4~1-fd_model.json");' >> main.cpp
RUN echo '}' >> main.cpp

RUN g++ -std=c++14 -O3 main.cpp -o main

RUN ./main
```

The output is:

```
Loading json ... done. elapsed time: 0.192737 s
Building model ... terminate called after throwing an instance of 'std::runtime_error'
  what():  unknown layer type: RandomRotation
Aborted (core dumped)
```

So your model uses the experimental [`RandomRotation`layer ](https://www.tensorflow.org/api_docs/python/tf/keras/layers/experimental/preprocessing/RandomRotation), which is not supported by frugally-deep.

**Comment by Dobiasd** [comment]
According to [the docs of `RandomRotation`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/experimental/preprocessing/RandomRotation):

> At inference time, the layer does nothing.

Thus, it's very simple to support it in frugally-deep, and I just pushed [the commit doing so](https://github.com/Dobiasd/frugally-deep/commit/fdf0825eca46ca3642ccbbd89cb00808bd744761). This means, the latest version of frugally-deep in `master` works with `RandomRotation`.

**Comment by Dobiasd** [comment]
Your original model, however, still is not supported by frugally-deep. [This time](https://gist.github.com/Dobiasd/abfe0e53fd0cb9fbe55341b99bac931d), the output is as follows:

```
Loading json ... done. elapsed time: 0.202020 s
Building model ... terminate called after throwing an instance of 'std::runtime_error'
  what():  unknown layer type: TFOpLambda
Aborted (core dumped)
```

You could either try to get rid of the `TFOpLambda` layer in your model or try if you can make it work using [the support for custom layers in frugally-deep](https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#how-to-use-custom-layers).

**Comment by xianmuyang** [comment]
Thanks a lot, Dobiasd, for your prompt reply!
I didn't put in a TFOpLambda layer myself.  It must be from the transfer learned model, MobileNetV2.  I will try other things.
Best, Will
