### ISSUE TITLE
Char-RNN Support

### ISSUE THREAD

**Issue by loretoparisi** [Dobiasd/frugally-deep#27]
Given the current layers support, is it possibile to load a keras char-rnn model like the one described in "Xiang Zhang, Junbo Zhao, Yann LeCun. Character-level Convolutional Networks for Text Classification. NIPS 2015"

An implementation of this CNN based architecture is available here:

https://github.com/chaitjo/character-level-cnn/blob/master/models/zhang_char_cnn.py

Thank you.

**Comment by Dobiasd** [comment]
Hi Loreto,
sorry, but the `Embedding` layer is currently not supported by frugally-deep.
Tobias

**Comment by Dobiasd** [comment]
Hi Loreto,

it took some time, but the `Embedding` layer needed for Char-RNN models is now supported. :tada:

**Comment by loretoparisi** [comment]
@Dobiasd amazing great work 🥇 💯  can't wait to try it out :)
