### ISSUE TITLE
AttributeError: '_UserObject' object has no attribute 'compile'

### ISSUE THREAD

**Issue by sahooora** [Dobiasd/frugally-deep#271]
Hello,

I have a `onnx` model that I convert to a tensorflow saved_model using [onnx-tensorflow](https://github.com/onnx/onnx-tensorflow) library. Then I‌ tried to use my tensorflow model with frugally-deep to get a .json file but I got the following error:

```
File "../../frugally-deep/keras_export/convert_model.py", line 818, in <module>
    main()
  File "../../frugally-deep/keras_export/convert_model.py", line 814, in main
    convert(in_path, out_path, no_tests)
  File "../../frugally-deep/keras_export/convert_model.py", line 787, in convert
    json_output = model_to_fdeep_json(model, no_tests)
  File "../../frugally-deep/keras_export/convert_model.py", line 755, in model_to_fdeep_json
    model.compile(loss='mse', optimizer='sgd')
AttributeError: '_UserObject' object has no attribute 'compile'

```

PS: Tensorflow version =2.3.0

**Comment by Dobiasd** [comment]
Can you update the model, so I can try to reproduce and debug the issue?

**Comment by sahooora** [comment]
Actually, I'm working with a tf model(not a Keras model in hdf5 format) which is uploaded here. I already used a tf model with Frugally-deep and it was OK, but now I get the error for this model.
[out.tar.gz](https://github.com/Dobiasd/frugally-deep/files/5851423/out.tar.gz)

**Comment by Dobiasd** [comment]
I've tested the following minimal code with your model:

```
from tensorflow.keras.models import load_model

model = load_model("out")
model.summary()
```

But it gives the following error:

`AttributeError: '_UserObject' object has no attribute 'summary'`

---

I suggest you try to find a way to make this work first. Then, the model might also work with frugally-deep.

A Google search for `keras user_object` shows some issues in the TensorFlow repository, which discuss the same error. Maybe you find something helpful there.
