### ISSUE TITLE
fdeep::model initialization and predict seg fault

### ISSUE THREAD

**Issue by richjohnson905-home** [Dobiasd/frugally-deep#275]
`I'm` trying to wrap the fdeep:: model in a wrapper to allow mocking in the unit testing of my code that uses the fdeep::model.  When the app run however I either get a pure virtual function error but mostly a seg fault using clang on macos with fdeep 0.15.1
I suspect the member initialization list in MyWrapper ctor isn't happy but it blows up calling predict.  I can call other member functions on the m_fdeepModel instance but not the predict. 
All works fine if I don't use the wrapper but then my unit tests have to call the real fdeep code which is not ideal.  Is there a way to accomplish this?

```
#include <fdeep/fdeep.hpp>

class MyWrapper {
public:
    MyWrapper(std::string& jsonModelPath);
    fdeep::tensors predict(fdeep::tensors& tensors);
};

MyWrapper::MyWrapper():
    m_fdeepModel(load_model(jsonModelPath))
{
}

fdeep::tensors MyWrapper::predict(fdeep::tensors& t) {
    m_fdeepModel.predict(t);    // blows up with seg fault or libc++abi.dylib: Pure virtual function called!
}

int main()
{
    auto wrapper = MyWrapper("path-to-json");
    const auto result = wrapper.predict(
        {fdeep::tensor(fdeep::tensor_shape(static_cast<std::size_t>(4)),
        std::vector<float>{1, 2, 3, 4})});
    std::cout << fdeep::show_tensors(result) << std::endl;
}
```

**Comment by Dobiasd** [comment]
Hi. :slightly_smiling_face:

While trying to reproduce your runtime error with the minimal example you provided, I noticed that it does not compile. It's missing some things. After fixing these compile-time errors, it works fine, i.e., it not only compiles but also runs without any runtime errors.

Here it is:

```cpp
#include <fdeep/fdeep.hpp>

class MyWrapper {
public:
    MyWrapper(const std::string& jsonModelPath);
    fdeep::tensors predict(const fdeep::tensors& tensors);
    fdeep::model m_fdeepModel;
};

MyWrapper::MyWrapper(const std::string& jsonModelPath) :
m_fdeepModel(fdeep::load_model(jsonModelPath))
{
}

fdeep::tensors MyWrapper::predict(const fdeep::tensors& tensors)
{
    return m_fdeepModel.predict(tensors);
}

int main()
{
    auto wrapper = MyWrapper("model.json");
    const auto result = wrapper.predict(
        {fdeep::tensor(fdeep::tensor_shape(static_cast<std::size_t>(4)),
        std::vector<float>{1, 2, 3, 4})});
    std::cout << fdeep::show_tensors(result) << std::endl;
}
```

In case you still encounter your original problem, please provide an actual [SSCCE](http://sscce.org/) to help me reproduce and fix it.

**Comment by richjohnson905-home** [comment]
Thanks for the reply.  It turns out it was the custom layer initialization giving me trouble in the member initialization.  That double-bracket syntax threw me off.  This example while not runnable without the custom implementation woks when setting up a wrapper with custom layer:
```
#include <fdeep/fdeep.hpp>

class MyWrapper {
public:
    MyWrapper(const std::string& jsonModelPath);
    fdeep::tensors predict(const fdeep::tensors& tensors);
    const fdeep::internal::layer_creators m_custom_creator;
    fdeep::model m_fdeepModel;
};

MyWrapper::MyWrapper(const std::string& jsonModelPath) :
m_custom_creator{{"TensorFlowCustomLayer", fdeep::internal::create_my_layer}},
m_fdeepModel(fdeep::load_model(jsonModelPath, false, NULL, 0.0001, m_custom_creator))
{
}

fdeep::tensors MyWrapper::predict(const fdeep::tensors& tensors)
{
    return m_fdeepModel.predict(tensors);
}

int main()
{
    auto wrapper = MyWrapper("model.json");
    const auto result = wrapper.predict({<custom-input>});
    std::cout << fdeep::show_tensors(result) << std::endl;
}
```
