### ISSUE TITLE
FYI: vcpkg port

### ISSUE THREAD

**Issue by mathisloge** [Dobiasd/frugally-deep#276]
With https://github.com/microsoft/vcpkg/pull/17559 (as soon as the PR is merged) this library will be available in https://github.com/microsoft/vcpkg . 

Usage instructions: 
`vcpkg install frugally-deep`

and then the normal way with cmake 
```cmake
find_package(frugally-deep CONFIG REQUIRED)
target_link_libraries(main PRIVATE frugally-deep::fdeep)
```

**Comment by Dobiasd** [comment]
Cool, thanks! :+1:
