### ISSUE TITLE
Invalid float array format

### ISSUE THREAD

**Issue by melody870322** [Dobiasd/frugally-deep#285]
Hello!

Currently I run following main cpp program:

// main.cpp
#include <fdeep/fdeep.hpp>

int main(){
    const auto net_model = fdeep::load_model("/home/user/QT_project/yolov5/data/checkpoints/fdeep_model.json");
}

I receive following error:

Loading json ... done. elapsed time: 0.291397 s
Building model ... terminate called after throwing an instance of 'std::runtime_error'
  what():  invalid float array format
Aborted (core dumped)

The following is my json file:

https://drive.google.com/file/d/1aBONNQCaJ7MyXD75DkzXL1KshjI6EG29/view?usp=sharing

Thanks and best,

Will

**Comment by Dobiasd** [comment]
Hi Will,

thanks for the report. :slightly_smiling_face:

Could you please upload the `.h5` file of your model too?
(This would enable me to debug if something goes wrong in `convert_model.py` when converting the `.h5` file to `.json`.)

**Comment by melody870322** [comment]
This is my .h5 file:

https://drive.google.com/file/d/16DzoUYyGiqTEQ3F0LaanIt9eD-NXROOQ/view?usp=sharing

Thanks and best！

**Comment by Dobiasd** [comment]
Sorry, but I can't load this model:

```python3
from tensorflow.keras.models import load_model
load_model("cnn_lstm-images.0025-0.006.h5.hdf5")
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tobias/.local/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 201, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
  File "/home/tobias/.local/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 167, in load_model_from_hdf5
    f = h5py.File(filepath, mode='r')
  File "/usr/local/lib/python3.8/dist-packages/h5py/_hl/files.py", line 424, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/usr/local/lib/python3.8/dist-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 6143900, sblock->base_addr = 0, stored_eof = 146976688)
```

The uploaded file (`cnn_lstm-images.0025-0.006.h5.hdf5`) has a size of 6143900 bytes. Is something missing?

(I've tried re-downloading multiple times.)

**Comment by melody870322** [comment]
Sorry！It's my fault！
I uploaded the old version

This should be right

https://drive.google.com/file/d/1Wba6Oih22gCVka6SDGyUyH7YU9tMkqYN/view?usp=sharing

**Comment by Dobiasd** [comment]
Thanks. I was able to [reproduce the problem](https://gist.github.com/Dobiasd/53b4eba05b1ff333e271e450afe5dd64) with this file. :white_check_mark:

I'll investigate and get back to you with the results. :monocle_face:

**Comment by Dobiasd** [comment]
The exception is thrown while trying to load a layer named `conv1/conv`:

![y5uSGYx](https://i.imgur.com/y5uSGYx.png)

It's present in the `.json` file:

```json
                        {
                          "class_name": "Conv2D",
                          "config": {
                            "activation": "linear",
                            "activity_regularizer": null,
                            "bias_constraint": null,
                            "bias_initializer": {
                              "class_name": "Zeros",
                              "config": {}
                            },
                            "bias_regularizer": null,
                            "data_format": "channels_last",
                            "dilation_rate": [
                              1,
                              1
                            ],
                            "dtype": "float32",
                            "filters": 64,
                            "groups": 1,
                            "kernel_constraint": null,
                            "kernel_initializer": {
                              "class_name": "GlorotUniform",
                              "config": {
                                "seed": null
                              }
                            },
                            "kernel_regularizer": null,
                            "kernel_size": [
                              7,
                              7
                            ],
                            "name": "conv1/conv",
                            "padding": "valid",
                            "strides": [
                              2,
                              2
                            ],
                            "trainable": true,
                            "use_bias": false
                          },
                          "inbound_nodes": [
                            [
                              [
                                "zero_padding2d",
                                0,
                                0,
                                {}
                              ]
                            ]
                          ],
                          "name": "conv1/conv"
                        },
```

But it seems to not be an actual part of the model:

```python3
from tensorflow.keras.models import load_model
from tensorflow.keras.utils import plot_model

model = load_model("cnn-lstm.h5")
model.summary()

plot_model(model, to_file='model_plot.png', show_shapes=True, show_layer_names=True)
```

```
Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_3 (InputLayer)         [(None, 16, 100, 100, 3)] 0         
_________________________________________________________________
time_distributed (TimeDistri (None, 16, 3, 3, 640)     5294912   
_________________________________________________________________
time_distributed_1 (TimeDist (None, 16, 640)           0         
_________________________________________________________________
lstm (LSTM)                  (None, 1024)              6819840   
_________________________________________________________________
dense (Dense)                (None, 64)                65600     
_________________________________________________________________
dropout (Dropout)            (None, 64)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 325       
=================================================================
Total params: 12,180,677
Trainable params: 12,120,453
Non-trainable params: 60,224
_________________________________________________________________
```

![quxSZMt](https://i.imgur.com/quxSZMt.png)

I'll try to find out what's happening here.

**Comment by Dobiasd** [comment]
Ah, the "inner" layer of the `TimeDistributed` layer is another model. Oh, I guess frugally-deep currently does not support that. Of course, there should be a better error for this. :grimacing:

**Comment by Dobiasd** [comment]
I vaguely remember, at some point in the past I started trying to implement support for models inside `TimeDistributed` layers, but it was kinda complicated and back then there was no actual need.

Are you interested in giving it a try? :grin:

For now, I've pushed [a commit](https://github.com/Dobiasd/frugally-deep/commit/ea7f02d1a8fd29895ccf4314926906683a67bfef), which makes using `convert_model.py` fail with `AssertionError: Models nested in a TimeDistributed layer are not supported.` to avoid future confusion.

**Comment by Dobiasd** [comment]
> Are you interested in giving it a try?

Never mind, I figured it out. :slightly_smiling_face:

Support for models inside `TimeDistributed` layers was added. Your model [works nicely](https://gist.github.com/Dobiasd/bfe6dfa9c010a6390e47b08d462d8d7c) with the new release `v0.15.7-p0`. :tada:

**Comment by melody870322** [comment]
My model works nicely with the new release, too.

Thanks for your consideration and hard-working.👍
