### ISSUE TITLE
Does this work on Windows? I am having problem to build and  install FunctionalPlus on my Windows PC. Thanks.

### ISSUE THREAD

**Issue by Gabit07** [Dobiasd/frugally-deep#288]
- Before reporting an issue, please make sure you are using the latest versions of frugally-deep, and [the right TensorFlow version](README.md#requirements-and-installation).

- Also check out the [FAQ](../FAQ.md). Maybe your problem/question is common and there already is a canonical answer for it.

- If you have a model and you get unexpected errors when converting it for or when using it with frugally-deep, please upload and post a link to your model file (`.h5`).

- Please try to make the problem reproducible by providing a [SSCCE](http://sscce.org/) as code.

- Feel free to also submit any other feedback, suggestions or questions you might have. :)

**Comment by Dobiasd** [comment]
Hi.

Yes, FunctionalPlus and frugally-deep do work on Windows.

Do you have a specific error message to show?

**Comment by Gabit07** [comment]
> Hi.
> 
> Yes, FunctionalPlus and frugally-deep do work on Windows.
> 
> Do you have a specific error message to show?

Thank you for your quick reply.
I couldn't install FunctionalPlus on my windows PC.
I have this error.
user@DESKTOP-NEBJJJL MINGW64 ~/Documents/PythonCpp/FunctionalPlus/build ((v0.2.14-p0))
$ make && sudo make install
make: *** No targets specified and no makefile found.  Stop.

**Comment by Dobiasd** [comment]
Please check the following link:

https://github.com/Dobiasd/FunctionalPlus/blob/master/INSTALL.md

It shows different ways to install FunctionalPlus you can try.

**Comment by Gabit07** [comment]
> Please check the following link:
> 
> https://github.com/Dobiasd/FunctionalPlus/blob/master/INSTALL.md
> 
> It shows different ways to install FunctionalPlus you can try.

Thank you.
I've just installed it with the help of way 4: using cget.
But how about Eigen?
Can I just download the repo?

**Comment by Gabit07** [comment]
There is also an error when I install frugally-deep with CMake GUI
What should I do?
How can I install it on windows?
![Eror](https://user-images.githubusercontent.com/35021706/126454286-215562ac-c997-4d38-a9ee-a749a7109b03.png)

**Comment by Dobiasd** [comment]
All these libraries are header-only. So for each of them you can just download the repository/code and point your compiler to consider this additional include directory.

On how to do this, please refer to the documentation of your compiler or StackOverflow or similar.

Basically, there is no need to build anything. :)
