### ISSUE TITLE
Working with online trained models

### ISSUE THREAD

**Issue by rpuenter** [Dobiasd/frugally-deep#297]
Hi, 

I am using this library with some success using an offline trained model with a predefined database. But for following work I'd like to be able to update the database during runtime and retrain the model.

So far the solution I came up with involves system calls to a python script where keras functionality is actually called.

If I understand the purpose of frugally-deep, it only implements the actual neural network architecture, it isn't intended to be an API of sorts to every Keras functionality.

So this is not really an issue or feature request, just asking for advice, unless giving an API to the compile and fitting functinalities is straight forward. What do you suggest as the best approach to online training from c++ code avoiding system calls?

Thanks

**Comment by Dobiasd** [comment]
Hi Ricardo,

frugally-deep can only do predictions, i.e., forward passes, on an already trained model. It does not support any training, nor is it intended to be a full drop-in replacement for Keras.

When need to regularly re-train your model used in frugally-deep, you have to do it "normally":
- train and save as `.h5` in Python
- use `convert_model.py` to convert `.h5` to `.json`
- let your C++ application re-load the new `.json` file.

How to best trigger the train/save/convert things depends on your environment. It might be a system call from your C++ application. Or it might be having some scheduled job in your Kubernetes cluster running regularly, etc.

**Comment by rpuenter** [comment]
Hi Dobias,

Thanks, system calls it is then. 

Cheers.
