### ISSUE TITLE
How to convert model with "relu6" layer?

### ISSUE THREAD

**Issue by binlbl** [Dobiasd/frugally-deep#298]
My Keras model uses "rule6" layer , how to change convert_model.py to make the json file? 
and any examples for adding custom layer in fdeep::load_model? 

Thank you very much!

**Comment by Dobiasd** [comment]
It's hard to tell because you're not showing the full code. Probably the print statement is never reached during execution. To find out, either attach a debugger or replace `std::cout << fdeep::show_tensors(result) << std::endl;` with something like `std::cout << "TEST! :)" << std::endl;` and see if that is printed. If not, make sure you're actually recompiling the source, running the correct executable (not another old one), etc. :slightly_smiling_face:

**Comment by binlbl** [comment]
If the print statement is never reached, why it says `Running test 1 of 1 ... done.` and show the elapsed time?

**Comment by Dobiasd** [comment]
> If the print statement is never reached, why it says `Running test 1 of 1 ... done.` and show the elapsed time?

Because `Running test 1 of 1 ... done. elapsed time: 5.871659 s` is printed from inside your call to `fdeep::load_model`.

> Do you have examples for using Frugally-deep in image segmentation? e.g. input image for prediction and output image

The [FAQ](https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md) shows how to use images as input for a model (`fdeep::tensor`) and also how to treat the output of a model (`fdeep::tensor`) as an image.

**Comment by binlbl** [comment]
Dear Sir,
My codes are following your examples, and I don't use the model with "`relu6`" layer, and the model runs correctly in Python. "`convert_model.py`" doesn't give any errors when converting to` .json `. Could you see why nothing is out?  

```
#include <iostream>
#include <fdeep/fdeep.hpp>
#include <opencv2/opencv.hpp>

using namespace fdeep;

int main()
{
	const cv::Mat src = cv::imread("image.png", 1);
	cv::Mat image;
	cv::resize(src, image, cv::Size(608, 416));
	cv::cvtColor(image, image, cv::COLOR_BGR2RGB);
	assert(image.isContinuous());	
	cv::imshow("original", src);
	cv::imshow("resize", image);
	cv::waitKey(0);

	const auto input = fdeep::tensor_from_bytes(image.ptr(),
			static_cast<std::size_t>(image.rows),
			static_cast<std::size_t>(image.cols),
			static_cast<std::size_t>(image.channels()),
			0.0f, 1.0f);

	assert(input.shape().depth_ == 1 || input.shape().depth_ == 3);
	printf("Width is: %zd\n", input.shape().width_);

	const int mat_type = input.shape().depth_ == 1 ? CV_8UC1 : CV_8UC3;
	const cv::Mat out(cv::Size(input.shape().width_, input.shape().height_), mat_type);
	fdeep::tensor_into_bytes(input, out.data, out.rows * out.cols * out.channels());
	cv::imshow("input", out);
	cv::waitKey(0);
	
	const auto model = fdeep::load_model("model.json");
	const auto result = model.predict({ input });
	std::cout << fdeep::show_tensors(result) << std::endl;

}
```

**Comment by Dobiasd** [comment]
It would be easier to help you if you would explain what "nothing is out" means. Is the image window you open empty? Does the process exit with an exception? Does it exit without an exception? Does it hang? Does it print the stuff from `load_model`, but not what you expect from `show_tensors`? Etc.

Try to remove the OpenCV-window stuff, like so:

```cpp
#include <iostream>
#include <fdeep/fdeep.hpp>
#include <opencv2/opencv.hpp>

using namespace fdeep;

int main()
{
    const cv::Mat src = cv::imread("image.png", 1);
    cv::Mat image;
    cv::resize(src, image, cv::Size(608, 416));
    cv::cvtColor(image, image, cv::COLOR_BGR2RGB);
    assert(image.isContinuous());   
    
    const auto input = fdeep::tensor_from_bytes(image.ptr(),
            static_cast<std::size_t>(image.rows),
            static_cast<std::size_t>(image.cols),
            static_cast<std::size_t>(image.channels()),
            0.0f, 1.0f);

    assert(input.shape().depth_ == 1 || input.shape().depth_ == 3);
    printf("Width is: %zd\n", input.shape().width_);

    const int mat_type = input.shape().depth_ == 1 ? CV_8UC1 : CV_8UC3;
    const cv::Mat out(cv::Size(input.shape().width_, input.shape().height_), mat_type);
    fdeep::tensor_into_bytes(input, out.data, out.rows * out.cols * out.channels());
    
    const auto model = fdeep::load_model("model.json");
    const auto result = model.predict({ input });
    std::cout << fdeep::show_tensors(result) << std::endl;
}
```

Also, make sure, 608x416x1 is the actual image format your model expects. However, `model.predict` would raise an exception if it is called with a wrong input shape.

---

But actually, your current problems have nothing to do with frugally-deep as a library, but, at least that's my impression, with the fact that you're missing some basics regarding (C++) programming in general. I.e., you don't even know where your application stops executing, etc. And I can not teach you all these things. I suggest you find some other experienced dev to help you and only post here if you have an actual problem with frugally-deep.

**Comment by binlbl** [comment]
The result I stated before, doesn't go to the std::cout: 
```
Loading json ... done. elapsed time: 0.784614 s
Building model ... done. elapsed time: 2.151824 s
Running test 1 of 1 ... done. elapsed time: 5.871659 s
```

**Comment by Dobiasd** [comment]
If you'd send me the model file and the image file, I could test. So I can just continue to guess.

Does the application **hang** in `model.predict` or does it **exit**?
Please try to put an incorrect input shape into the model. Different target size for `cv::resize`. `model.predict` should throw an exception. Do you see the error (exception message)? If not, find out how to do this in your environment. Maybe IDE settings. (I don't know what IDE you're using.)

If you don't see the error, try with this minimal example:

```cpp
#include <stdexcept>
int main()
{
    throw std::runtime_error("hello exception");
}
```

If you are sure you are able to see exceptions, and you're sure the application is not exiting during `model.predict`, but hanging, check if it's still doing something (CPU usage of this process). Attach a debugger, pause the process, and see where it is. Etc. All this basic debugging stuff.

Maybe `model.predict()` just takes very long. Make sure you have enabled compiler optimizations. (see [here](https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#why-is-my-prediction-roughly-100-times-slower-in-c-as-in-python))

If these things did not help, please send over (upload somewhere and post the link) the model and the image file, so I can reproduce the error. All this guessing does not feel very efficient. :neutral_face:

**Comment by binlbl** [comment]
In Debug mode for Visual C++, it did throw an "`abort()`", but didn't state any reason.
In release mode, no hang in and exit, didn't go to the"`std::out`" line. 

Thank you very much for your help, I will take a weekend break now and see what I can do next week.

**Comment by Dobiasd** [comment]
Sorry, I don't understand what you mean by "no hang in and exit".

Does it hang? Or does it exit? It must be one of the two.

If it exits, there likely is an exception thrown.

Again, please make sure you're able to see exceptions like the following when thrown:

```cpp
#include <stdexcept>
int main()
{
    throw std::runtime_error("hello exception");
}
```

Since you don't even tell me, which IDE you're using, I can't explain to you how to do this.

So, three tasks for you:
- Make sure you can see exceptions like in the minimal example above.
- Tell me exactly if it hangs or exits.
- If you then still did not solve it, please upload the model file and the image file to post here.

Please actually do these things before posting again. Otherwise, it does not make any sense to continue this way, and I'd have to ban you from posting in this repository.

**Comment by binlbl** [comment]
Thank you very much! it doesn't hang
![image](https://user-images.githubusercontent.com/66796464/131228360-0da31560-3dd4-454d-9f47-bcd634f8f0cc.png)
I am using Visual studio 2017 (Visual C++), I will try to see how to show the exceptions.
It did show the exception in Debug mode, but state no reason.

**Comment by Dobiasd** [comment]
> it doesn't hang

Ok, good to know. :+1:

Once you can view exception messages, you should find out what happens. Ideally, you can even get a stack trace.

In case there is no exception eleven, you can check if the process exited gracefully or with an error like so (in the terminal after executing the application):

```batch
echo %errorlevel%
```

When there is no exception, maybe your PC is going out of memory during this step. :shrug:

Again, upload the model and image, and I could check myself.
