### ISSUE TITLE
My model runs in python and runs in fdeep, the results are not the same.

### ISSUE THREAD

**Issue by SEEYOU20** [Dobiasd/frugally-deep#303]
Hello, when I use fdeep to load my model, I found that the running result is different from when I run it in python. The keras model used is [here](https://github.com/SEEYOU20/keras_model).
Run in python.
![image](https://user-images.githubusercontent.com/36726231/132990206-c9aa0557-32e2-4c16-8e6d-fb12d9e7b6c0.png)
Run in c++.
![image](https://user-images.githubusercontent.com/36726231/132990313-0cd7032a-d77b-4781-a302-2f6dcde972f9.png)

**Comment by Dobiasd** [comment]
Hi, and thanks for the good and clear problem description.

However, I'm unable to reproduce your issue.

When using your model with input `[0.5, 0.5]` in frugally-deep, I get the same results as you get in Python, i.e., `0.5069`.

I'm invoking the model as follows:

```cpp
#include "fdeep/fdeep.hpp"
int main()
{
    const auto model = fdeep::load_model("my_model_relu.json");
    const auto input_values = std::vector<float>{0.5, 0.5};
    const auto input_shape = fdeep::tensor_shape(1, 2);
    const auto input = fdeep::tensor(input_shape, input_values);
    const fdeep::tensors inputs = {input};
    const auto result = model.predict(inputs);
    std::cout << fdeep::show_tensors(result) << std::endl;
}
```

Output:

```
Loading json ... done. elapsed time: 0.001784 s
Building model ... done. elapsed time: 0.001331 s
Running test 1 of 1 ... done. elapsed time: 0.000087 s
Loading, constructing, testing of my_model_relu.json took 0.003366 s overall.
[[[[[[0.5069]]]]]]
```

Here is the full `Dockerfile` for this test:
https://gist.github.com/Dobiasd/a7124a964ed117840fc12196655f293e

**Comment by SEEYOU20** [comment]
Thank you very much for your recovery. After I tried it, I found that using the code you provided can get the same result. I found that if I use model.predict_single_output() to make predictions, then I cannot get the results I want, and sometimes errors will be reported.
![image](https://user-images.githubusercontent.com/36726231/133022338-d119b060-052d-4be1-a6e3-69e41922ffc1.png)
Finally, I would like to ask if fdeep provides a function to convert the result of fdeep::show_tensors(result) into a float for use.

**Comment by Dobiasd** [comment]
When using `predict_single_output` it should not just error *sometimes* with your model, but every time. And there is a message attached to the exception, your screenshot just does not show it. It is `Invalid position rank for tensor`.

The reason for this is, `predict_single_output` only works with models outputting exactly one value with shape `(1)`. Your model outputs shape `(1, 1)`, so it has one superfluous dimension. Similar to the input, i.e., your model takes `(1, 2)`, while `(2)` would suffice.

Code to reproduce this error:

```cpp
#include "fdeep/fdeep.hpp"
int main()
{
    const auto model = fdeep::load_model("my_model_relu.json");
    const auto input_values = std::vector<float>{0.5, 0.5};
    const auto input_shape = fdeep::tensor_shape(1, 2);
    const auto input = fdeep::tensor(input_shape, input_values);
    const fdeep::tensors inputs = {input};
    const auto result_value = model.predict_single_output(inputs);
    std::cout << result_value << std::endl;
}
```

Output:

```
Loading json ... done. elapsed time: 0.003434 s
Building model ... done. elapsed time: 0.003737 s
Running test 1 of 1 ... done. elapsed time: 0.000264 s
Loading, constructing, testing of my_model_relu.json took 0.008013 s overall.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Invalid position rank for tensor
```

Here is the full `Dockerfile` for this: https://gist.github.com/Dobiasd/50ec5791a3442661da3fae6ef51ff859

I highly recommend finding out how to view messages of uncaught exceptions like this in your development environment. It will help you solve similar problems in the future. :slightly_smiling_face: 

---

So you have two options to get the output value of your model as `float`:

1) Drop the superfluous output dimension in your model architecture and use `predict_single_output`.

or

2) Extract the value from the output tensors using `model.predict(...).front().to_vector().front()`.

Full code:

```cpp
#include "fdeep/fdeep.hpp"
int main()
{
    const auto model = fdeep::load_model("my_model_relu.json");
    const auto input_values = std::vector<float>{0.5, 0.5};
    const auto input_shape = fdeep::tensor_shape(1, 2);
    const auto input = fdeep::tensor(input_shape, input_values);
    const fdeep::tensors inputs = {input};
    const auto result = model.predict(inputs);
    const float result_value = result.front().to_vector().front();
    std::cout << result_value << std::endl;
}
```

Output:

```
Loading json ... done. elapsed time: 0.001352 s
Building model ... done. elapsed time: 0.000966 s
Running test 1 of 1 ... done. elapsed time: 0.000071 s
Loading, constructing, testing of my_model_relu.json took 0.002543 s overall.
0.506895
```

Dockerized version: https://gist.github.com/Dobiasd/c330d1c472a115c69c33f1fa09c567a1
