### ISSUE TITLE
Is the library support output image? I'd like to use a Autoencoder trained keras model with the c++ using this library! thanks.

### ISSUE THREAD

**Issue by besmaGuesmi** [Dobiasd/frugally-deep#304]
Hello

I converted an input image to a tensor and then I applied the model. predict on the tensor, the result of the model. predict is multiple tensors, what I want to do is to convert the vector of tensors to image as output because I'm using the Autoencoder model.

**Comment by Dobiasd** [comment]
Hi,

["How to convert an fdeep::tensor to an (OpenCV) image and back?" in the FAQ](https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#how-to-convert-an-fdeeptensor-to-an-opencv-image-and-back) should answer your question. :slightly_smiling_face:

**Comment by besmaGuesmi** [comment]
Yes I checked it and everything works fine, Thank you!
