### ISSUE TITLE
How to convert an output from model.predict to an std::vector<std::vector<float>>?

### ISSUE THREAD

**Issue by createmomo** [Dobiasd/frugally-deep#309]
I tried to use result.to_vector(), but the output data type did not have such function.

Is there a way to convert the output of model.predict to the std::vector<float>? Thank you very much!

Update:
I think I found a temporary solution, but I am not sure if this is an elegant solution. :) 
```c++
    result = model.predict(...)

    const auto 1d_cpp_vector = result.front().to_vector(); 
    const auto num_of_rows = 3;
    const auto num_of_cols = 1d_cpp_vector.size() / num_of_rows;

    vector<vector<float>> 2d_cpp_vector(num_of_rows);

    for (int i = 0; i < (int)num_of_rows; i++){       
        vector<float> & inner_vector = 2d_cpp_vector[i];

        for(int j = 0; j < (int)num_of_cols; j++){
            inner_vector.push_back(1d_cpp_vector[num_of_cols * i + j]);
        }
    }
```
Is there a better way to convert the result to a single vector<vector<float>> matrix in c++?

**Comment by Dobiasd** [comment]
To split an `std::vector<T>` into an `std::vector<std::vector<T>>`, you could use `fplus::split_every`. :slightly_smiling_face:

In your case:

```cpp
const auto result = model.predict(...);
const auto rows = fplus::split_every(num_of_cols, result.front().to_vector());
```
