### ISSUE TITLE
Support Reshape layer

### ISSUE THREAD

**Issue by thefiddler** [Dobiasd/frugally-deep#31]
I am preparing a PR to add support for the Keras Reshape layer.

One question: should the conversion of the target_shape from HWC to CHW be done in the convert_model script, or in the C++ implementation of `reshape_layer`?

**Comment by Dobiasd** [comment]
The HWC-to-CHW should happen in `convert_model.py`, since for example the convolution filter weights [also are converted there](https://github.com/Dobiasd/frugally-deep/blob/master/keras_export/convert_model.py#L30).

**Comment by Dobiasd** [comment]
How's it going? Did any questions or problems arise yet?
