### ISSUE TITLE
Compilation Failure Using Beagle Bone Black

### ISSUE THREAD

**Issue by jehanyang** [Dobiasd/frugally-deep#311]
I am having an issue with compiling my code that uses fdeep on the Beagle Bone Black in Debian. It seems to work fine when I am compiling fdeep by itself as a library on the Beagle Bone, but when I try to compile my code that ```#includes fdeep/fdeep```, the compilation fails after running for a long time (> 1 hour). I am using ```catkin_make```, the ROS build function, for compilation. 

My code compiles fine on my desktop in Linux. I was wondering if there would be any reason that it doesn't work on the Beagle Bone Black? It seems like the Beagle Bone Black runs out of memory during compilation, as when I run ```free -m```, the free memory gets smaller and smaller as the compilation time goes on.

**Comment by Dobiasd** [comment]
Hi, I don't have any experience with the Beaglebone Black, but I guess you already found the problem, i.e., the compiler going OOM. Maybe it's the heavy template stuff in the dependencies (Eigen, FunctionalPlus, etc.) that causes the compiler to need so much mem.

Maybe there is a never version of your compiler available, which might help? Or maybe there is some flag you can provide to trade memory usage against some other property (throughput or whatever)? Just guessing here. :grin:
