### ISSUE TITLE
Add frugally-deep version compatible with TensorFlow 2.7.0 to Conan.io

### ISSUE THREAD

**Issue by richjohnson-wwt** [Dobiasd/frugally-deep#313]
We need to depend on a frugally deep in conan.io that is compatible with TensorFlow 2.7.0.  Is it possible to get an updated version that meets this criteria added to Conan.io? Looks like maybe that would be frugally-deep/0.15.13-p0.

The latest today in conan is frugally-deep/0.15.1-p0.

**Comment by Dobiasd** [comment]
Some time ago, the responsibility was moved out of the `Dobiasd/frugally-deep` repo, and into the external `conan-io/conan-center-index`:
- https://github.com/Dobiasd/frugally-deep/issues/262
- https://github.com/Dobiasd/frugally-deep/issues/270
- https://github.com/Dobiasd/frugally-deep/pull/266
- https://github.com/conan-io/conan-center-index/issues/3956
- https://github.com/conan-io/conan-center-index/pull/3993

So in theory, everybody can put the latest frugally-deep version to conan.io.

Are you interested in doing this, i.e., creating a pull request in the `conan-io/conan-center-index` repo? If not, I'll try to do it in a timely manner. Please let me know which way you prefer. :slightly_smiling_face:

**Comment by richjohnson-wwt** [comment]
Reviewing the links you provided, I am happy to let you do it in a timely manner as it is out of my comfort zone.  I would have been interested if I saw a clear path forward.

**Comment by Dobiasd** [comment]
Ok, I'll let you know when done.

**Comment by Dobiasd** [comment]
The pull request for updating FunctionalPlus in conan.io is waiting for approval: https://github.com/conan-io/conan-center-index/pull/8631

As soon as this one is merged, I'll create second one, adding the latest frugally-deep version (depending on the latest FunctionalPlus version).

**Comment by richjohnson-wwt** [comment]
Thanks, I am keeping my eye on this page for the update to show up.  I'll update here when it does.
https://conan.io/center/frugally-deep?tab=overview

**Comment by Dobiasd** [comment]
Yes, it will show up there.

**Comment by Dobiasd** [comment]
There it is. ✅
