### ISSUE TITLE
Is there a function to extract convolution kernels and weights into vector?

### ISSUE THREAD

**Issue by DylanWangWQF** [Dobiasd/frugally-deep#315]
After loading the model `const auto model = fdeep::load_model("../readme_example_model.json");`, is there a function to extract convolution kernels and weights into vectors, such as `vector<vector<float>>`. etc.. ? 

I need the kernels and weights to be stored into `vector<vector<float>>` so that I can use them in my applications.
But it seems that all of these `parameters` are private members in `model.hpp`.

For example, given such CNN structure (MNIST dataset):
<img width="406" alt="截屏2022-01-15 17 27 52" src="https://user-images.githubusercontent.com/26397284/149608790-c10fe4ec-0122-4883-b274-f03ab45c1452.png">

I want to load data/weights of each layer into vectors for following computation.

**Comment by Dobiasd** [comment]
Hi,

frugally-deep hides the internals of a model on purpose for the following reason:
- If these things would not be `private` they would be part of the library's API.
- This would mean, users (e.g., you :slightly_smiling_face:) would start to use it and depend on it.
- And now, even if I maybe don't need to document this feature, I would need to maintain it, i.e., make sure it's still available in future versions, etc.

This kind of additional responsibility would limit my future freedom to refactor the internals of the library without breaking the API. So I try to keep the "surface" of the library as small as possible.

Also, I feel, a feature like that would not really fit the intention of the library, and it could open pandora's box. Many other features would now be (rightfully so) requested.

But of course, I do understand your need. So let's try to find a solution. Some options that come to my mind are the following:
- Load the (original `.h5`) model in Python, get the layer weights there, and export them for your C++ application.
- Load the `.json` model in C++ in your user-land code and get the (base64-encoded) layer weights from there.
- Do something "crazy" like `#define private public` ([1](https://stackoverflow.com/questions/27778908/define-private-to-public-in-c), [2](https://stackoverflow.com/questions/2726204/c-preprocessor-define-ing-a-keyword-is-it-standards-conforming)) before `#include "fdeep/fdeep.hpp"`. (downside: maybe undefined behavior)
- Edit `model.hpp` to your needs. (downside: updating to a later version is annoying)

Would any of those be feasible for your use case?

**Comment by DylanWangWQF** [comment]
Hi, @Dobiasd , many thanks for your reply!
I guess the first method would be more suitable for me since I don't care too much about the details of processing params of each layer.
