### ISSUE TITLE
json file from python resulted in "type must be string, but is null"

### ISSUE THREAD

**Issue by mathbird** [Dobiasd/frugally-deep#316]
I ran the mini test readme_example_main.py  you provided, but output .json directly from python. When the "readme_example_main" read the file, however, it said "**type must be string, but is null**" as follows. 

do you know how to fix it?

```
import numpy as np
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model

inputs = Input(shape=(4,))
x = Dense(5, activation='relu')(inputs)
predictions = Dense(3, activation='softmax')(x)
model = Model(inputs=inputs, outputs=predictions)
model.compile(loss='categorical_crossentropy', optimizer='nadam')

model.fit(
    np.asarray([[1, 2, 3, 4], [2, 3, 4, 5]]),
    np.asarray([[1, 0, 0], [0, 0, 1]]), epochs=10)

model.save('keras_model.h5', include_optimizer=False)


# serialize model to JSON
model_json = model.to_json()
with open("model_direct.json", "w") as json_file:
    json_file.write(model_json)
```

 
 ===============================================================================
 1.cpp:11:
 TEST CASE:  readme_example_main, main
 
 1.cpp:11: ERROR: test case THREW exception: [json.exception.type_error.302] type must be string, but is null
 
 ===============================================================================
 [doctest] test cases: 1 | 0 passed | 1 failed | 0 skipped
 [doctest] assertions: 0 | 0 passed | 0 failed |
 [doctest] Status: FAILURE!_
 
 

```
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest/doctest.h"
#include <fdeep/fdeep.hpp>

TEST_CASE("readme_example_main, main")
{

    //const auto model = fdeep::load_model("fdeep_model.json");
    //const auto model = fdeep::load_model("mymodel0.json");
    const auto model = fdeep::load_model("model_direct.json");
    const auto result = model.predict(
        {fdeep::tensor(fdeep::tensor_shape(static_cast<std::size_t>(4)),
        fdeep::float_vec{1, 2, 3, 4})});
    std::cout << fdeep::show_tensors(result) << std::endl;
}

```

**Comment by Dobiasd** [comment]
Hi. :slightly_smiling_face:

Here is a `Dockerfile` showing that it normally works:

```Dockerfile
FROM python:3.9

RUN apt-get update
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y build-essential cmake

RUN pip3 install tensorflow==2.7.0

RUN apt-get remove --purge -y cmake
RUN pip install cmake --upgrade

RUN git clone -b 'v0.2.18-p0' --single-branch --depth 1 https://github.com/Dobiasd/FunctionalPlus && cd FunctionalPlus && mkdir -p build && cd build && cmake .. && make && make install
RUN git clone -b '3.4.0' --single-branch --depth 1 https://gitlab.com/libeigen/eigen.git && cd eigen && mkdir -p build && cd build && cmake .. && make && make install && ln -s /usr/local/include/eigen3/Eigen /usr/local/include/Eigen
RUN git clone -b 'v3.10.5' --single-branch --depth 1 https://github.com/nlohmann/json && cd json && mkdir -p build && cd build && cmake -DBUILD_TESTING=OFF .. && make && make install
RUN git clone -b 'v0.15.13-p0' --single-branch --depth 1 https://github.com/Dobiasd/frugally-deep && cd frugally-deep && mkdir -p build && cd build && cmake .. && make && make install
RUN git clone -b '2.3.5' --single-branch --depth 1 https://github.com/onqtam/doctest.git && cd doctest && mkdir -p build && cd build && cmake .. -DDOCTEST_WITH_TESTS=OFF -DDOCTEST_WITH_MAIN_IN_STATIC_LIB=OFF && make && make install && cd ../..

WORKDIR /frugally-deep

RUN python3 ./test/readme_example_generate.py
RUN python3 ./keras_export/convert_model.py readme_example_model.h5 readme_example_model.json

WORKDIR /frugally-deep/test
RUN g++ -std=c++14 -O3 ./readme_example_main.cpp -o ./readme_example_main
RUN ./readme_example_main
```

Output:

```
Loading json ... done. elapsed time: 0.000083 s
Building model ... done. elapsed time: 0.000213 s
Running test 1 of 1 ... done. elapsed time: 0.004602 s
Loading, constructing, testing of ../readme_example_model.json took 0.004996 s overall.
[[[[[[0.5679, 0.3584, 0.0737]]]]]]
===============================================================================
[doctest] test cases:      1 |      1 passed |      0 failed |      0 skipped
[doctest] assertions:      0 |      0 passed |      0 failed |
[doctest] Status: SUCCESS!
```

My guess is, you have some old versions installed. Please make sure you're not only using the latest version of the C++ part from frugally-deep, but also the latest `convert_model.py`.

In case that does not help, please check your versions of TensorFlow and Keras.

**Comment by mathbird** [comment]
Hi, Thanks for reply.

My question is why the .json model file directly from the following python code (I added ) "readme_example_generate.py" in  could not be read into c++ test.  

If I generated .h5, and then converted it to  a .json file (called B.json) using "convert_model.py", this json file B.json could be read correctly in "readme_example_main"


**model_json = model.to_json()
with open("model_direct.json", "w") as json_file:
    json_file.write(model_json)**

**Comment by Dobiasd** [comment]
Ah, you're trying to write your Keras model from Python directly as a `json` file, and load that with frugally-deep in C++. That can't work. The content is totally different. To see, just open both `json` files in a text editor. :slightly_smiling_face:

**Comment by mathbird** [comment]
I developed a simple model, and saved it as .h5 file. and then converted it as .json format. but c++ test show the error " **type must be string, but is object**".  The code and outputs are attached. any idea?

```
import numpy as np
import tensorflow as tf

# ........................................... 
# Make data.
# ........................................... 

A=1000.0
alpha=0.25

X0 = np.arange(0.0, 1.0+0.04, 0.04)
dt = X0*X0*X0
X=200.0*dt
Y=10.0-20.0*dt 

X_len, Y_len = len(X), len(Y)
num=X_len*Y_len

X, Y = np.meshgrid(X, Y)
Z = A*np.exp(-alpha*(X-Y))

# ........................................... 
# Neural network
# increasing the middle layers can improve 
# the accuracy of the predicted data 
# using the same epoches.
# ........................................... 

act = tf.keras.layers.ReLU() # Rectified Linear Unit (ReLU)
nn_sv = tf.keras.models.Sequential([
  tf.keras.layers.Dense(100, activation=act, input_shape=(2,)),
  tf.keras.layers.Dense(100, activation=act),
  tf.keras.layers.Dense(100, activation=act),
  tf.keras.layers.Dense(1,activation='linear')])

# Loss function
loss_sv = tf.keras.losses.MeanSquaredError()
optimizer_sv = tf.keras.optimizers.Adam(learning_rate=0.001)
nn_sv.compile(optimizer=optimizer_sv, loss=loss_sv)

# ........................................... 
# Training
# ........................................... 
Z_values = Z.flatten() 


#  use coodinate (x,y) as input
XY=list(zip(X.flatten(), Y.flatten()))
XY_T= np.reshape(XY, (num,2))
results_sv = nn_sv.fit(XY_T, Z_values, epochs=100, batch_size=32, verbose=1)

nn_sv.save("mymodel0.h5")

```


>> python ..\frugally-deep-master\keras_export\convert_model.py mymodel0.h5 mymodel0.json
loading mymodel0.h5
Forward pass took 0.125401 s.
Forward pass took 0.038104 s.
Forward pass took 0.036954 s.
Starting performance measurements.
Forward pass took 0.037125 s.
Forward pass took 0.03714 s.
Forward pass took 0.035745 s.
Forward pass took 0.042407 s.
Forward pass took 0.037083 s.
Forward pass took 0.0379 s on average.
Converting model architecture.
Converting model weights.
Done converting model weights.
Calculating model hash.
Model conversion finished.
writing mymodel0.json


[doctest] doctest version is "2.4.5"
[doctest] run with "--help" for options
Loading json ... done. elapsed time: 0.004288 s
Building model ... ===============================================================================
1.cpp:11:
TEST CASE:  readme_example_main, main

1.cpp:11: ERROR: test case THREW exception: [json.exception.type_error.302] type must be string, but is object

===============================================================================
[doctest] test cases: 1 | 0 passed | 1 failed | 0 skipped
[doctest] assertions: 0 | 0 passed | 0 failed |
[doctest] Status: FAILURE!

**Comment by Dobiasd** [comment]
Oh, interesting. Thanks for the very good report and code example. :+1:

The exception is thrown when frugally-deep tried to load the activation layer.

You can fix this by replacing this part of your code

```python3
act = tf.keras.layers.ReLU() # Rectified Linear Unit (ReLU)
nn_sv = tf.keras.models.Sequential([
  tf.keras.layers.Dense(100, activation=act, input_shape=(2,)),
  tf.keras.layers.Dense(100, activation=act),
  tf.keras.layers.Dense(100, activation=act),
```

with the following:

```python3
nn_sv = tf.keras.models.Sequential([
  tf.keras.layers.Dense(100, activation='relu', input_shape=(2,)),
  tf.keras.layers.Dense(100, activation='relu'),
  tf.keras.layers.Dense(100, activation='relu'),
```

But I admit, the error message could be a lot better. :grimacing: I'll improve the checks in `convert_model.py`, such that already the conversion step fails in that case, and the user sees a meaningful error message. :office_worker:

**Comment by Dobiasd** [comment]
Ok, I adjusted the model loading to help diagnose such situations much more easily in the future, i.e., there will now be an `std::runtime_error("Layer activation must be a string.")`.

Thanks again for the report. It helped improve the user experience of frugally-deep. :+1:

**Comment by mathbird** [comment]
Thanks a lot. It worked!

**Comment by mathbird** [comment]
@Dobiasd , I met the following error sometimes, but value = target. any idea?

1.cpp:11:
TEST CASE:  readme_example_main, main

1.cpp:11: ERROR: test case THREW exception: test failed: output=0 pos=0,0,0 value=1043.69 target=1043.69

[doctest] test cases: 1 | 0 passed | 1 failed | 0 skipped
[doctest] assertions: 0 | 0 passed | 0 failed |
[doctest] Status: FAILURE!

**Comment by Dobiasd** [comment]
Please have a look at ["What to do when loading my model with frugally-deep throws an `std::runtime_error` with test failed?" in the FAQ](https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#what-to-do-when-loading-my-model-with-frugally-deep-throws-an-stdruntime_error-with-test-failed). In case this does not help, I'd need to `h5` version of the model too.

---

Btw., you don't need to use doctest, you can just write a normal main function, i.e., instead of this:

```cpp
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>
#include <fdeep/fdeep.hpp>

TEST_CASE("readme_example_main, main")
{
    fdeep::load_model ...
}
```

you can to that:

```cpp
#include <fdeep/fdeep.hpp>

int main()
{
    fdeep::load_model ...
}
```

**Comment by mathbird** [comment]
how to rewrite the following code, and define an input tensor vector, and call predict just one time? 


```
    //inputs.insert(0, sizeof(fdeep::tensor),  fdeep::tensor(fdeep::tensor_shape(2),fdeep::float_vec{0.0,  5.0}) );

    fdeep::tensors result = model.predict({
        fdeep::tensor(
          fdeep::tensor_shape(2),
          fdeep::float_vec{0.0,  5.0}
         )
      });
    const auto result1 = model.predict({
        fdeep::tensor(
          fdeep::tensor_shape(2),
          fdeep::float_vec{0.0, -5.0}
         )
      });

    const auto result2 = model.predict({
        fdeep::tensor(
          fdeep::tensor_shape(2),
          fdeep::float_vec{0.0, 0.0}
         )
      });

    std::cout << fdeep::show_tensors(result) << std::endl;
    std::cout << fdeep::show_tensors(result1) << std::endl;
    std::cout << fdeep::show_tensors(result2) << std::endl;

```

**Comment by Dobiasd** [comment]
```cpp
const std::vector<fdeep::tensors> inputs = {
    {{fdeep::tensor_shape(2), fdeep::float_vec{0.0,  5.0}}},
    {{fdeep::tensor_shape(2), fdeep::float_vec{0.0, -5.0}}},
    {{fdeep::tensor_shape(2), fdeep::float_vec{0.0,  0.0}}}
    };
    
const auto results = model.predict_multi(inputs, true); // Or false if you want it to be single threaded.

for (const auto result: results) {
    std::cout << fdeep::show_tensors(result) << std::endl;
}
```

**Comment by mathbird** [comment]
Thanks, any fdeep function can release the number from a  tensor? or it is the user's job?

**[[[[[[140.4323]]]]]] --> 140.4323**

**Comment by Dobiasd** [comment]
Either do it on your own using `fdeep::tensor::get(fdeep::tensor_pos(0)` or `fdeep::tensor::to_vector` (then `.at(...`)), or use `fdeep::model::predict_single_output` to let the library do it for you.
