### ISSUE TITLE
Broadcast semantics for elementwise ops

### ISSUE THREAD

**Issue by thefiddler** [Dobiasd/frugally-deep#32]
Keras supports broadcasting on elementwise op layers (e.g. Add, Multiply, etc). For example an elementwise op can receive inputs where each dimension has the same size **or** a size of 1.

I am opening this issue to investigate what would be the best way to support this kind of broadcasting.

**Comment by Dobiasd** [comment]
Like [`concatenate`](https://keras.io/layers/merge/#concatenate) these are "merge layers", I think.

So it should be feasible to implement them in the same way `concatenate` is already implemented. If you are interested in doing this and sending a PR, here are the needed steps (similar to the steps adding [LSTM layer](https://github.com/Dobiasd/frugally-deep/issues/8):

- use the layer type in question in `get_test_model_small` in `keras_export/generate_test_models.py`
- add an export function for the layer (if needed) to `keras_export/convert_model.py`
- add the new layer class to `include/fdeep/layers` (actual implementation), `concatenate_layer.hpp` would probably be a good example for this
- add a create function (deserialization from JSON) to `include/fdeep/import_model.hpp`
- also in `include/fdeep/import_model.hpp`, extend the `unordered_map` `creators` in `create_layer` to also dispatch to your new create function.

When you have all this, your new layer type will automatically be tested (i.e. its results compared with the Keras implementation) in the unit tests. You can run the tests locally as described in README.md or by creating a pull request here in this repo and letting Travis CI do it.

If any questions arise, just let me know. :)
