### ISSUE TITLE
How can I speed up the prediction rate of the frugally-deep library?

### ISSUE THREAD

**Issue by SEEYOU20** [Dobiasd/frugally-deep#321]
hello, how can i make the prediction rate of frugally-deep library faster. In my application scenario, I tested the approximate time of using the frugally-deep library to predict a time from tens to more than 100 milliseconds. I would like to shorten this forecast time, how can I improve it?

**Comment by Dobiasd** [comment]
In most cases, frugally-deep won't be faster than using TensorFlow directly.

If you see frugally-deep being significantly slower than TensorFlow in your use-case, please check out the following parts of the [FAQ](https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md):
- [Why is my prediction roughly 100 times slower in C++ as in Python?](https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#why-is-my-prediction-roughly-100-times-slower-in-c-as-in-python)
- [Why is my prediction roughly 10 times slower in C++ as in Python?](https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#why-is-my-prediction-roughly-10-times-slower-in-c-as-in-python)
- [Why is my prediction roughly 4 times slower in C++ as in Python?](https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#why-is-my-prediction-roughly-4-times-slower-in-c-as-in-python)
- [Why is my prediction roughly 2 times slower in C++ as in Python?](https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#why-is-my-prediction-roughly-2-times-slower-in-c-as-in-python)

**Comment by SEEYOU20** [comment]
If I want to speed up, can I only choose the conversion method on the tensorflow official website? Or that method is not much faster.

**Comment by Dobiasd** [comment]
> If I want to speed up, can I only choose the conversion method on the tensorflow official website?

Which conversion method are you referring to?

> Or that method is not much faster.

Trying it out for your special use-case might be the best way to find out! :construction_worker_man:
