### ISSUE TITLE
hi thanks for your great work , I used all the same version tensorflow 2.6 but when load model ,there is error Loading json ... done. elapsed time: 0.037813 s Building model ... done. elapsed time: 0.086107 s Running test 1 of 1 ... done. elapsed time: 0.029230 s terminate called after throwing an instance of 'std::runtime_error'   what():  test failed: output=0 pos=0,0,3 value=0.246228 target=0.246346

### ISSUE THREAD

**Issue by Hongpeng1992** [Dobiasd/frugally-deep#322]
- Before reporting an issue, please make sure you are using the latest versions of frugally-deep, and [the right TensorFlow version](README.md#requirements-and-installation).

- Also check out the [FAQ](../FAQ.md). Maybe your problem/question is common and there already is a canonical answer for it.

- If you have a model and you get unexpected errors when converting it for or when using it with frugally-deep, please upload and post a link to your model file (`.h5`).

- Please try to make the problem reproducible by providing a [SSCCE](http://sscce.org/) as code.

- Feel free to also submit any other feedback, suggestions or questions you might have. :)

**Comment by Dobiasd** [comment]
> hi thanks for your great work , I used all the same version tensorflow 2.6 but when load model ,there is error Loading json ... done. elapsed time: 0.037813 s Building model ... done. elapsed time: 0.086107 s Running test 1 of 1 ... done. elapsed time: 0.029230 s terminate called after throwing an instance of 'std::runtime_error' what(): test failed: output=0 pos=0,0,3 value=0.246228 target=0.246346

Please check out this part of the FAQ: https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#what-to-do-when-loading-my-model-with-frugally-deep-throws-an-stdruntime_error-with-test-failed
