### ISSUE TITLE
Runtime error load_model

### ISSUE THREAD

**Issue by nbiresev** [Dobiasd/frugally-deep#323]
const auto mymodel = fdeep::load_model("model.json");

Here i am getting the following exception:
Exception thrown at 0x00007FFC3E314F69 in PADGui.exe: Microsoft C++ exception: std::runtime_error at memory location 0x0000008CD15F9A28.

I am using 2.8 tensorflow and frugally-deep up to date. Able to build code, tried using different models always the same. Tried using absolute path of model. 
[eoImages.zip](https://github.com/Dobiasd/frugally-deep/files/8169696/eoImages.zip)

I was following this tutorial https://m-shaeri.ir/blog/tensorflow-keras-train-in-python-predict-use-in-c-plus/
it offers all include files which i downloaded and added include path to my project so that it can build like in tutorial.

**Comment by Dobiasd** [comment]
Hi,

using your model file, I was able to reproduce the problem. `fdeep::load_model("modelEOIMages.json")` throws an exception:

```
Loading json ... done. elapsed time: 0.176239 s
Building model ... terminate called after throwing an instance of 'std::runtime_error'
  what():  unknown layer type: TFOpLambda
```

You very likely have the same error in your environment, it's just that you did not see the error message (or it's hidden by the settings of your IDE).

But in general, the error is expected for your model. Frugally-deep does not support `TFOpLambda` layers.
