### ISSUE TITLE
Function call Trace of predict_class

### ISSUE THREAD

**Issue by SwatikSahoo** [Dobiasd/frugally-deep#327]
Hi Tobias,

Can you please give me the function call trace of predict_class() to understand the frugally_deep library better?

**Comment by Dobiasd** [comment]
> function call trace of predict_class()

Sorry, but I think I don't understand what that means.

[`fdeep::model::predict_class` is defined in `fdeep/model.hpp`](https://github.com/Dobiasd/frugally-deep/blob/58b7e70bd391e018147e0aa8289a22e6c4d2e821/include/fdeep/model.hpp#L66). You can use any C++-capable IDE to navigate there automatically and also go to the definitions of the function called from inside it.

Or, if you want to observe things not statically but at runtime, you could use a debugger to follow the path taken during prediction.

Doing these things is not specific to frugally-deep, but a standard approach to read any foreign codebase. `¯\_(ツ)_/¯`
