### ISSUE TITLE
Bad performance.

### ISSUE THREAD

**Issue by TrueWodzu** [Dobiasd/frugally-deep#329]
Hi Tobias,

I am getting a bad performance when using frugally-deep and I wanted to ask you about some advice. Of course I've read FAQ about the performance so I got that covered.

Here is what I've tested so far:

| Environment|      Description    |  Time |
|----------|:-------------|------:|
| Python |  Default settings (GPU ON) | 35ms|
| Python |  os.environ['CUDA_VISIBLE_DEVICES']='-1' | 45ms|
| Python |  NO GPU and tf.config.threading.set_intra_op_parallelism_threads(1) | 75ms|
| Visual Studio 2017 |  Default (Release -O2, whole program optimization) | 310ms|
| Visual Studio 2017 | Compiled with AVX2 | 280ms|

It is quite interesting that single switch (AVX2) gave me 10% boost! but it is still far, very far from what you have advocated.

I did run a benchmark and here is what I've got:

![obraz](https://user-images.githubusercontent.com/10086987/157890846-cc68fc6e-5773-499a-b41b-84826a47dc2b.png)

Any ideas? Could I send you my model and example code? (privately as this is for the job, I will be happy to support you if I get paid for the project :) ).

**Comment by Dobiasd** [comment]
Hi, and thanks for the good preparatory work. :+1:

If your model architecture differs significantly from the ones with the performance tests in the README, the performance might also differ a lot. Maybe the bottleneck, in this case, is in a function I have not yet fully optimized because it never appeared in my profiling runs so far.

It would be great if you could send me your model file, or a link to download it, (as `.h5`) to editgym@gmail.com. I'll then have a look and check if I can reproduce the performance difference you see between TensorFlow and frugally-deep, and then check if I can improve the situation. :construction_worker:

**Comment by TrueWodzu** [comment]
Hi,

it is my who is grateful for your hard work! :) I will send you an e-mail shortly with a link to google drive with model and a sample application.

**Comment by Dobiasd** [comment]
Status: I received your email and was able to reproduce a measurable performance difference between TensorFlow and frugally-deep in predictions speed using your model, with the following `Dockerfile`:

```Dockerfile
FROM python:3.9

RUN apt-get update
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y build-essential cmake

RUN pip3 install tensorflow==2.8.0

RUN apt-get remove --purge -y cmake
RUN pip install cmake --upgrade

RUN git clone -b 'v0.2.18-p0' --single-branch --depth 1 https://github.com/Dobiasd/FunctionalPlus && cd FunctionalPlus && mkdir -p build && cd build && cmake .. && make && make install
RUN git clone -b '3.4.0' --single-branch --depth 1 https://gitlab.com/libeigen/eigen.git && cd eigen && mkdir -p build && cd build && cmake .. && make && make install && ln -s /usr/local/include/eigen3/Eigen /usr/local/include/Eigen
RUN git clone -b 'v3.10.5' --single-branch --depth 1 https://github.com/nlohmann/json && cd json && mkdir -p build && cd build && cmake -DBUILD_TESTING=OFF .. && make && make install
RUN git clone -b 'v0.15.14-p0' --single-branch --depth 1 https://github.com/Dobiasd/frugally-deep && cd frugally-deep && mkdir -p build && cd build && cmake .. && make && make install

WORKDIR /frugally-deep

# model file from the email on 2022-03-14 08:38
ADD frugally.h5 fdeep_issue_329.h5

ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache

RUN CUDA_VISIBLE_DEVICES='' taskset --cpu-list 1 python3 ./keras_export/convert_model.py fdeep_issue_329.h5 fdeep_issue_329.json

RUN echo '#include "fdeep/fdeep.hpp"\n\
int main()\n\
{\n\
    const auto model_path = "fdeep_issue_329.json";\n\
    const auto model = fdeep::load_model(model_path, true);\n\
    const std::size_t warm_up_runs = 3;\n\
    const std::size_t test_runs = 5;\n\
    for (std::size_t i = 0; i < warm_up_runs; ++i)\n\
    {\n\
        const double duration = model.test_speed();\n\
        std::cout << "Forward pass took "\n\
            << duration << " s." << std::endl;\n\
    }\n\
    double duration_sum = 0;\n\
    std::cout << "Starting performance measurements." << std::endl;\n\
    for (std::size_t i = 0; i < test_runs; ++i)\n\
    {\n\
        const double duration = model.test_speed();\n\
        duration_sum += duration;\n\
        std::cout << "Forward pass took "\n\
            << duration << " s." << std::endl;\n\
    }\n\
    const double duration_avg =\n\
        duration_sum / static_cast<double>(test_runs);\n\
    std::cout << "Forward pass took "\n\
        << duration_avg << " s on average." << std::endl;\n\
}' >> main.cpp

RUN g++ -std=c++14 -O3 -march=native main.cpp -o main

RUN ./main
```

Output Python:

```
Forward pass took 0.0645328 s on average.
```

Output C++:

```
Forward pass took 0.152025 s on average.
```

The gap is smaller compared to what you measured, but still there. I'll investigate and get back to you. :technologist:

**Comment by TrueWodzu** [comment]
Awesome, thanks!

**Comment by TrueWodzu** [comment]
Hmm,

what about these destructors? `~batch_normalization_layer() `and `~relu_layer()` doesn't that look suspicious to you?

**Comment by Dobiasd** [comment]
That looks weird, yes. But since the destructors of `batch_normalization_layer` and `relu_layer` are trivial, and the [member variables to be destructed in `relu_layer` are just 3 plain basic floats](https://github.com/Dobiasd/frugally-deep/blob/c5ec811c6394eda94b0b4bcbe4f9bd3879ee06d1/include/fdeep/layers/relu_layer.hpp#L43-L45), I'm not sure if we can take this part of the profiler output seriously.

**Comment by Dobiasd** [comment]
Replacing the [implementation of the `separable_conv_2d_layer` in frugally-deep](https://github.com/Dobiasd/frugally-deep/blob/master/include/fdeep/layers/separable_conv_2d_layer.hpp#L54-L78) with a dummy like

```cpp
    tensors apply_impl(const tensors& inputs) const override
    {
        return {tensor(tensor_shape(inputs.front().shape().height_,
                                    input.front().shape().width_,
                                    filters_pointwise_.filter_count_),
                       0.0f)};
    }
```

brings down the forward pass duration (on my machine) from 0.152 s to 0.067 s. So, yeah, this is the part where there should be the most to gain from when optimizing.

**Comment by TrueWodzu** [comment]
Tobias, thank you for your effort :) I fully understand if this might be too big task to handle. What is worrying me is that, in my tests it is **4 times** slower than in Python, while in your tests it is **2.3 times** slower. I've checked Eigen compilation and it is compiled with AVX2, so I don't understand where this discrepancy comes from.

**Comment by Dobiasd** [comment]
Phew! :sweat_smile:

After quite intense thinking and experimenting, I've managed to improve the performance of your model (on my machine) from 0.152 s to 0.116 s. :tada:

Could you please re-check the performance in your environment (just use the latest version of frugally-deep from the `master` branch)? :slightly_smiling_face:

**Comment by TrueWodzu** [comment]
Excellent job! :grinning: I did check the latest version and my results are consistent with yours. You got 24% gain in speed while I got 28%. 🎉

Many thanks for your support. I won't forget about you if I will ever get paid for my model :moneybag:

**Comment by Dobiasd** [comment]
Ha, I've discovered another optimization possibility. On my machine, the prediction time for your model is now down to 0.093 s. :sunglasses:

**Comment by TrueWodzu** [comment]
I am glad that you are enjoying working on it :grinning:

**Comment by TrueWodzu** [comment]
> Ha, I've discovered another optimization possibility. On my machine, the prediction time for your model is now down to 0.093 s. 😎

If there is anything you want me to re-test, please let me know :)

**Comment by Dobiasd** [comment]
Yeah, it could be interesting to learn if you also see the second increase in performance with the latest version. :slightly_smiling_face:

**Comment by TrueWodzu** [comment]
Latest changes do not compile for me, I am getting linking error about multiple definition:

Error	LNK2005	"class Eigen::Map<class Eigen::Matrix<float,-1,-1,0,-1,-1>,0,class Eigen::OuterStride<-1> > __cdecl fdeep::internal::get_im2col_mapping(class fdeep::internal::tensor const &,unsigned int,unsigned int,unsigned int,unsigned int,unsigned int,unsigned int)" (?get_im2col_mapping@internal@fdeep@@YA?AV?$Map@V?$Matrix@M$0?0$0?0$0A@$0?0$0?0@Eigen@@$0A@V?$OuterStride@$0?0@2@@Eigen@@ABVtensor@12@IIIIII@Z) already defined

**Comment by Dobiasd** [comment]
Ah, sorry, my mistake. Should be [fixed](https://github.com/Dobiasd/frugally-deep/commit/0dc15d5c3c5c920fe6dccb00c145c4bb368725bd) now. Can you please try again?

**Comment by TrueWodzu** [comment]
Tested it. I got another 6% performance gain! Is it stable? Can I use this in production code?

**Comment by Dobiasd** [comment]
Yes, it's stable. You can use it. 👍

**Comment by TrueWodzu** [comment]
Thanks!

**Comment by Dobiasd** [comment]
Hope with the performance improvement, it suffices for your use case, even though it still might not be as fast as TensorFlow. But currently (also when looking at profiler outputs from today) I'm out of (feasible) further optimization ideas. :wink:

**Comment by TrueWodzu** [comment]
It was sufficient even before, but it is always worth to save some CPU cycles. :)

**Comment by Dobiasd** [comment]
FYI: You might be interested in trying out [release `v0.15.18-p0`](https://github.com/Dobiasd/frugally-deep/releases/tag/v0.15.18-p0), which [improves the performance on some model types significantly](https://github.com/Dobiasd/frugally-deep/commit/09034bf857638880aaf2cf4c278014ebfd611bb3). :slightly_smiling_face:

**Comment by TrueWodzu** [comment]
Excellent, thank you for letting me know! I will check it on Monday :) BTW: would it be possible to add to your benchmark an EfficientNet? You can easily download it using [Keras Applications](https://keras.io/api/applications/).

**Comment by Dobiasd** [comment]
Sure, done. :heavy_check_mark:

**Comment by TrueWodzu** [comment]
Hi, tested this today thoroughly and it does not make difference on my model. It might be even slightly worse in comparison to previous version of fdeep.:confused:  but for me the current performance is totally fine:) Thanks for trying to make it even better 🖤
