### ISSUE TITLE
Support for variable-size InputLayer

### ISSUE THREAD

**Issue by thefiddler** [Dobiasd/frugally-deep#33]
Keras supports InputLayers where one or more dimensions can be `None` (i.e. receive an input of any size). This is allowed for the batch axis (ignored here), the width and the height axes, but not for the channel axis (for obvious reasons).

I am opening this issue to discuss what we would need to modify to support graphs with variable-size inputs.

**Comment by Dobiasd** [comment]
Interesting proposal. However on first thought I does not sound trivially to implement to me. ;)
