### ISSUE TITLE
AttributeError: 'Node' object has no attribute 'call_kwargs'

### ISSUE THREAD

**Issue by dfy888** [Dobiasd/frugally-deep#340]
when run  :  python3 keras_export/convert_model.py keras_model.h5 fdeep_model.json

my version:

tensorboard            2.4.1
tensorboard-plugin-wit 1.8.0
tensorflow             2.1.0
tensorflow-estimator   2.1.0
Keras                  2.3.1
h5py                   2.10.0

**Comment by Dobiasd** [comment]
> tensorflow 2.1.0
> Keras 2.3.1

That's quite old. Please update in order to use frugally-deep. (see [Requirements and Installation](https://github.com/Dobiasd/frugally-deep#requirements-and-installation)

**Comment by dfy888** [comment]
> > tensorflow 2.1.0
> > Keras 2.3.1
> 
> That's quite old. Please update in order to use frugally-deep. (see [Requirements and Installation](https://github.com/Dobiasd/frugally-deep#requirements-and-installation))

thanks!  it work
