### ISSUE TITLE
How do I change the shape of input tensor?

### ISSUE THREAD

**Issue by InvincibleKnight** [Dobiasd/frugally-deep#343]
Hi! I have been trying to use frugally-deep for an audio event detection problem. I have completed transporting most of my code to C++ (reading .wav files, feature extraction, etc)
I have augmented the VGG_16 model according to my needs however I am facing the issue of providing input to the frugally_deep model in C++

What I'm looking for is to input an `n x m` vector
The SSCCE version of the python model is:
```python
# create_model.py

import numpy as np
from tensorflow.keras.layers import Input, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.models import model_from_json

inputs = Input(shape=(2,3))
x = Flatten()(inputs)
x = Dense(5, activation='relu')(x)
predictions = Dense(2, activation='softmax')(x)
model = Model(inputs=inputs, outputs=predictions)
model.compile(loss='categorical_crossentropy', optimizer='nadam')
data1 = np.array([[[1,3,5],[2,5,2]]])
print(data1.shape) # Outputs : (1, 2, 3)

data2 = np.array([[1,2]])
print(data2.shape) # Outputs: (1, 2)

model.fit(data1, data2, epochs=50)

model.save('keras_model.h5', include_optimizer=False)

print()

prediction = model.predict(np.array([[[1,3,1],[4,1,2]]]).reshape(-1, 2, 3))
print(prediction) # Output: [[0.5609962 0.4390038]]


```
How do I give the `[ [1,3,1],[4,1,2] ]` input in `main.cpp`?

Thank you

**Comment by Dobiasd** [comment]
Hi, and thanks for providing such a good minimal example. :+1:

This makes proving help very pleasant. :slightly_smiling_face:

I don't know how your current attempts in C++ look like, but here is an example for giving `[[1, 3, 1], [4, 1, 2]]` to such a model:

```cpp
#include <fdeep/fdeep.hpp>
int main()
{
    const auto model = fdeep::load_model("fdeep_model.json");
    const auto shape = fdeep::tensor_shape(2, 3);
    const auto input = fdeep::tensor(shape, std::vector<float>{1, 3, 1,  4, 1, 2});
    const auto result = model.predict({input});
    std::cout << fdeep::show_tensors(result) << std::endl;
}
```

**Comment by InvincibleKnight** [comment]
Hello! Thank you for your prompt response. 

I was trying to pass a 2D vector which is why I was being thrown warnings and errors. Your solution works wonderfully. I'll now implement it in my original model. Closing the issue for now. Thanks!
