### ISSUE TITLE
conversion of .wav file to tensor

### ISSUE THREAD

**Issue by NiharikaRINKU** [Dobiasd/frugally-deep#347]
I am using frugally deep library for project related to Speech Enhancement. I have read the .wav file and I have to predict these stored values of audio signal through the model using model.predict. I am facing errrors in converting the values to tensor. Kindly, help me out in doing so as soon as possible.
Thanking you

**Comment by Dobiasd** [comment]
Can you show the problem (and the errors) in a [minimal code example](http://sscce.org/)?
