### ISSUE TITLE
Use VS to generate dynamic link library error

### ISSUE THREAD

**Issue by BraveZFLin** [Dobiasd/frugally-deep#352]
If the frugally-deep library is included in the file that generates the dynamic link library, it will prompt that the file content is wrong.
The configuration of project has involve the additional include directiories.
IDE: VS2022

A.cpp
#include <fdeep/fdeep.hpp>
#include “A.h”

void XX()
{}
-------------------------
A.h
#ifdef A_API_EXPORTS
#define A_API __declspec(dllexport)
#else
#define A_API __declspec(dllimport)
#endif

extern "C" A_API void XX();
-------------------------

**Comment by Dobiasd** [comment]
To make sure I understand correctly (despite the formatting noise), you have the following two files

`A.cpp`:

```cpp
#include <fdeep/fdeep.hpp>
#include “A.h”

void XX()
{}
```

and

`A.h`:

```cpp
#ifdef A_API_EXPORTS
#define A_API __declspec(dllexport)
#else
#define A_API __declspec(dllimport)
#endif

extern "C" A_API void XX();
```

and you use Visual Studio 2022 to create a `.dll` file from `A.cpp`.

When you remove `#include <fdeep/fdeep.hpp>` from `A.cpp`, things work fine, but when it's there, you get an error.

Correct?

If yes, please let me know the exact error, to help me help you. :slightly_smiling_face:

**Comment by BraveZFLin** [comment]
yes, the picture is show the error
> ![image](https://github.com/BraveZFLin/picture/blob/main/1.jpg)
![image](https://github.com/BraveZFLin/picture/blob/main/1.jpg)

**Comment by BraveZFLin** [comment]
this picture show remove #include<fdeep/fdeep.hpp> from A.cpp
![image](![image](https://github.com/BraveZFLin/picture/blob/main/2.jpg))

**Comment by BraveZFLin** [comment]
If the picture does not display properly, you can find it from my “Popular repositories/picture"
thanks T T

**Comment by Dobiasd** [comment]
Any news?
