### ISSUE TITLE
Issues with input shape

### ISSUE THREAD

**Issue by belamarib** [Dobiasd/frugally-deep#356]
Hello!
I'm using frugally deep to convert this model https://colab.research.google.com/github/bmild/nerf/blob/master/tiny_nerf.ipynb to C++, but when I do the inference it says the following: "Invalid inputs shape. The model takes [1(Just 39)] but provided was: [2(32768, 39)]".
 
The actual shapes I need are (32768, 39) and (17408, 39). I believe this is happening because in the python code the input shape is defined as inputs = tf.keras.Input(shape=(39)), which works in python as (None, 39), but when I convert to C++ it takes 39 only. 
I've tried changing the input shape on the json file, but it still didn't work. So I would like to know if there is a way of using the right shape in C++ without changing the python code.
Here goes the json file:
[my_model_with_concatenate.zip](https://github.com/Dobiasd/frugally-deep/files/9010279/my_model_with_concatenate.zip)

**Comment by belamarib** [comment]
Actually, when I use (32768, 39) in Python it is a tensor of that shape. As frugally deep doesn't accept a tensor as a predict parameter, I converted it to a vector of size 1.277.952 (32768 x 39). 

So I tried to do it the way you showed:
const auto input = std::vector<fdeep::tensors>(32768, {fdeep::tensor(fdeep::tensor_shape(39), partial_pts_float)});
model.predict_multi(input, true);

Being partial_pts_float that vector I mentioned. 
But it showed the following error: "invalid number of values. shape: 1(39); value count: 1277952"
I also didn't understand why you put the **42** as a parameter.
Here goes the .h file:
[my_model.zip](https://github.com/Dobiasd/frugally-deep/files/9012702/my_model.zip)

**Comment by belamarib** [comment]
I see. 
I've tried running the code the way you showed and it really worked. The only thing I didn't know was if it would still be equivalent to what is being made in the python code. There, there is only one prediction made using the whole tensor as input, while in here we are making 32768 predictions out of a single tensor.
Also, in the end I need this results as a torch tensor, so I would like to know if there is a way of converting a fdeep::tensor to torch tensor.
Thanks for your responses!!

**Comment by Dobiasd** [comment]
Frugally-deep does not provide functions to convert its tensors to Torch structures.

But you can fetch the raw values from an `fdeep::tensor` and store them whereever you need.
