### ISSUE TITLE
convert_model.py line 78 and 307:model._input_layers

### ISSUE THREAD

**Issue by 4SmarterWorld** [Dobiasd/frugally-deep#36]
when i intended to use the script convert_model.py to convert the .h5 file saved by Keras, I was told that:
AttributeError: 'Model' object has no attribute '_input_layers'

so after some attempts i found if i change "_input_layers" to "input_layers", it seems work properly,
so i guess if this was a typo? by the way, the version of tensorflow for me was 1.3.0 and keras was 2.0.5,
maybe because of the version, i don't know. Anyway,hope you can look into this, thanks!

**Comment by Dobiasd** [comment]
Yes, in earlier TF/Keras versions it was `model.input_layers` instead of `model._input_layers`. I just changed the code so it should accept both. Please let me know if this helps and if you in general get frugally-deep to work with your ancient TF/Keras versions. :)
