### ISSUE TITLE
Unable to use frugally-deep with FetchContent

### ISSUE THREAD

**Issue by GiulioRomualdi** [Dobiasd/frugally-deep#363]
Hi @Dobiasd! First of all, thank you very much for developing and maintaining `frugally-deep`!

I would like to use `frugally-deep` with CMake `FetchContent`, however, I'm having some trouble.

I wrote this very simple `main.cpp` file
```cpp
// main.cpp
#include <fdeep/fdeep.hpp>

int main()
{
    return 0;
}
```
and the associated `CMakeLists.txt` file
```cmake
cmake_minimum_required(VERSION 3.16)
project(test_keras_model)

include(FetchContent)
FetchContent_Declare(
    functional_plus
    GIT_REPOSITORY https://github.com/Dobiasd/FunctionalPlus.git
    GIT_TAG master
    )

  FetchContent_Declare(
    frugally_deep
    GIT_REPOSITORY https://github.com/Dobiasd/frugally-deep.git
    GIT_TAG master
)

FetchContent_MakeAvailable(functional_plus frugally_deep)

add_executable(test_keras_model main.cpp)
target_link_libraries(test_keras_model frugally-deep::fdeep)
```
when I call `cmake .` I got the following error
```
-- ===( frugally-deep 0.15.19 )===
-- Configuring done
CMake Error at CMakeLists.txt:20 (add_executable):
  Target "test_keras_model" links to target "frugally-deep::fdeep" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
```
there seems that `FetchContent_MakeAvailable()` is not able to generate the target `frugally-deep::fdeep`

cc @isorrentino

**Comment by GiulioRomualdi** [comment]
I noticed that liking `fdeep` instead of `frugally-deep::fdeep` fixes the problem. 
Adding
```cmake
 add_library(frugally-deep::fdeep ALIAS fdeep)
```
in the `frugally-deep` `CMakeLists.txt` should fix the issue

**Comment by Dobiasd** [comment]
Hi @GiulioRomualdi ,

thanks a lot for the nice feedback, the good issue report, and the fix! 🚀🤩
