### ISSUE TITLE
Unable to call `predict_single_output_stateful` when the model is stateful

### ISSUE THREAD

**Issue by GiulioRomualdi** [Dobiasd/frugally-deep#365]
Hi @Dobiasd 😃 . I'm trying to use frugally-deep with an LSTM designed in KERAS. The network does binary classification.
When I try to predict the model with `predict_single_output_stateful` I got the following error  
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Prediction on stateful models is not const. Use predict_stateful instead.
Aborted (core dumped)
```

I noticed that the issue is due to the fact that `predict_class_with_confidence_stateful` calls `predict_class_with_confidence_impl` that ends in calling `predict` which is a const method.

**Comment by GiulioRomualdi** [comment]
#366 fixes the issue

**Comment by Dobiasd** [comment]
Wow, thanks a lot for the nice explanatory report, and also for the fix! :rocket: :heart:
