### ISSUE TITLE
Thanks !

### ISSUE THREAD

**Issue by sirius-william** [Dobiasd/frugally-deep#367]
Thank the project author very much! My graduate design project is a one-dimensional convolutional neural network. After training with Python's TensorFlow 2.10, I have been looking for ways to deploy the model in my Qt project. I have tried to compile TensorFlow C++(compilation always fails), TensorFlow C API (TensorFlow 2.10 is not supported), TensorRT (AMD graphics driver is not supported), OpenVino (the network architecture I choose is not supported). By chance, I found this library in Google. It is easy to use and does not require much dependence. It only requires header files. It perfectly solves my project needs. Thank you!
PS. When using, the python script part is executed in CMakeList.txt in the test, using python3 xxxx. However, not all users can run Python scripts through the command 'python3'. It is recommended to find Python in CMakeLists.txt, or let users specify Python paths. In addition, Mingw will report Fatal error: can't write 286 bytes to section. text when compiling unittest. It is recommended to add:
target_ compile_ options(PROJECT_NAME
PRIVATE
$<$<CXX_ COMPILER_ ID:MSVC>:/bigobj>
$<$<CXX_ COMPILER_ ID:GNU>:-Wa,-mbig-obj>)
This problem also arises when the library is used in other projects. #

**Comment by Dobiasd** [comment]
Thanks a lot for the positive feedback. I'm happy to hear that frugally-deep is of use for you. 🙂

Also thanks for the tips. Would you like to open a pull request implementing them?

**Comment by sirius-william** [comment]
> 

Yes, I have just created a pull request, please check whether some mistake where I modified.

**Comment by cpusam** [comment]
@Dobiasd I came to give thanks too! Thank you for your work.
