### ISSUE TITLE
Multi-threading

### ISSUE THREAD

**Issue by gavalian** [Dobiasd/frugally-deep#369]
I was wondering if the predict() method of models is thread-safe. May I use an instance of the model in many threads to run predictions (somehow wasn't obvious from the code)?

If not, what would be the best suggested way of doing this?

**Comment by Dobiasd** [comment]
Yes, `model::predict` is thread-safe. :heavy_check_mark:

You can see this from
- the fact, that it work with `const model`
- and from the [implementation](https://github.com/Dobiasd/frugally-deep/blob/a6a01e5c32e4724c11544f73a815380564c2f54b/include/fdeep/model.hpp#L43) of `model::predict_multi`.

`model::predict_stateful`, on the other hand, is not thread-safe. Hence, it [requires](https://github.com/Dobiasd/frugally-deep/blob/a6a01e5c32e4724c11544f73a815380564c2f54b/include/fdeep/model.hpp#L35) a non-const `model` instance.
