### ISSUE TITLE
Can't import fdeep into header file

### ISSUE THREAD

**Issue by simonjeger** [Dobiasd/frugally-deep#377]
Hi there,

I'm quite new to C++, so this might just be my fault.
I've dragged the fdeep folder into my include directory and did the same with the other libraries (fplus, euler, json). 
Now if I include #include "fdeep/fdeep.hpp" in my_file.cpp, everything works fine.
But if I move the include-line to my_file.hpp, it throws me the following error:

_multiple definition of `fdeep::internal::inner_average_pool(fdeep::internal::tensor const&, fdeep::internal::tensor&, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, int, int, int)'; libflightlib.a(robot_vec_env.cpp.o):robot_vec_env.cpp:(.text+0x0):_

I need the include line already in the .hpp file to be able to initialize global variables of the type fdeep::model.

I'm using cmake version 3.16.3

Do you have any pointers?

**Comment by Dobiasd** [comment]
Hi, and thanks a lot for the report. You did nothing wrong. :+1: I did! :grimacing:
I've just pushed [a commit](https://github.com/Dobiasd/frugally-deep/commit/84446545dd81a96a5f7511519062e90aec7b3fa3) that should fix it. Please try again with the latest version from the `master` branch, and let me know if you encounter any further issues.

**Comment by simonjeger** [comment]
Awesome, thanks a ton! :D

**Comment by Dobiasd** [comment]
**Thank you** for letting me know about this bug already two days after I [introduced it](https://github.com/Dobiasd/frugally-deep/commit/b776285b0dd5a6ccf7674ba5ec382ef27b86348a#diff-8cbca3faa013fb8c64ab19bc1e55723329d13016a905a815c928a4cb01adc57cR17). :grin:
