### ISSUE TITLE
Several compiler errors with Visual Studio 2022 (C++20)

### ISSUE THREAD

**Issue by dasmysh** [Dobiasd/frugally-deep#395]
I encountered several compiler errors with your code in VS2022 and C++20. The first issue is for sure a C++20 issue, the second one might be a VS(2022) thing.

First, FunctionalPlus does not work. `std::result_of` was removed in favor of `std::invoke_result` and they are still using that. I'll write a github issue there as well but I'll also describe the fix here:

Any instance of
```
std::result_of<Func(Params)>
```
becomes
```
std::invoke_result<Func, Params>
```

Another issue is in the `attention_layer.hpp` and `additive_attention_layer.hpp`:
The `tanh` used in one of the `transform_tensor` calls seems to be ambiguous. Replacing that with a `tanhf` fixes it.

**Comment by Dobiasd** [comment]
Hi, and thanks for the report. :+1:

The problem with `std::result_of` should be solved when switching to the latest version of FunctionalPlus. See [this thread](https://github.com/Dobiasd/FunctionalPlus/issues/275#issuecomment-1715336392) for details.

**Comment by Dobiasd** [comment]
The above suggestion might not work. But I just pushed a commit, that should fix it.

Can you please try compiling again with the latest version from `master` and let me know if that helped?

**Comment by dasmysh** [comment]
> Can you try replacing `tanh` with `std::tanh` in `attention_layer.hpp` locally, and let me know if this resolves your compiler error?
That is still ambiguous. But what does help is specifying the template arguments of `transform_tensor` by explicitly calling `transform_tensor<float_type(float_type)>(tanh, [...])`.

**Comment by Dobiasd** [comment]
And how about the latest version from `master`, i.e., the one with `tanh_typed`?

**Comment by dasmysh** [comment]
`master` also works.

**Comment by dasmysh** [comment]
So yes, issue is fixed. Thanks for the fast replies.

**Comment by Dobiasd** [comment]
Thanks for the error report, helping to make the library better, and to make the experience smoother for future users! :heart:
