### ISSUE TITLE
terminate called after throwing an instance of 'std::runtime_error'

### ISSUE THREAD

**Issue by pinyuan-tsai** [Dobiasd/frugally-deep#396]
Hello, I'm trying to use full workflow, after i compile the main.cpp with (g++ main.cpp -o main and do ./main) i got a runtime_error as below.

![image](https://github.com/Dobiasd/frugally-deep/assets/113095472/86a52cc8-1ce3-4d1c-8d43-c1b8774a7679)

Thank you for your help!

**Comment by Dobiasd** [comment]
Hi,

please have a look at ["What to do when loading my model with frugally-deep throws an `std::runtime_error` with `test failed`" in the FAQ](https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#what-to-do-when-loading-my-model-with-frugally-deep-throws-an-stdruntime_error-with-test-failed) and let me know if that helped.

**Comment by cemox35** [comment]
Hello,

I also got a runtime_error in the tensor.hpp file line 55.

![image](https://github.com/Dobiasd/frugally-deep/assets/29412524/54272096-4e37-4a67-8c8f-c8c01f965f9a)

I tried to change float to double, I also changed verify to false. 

In my case, I have a JSON file of nearly 1 MB. It's a CNN model. (conv1d, flatten, maxpooling1d etc.

**Comment by Dobiasd** [comment]
Can you show the actual exception message (`msg`) please?

Or, if possible, upload your model, so I can try to reproduce (and then potentially debug) the problem locally.

**Comment by Dobiasd** [comment]
Ah, ok. So this is no longer from the automated tests invoked by `fdeep::load_model`, but from some `model.predict(...);` call (obviously with an incorrect data shape). :+1:
