### ISSUE TITLE
No love for bicubic interpolation ?

### ISSUE THREAD

**Issue by Panjaksli** [Dobiasd/frugally-deep#401]
I don't think it's necessary to upload a full model, your library simply won't convert upsampling2D layer with bicubic filter. You could definitely implement it, since it's pretty much as simple as extending bilinear filter.
Anyways here is the error:
 File "C:\Users\...\convert_model.py", line 513, in show_upsampling2d_layer
    assert layer.interpolation in ["nearest", "bilinear"]

**Comment by Dobiasd** [comment]
Hi, are you interested in giving the implementation a try in a pull request? :slightly_smiling_face:

If not, I'll see what I can do.

**Comment by Panjaksli** [comment]
> Hi, are you interested in giving the implementation of bicubic interpolation for the `UpSampling2D` layer a try in a pull request? 🙂
> 
> If not, I'll see what I can do.

Haha If I knew how to work with pull requests... I'll try, in the worst case I can provide just the algorithm. :D

**Comment by Dobiasd** [comment]
Cool! :+1:

If I can support you in some way with this, please let me know.

**Comment by Panjaksli** [comment]
> Cool! 👍
> 
> If I can support you in some way with this, please let me know.

Okay, here goes nothing.
```
//just a clamping function, since I don't know if project has one
inline std::size_t clamp(const std::size_t x, const std::size_t min, const std::size_t max) {
    return fplus::min(fplus::max(x, min), max);
}
//cubic spline interpolation
inline float_type cerp(const float_type* p, const float_type t) {
    return p[1] + 0.5 * t * (p[2] - p[0] + t * (2.0 * p[0] - 5.0 * p[1] + 4.0 * p[2] - p[3] + t * (3.0 * (p[1] - p[2]) + p[3] - p[0])));
}
//bicubic extrapolation
inline float_type bicerp(const float_type* p, float_type x, float_type y) {
    float_type tmp[4];
    tmp[0] = cerp(p, x);
    tmp[1] = cerp(p + 4, x);
    tmp[2] = cerp(p + 8, x);
    tmp[3] = cerp(p + 12, x);
    return cerp(tmp, y);
}
inline float_type interpolate_2d_value_bicubicly(const tensor& t, float_type y, float_type x, std::size_t z) {
    //Clamping to max size is done in the gathering step
    y = fplus::max(0, y);
    x = fplus::max(0, x);
    //Corner coordinates as integers
    std::size_t y0 = static_cast<std::size_t>(y); 
    std::size_t x0 = static_cast<std::size_t>(x);
    //Relative position for interpolation
    float_type vals[16];
    //Gather values in area of 4x4 pixels, might want to switch the loop ordering, since idk what is the storage order
    for(std::size_t i = 0; i < 4; i++) {
        std::size_t pos_y = clamp(y0 + i - 1, 0, t.height() - 1);
        for(std::size_t j = 0; j < 4; j++) {
            std::size_t pos_x = clamp(x0 + j - 1, 0, t.width() - 1);
            vals[i * 4 + j] = t.get_ignore_rank(tensor_pos(pos_y, pos_x, z));
        }
    }
    float_type x_t = x - static_cast<float_type>(x0);
    float_type y_t = y - static_cast<float_type>(y0);
    return static_cast<float_type>(bicerp(vals, x_t, y_t));
}
```
You can modify the utility functions to your coding style, since I didn't check for built in functions you have, so the clamp is kind of arbitrary. And the interpolate_2d_value_bicubicly() function should be a drop-in replacement for interpolate_2d_value_bilinearly(), like this:
```
inline tensor resize2d_bicubic(const tensor& in_vol, const shape2& target_size) {
    tensor out_vol(tensor_shape(target_size.height_, target_size.width_, in_vol.shape().depth_), 0)
    const float_type scale_y = static_cast<float_type>(target_size.height_) / static_cast<float_type>(in_vol.shape().height_);
    const float_type scale_x = static_cast<float_type>(target_size.width_) / static_cast<float_type>(in_vol.shape().width_);
    for(std::size_t y = 0; y < out_vol.shape().height_; ++y) {
        const auto y_in = (static_cast<float_type>(y) + 0.5f) / scale_y - 0.5f;
        for(std::size_t x = 0; x < out_vol.shape().width_; ++x) {
            const auto x_in = (static_cast<float_type>(x) + 0.5f) / scale_x - 0.5f;
            for(std::size_t z = 0; z < in_vol.shape().depth_; ++z) {
                out_vol.set_ignore_rank(tensor_pos(y, x, z),
                    interpolate_2d_value_bicubicly(in_vol, y_in, x_in, z));
            }
        }
    }
    return out_vol;
}
```
You could check the function for correctness, but if I didn't make a mistake when porting, the result should match Keras/Tensorflow built-in bicubic interpolation perfectly (checked by overlaying in gimp).

**Comment by Dobiasd** [comment]
Wow, thanks, that was quick! :rocket:

I just added your code to a new branch plus two automated test cases, but they fail. I.e., the output of this bicubic interpolation is not exactly the same as the one in TensorFlow:
https://github.com/Dobiasd/frugally-deep/pull/403

Since having these automated tests succeed (for the overall equivalence guarantee) is a requirement, I can't merge yet. Do you have an idea what needs to be adjusted?

**Comment by Dobiasd** [comment]
Yeah, [their code](https://github.com/tensorflow/tensorflow/blob/0d09ec0c1e2cce294b338e8f2e0e52ce9ccdc5e3/tensorflow/core/kernels/image/resize_bicubic_op.cc) looks complicated. :/ Maybe it's all for squeezing out the maximum performance.

I just [tried your suggestion](https://github.com/Dobiasd/frugally-deep/pull/403/commits/b1f5ed2a9d804b31c5047307b54f62dce7abf43a), but as you expected, the tests still fail.

**Comment by Panjaksli** [comment]
> Yeah, [their code](https://github.com/tensorflow/tensorflow/blob/0d09ec0c1e2cce294b338e8f2e0e52ce9ccdc5e3/tensorflow/core/kernels/image/resize_bicubic_op.cc) looks complicated. :/ Maybe it's all for squeezing out the maximum performance.
> 
> I just [tried your suggestion](https://github.com/Dobiasd/frugally-deep/pull/403/commits/b1f5ed2a9d804b31c5047307b54f62dce7abf43a), but as you expected, the tests still fail.

Just leave it then. It's a bummer, but for my model I can get around bicubic interpolation with pretrained subpixel upscaling network. Thanks for your time :D I might try to port the code from TF someday, if I really need it.

**Comment by Dobiasd** [comment]
Thank you too! So I'll close the issue for now. :+1:

> I can get around bicubic interpolation with pretrained subpixel upscaling network

`UpSampling2D` + `Conv2D` trained on bicubicly upsampled images? :smiley:

**Comment by Panjaksli** [comment]
> Thank you too! So I'll close the issue for now. 👍
> 
> > I can get around bicubic interpolation with pretrained subpixel upscaling network

> `UpSampling2D` + `Conv2D` trained on bicubicly upsampled images? 😃

Just conv2d with  

> Thank you too! So I'll close the issue for now. 👍
> 
> > I can get around bicubic interpolation with pretrained subpixel upscaling network
> 
> `UpSampling2D` + `Conv2D` trained on bicubicly upsampled images? 😃

No, it's just Conv2D + depth_to_space to get 2x the resolution and it's trained on original full res images. It's about as fast as bicubic interpolation, and achieves about the same/a bit better PSNR, and it's really just for getting the rough shape of the image, so that another larger network can be trained to correct the 'error' of this upscaling method. It's much better than training large network to generate full res images directly.
