### ISSUE TITLE
MSYS2 Compiling/Linking Issues

### ISSUE THREAD

**Issue by ftuffner** [Dobiasd/frugally-deep#404]
Encountering issues compiling (at the linker stage, it appears), even with the simple example from the readme.md.  Compiling in Linux in a similar manner has no issues.  I'm not sure if it is an MSYS2 MinGW issue, or something I have configured wrong.

GCC: `gcc.exe (Rev2, Built by MSYS2 project) 13.2.0`
G++: `g++.exe (Rev2, Built by MSYS2 project) 13.2.0`
LD: `GNU ld (GNU Binutils) 2.41`

Sample file (copied from the readme.md, but including for thoroughness):
```
// main.cpp
#include <fdeep/fdeep.hpp>
int main()
{
    const auto model = fdeep::load_model("fdeep_model.json");
    const auto result = model.predict(
        {fdeep::tensor(fdeep::tensor_shape(static_cast<std::size_t>(4)),
        std::vector<float>{1, 2, 3, 4})});
    std::cout << fdeep::show_tensors(result) << std::endl;
}
```

Command to compile (libraries installed locally):
```
g++ test_fdeep_single.cpp -I/home/user_name/frugally-deep_libs/frugally_deep/install64/include/ -I/home/user_name/frugally-deep_libs/eigen/install64/include/eigen3/ -I/home/user_name/frugally-deep_libs/functionalplus/install64/include -I/home/user_name/frugally-deep_libs/nlohmann_json/install64/include/ -std=c++14 -o fdeep_single
```

(/home is c:/Code)

Attached is a partial output log - a `vtable` reference appears very common, but that may be a red herring.

[test_output_log.txt](https://github.com/Dobiasd/frugally-deep/files/12730109/test_output_log.txt)

**Comment by Dobiasd** [comment]
Oh, thanks for the report! 👍

Yeah, it's weird. `undefined reference to vtable for fdeep::internal::...layer` does not seem to make too much sense.

Currently, I have no idea what could be the problem.

Have you tried different versions already?

**Comment by ftuffner** [comment]
> Have you tried different versions already?

On the Frugally Deep side (and the non-Eigen dependency libraries), I tried a couple versions, but that was mostly a consequence of some older versions being referenced in examples, or a code update being pushed after I started messing with it.  So only within the last couple versions, not too far back.  I can try pulling some earlier releases if that might be useful to check (just in case it was something introduced).

In terms of MSYS2/MinGW, only so much as on some slightly out-of-date computers, or before I updated them (first thing I tried after it failed the first time).  That said, that has probably only been a couple minor revisions back on the GCC/G++/LD side.  I'll reach out to some colleagues who don't regularly update and see if it behaves differently on their systems and report back.

I'll report back here with any data points on the process.

**Comment by Dobiasd** [comment]
Great,  thanks a lot! ❤️

My guess is, older frugally-deep versions won't help, because the C++ here is quite simple. But maybe an older json lib version, or older FunctionalPlus or Eigen might help.

Ah, you could also try to compile/link minimal examples of these libraries. Perhapa that reveals the origin of the problem.

**Comment by ftuffner** [comment]
Updated note in case anyone else runs across this - we were able to get it compiling/running under MSYS2 as long as it was compiled as a Release version.  All attempts to compile as a Debug build result in the above issue.  This has allowed the incorporation of the library in the MSYS2-compiler-based program, and we just use Linux or WSL if any debugging is needed.

**Comment by Dobiasd** [comment]
Nice! Thanks a lot for the update! 👍
