### ISSUE TITLE
example suggestion

### ISSUE THREAD

**Issue by alan-man** [Dobiasd/frugally-deep#412]
As a way to explore neural network, I wrote some example learning of logical operators (AND, OR, XOR) and was wondering if it would be of any use for the project. More examples can help for some. Let me know !

**Comment by Dobiasd** [comment]
Hi @alan-man,

thanks for the idea, but I'm not sure I understand what you mean.

Did you create a model in Keras showing how neural networks can be trained to emulate logical operators?
Or something different, which is directly related to frugally-deep?
