### ISSUE TITLE
error: implicit conversion changes signedness: 'int' to 'std::size_t' (

### ISSUE THREAD

**Issue by MyraBaba** [Dobiasd/frugally-deep#45]
Finally I compiled and tested weights..

it is ok if I compile through 

> g++ -std=c++14 -O3 Predict.cpp -lopencv_core -lopencv_imgproc -lopencv_imgcodecs -o opencv_example

but from Clion , cmake it gaves : error: implicit conversion changes signedness: 'int' to 'std::size_t'  error:  here : 

const auto input = fdeep::tensor3_from_bytes(image.ptr(),
                                                 image.rows, image.cols, image.channels(), 0.0f, 1.0f);

I put c++14 to cmake flag also.

**Comment by Dobiasd** [comment]
You seem to have some warnings enables as errors. This is OK and actually good practice. But in that case you need to convert from `int` to `std::size_t` explicitly, like so:

```cpp
const auto input = fdeep::tensor3_from_bytes(image.ptr(), static_cast<std::size_t>(image.rows), static_cast<std::size_t>(image.cols), static_cast<std::size_t>(image.channels()), 0.0f, 1.0f);
```
