### ISSUE TITLE
Invalid divisor in softmax

### ISSUE THREAD

**Issue by MyraBaba** [Dobiasd/frugally-deep#47]
I have below error for : https://drive.google.com/open?id=189Yuna5IPGBy6GFWKxLP-DqU2NRl031E  model.

I put  #define FDEEP_FLOAT_TYPE double
before fdeep.hpp . but same error.

any idea ?

Best

> 
> Parsing json ... done. elapsed time: 0.505266 s
> Running test 1 of 1 ... libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Invalid divisor in softmax layer. Try using
> #define FDEEP_FLOAT_TYPE double
> before
> #include "fdeep/fdeep.hpp"
> Abort trap: 6

**Comment by Dobiasd** [comment]
```
const auto model = fdeep::load_model(model_path, false);

**Comment by Dobiasd** [comment]
Perhaps this is the result of the random input values being used for the verification step. You can skip this step by setting `verify` to `false` in your call to `fdeep::load_model`, like so:

```cpp
const auto model = fdeep::load_model("_top_model_weights.json", false);
```

With this your model will not be tested after loading, however you can use it normally after than nonetheless.

**Comment by MyraBaba** [comment]
Hi ,

for this new one It is successfully loaded gives below error:

> Assertion failed: (lhs.cols() == rhs.rows() && "invalid matrix product" && "if you wanted a coeff-wise or a dot product use the respective explicit functions"), function Product, file /usr/local/include/Eigen/src/Core/Product.h, line 97.
> Abort trap: 6

i convert the image 224x244 like before
`cv::resize(image, image, cv::Size(224, 224), 0, 0, cv::INTER_CUBIC);`

the python codes for training and the preditc are here : https://github.com/lrojas12/distracted-driver-detection/tree/master/src/keras/vgg
train_top.py . and predict.py

am I missing something ?

**Comment by Dobiasd** [comment]
Can you please provide a [SSCCE](http://sscce.org/) of the C++ code to reproduce the error?

**Comment by MyraBaba** [comment]
`#define FDEEP_FLOAT_TYPE double

#include <fdeep/fdeep.hpp>
#include <opencv2/opencv.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <stdio.h>
#include <iostream>
#include <string>
#include <vector>
#include <sys/time.h>
#include <unistd.h>

#define FDEEP_FLOAT_TYPE double

int main(int  , char *argv[])
{

    struct timeval start, end;
    double mtime, seconds, useconds;

    const auto model = fdeep::load_model("topModel_weightsCPP.json",false);

  // arg[1] is any jpg image...
    std::cout << argv[1] << std::endl;
    cv::Mat image = cv::imread(argv[1]);
    cv::Mat image_2;
    cv::cvtColor(image, image, cv::COLOR_BGR2RGB);
    assert(image.isContinuous());

      cv::resize(image, image, cv::Size(224, 224), 0, 0, cv::INTER_CUBIC); // resizeresolution

//    cv::resize(image, image, cv::Size(150,150));
    imwrite("./rr.png" ,image);


    gettimeofday(&start, NULL);

//    const auto input = fdeep::tensor3_from_bytes(image.ptr(),
//                                                 image.rows, image.cols, image.channels(), 0.0f, 1.0f);

    const auto input = fdeep::tensor3_from_bytes(image.ptr(),
            static_cast<std::size_t>(image.rows), static_cast<std::size_t>(image.cols), static_cast<std::size_t>(image.channels()), 0.0f, 1.0f);

    const auto result = model.predict_class({input});
    gettimeofday(&end, NULL);

    seconds  = end.tv_sec  - start.tv_sec;
    useconds = end.tv_usec - start.tv_usec;

    mtime = (((seconds) * 1000 + useconds/1000.0) + 0.5);

    std::cout << "Elapsed time: milliseconds : " << mtime << std::endl;

    std::cout << result << std::endl;
}
`

**Comment by MyraBaba** [comment]
this is the working python code with same model: 

https://github.com/lrojas12/distracted-driver-detection/blob/master/src/keras/vgg/predict.py

**Comment by Dobiasd** [comment]
Btw, I just [added an additional safety belt](https://github.com/Dobiasd/frugally-deep/commit/9be2be0afa458edbdff449cd80e14bddf6926ff2) (no pun regarding your project intended ^_-) to frugally-deep, so that it checks if the shape of the inputs provided to the model match the requirements. If this is not the case, a much nicer error message will be given, in your case:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Invalid inputs shape.
The model takes [(512, 7, 7)] but you provided: [(3, 224, 224)]
```
Thanks for helping me make this library more user friendly by reporting your problem. :+1:

**Comment by MyraBaba** [comment]
thanks a lot. 🥇
