### ISSUE TITLE
is it possible to create model dynamicly ?

### ISSUE THREAD

**Issue by MyraBaba** [Dobiasd/frugally-deep#48]
Hi,

We are using a VGG16model for transfer learning dynamically to have better result. Is it possible to use it with you solution ?

**Comment by Dobiasd** [comment]
It does not matter how the model was trained in Keras. If you export it using `model.save(...)`, you can import and use it in frugally-deep.

**Comment by MyraBaba** [comment]
Hi Tobias ,

Let me make myself clear to introduce the situation to better understand;

`        model = applications.VGG16(include_top=False, weights='imagenet')
`
is the first model we utilizing;
than:
`        bottleneck_features = model.predict(image_arr)
`
to get bottlenev_features

than build top model and predict:
```

        model2 = create_top_model("softmax", bottleneck_features.shape[1:])
          model2.load_weights("res/_top_model_weights.h5")
         predicted = model2.predict(bottleneck_features)

```


this is the full flow for each image.

Yes I am bit lac of the deep knowledge. If there is a straight forward way to do this it could be help me and the other people who is looking a candle in the darkness :)

Best

**Comment by Dobiasd** [comment]
OK, so in Keras, you have two models. And if I understand correctly, you basically do:
```python
bottleneck_features = model.predict(image_arr)
predicted = model2.predict(bottleneck_features)
```

If you now want to do this prediction pipeline using frugally-deep you have two options:

## 1) merge both models into one
This is possible using the [functional api](https://keras.io/getting-started/functional-api-guide/) of Keras.

Basically it is something like:

```python
# Python
pipeline_model = model2(model1)
pipeline_model.save('pipeline_model.h5')
# predicted = pipeline_model.predict(image_arr)
```

```bash
# Console
convert_model.py pipeline_model.h5 pipeline_model.json
```

```cpp
# C++
const auto pipeline_model = fdeep::load_model("pipeline_model.json");
const auto predicted = pipeline_model.predict(image_arr);
```

or you can do

## 2) export and use both models separately

Basically it is something like:

```python
# Python
model.save('model1.h5')
model2.save('model2.h5')
```

```bash
# Console
convert_model.py model1.h5 model1.json
convert_model.py model2.h5 model2.json
```

```cpp
# C++
const auto model1 = fdeep::load_model("model1.json");
const auto model2 = fdeep::load_model("model2.json");
const auto bottleneck_features = model1.predict(image_arr);
const auto predicted = model2.predict(bottleneck_features);
```

---

I'd say both options are good solutions. For simplicity I personally would tend to choose option 1. But if at some point you need the access the intermediate Tensors (i.e. `bottleneck_features`) in C++, you of course have to choose option 2.

**Comment by MyraBaba** [comment]
Tobias,

Thanks a lot for your explenation. 
What is confusing for me is the second model created dynamically every time with the new image. 
Am I wrong ? 
```

     model = applications.VGG16(include_top=False, weights='imagenet')

        image_arr = img_to_array(image)  # convert from PIL Image to NumPy array
        image_arr /= 255

        # to be able to pass it through the network and use batches, we want it with shape (1, 224, 224, 3)
        image_arr = np.expand_dims(image_arr, axis=0)
        # model = applications.VGG16(include_top=False, weights='imagenet')

        # get the bottleneck prediction from the pre-trained VGG16 model
        bottleneck_features = model.predict(image_arr)

        # build top model
        model2 = create_top_model("softmax", bottleneck_features.shape[1:])

        model2.load_weights("res/_top_model_weights.h5")
```

**Comment by MyraBaba** [comment]
Hi Tobias,

Thanks it really help for speeding up the Keras side ( X2 ) . And succesfully export / import model2.

Just couldn't properly export /  import model1 : 
`model = applications.VGG16(include_top=False, weights='imagenet')
`
saving this model and trying to export with convert_model.py gives error: says I need to compile model .


Due to lack of my keras knowledge I think. 

Best & Thanks

**Comment by Dobiasd** [comment]
I guess normally it would be
`keras.applications.vgg16.VGG16(...)`
and not
`applications.VGG16(....)`
but let's ignore this for now.

Please try the following:

1)
```python
# Python
model = applications.VGG16(include_top=False, weights='imagenet') # or whatever
model.compile(loss='mse', optimizer='sgd') # since you don't train the model, the actual loss and optimizer do not matter.
model.save('model1.h5')
```

2)
```bash
# Console
convert_model.py model1.h5 model1.json
```

3)
```cpp
// C++
const auto model1 = fdeep::load_model("model1.json");
```

Make sure you are using the latest version of Keras, TensorFlow and frugally-deep.

If you still receive an error, please post a **minimal** code example (see [SSCCE](http://sscce.org/)) to reproduce the problem.

**Comment by MyraBaba** [comment]
Tobias,
I have below Error with this code flow:
Keras 2.1.6
Tensorflow 1.8.0

`model = applications.VGG16(include_top=False, weights='imagenet')
 model.compile(loss='mse', optimizer='sgd')
 model.save('model1.h5', include_optimizer=False)`

Than : 
convert_model.py model1.h5 model1.json

The Error:

> Using TensorFlow backend.
loading /Users/xxx/Projects/distracted-driver-detection/src/keras/vgg/model1.h5
2018-05-18 01:19:07.536576: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/models.py:282: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
Traceback (most recent call last):
  File "/Users/xxx/Projects/frugally-deep/keras_export/convert_model.py", line 504, in <module>
    main()
  File "/Users/xxx/Projects/frugally-deep/keras_export/convert_model.py", line 500, in main
    convert(in_path, out_path)
  File "/Users/xxx/Projects/frugally-deep/keras_export/convert_model.py", line 455, in convert
    test_data = gen_test_data(model)
  File "/Users/xxx/Projects/frugally-deep/keras_export/convert_model.py", line 97, in gen_test_data
    get_model_input_layers(model)))
  File "/Users/xxx/Projects/frugally-deep/keras_export/convert_model.py", line 96, in <lambda>
    set_shape_idx_0_to_1(l.input_shape)).astype(np.float32),
  File "mtrand.pyx", line 856, in mtrand.RandomState.random_sample
  File "mtrand.pyx", line 167, in mtrand.cont0_array
TypeError: 'NoneType' object cannot be interpreted as an integer

Process finished with exit code 1



Thanks

**Comment by Dobiasd** [comment]
Please read about [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/) and use triple backticks in the future. ;)

So like this, I get the same error:

```python
import keras
model = keras.applications.VGG16(include_top=False, weights='imagenet')
model.save('model1.h5')
```

```bash
# Console
convert_model.py model1.h5 model1.json
```



Like that it works:

```python
import keras
model = keras.applications.VGG16(include_top=True, weights='imagenet')
model.save('model1.h5')
```

Also like that it works too:

```python
import keras
model = keras.applications.VGG16(include_top=False, weights='imagenet', input_shape=(224, 224, 3))
model.save('model1.h5')
```

The reason for this is, frugally-deep needs concrete input shapes and output shapes of a model, for example to generate test cases like in your error message.

The shapes are forces by either including the fully-connected layers at the end, or by specifying the input shape explicitly. You can find more about this in the docs/source of the model you are re-using: https://github.com/keras-team/keras/blob/b0f1bb9c7c68e24137a9dc284dc210eb0050a6b4/keras/applications/vgg16.py#L62

In your case, you probably need the version with the explicit `input_shape`.

However I still recommend thinking about the option where you fuse the two models into one using the functional API, since it seems easier to handle.

**Comment by MyraBaba** [comment]
Quick Solution : 
```
           const auto predicted = model2.predict(bottleneck_features);

            auto pred0 = predicted[0].values_.operator*()[0];
            auto pred1 = predicted[0].values_.operator*()[1];
            auto pred2 = predicted[0].values_.operator*()[2];
            auto pred3 = predicted[0].values_.operator*()[3];
            auto pred4 = predicted[0].values_.operator*()[4];
            auto pred5 = predicted[0].values_.operator*()[5];
            auto pred6 = predicted[0].values_.operator*()[6];
            auto pred7 = predicted[0].values_.operator*()[7];
            auto pred8 = predicted[0].values_.operator*()[8];
            auto pred9 = predicted[0].values_.operator*()[9];
```

PS: I made the values_ from tensor3.hpp public for dirty solution.

Now testing the speed and the accuracy.  I Will post here.

**Comment by MyraBaba** [comment]
Hi Tobias,

I succesfully running the models in C++ and benchmarking . What I saw its slower than the python version.

```
C++      version : Elapsed time: milliseconds :  4575.29
Python version  : Elapsed time: milliseconds : 0.2345.0
```

C++ version 20X slower than the Python version for this spesific case:
```

const auto model1 = fdeep::load_model("model1.json");
 const auto model2 = fdeep::load_model("model2.json");

const auto bottleneck_features = model1.predict(image_arr); //This One extremely slow 20X
const auto predicted = model2.predict(bottleneck_features);
```

I will look again with fresh mind to understand why?

Best

**Comment by Dobiasd** [comment]
Or you could just use `tensor3`'s member function `get` instead. ;-)

**Comment by Dobiasd** [comment]
Make sure you compile your C++ code as a release (not debug) version with performance optimizations enabled.

**Comment by MyraBaba** [comment]
compiled release already...  result timing from release compiled executable

**Comment by Dobiasd** [comment]
Make sure you only measure the time of the prediction, not the time of loading the model too. In the `README` file of this repo you can see typical run times of a VGG16 net compared with Keras.

Also keep in mind frugally-deep does not support GPUs.

And when measuring the performance of your release version don't attach a debugger to it, since it also slows down.

If you have specific questions regarding the settings of your C++ IDE or compiler flags, I recommend stackoverflow.com.
Sorry, but I think I already did enough free consulting work here. ;-)

**Comment by MyraBaba** [comment]
Hi Tobias,

I am working on mac book pro 2018. 16 gig ram. No GPU.

test results from the 100 images  code part:
```

` .         gettimeofday(&start, NULL); 
            const auto input = fdeep::tensor3_from_bytes(image.ptr(),
                                                         static_cast<std::size_t>(image.rows), static_cast<std::size_t>(image.cols), static_cast<std::size_t>(image.channels()), 0.0f, 1.0f);

            const auto bottleneck_features = model1.predict({input});
            const auto predicted = model2.predict(bottleneck_features);

            gettimeofday(&end, NULL);
            
            seconds  = end.tv_sec  - start.tv_sec;
            useconds = end.tv_usec - start.tv_usec;
            mtime = (((seconds) * 1000 + useconds/1000.0) + 0.5);`

```

it is also suprising to me to slower than the keras. I will look again the .

model1.json . 81MB
model2.json . 34MB
