### ISSUE TITLE
Memory usage & loading time of large models

### ISSUE THREAD

**Issue by patrikhuber** [Dobiasd/frugally-deep#50]
Hi Tobias,

I've got a model that's a bit bigger - the `.h5` file is 630 MB and the fdeep `.json` is 900 MB.
The problem is that the loading takes ~2:00mins, and also the RAM usage is pretty large, it goes up to 4 GB during the loading (and then back to a more reasonable value). This is in Release mode of course (well, in `RelWithDebugInfo` technically, but I've also run it in pure Release mode once or twice and the outcome was similar).
I'm wondering actually whether you've noticed this yet - I think some of the models you've tested and quite a large number of parameters too and should be similar or larger in file size.

![image](https://user-images.githubusercontent.com/4967343/40258733-707d7680-5aea-11e8-9a67-59be1836ff08.png)
![image](https://user-images.githubusercontent.com/4967343/40258735-74187038-5aea-11e8-9d3e-cadbf15813f1.png)

I think that nlohmann/json is probably doing it as best as possible, so there might not be too much optimisation potential there. Which I guess maybe only leaves storing and reading the model in binary format from C++. I would definitely not want to directly read the .h5 model from C++, hdf5 is a complete nightmare to use in C++ projects, and I think we would both like to leave fdeep without such dependencies.

Have you thought about binary serialisation before? Like, I would for example suggest [cereal](https://github.com/USCiLab/cereal), a header-only modern C++ serialisation library. It's pretty awesome and I've had very good experience with it. The author(s) have gone a bit quiet the last year or two (who can blame them for being busy ;-) ) but the library is still somewhat in slow development, and critical things are usually fixed. And it's still one of the best out there.
Using this strategy, we'd have to add a `serialize` function to all the classes that we want to serialise, and I think that would include all layers. It's pretty trivial though, except for non-trivial types like `tensor3` where one would need to write a serialisation function (pretty easy too).

This still leaves the question open of how to write the model into that format from Python. You could use pybind11 for that, and expose fdeep's types to Python, so one can directly create an fdeep model from Python - it's pretty cool. You can even put the fdeep python module on pypi, then a user can just do `pip install fdeep` and convert models with one or two commands.

I'm sure there would be other strategies too, very likely something that I haven't thought of yet. Or quite possibly you have thought about this problem too already. :-)

**Comment by Dobiasd** [comment]
Hi Patrik,

yes, I've observed similar things, and I'm interested in improving the situation. It's just that I did not yet do something because changing it sounded non-trivial to me. Also the issue was not reported yet as a real problem by users as far as I can remember. But it was mentioned for sure.

So now perhaps it is time to do something about it. However I somehow would like to first explore solutions that allow to keep the existing constructor functions of the layers, mainly because it was some trial-end-error pain to get things working as they are, and I fear to start this cycle again. ;-)

But of course if you are interested in implementing a solution like the really good one you suggest, I of course would be happy to give support where possible.
What do you think?

**Comment by Dobiasd** [comment]
> Is the peak memory usage you observe during loading higher than the peak during prediction?

Just measured `application_performance.cpp` with just `vgg19.json` and `valgrind --tool=massif`.

The result is clear. Memory usage during prediction is much lower compared to loading.

So yes, improving the loading really would bring down the overall memory requirements.

![image](https://i.imgur.com/jnRsDaX.png)

![image](https://i.imgur.com/lGnyuoc.png)

**Comment by Dobiasd** [comment]
Perhaps we don't need to use a completely new data format, but only store the weights differently.

In large models, the `trainable_params` part of the json file makes out the vast majority of data.
So if we only store these in a different way, I hope we can have the wanted effect without needing to change that much.

Access to `trainable_params` in `read_model` is already abstracted away into the `get_param` function, so not much would need to be changed there.

Now we need a nice binary data format to write in Python and read in C++. The structure of `trainable_params` also is quite simple. We could even flatten the hierarchy and basically we only need to store a dictionary mapping from strings to raw byte arrays.

**Comment by Dobiasd** [comment]
cereal seems like a very good library. However I made negative experiences in the past with function calls from/into different programming languages, which makes me a bit biased against this solution. :wink: Also I would like to avoid this additional complexity in the infrastructure of the project.
Re-implementing parts of cereal it Python also does not sound too cool either.
So I'm still thinking about this.

One other thing:
As shown I was able to reproduce a too large memory consumption during loading but not the reported runtime.

The two VGG models are similar in size to your model, however load about on order of magnitude faster (on my machine™):
- `vgg16.json`: `713M` -> `Parsing json ... done. elapsed time: 10.302079 s`
- `vgg19.json`: `741M` -> `Parsing json ... done. elapsed time: 10.672227 s`

Could you please try these out on your machine, so we can see if it is your model that is different or your configuration?

Also make sure you did not accidentally set `STORE_FLOATS_HUMAN_READABLE = True` in `convert_model.py`.

**Comment by patrikhuber** [comment]
Hi @Dobiasd! Sorry for my absence from this ticket.

Just a quick reply to this part (though maybe not very relevant to this issue):

> cereal seems like a very good library. However I made negative experiences in the past with function calls from/into different programming languages, which makes me a bit biased against this solution. 😉 Also I would like to avoid this additional complexity in the infrastructure of the project.
Re-implementing parts of cereal it Python also does not sound too cool either.

I think you slightly misunderstood what I meant (but that doesn't mean what I proposed was a good idea... might be way too complicated indeed :-) ).
There would not be anything to reimplement from Cereal in Python, basically you use Pybind11 to hook up C++ and Python. If you haven't used pybind11 before - it's completely awesome, and I can only recommend that you try it in a toy-example or hobby project or something. It results in a very easy & powerful way of combining C++ libraries and Python. But - back on topic - to do it the way I proposed would indeed require us to write bindings code in C++ for the data structures of fdeep - i.e. anything that we want to pass to/from Python/C++. (See [here](https://github.com/patrikhuber/eos/blob/v0.16.1/python/pybind11_Image.hpp#L56-L107) for an example type-caster for a custom Image class to convert to and from numpy.ndarray. Don't look at that code too much... it never left beta-stage... :-) But it's worth mentioning that anything involving `Eigen::Matrix` works out of the box with Pybind (and even avoids copies when possible). It's really cool.).
But anyway, yes, it would add significant complexity, so probably not the best solution. Especially if you mention you had some troubles to get the construction of the layers right.

So I think whatever you can come up with will be the better idea :-)

(Apart from that, adding just pybind11 (it's header-only as well) might well be worth it if you need to interface with Python or want some parts/classes/data of fdeep to be better accessible from Python.)

> Could you please try these out on your machine, so we can see if it is your model that is different or your configuration?

Hmm yes I'm going to try that! Indeed if these 700 MB models take 10s, my 900 mb model shouldn't take 2 mins...
I don't think I had `STORE_FLOATS_HUMAN_READABLE = True`, I left everything on the default, and I believe I saw base64 encoded strings in the .json, not floats (otherwise the model would probably be even 10x bigger :-) ).

**Comment by Dobiasd** [comment]
Yes, I understood what you meant with pybind11. The approach with re-implementing parts of cereal in Python, that I suggested, was just meant as an alternative, i.e. if we want to avoid cross calls (using pybind11 or similar) but still want to use cereal, we could try to re-create the format writer in Python. But that's probably the worst idea. :wink:

I'll have a look into `pybind11`, since I did not use it yet.

---

Also I'm looking forward to learn about what causes the 2 minutes loading time.

**Comment by Dobiasd** [comment]
Here is an idea that could reduce the memory usage during loading quite a lot. I'd love to hear your opinion about it before I start to implement it. Perhaps you can foresee some potentional problems that I currently don't see.

### Usage

At first the new format would only be used when the target filename for `convert_model.py` ends with `".jsons"` (yes, with an `s`. :wink:).

In C++ `fdeep::load_model` would switch to the new loader in case of `.jsons` files.

The old format would still work, so updating fdeep to the next version would not require users to convert re-convert models to the new-format.

### Model format

Currently the content of a model's `json` file looks like this:
```json
{
  "architecture": {
      "input_layers": [...]
      "layers": [...]
  }
  "some_strange_offset_flag": false,
  "input_shapes": [...]
  "output_shapes": [...],
  "tests": [{
      "inputs": [{"shape": [...], "values": [...]}]
      "outputs": [{"shape": [...], "values": [...]}]
  }]
  "trainable_params": {
    "layer_name_1": {
      "beta": [...],
      "moving_variance": [...]
    }
    "layer_name_2": {
      "weights": [...],
      "bias": [...]
    }
  }
}
```

The new `jsons` format would look as follows
```json
{
  "model": {
    "architecture": {
        "input_layers": [...]
        "layers": [...]
    }
    "some_strange_offset_flag": false,
    "input_shapes": [...]
    "output_shapes": [...]
  }
}
{
  "tests": [{
      "inputs": [{"shape": [...], "values": [...]}]
      "outputs": [{"shape": [...], "values": [...]}]
  }]
}
{
  "trainable_params": {
    "layer_name_1": {
      "beta": [...]
    }
  }
}
{
  "trainable_params": {
    "layer_name_1": {
      "moving_variance": [...]
    }
  }
}
{
  "trainable_params": {
    "layer_name_2": {
      "weights": [...]
    }
  }
}
{
  "trainable_params": {
    "layer_name_2": {
      "bias": [...]
    }
  }
}
```

### How does it work

The C++ code would not read and parse the whole file in one go as with the old format, but only consume the stream one json object at once (by simply counting `{`s and `}`s). When it encounters a `"trainable_params"` object it would convert the base64 encoded floats into a `fdeep::float_vec` and that way build up an `std::map<std::string, std::map<std::string, fdeep::float_vec>>` (`dict<layer_name, dict<param_name, float_vec>>`).

Currently when the layers are created they access the trainable parameters with a function call `get_param(layer_name, param_name)`. This function would now access the map with the preloaded `float_vec`s instead of the json object. (To avoid copying, used vectors could be moved out of the map, since they are only needed once per model anyways.) So not much changes in the layers loading code are needed, but the effect would be quite optimal. Only one weight vector of a single layer would need to be parsed at a time, i.e. reside im memory as parsed JSON object. Since most large models have many layers, it would only be a tiny overhead compared to the destination size of the model in memory.

---

What do you think?

**Comment by Dobiasd** [comment]
Just discovered [one ridiculously low-hanging fruit regarding memory usage while loading a model](https://github.com/Dobiasd/frugally-deep/commit/f37786af2bb69f27ddc023c6b4956b676002bf17). :grin:

With `VGG19` we are now down from roughly 4.7 GB to roughly 4.0 GB. Still, the proposed new model format would save even more.

before:
![image](https://i.imgur.com/85agEcn.png)

after:
![image](https://i.imgur.com/8lkdZdt.png)

**Comment by Dobiasd** [comment]
Hey. [one more](https://github.com/Dobiasd/frugally-deep/commit/84550292b275b65bbb794622b4ce5104fefa50f4). :slightly_smiling_face:

![image](https://i.imgur.com/ZF0fOnR.png)

Now peak memory usage on `VGG19` is at roughly 3.4 GB. Still, the proposed new model format would save even more. :wink:

**Comment by Dobiasd** [comment]
Aaaaand [another one](https://github.com/Dobiasd/frugally-deep/commit/563062ad054d45d250855799778ada1811487a29). :smile:

Now we're down to 2.9 GB memory peak on `VGG19`.
![image](https://i.imgur.com/eSWMyC2.png)

**Comment by patrikhuber** [comment]
Cool! :D These are really impressive... and from 4.7 GB to 2.9 GB is really fantastic. I think that makes changing the format less important, or maybe even not worth the trade-off of a new format anymore (at least until someone comes with a really problematic, practical use case). Or what are your thoughts?

**Comment by Dobiasd** [comment]
I was hoping you would say that, but I did not want to state it, in order to hear your unbiased opinion. :wink:

**Comment by patrikhuber** [comment]
Found this on /r/cpp today, might be interesting - Its benchmarks show it's quite a bit faster than nlohmann/json, but, more interestingly, it supports the MessagePack and CBOR formats.

/r/cpp thread: https://www.reddit.com/r/cpp/comments/91wahu/jsoncons_a_c_headeronly_library_for_constructing/
GitHub: https://github.com/danielaparker/jsoncons

**Comment by Dobiasd** [comment]
Interesting library, thanks. At first glance from its [floating-point-benchmarks](https://github.com/danielaparker/json_benchmarks/blob/master/report/performance_fp.md) it seems like we would not save a significant amount of memory, but some runtime. I'll spin up a quick benchmark with a VGG model.

**Comment by Dobiasd** [comment]
Here it is:

```cpp
#include <chrono>
#include <iostream>
#include <climits>
#include <jsoncons/json.hpp>
#include <nlohmann/json.hpp>

void load_nlohmann()
{
    std::ifstream is("vgg19.json");
    nlohmann::json j;
    is >> j;
}

void load_jsoncons()
{
    std::ifstream is("vgg19.json");
    jsoncons::json j = jsoncons::json::parse(is);
}

template <typename Func>
void measure(const std::string& name, const Func f)
{
    using namespace std::chrono;
    const auto start_time_ns = high_resolution_clock::now().time_since_epoch().count();
    f();
    const auto end_time_ns = high_resolution_clock::now().time_since_epoch().count();
    const auto elapsed_ms = (end_time_ns - start_time_ns) / 1000000;
    std::cout << name << " elapsed_ms: " << elapsed_ms << std::endl;
}

int main()
{
    for (std::size_t i = 0; i < 5; ++i)
    {
        measure("nlohmann ", load_nlohmann);
        measure("jsoncons ", load_jsoncons);
        std::cout << "--------" << std::endl;
    }
}
```

```
$ g++ --std=c++14 -O3 -mfma -Ijson/include -Ijsoncons/include json_benchmark.cpp -o json_benchmark && taskset --cpu-list 1 ./json_benchmark
nlohmann  elapsed_ms: 9574
jsoncons  elapsed_ms: 6276
--------
nlohmann  elapsed_ms: 9616
jsoncons  elapsed_ms: 6253
--------
nlohmann  elapsed_ms: 9583
jsoncons  elapsed_ms: 6251
--------
nlohmann  elapsed_ms: 9590
jsoncons  elapsed_ms: 6254
--------
nlohmann  elapsed_ms: 9576
jsoncons  elapsed_ms: 6247
```

Memory usage looks as follows (first hill is nlohmann, second one is jsoncons):

```
g++ --std=c++14 -O3 -mfma -Ijson/include -Ijsoncons/include json_benchmark.cpp -o json_benchmark && taskset --cpu-list 1 valgrind --tool=massif ./json_benchmark
```

![image](https://i.imgur.com/WNvOJGt.png)

So the runtime for loading is reduced by a factor of roughly 0.65. Memory usage is roughly the same. Both match the expectations created by [the benchmarks](https://github.com/danielaparker/json_benchmarks/blob/master/report/performance_fp.md). That's nice. :)

**Comment by patrikhuber** [comment]
Hey cool! That's quite a difference. Even though that difference is quite large, it is probably not worth the switch, or what are your thoughts? I think I would still be a bit hesitant because nlohmann/json is really the extremely well-established go-to json library :-) Though jsoncons makes a really good impression too! (it includes & passes conformance tests etc.)
