### ISSUE TITLE
misbehavior in convert_model.py 

### ISSUE THREAD

**Issue by smartsl** [Dobiasd/frugally-deep#51]
The func arr3_to_channels_first_format() supposed to change shape from (w, h, c) to (c, h, w) as docs said. But instead changes it to (c, w, h), which is not working.

The fix should be:
return np.swapaxes(arr, 0, 2)

So, am I right about this? Err.. plz point it out. :P

**Comment by Dobiasd** [comment]
`arr3_to_channels_first_format` converts from `hwc` (TensorFlow format) to `chw` (frugally-deep format).

What docs are you referring to. :)

**Comment by Dobiasd** [comment]
Just [extended the docstring of `arr3_to_channels_first_format`](https://github.com/Dobiasd/frugally-deep/commit/7c0ad082781d7e3dfbc8f107f40c673299795b52). If anything is unclear, feel free to re-open the issue.

**Comment by smartsl** [comment]
That is clear enough for me. You are right :)
