### ISSUE TITLE
Concatename instead of concatenate? 

### ISSUE THREAD

**Issue by mpariente** [Dobiasd/frugally-deep#52]
I guess these typos are not intentional, right?
[here](https://github.com/Dobiasd/frugally-deep/blob/master/include/fdeep/import_model.hpp#L463) and [here](https://github.com/Dobiasd/frugally-deep/blob/master/include/fdeep/import_model.hpp#L785), the function name should be `create_concatenate_layer`

**Comment by Dobiasd** [comment]
Oh, yes, typo. Thank you. :)
Would you like to create a pull request with the fix?

**Comment by mpariente** [comment]
Pull request created, thanks!

**Comment by Dobiasd** [comment]
Cool, thanks. :)
