### ISSUE TITLE
Fatal exception when loading json model: type_error at memory location

### ISSUE THREAD

**Issue by tostaess** [Dobiasd/frugally-deep#59]
Hi Tobias!

First of all, thanks a lot for all the work put in this project.

I would like to use my Keras model to classify an image in one of two classes in C++.
For that, I try to use the opencv_example you provided.

The conversion of the model to json seems to be succesful. After that I use the opencv_example code unaltered, except for the name of the image and the json model.
I run it on Windows 7 in Visual Studio 2015.
The build is succesful, however when debugging an exception occurs that prevents the program from executing:
 Unhandled exception at 0x000007FEFD31A06D in ConsoleApplication1.exe: Microsoft C++ exception: nlohmann::detail::type_error at memory location 0x000000000021E448.

This appears to happen when loading the json model with fdeep::load_model('model.json').

The line that provokes the error is the penultimate line in (in json.hpp):

    reference operator[](T* key)
    {
        // implicitly convert null to object
        if (is_null())
        {
            m_type = value_t::object;
            m_value = value_t::object;
            assert_invariant();
        }

        // at only works for objects
        if (JSON_LIKELY(is_object()))
        {
            return m_value.object->operator[](key);
        }

        JSON_THROW(type_error::create(305, "cannot use operator[] with " + std::string(type_name())));
    }

I am quite new to this and have been searching for a solution for about a day now and have failed to find anything useful. Does anything occur to you as to what may be causing this?

My apologies if this is a vague question. If any more details are needed, let me know!

Thanks in advance.

**Comment by tostaess** [comment]
Hi Tobias,

Thanks a lot for the prompt reply.

I have tried it with both Keras 2.2.0 and 2.1.6, with the same result. The frugally-deep and JSON versions are the latest (0.2.3 and 3.1.2 respectively).

I have added a zip folder with the files:

- `classifier.py`: the model in python code
- `cppmodel.h5`: the h5 file of the saved model
- `fdeep_model.json`: the json model generated with `convert_model.py`
- `CppPrediction.cpp`: the opencv_example where I changed the image and json model name.

[project_files.zip](https://github.com/Dobiasd/frugally-deep/files/2119114/project_files.zip)

**Comment by Dobiasd** [comment]
I see you are using a sequential model. Only three hours ago I fixed something in frugally-deep regarding the handling of sequential models. Could you please download/install/use this really bleeding-edge version of frugally-deep and try again, starting from `python3 convert_model.py cppmodel.h5 fdeep_model.json`?

**Comment by tostaess** [comment]
You are exactly on top of things, your fix from this morning has solved the issue indeed. Thanks a lot!

If I may, I have one more question that has kept me busy now for the entire afternoon after the loading of the json model worked.

For some reason, the result of the classification is always 0. In [this issue](https://github.com/Dobiasd/frugally-deep/issues/6), I read that if that is the case, my input must simply be different from the one in python.
The only preprocessing I do in python is rescaling the values from [0, 255] to [0, 1], so I did that using 
```
cv::Mat img2;
image.convertTo(img2, CV_32F, 1.f/255.0f);
```

I checked pixel values both in Python and C++ and they are the same.

The total code adapted from the open_cv example, with only the rescaling added is:
```
int main()
{
	const auto model = fdeep::load_model("fdeep_model.json");
	const cv::Mat image = cv::imread("Good1525.png");
	cv::cvtColor(image, image, cv::COLOR_BGR2RGB);
	assert(image.isContinuous());
	cv::Mat img2;
	image.convertTo(img2, CV_32F, 1.f/255.0f);

	// Use the correct scaling, i.e. low and high.
	const auto input = fdeep::tensor3_from_bytes(img2.ptr(),
		img2.rows, img2.cols, img2.channels(), 0.0f, 1.0f);
	//fdeep::show_tensor3(input);
	const auto result = model.predict_class({ input });
	std::cout << result << std::endl;
	return 0;
}
```

Is there any common thing that I need to do that I'm still missing? For example I see in the code of `tensor3_from_bytes` that it also reshapes the pixel values to [0, 1]. However leaving out my rescaling doens't seem to change anything.

Thanks in advance if you have any idea. I'm kind of at a loss here.

**Comment by Dobiasd** [comment]
`fdeep::tensor3_from_bytes` takes a `const std::uint8_t* value_ptr` as its first parameter. It assumes every pixel is stored in 1 byte (3 bytes for color images).

`img2` in your code is of type `CV_32FC3`, i.e. every pixel is 12 bytes long (3 `float`s of 4 bytes each).

Leaving out your re-scaling, i.e. skipping the `convertTo` step and giving `image` directly to `fdeep::tensor3_from_bytes` (and let it do the re-scaling) should be the correct solution.
You can then use `fdeep::show_tensor3` to output the exact values of the tensor that are passed to your model. Please compare those with the values in Python (after re-scaling of course).

If you get different results in C++ and Python despite inputting the same values to the model, please provide the minimal (but complete) code and image file needed to reproduce the problem.

**Comment by tostaess** [comment]
The values that are fed to the model in C++ and Python are different indeed, but it seems to be because `tensor3_from_bytes` rearranges the image.

I have attached a zip file with:
- a Python script that reads the image using OpenCV, changes it from BGR to RGB, re-scales it and feeds this to the model to predict the class.
- A C++ script that reads the image using OpenCV, changes it from BGR to RGB, feeds it to `tensor3_from_bytes` (that performs the re-scaling) and feeds this tensor3 to the network.
- The image and the necessary h5 and json models.

The result of tensor3_from_bytes is not the same anymore as the input to the model in the Python script, although the preprocessing seems to be the same to me. 
Is this behaviour expected? 

[project_files.zip](https://github.com/Dobiasd/frugally-deep/files/2123063/project_files.zip)

As I said, I'm quite new at this, my apologies if this would be something obvious that I'm missing.

**Comment by Dobiasd** [comment]
You currently are using `fdeep::predict_class`:

```cpp
    // Convenience wrapper around predict for models with
    // single tensor outputs of shape (1, 1, z).
    // Returns the index of the output neuron with the maximum activation.
    std::size_t model::predict_class(const tensor3s& inputs) const;
```

Since your model only has one output neuron the result will always be `0`. (`std::size_t` `0` not `float` `0.1`).
So this function is only suitable for classification models with more than one output neuron.

What you need is the raw value of the output, which you can get like so:

```cpp
#include <opencv2/opencv.hpp>
#include <fdeep/fdeep.hpp>

int main()
{
    const auto model = fdeep::load_model("fdeep_model.json");
    const cv::Mat image = cv::imread("Good1974.png");
    cv::cvtColor(image, image, cv::COLOR_BGR2RGB);
    assert(image.isContinuous());
    // Use the correct scaling, i.e. low and high.
    const auto input = fdeep::tensor3_from_bytes(image.ptr(),
        static_cast<std::size_t>(image.rows),
        static_cast<std::size_t>(image.cols),
        static_cast<std::size_t>(image.channels())
        , 0.0f, 1.0f);
    const auto result = model.predict({ input }).front().get(0, 0, 0);
    std::cout << result << std::endl;
}
```

Just tested it with your model and image, and the output is `0.999936`, similar to Python. :)

But to make your use-case more convenient, I [added a new function `model::predict_single_output`](https://github.com/Dobiasd/frugally-deep/commit/9ecdc9503b04c539954ec2589bb9e2396733d8aa), that lets you write more expressive code.

So if you use that latest version of frugally-deep, you can replace

```cpp
const auto result = model.predict({ input }).front().get(0, 0, 0);
```

with

```cpp
const auto result = model.predict_single_output({ input });
```

**Comment by tostaess** [comment]
I was focused on the `tensor3_from_bytes` and never thought to check how the `predict_class` works. Now it's all clear to me and the C++ model works perfectly. 
Really great support, thanks a lot! 

And in general thanks for the great work your're doing here. I'm sure frugally-deep will help many more people enormously. :)

**Comment by Dobiasd** [comment]
Thanks a lot for this positive feedback and also for the clear problem description. :+1:
