### ISSUE TITLE
Should I write python layer into C++ again for inference

### ISSUE THREAD

**Issue by jinfagang** [Dobiasd/frugally-deep#71]
Hello, may I ask if I want using frugally-deep to inference on my trained model, should I write a C++ network structure to load that weights?

**Comment by Dobiasd** [comment]
Hi jinfagang,

you don't have to re-create the model structure in C++ by hand. When exporting from Python to frugally-deep format the architecture is also exported with the weights. Simply follow [the usage instructions in the README file](https://github.com/Dobiasd/frugally-deep#usage). :)
