### ISSUE TITLE
Note for using frugally-deep with Eigen 3.2

### ISSUE THREAD

**Issue by LinYuChi** [Dobiasd/frugally-deep#79]
Eigen deprecated Eigen::DenseIndex in Eigen 3.3, and replaced it with Eigen::Index. To compile your project which includes frugally-deep with Eigen 3.2, the user can replace all the Eigen::Index in frugally-deep with Eigen::DenseIndex. I did not test the general correctness of the result using Eigen 3.2, but in my application it works the same with my keras model in python.

**Comment by Dobiasd** [comment]
Thanks for the remark. I think we have two reasonable options here:
- Add to the `README` that one needs at least version 3.3 of Eigen
- Detect Eigen version at compile time and `typedef` Index accordingly

What do you think?

**Comment by Dobiasd** [comment]
Mhh, [version 3.3.1 was released in December 2016](http://eigen.tuxfamily.org/index.php?title=News:Eigen_3.3.1_released!), so I guess requiring it it not totally unreasonable.

**Comment by LinYuChi** [comment]
Although the code change from the developer side may not be necessary in my opinion, the second option is better. The users may use Eigen 3.2 for a couple reasons:

First, Eigen 3.2 comes with apt-get install in Ubuntu 14.04 which is still a very popular version used across research labs. Second, in my weird case, I have other codes which depend on Eigen 3.2, and need to run with frugally-deep in the same process. Although I can use cmake to let project links to different eigen version and pass the compilation, when I declare an object which was built with another version of Eigen I get a seg fault.

**Comment by Dobiasd** [comment]
It was quite easy to implement, just:

```cpp
#if EIGEN_VERSION_AT_LEAST(3,3,0)
    typedef Eigen::Index EigenIndex;
#else
    typedef Eigen::DenseIndex EigenIndex;
#endif
```

So thanks for this very good suggestion. :+1:

**Comment by LinYuChi** [comment]
Thank you, too, for the nice codes.
