### ISSUE TITLE
Keras 'predict_proba' feature in frugally-deep.

### ISSUE THREAD

**Issue by Aghabeiki** [Dobiasd/frugally-deep#80]
Problem :
As due to the applicant of Keras in python, there is one function for computing the probability in the prediction that its syntax is " predict_proba".

My Investigate: 
I couldn't find this function in frugally-deep. As considered comments, for the "predict_class" has same eligible usage for us (I Hope:D). The difference is that predict_proba has multi-output based on numbers of groups on python but predict_class has one output so that maximum values between them has been supposed.

Questions:
1- this assumption is correct or not?
2- Please help/guide me to implement this feature in frugally-deep.

**Comment by Dobiasd** [comment]
As far as I know `model.predict_proba` was kept in Keras only for backwards-compatibility reasons, but actually it was the same as `model.predict`. The current version of Keras does not include `model.predict_proba` at all any more.

Conclusion: `fdeep::model::predict` is what you are looking for. :)

**Comment by Aghabeiki** [comment]
Sorry to open it again , But I think you say it wrong,
based Keras docs it's a very usefull function in classification, exaclly when we have more then one neruns in our ML output, 

````
    def predict_proba(self, x, batch_size=32, verbose=0):
        """Generates class probability predictions for the input samples.
        The input samples are processed batch by batch.
        # Arguments
            x: input data, as a Numpy array or list of Numpy arrays
                (if the model has multiple inputs).
            batch_size: integer.
            verbose: verbosity mode, 0 or 1.
        # Returns
            A Numpy array of probability predictions.
        """
`````
