### ISSUE TITLE
Bypassing Lambda layers/adding placeholders during model conversion

### ISSUE THREAD

**Issue by VC86** [Dobiasd/frugally-deep#82]
Very often, Lambda layers in Keras perform simple operations such as selecting image/data channels and performing very basic operations on them; nevertheless, they cannot be converted, as reasonable. One simple example could be:

output_data = Lambda(lambda x: x[:,:,:,1:2])(input_data)

to just extract one channel from the tensor x.

Is there a way to bypass this layer and go on with the model conversion so that it doesn't return an error such as:
File "<ipython-input-83-8b56c8721f37>", line 18, in <lambda>
SystemError: unknown opcode
? Is there then a way to adding back the operation I bypassed in the frugally-deep json description or when the json is loaded in C++?

Trivial solution: saving separately as models what follows and precedes the Lambda layer, and converting the branches of the graph separately.

**Comment by Dobiasd** [comment]
Hi VC86,

currently there is no simple solution for this in frugally-deep. But I guess actually supporting lambda functions would be the cleaner solution compared to some bypassing.

At some point I proposed a possible interface for lambda support [here](https://github.com/Dobiasd/frugally-deep/issues/54#issuecomment-393044777) but then the requester did not need it any more.

I'll copy it here, so this thread can be read more easily.

---

For example you have the following code in Python

```python
def my_func(input_tensor):
    # output_tensor = ... some code ...
    return output_tensor

model.add(Lambda(my_func))
```

Now it would be nice if we could
- serialize the lamba function itself
- load it with the model again in C++
- convert the functions code to C++ and compile/interpret it at runtime

But this (the last step) sounds extremely complicated to me.

So in Python you would provide your lambda as a custom object when loading the model again:

```python
model = load_model('model.h5', custom_objects={'my_func': my_func})
```

If you now would re-implement your function in C++, perhaps we could have an interface like so:

```cpp
fdeep::tensor3s my_func(const fdeep::tensor3s& input)
{
    // fdeep::tensor3s output = ... some code ...
    return output;
}

using custom_function_t = std::function<fdeep::tensor3s(const fdeep::tensor3s&)>;

const std::unordered_map<std::string, custom_function_t> custom_functions = {
    {"my_func", my_func}
};

fdeep::load_model("model.json", custom_functions);
```

---

What do you think about this? I guess this would solve your problem, right?

**Comment by Dobiasd** [comment]
Hi VC86, for now I'll interpret your inactivity in this issue as the issue being obsolete from your point of view. So I'll close it for now. Feel free to re-open it in case of need. :+1:
