### ISSUE TITLE
Is there a available way to convert the tensorflow model to keras ?

### ISSUE THREAD

**Issue by ligonzheng** [Dobiasd/frugally-deep#85]
Hello ,
    I have a tensorflow model and I want to use frugally-deep, How should I convert my model to keras so that I can go on.
    Thanks in advance.
Li

**Comment by Dobiasd** [comment]
Hi Li,

to me it looks like your question is not related to frugally-deep. I suggest you search the net for "convert tensorflow model to keras" or similar, and in case you don't find anything, ask on stackoverflow or in the Keras repo.

Tobias
