### ISSUE TITLE
unknown layer type: ReLU

### ISSUE THREAD

**Issue by dankresio** [Dobiasd/frugally-deep#86]
Hello,

I was trying frugally-deep with common Keras models through the script _save_application_examples.py_ provided on _keras_export_ folder, and found out that is not fully working for mobilenet model.

When loading JSON file through fdeep::load_model, following error is thrown:
**terminate called after throwing an instance of 'std::runtime_error'
  what():  unknown layer type: ReLU**

In README.md it is said that ReLU layers are supported, but when looking at import_model.hpp -> inline layer_ptr create_layer, I can't find it.

Did I misunderstand something or it should be working?

Kind regards!

**Comment by Dobiasd** [comment]
Hi Daniel,

please make sure you are using the latest version of frugally deep. [`import_model.hpp` should include `create_relu_layer`](https://github.com/Dobiasd/frugally-deep/blob/c84d256f49e41b213d740999140dd7099a853491/include/fdeep/import_model.hpp#L670).

Is this does not help, please check your Keras version, and maybe update. You should be using something recent. You can find out which version you are using like this:

```bash
python -c "import keras; print(keras.__version__)"
```

**Comment by dankresio** [comment]
Yes, it exists as an activation creator, but not as a **layer_ptr** type.
I have latest version of frugally deep and latest version of Keras.

Quoting your code, I think (but I'm not sure) that there should be a **`layer_ptr create_relu_layer`** method which had to be called from [creators](https://github.com/Dobiasd/frugally-deep/blob/c84d256f49e41b213d740999140dd7099a853491/include/fdeep/import_model.hpp#L808) (i.e: when defining the type of layer, not the activation only).

The line you quoted refers to [activation layer creators](https://github.com/Dobiasd/frugally-deep/blob/c84d256f49e41b213d740999140dd7099a853491/include/fdeep/import_model.hpp#L747).

Maybe is a problem when using mobilenet, but JSON file generates a layer called ReLU ("class_name": "ReLU") and [when parsing on `import_model.hpp`](https://github.com/Dobiasd/frugally-deep/blob/c84d256f49e41b213d740999140dd7099a853491/include/fdeep/import_model.hpp#L799), it can't find this type of layer.

**Comment by Dobiasd** [comment]
I'll try to re-create the issue with the same Keras version an get back to you. I guess at some point in the past `MobileNet` worked, because otherwise I would not have been able to create the [performance measurement](https://github.com/Dobiasd/frugally-deep#performance) using it. :)

**Comment by dankresio** [comment]
Perfect!

And also for your info: inceptionresnetv2 is neither working. New implementation seems to use Lambda layer and it is not supported as said on [README](https://github.com/Dobiasd/frugally-deep#introduction). The following error is thrown:

**_unknown layer type: Lambda_** 

Thanks for answering so fast!

**Comment by Dobiasd** [comment]
I've upgraded my libraries (TensorFlow to 1.10.1 and Keras to 2.2.2) and now I when I compile and run `test/applications_performance.cpp` I also get the following:

```
mobilenet.json
Loading json ... done. elapsed time: 0.329546 s
ERROR: unknown layer type: ReLU
```

I'll fix this and report back here when done.

However the Lamba problem with `InceptionResNetV2` is [more complicated](https://github.com/Dobiasd/frugally-deep/issues/82#issuecomment-414470730), so I'll probably drop support for `InceptionResNetV2` for now.

**Comment by Dobiasd** [comment]
OK, done. Actually things became simpler, because Keras replaced its strange `relu6` layer by using parametrized relu for the MobileNets. I now just followed. :)

Please let me know if further issues arise.
