### ISSUE TITLE
How can I predict with an vector of type: std::vector<double>? Help Wanted

### ISSUE THREAD

**Issue by matheusgmaia** [Dobiasd/frugally-deep#87]
My model use Image moments as features to classify, I have the moments in an std::vector<double> type. How to transform it in a fdeep::tensor3 ?

**Comment by Dobiasd** [comment]
Hi Matheus,

does [this explanation](https://gist.github.com/Dobiasd/8f41ef8bf4198ab535060a78b53f2008), which is also linked to in the `README.md`, help?

**Comment by Dobiasd** [comment]
I interpret your inactivity in this issue as a positive sign for now, so I'll close it. Feel free to re-open it if needed. :+1:
