### ISSUE TITLE
cannot build unit tests

### ISSUE THREAD

**Issue by illusioncognitive** [Dobiasd/frugally-deep#91]
I have followed [this](https://github.com/Dobiasd/frugally-deep/blob/master/INSTALL.md) to install frugally-deep but failed while I was trying to execute the command for **building unit tests** . While I have used `cmake -DFDEEP_BUILD_UNITTEST=ON ..` it has given me the following error:
`CMake Error: The source directory "/home/user/training_by_several_learning_process" does not appear to contain CMakeLists.txt.`
`Specify --help for usage, or press the help button on the CMake GUI.`
At that time I was in that directory where I have cloned the other repository instructed [here](https://github.com/Dobiasd/frugally-deep/blob/master/INSTALL.md)

I have also tried to make by Qt but failed.

Please help me out to solve this problem. Thanks in advance.

**Comment by Dobiasd** [comment]
Maybe you skipped the `mkdir -p build && cd build` step`. Obviously `./..` does not contain a `CMakeLists.txt` file.

Please try to do exactly the following, and let me know at which point the problem occurs:

```
git clone https://github.com/Dobiasd/FunctionalPlus
cd FunctionalPlus
mkdir -p build && cd build
cmake ..
make && sudo make install
cd ../..

sudo apt install mercurial
hg clone https://bitbucket.org/eigen/eigen/
cd eigen
mkdir -p build && cd build
cmake ..
make && sudo make install
sudo ln -s /usr/local/include/eigen3/Eigen /usr/local/include/Eigen
cd ../..

git clone https://github.com/nlohmann/json
cd json
git checkout v3.1.2
mkdir -p build && cd build
cmake ..
make && sudo make install
cd ../..

git clone https://github.com/onqtam/doctest.git
cd doctest
mkdir -p build && cd build
cmake -DDOCTEST_WITH_TESTS=OFF -DDOCTEST_WITH_MAIN_IN_STATIC_LIB=OFF ..
make && sudo make install
cd ../..

git clone https://github.com/Dobiasd/frugally-deep
cd frugally-deep
mkdir -p build && cd build
cmake -DFDEEP_BUILD_UNITTEST=ON ..
make && sudo make install
cd ../..
```

**Comment by illusioncognitive** [comment]
I have tried but this error has occurred. I have attached the image.
![error](https://user-images.githubusercontent.com/44234611/48436198-7a62f000-e77e-11e8-82f4-a7084c88cc03.png)

`

**Comment by Dobiasd** [comment]
```
ImportError: No module named 'keras'
```

You need keras installed for Python3 on your machine.

Please do
```
sudo python3 -m pip install keras
```
and then try again.

**Comment by illusioncognitive** [comment]
Thanks for your quick reply.
I have already keras installed and I have done also work with keras before
![error1](https://user-images.githubusercontent.com/44234611/48437323-548b1a80-e781-11e8-87d4-4db384720503.png)

**Comment by Dobiasd** [comment]
You have Keras installed for `python`, which on your machine points to a Python 3.6.6 installation.

However the unit tests of fdeep run `python3` instead.
Please make sure you have Keras installed for that too:
```
python3 -c 'import keras'
```
then (after expected failure) run
```
`sudo python3 -m pip install keras`
```
to install keras.

Or let `python3` point to the executable `python` is also pointing too.

---

In essence, `python3 -c 'import keras'` does not work on your machine. You have to make it work, in order for the fdeep unit tests to run.

**Comment by illusioncognitive** [comment]
![error2](https://user-images.githubusercontent.com/44234611/48437865-cb74e300-e782-11e8-866d-08454ab5e3e8.png)

![error4](https://user-images.githubusercontent.com/44234611/48437986-2c9cb680-e783-11e8-9ee8-35b558f8fe79.png)



I think it is working, isn't it?

**Comment by Dobiasd** [comment]
Mhh, this is with venv, but the fdeep unit tests maybe try to run without it.

What happens when you do `python3 -c 'import keras'` without venv?

**Comment by illusioncognitive** [comment]
> Mhh, this is with venv, but the fdeep unit tests maybe try to run without it.
> 
> What happens when you do `python3 -c 'import keras'` without venv?

At this time it is not working. I have setup everything keras, tensorflow only for **venv**.

**Comment by Dobiasd** [comment]
OK, then I guess you know what to do by now. :)

**Comment by illusioncognitive** [comment]
I am apologizing first for this comment as it is not directly related to this issue. 

While the day before yesterday I was trying to install **frugally-deep** I have executed the following command 
`sudo ln -s /usr/local/include/eigen3/Eigen /usr/local/include/Eigen` successfully. But today I have failed because it was showing that already a directory name Eigen is there. That's why I haven't executed it again. I am giving you the screenshot of those folders. Please check it is right or wrong. I am afraid that if it is the cause of this error.
![error7_eg](https://user-images.githubusercontent.com/44234611/48438923-62429f00-e785-11e8-8e2d-bdc67d48e475.png)
![error6_eg](https://user-images.githubusercontent.com/44234611/48438924-62429f00-e785-11e8-9791-21cd3ecb282b.png)

**Comment by Dobiasd** [comment]
Maybe it is the easiest to delete these old artifacts and start from scratch.

**Comment by illusioncognitive** [comment]
> OK, then I guess you know what to do by now. :)

Ok @Dobiasd  I will try it outside of **venv** and as soon as possible give you the feedback. Thank you again.

**Comment by illusioncognitive** [comment]
> Maybe it is the easiest to delete these old artifacts and start from scratch.

Can you please refer me an instructions what to do? For example: Will I delete the **doctest, eigen3, Eigen,fdeep, fplus** from `/usr/local/include` directory?

![error8](https://user-images.githubusercontent.com/44234611/48439627-07aa4280-e787-11e8-9a53-5bbab127f07f.png)

**Comment by Dobiasd** [comment]
Usually they would be overwritten when you install again. So perhaps it's not needed to delete them manually. What happens exactly when you just follow the install instructions again, but from a fresh directory? Make sure to have keras installed for python3 without venv first.

**Comment by Dobiasd** [comment]
If the unit tests still do not work on your machine, maybe just install fdeep without building/running the tests.

**Comment by illusioncognitive** [comment]
@Dobiasd 

1/ If I use **conda** environment to install **keras** will there be any problem? I have tried to run the command outside of venv
 ```
sudo python3 -m pip install keras
```
 but after installing it is giving import error.

2/ If I import all directory of your git repo and make it by Qt will it be possible?

**Comment by Dobiasd** [comment]
1) This seems to be a general python-library-management question unrelated to frugally-deep. So it might be out of the scope of the issues in this GitHub Repo. Also I don't really have much knowledge about this stuff. :wink:

2) Sorry, I really don't know.

---

Why is it so important for you to run the unit tests of frugally deep? You can use the library without running them, by just installing it normally.

**Comment by illusioncognitive** [comment]
> 1. This seems to be a general python-library-management question unrelated to frugally-deep. So it might be out of the scope of the issues in this GitHub Repo. Also I don't really have much knowledge about this stuff. wink

Yes I know. Sorry for asking it here.
> 2. Sorry, I really don't know.


> Why is it so important for you to run the unit tests of frugally deep? You can use the library without running them, by just installing it normally.

Ok. I will then run only this 
``` 
git clone https://github.com/Dobiasd/frugally-deep
cd frugally-deep
mkdir -p build && cd build
make && sudo make install
cd ../..
```

I have omitted here 
```
cmake -DFDEEP_BUILD_UNITTEST=ON ..
```

Is it right or I have to change anything? Because I have got the error after executing 
```
make && sudo make install
```
from ~/frugally-deep/build directory

**Comment by Dobiasd** [comment]
Yes, I think that is correct.

**Comment by Dobiasd** [comment]
No, that's not fully correct. You still have to call `cmake`. Simply do it as described in [the documentation](https://github.com/Dobiasd/frugally-deep/blob/master/INSTALL.md#installation), and it should be fine:

```
git clone https://github.com/Dobiasd/frugally-deep
cd frugally-deep
mkdir -p build && cd build
cmake ..
make && sudo make install
cd ../..
```

**Comment by illusioncognitive** [comment]
> No, that's not fully correct. You still have to call `cmake`. Simply do it as described in [the documentation](https://github.com/Dobiasd/frugally-deep/blob/master/INSTALL.md#installation), and it should be fine:
> 
> ```
> git clone https://github.com/Dobiasd/frugally-deep
> cd frugally-deep
> mkdir -p build && cd build
> cmake ..
> make && sudo make install
> cd ../..
> ```

Hi @Dobiasd  I have decided to work in **venv** as I am still getting the error in installing **keras** outside of **venv** of **conda**. I think if I follow the steps what you have told in this comment then the problem will be solved as the former error came along with the **building of unit test**. 

I have done the installtion(**skipped building unit test and the installation of docktest**). If you feel the installtion process still wrong please let me know.

While working with the **cpp file** I am getting the other error. I have mentioned it [here](https://github.com/Dobiasd/frugally-deep/issues/92#issue-380848822)

**Comment by Dobiasd** [comment]
Installation seems OK now, since you were able to compile a cpp file using `fdeep`. :+1:
