### ISSUE TITLE
error while executing the cpp file to compare the result with keras model output

### ISSUE THREAD

**Issue by illusioncognitive** [Dobiasd/frugally-deep#92]
I have installed frugally-deep by following from [here](https://github.com/Dobiasd/frugally-deep/blob/master/INSTALL.md#installation). I have skipped building the unit test part as well as the docktest installation as a [problem](https://github.com/Dobiasd/frugally-deep/issues/91#issue-379582974) has occurred during the first time installation.

I have loaded my JSON file in the cpp 
```
#include <fdeep/fdeep.hpp>
int main()
{
    const auto model = fdeep::load_model("/home/atif/training_by_several_learning_process/frugally_keras/traffic_frugally_keras/traffic_frugal.json");
    const auto result = model.predict(
        {fdeep::tensor5(fdeep::shape5(1, 1, 1, 1, 4), {1, 2, 3, 4})});
    std::cout << fdeep::show_tensor5s(result) << std::endl;
}
```

and executed it with
```
g++ -std=c++14 traffic_frugal.cpp -o traffic_frugal
```
It has given me the output file also. But while I ran it using
```
./traffic_frugal 
```
it has given me the following error.

![error11](https://user-images.githubusercontent.com/44234611/48506195-2ffa7580-e849-11e8-9fe2-937ebbe1cdc8.png)

I am also giving here my gcc version.
![error9](https://user-images.githubusercontent.com/44234611/48506372-9a131a80-e849-11e8-9f93-6f59b2550e4c.png)

Please kindly help me out.

**Comment by Dobiasd** [comment]
Your model takes an input tensor of shape `[1, 1, 48, 48, 3]`, but in your `traffic_frugal.cpp` you give it a tensor of shape `[1, 1, 1, 1, 4]`.

**Comment by illusioncognitive** [comment]
@Dobiasd thanks for your reply.
I have changed this line 
```
{fdeep::tensor5(fdeep::shape5(1, 1, 48, 48, 3), {1, 2,3,4})});
```

But it is giving me the following error

![error12](https://user-images.githubusercontent.com/44234611/48508388-b6658600-e84e-11e8-9ac5-4207073e12a5.png)

Do I need to change the values {1,2,3,4} ? And if YES then what should be the values?

**Comment by Dobiasd** [comment]
There are the actual values for your tensor to hold.

Your tensor has a shape that contains 6912 values. You try to initialize it with only 4.

**Comment by illusioncognitive** [comment]
> There are the actual values for your tensor to hold.
> 
> Your tensor has a shape that contains 6912 values. You try to initialize it with only 4.

Thanks. It has worked.
I have two questions related with the output.

1/ Why use only 4 while tensor shape is `48*48*3=6912` ?

2/ How do I compare the output of cpp file with the result of my keras model? I have assumed that I will get some accuracy and loss value that I have seen in the output of keras model after training.

![error13](https://user-images.githubusercontent.com/44234611/48509435-6b993d80-e851-11e8-9852-a97bff54a3cd.png)

**Comment by Dobiasd** [comment]
1) No, don't use 4. When I wrote "You try to initialize it with only 4.", I meant, that this is what you are doing in your code, and that this is the reason why it fails. You model obviously takes a `(1, 1, 48, 48, 3)` tensor, which is 6912 single values.

2) Sorry, this does not make any sense. Accuracy and loss are metrics you gather while training your model. Frugally-deep does not do training. You can only use it to use a already-trained model to make predictions on some input data. Also you don't need to compare the results manually, that is what the test, that automatically runs when loading, is doing.

---

So a more general question: What is it, that you are trying to achieve by using frugally-deep?

**Comment by Dobiasd** [comment]
In that case you should:
- have a trained keras model
- have on example image
- forward pass the example image through the model in keras, remember the resulting output values
- convert your keras model to fdeep
- load the example image in C++ and forward pass it through your model, remember the resulting output values.
- compare the output from C++ with the one from Keras.

So probably the next step for you is to load the image in C++ and pass it to the model. You can find an example on how to do this here: https://github.com/Dobiasd/frugally-deep#some-integration-examples

**Comment by illusioncognitive** [comment]
hello @Dobiasd I have tried to follow the instructions you have given. I am sorry that I couldn't understand something and getting error in while trying to execute the opencv code.

At first, I want need a help from you regarding one correction in the keras_2_fdeep.cpp code. Here I am giving the whole code where I have changed. Can you please check it? I couldn't get the inner message of your saying 

> You model obviously takes a (1, 1, 48, 48, 3) tensor, which is 6912 single values.

**keras_2_fdeep.cpp code**

```
#include <fdeep/fdeep.hpp>
int main()
{
    const auto model = fdeep::load_model("/home/atif/training_by_several_learning_process/frugally_keras/traffic_frugally_keras/traffic_frugal.json");
    const auto result = model.predict(
        {fdeep::tensor5(fdeep::shape5(1, 1, 48, 48, 3), {6912})});
    std::cout << fdeep::show_tensor5s(result) << std::endl;
}

```
It is giving me the following output

![error14](https://user-images.githubusercontent.com/44234611/48719009-c7324500-ec1c-11e8-92a9-75fec50faf62.png)

**Comment by Dobiasd** [comment]
OK, and what output do you expect to see from this code?

---

> You model obviously takes a (1, 1, 48, 48, 3) tensor, which is 6912 single values.

You are filling a (1, 1, 48, 48, 3) tensor (one that needs 6912 values) with only one item (which has value `6912.0`, but that does not matter). So you end up with 6912 items of value `6912.0`, because of how the constructor of `tensor5` is overloaded.

---

Here are some examples of valid expressions. Maybe this explains the issue better:

```cpp
fdeep::tensor5(fdeep::shape5(1, 1, 1, 1, 1), {42.0})
```

```cpp
fdeep::tensor5(fdeep::shape5(1, 1, 1, 1, 2), {42.0, 42.0})
```

```cpp
fdeep::tensor5(fdeep::shape5(1, 1, 1, 4, 2), {42.0, 42.0, 42.0, 42.0})
```

```cpp
fdeep::tensor5(fdeep::shape5(1, 1, 3, 4, 2), {42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, 42.0, })
```

---

Still I don't understand what you are trying to achieve. If you want to use your model in an image, you should do that. Running forward passes on manually generated random values, will probably not help you reach your goal.

---

In general I would suggest to learn some basics of machine learning and C++ first. Otherwise you will not have much fun or success with your project, and only be frustrated by running into many problems, that actually do not need to exist.

**Comment by illusioncognitive** [comment]
hi @Dobiasd I hope, I have understood what is going on here. Firts of all, again cordial thanks for your reply and direction. I have used [this file](https://gist.github.com/Dobiasd/3140cfd9f539b6adb346e0b4a0ce157b) to load the `json file` and `image`. And then it has given me the class number which is similar to the output of my keras model. I have loaded the image after resizing as like as the training images. 
I have given the output below.

![error15](https://user-images.githubusercontent.com/44234611/48858134-ed8de700-edba-11e8-8ded-12d0d43fd170.png)

**Comment by Dobiasd** [comment]
That sounds good! So if now everything is working as needed, feel free to close this issue. :slightly_smiling_face:

**Comment by illusioncognitive** [comment]
> That sounds good! So if now everything is working as needed, feel free to close this issue.

Really your work is amazing. I am closing this issue. I want to get a direction regarding your work. My desire is to know how you have represented one image as a tensor or std vector can you please give me a guideline?

**Comment by Dobiasd** [comment]
An image is just a big chunk of numbers. In a grayscale image, each pixel is represented by one value. In a color image (e.g., RGB), each pixel is represented by a 3-tuple (3 values).
So a color image with size 1024x768 consists of 2359296 values.

But that is nothing special to frugally deep. It's just the way images (disregarding vector graphics etc.) are represented in memory, also by Keras, OpenCV, Gimp, whatever.

I recommend you read up on basics like this before diving deep into machine learning or image recognition.

But you don't need me to explain these things. Just google stuff like "how is an image represented in a computer", and you will find your way.
